### ISSUE TITLE
2 cases where D3D11_PRIMITIVE_TOPOLOGY enum is used

### ISSUE THREAD

**Issue by floooh** [Microsoft/DirectX-Graphics-Samples#10]
There are 2 cases in D3D12PipelineStateCache.cpp where a D3D11 enum is used:

* https://github.com/Microsoft/DirectX-Graphics-Samples/blob/e4ce921702064c23495669907d0752333cbccb46/Samples/D3D12PipelineStateCache/src/D3D12PipelineStateCache.cpp#L422

* https://github.com/Microsoft/DirectX-Graphics-Samples/blob/e4ce921702064c23495669907d0752333cbccb46/Samples/D3D12PipelineStateCache/src/D3D12PipelineStateCache.cpp#L454

This is especially confusing since there's also an unrelated D3D12_PRIMITIVE_TOPOLOGY_TYPE, and the D3D12 documentation has a bug in ID3D12GraphicsCommandList::IASetPrimitiveTopology, where the link to D3D12_PRIMITIVE_TOPOLOGY actually points to D3D12_PRIMITIVE_TOPOLOGY_TYPE! (https://msdn.microsoft.com/en-us/library/windows/desktop/dn770385(v=vs.85).aspx)

**Comment by bobbrow** [comment]
Thanks for pointing these issues out.  We'll get an update out soon for the sample and notify the documentation team about the bad link.

**Comment by bobbrow** [comment]
Just to clarify while the changes are in progress, D3D12_PRIMITIVE_TOPOLOGY is typedef'ed to D3D_PRIMITIVE_TOPOLOGY.

And D3D11_PRIMITIVE_TOPOLOGY_* enum values are all duplicates of matching values in D3D_PRIMITIVE_TOPOLOGY_*.  So the D3D11 enum values will do the right thing, but it's certainly confusing in the code and I have a small change out for review that will go into the develop branch shortly.  It looks like this bug crept into 2 other samples as well.

**Comment by bobbrow** [comment]
The fix for this issue has been merged to master and a new release was created this morning.  I filed a bug on the MSDN topic and will continue to follow up on that until it gets fixed.

**Comment by floooh** [comment]
Thanks a lot for the updates, much appreciated :+1: I'm currently working on a D3D12 renderer backend for my weekend engine here: https://github.com/floooh/oryol/tree/d3d12 (it has a fairly limited feature set, governed by WebGL1, so the D3D12 backend is currently more like an experiment and exercise for things coming in the future).

The D3D12 stuff is here: but currently as I'm trying to grasp the new concepts there's a lot of short-cuts and copy-paste from the samples: https://github.com/floooh/oryol/tree/d3d12/code/Modules/Gfx/d3d12. 

I'll try to write more tickets if I stumble over similar problems in the future :)

**Comment by bobbrow** [comment]
I'm going to go ahead and close this issue.  The sample code is fixed and I'm tracking the MSDN update using our internal bug tracking system.

**Comment by bobbrow** [comment]
The link on MSDN appears to be fixed now.  The page describing IASetPrimitiveTopology now points to D3D_PRIMITIVE_TOPOLOGY.

https://msdn.microsoft.com/en-us/library/windows/desktop/dn903885(v=vs.85).aspx
