### ISSUE TITLE
directinput vs. rawinput in Miniengine

### ISSUE THREAD

**Issue by jmkinzer** [Microsoft/DirectX-Graphics-Samples#102]
As I understand it directinput is deprecated and the general consensus is that for keyboard/mouse raw input is that preferred approach. Is there a specific reason why Miniengine is using directinput and might it serve as a a better example if it were using raw input instead?

**Comment by stanard** [comment]
The mouse and keyboard input handling was some legacy code we had lying around.  Our path going forward will be to embrace WinRT APIs for keyboard, mouse, and gamepad input.  This will unify more of the engine with some Xbox-specific code paths that aren't present on GitHub (though you might have seen references to Xbox scattered around.)

**Comment by jmkinzer** [comment]
That will be great to see. Thanks!
