### ISSUE TITLE
Hope you can recommend me some good tutorials for beginners.

### ISSUE THREAD

**Issue by HppZ** [Microsoft/DirectX-Graphics-Samples#103]
I am planning to buy this book "Introduction to 3D Game Programming with DirectX 12", any other great tutorials online for beginners, please?

**Comment by lijipeng787** [comment]
If you have some experience about programing with DirectX 11, and assume you have accumulate some dx11 application code(some relative small tech demo,for example)，you can rewrite these demo with DirectX 12.
Recommend online tutorials: [http://www.rastertek.com/index.html](url)
The website provides 50 DirectX 11 samples for beginners,all of these samples can rewrite easily with new version of DirectX API.

**Comment by HppZ** [comment]
Thanks for your reply!  I do not have any experience about DirectX, but I want to do it.

**Comment by DrGr4f1x** [comment]
I recommend learning DirectX 11 first, it's still very relevant.  Understanding DX11 will make learning DX12 a lot easier.  The DirectX 11 version of that book you mentioned is very good, I recommend it.

Source code is the best resource for learning DX11/12.  There is a ton of sample code out there - look for demos from Microsoft, NVIDIA, and AMD.  You'll find plenty.

**Comment by lijipeng787** [comment]
I'm agreed with DrGr4f1x.
《Introduction to 3D Game Programming with DirectX 11》is enough for beginner.
You can also use《Practical Rendering and Computation with Direct3D 11》for more deeper study.
And another online tutorials:[http://www.braynzarsoft.net/viewtutorial/q16390-braynzar-soft-directx-11-tutorials](url).

**Comment by HppZ** [comment]
Thank you both. 
@bobbrow  you said you will give me a response here, please. Thank you!

**Comment by bobbrow** [comment]
Same as @lijipeng787, I was going to recommend starting with the Direct3D 11 version of the book you referenced.  You'll find it much easier to learn Direct3D 12 if you already have a solid understanding the graphics pipeline.

For samples/tutorials, Chuck Walbourn (MSFT) runs a DirectX development blog and has a good page with lots of links to information for starting out with Direct3D 11 [here] (http://blogs.msdn.com/b/chuckw/archive/2011/07/11/getting-started-with-direct3d-11.aspx).

**Comment by HppZ** [comment]
Thanks again to all of you great guys.

**Comment by bipul-mohanto** [comment]
@HppZ , thanks! I am currently in the same phase as u were in 2016. Hope you are an expert now.

**Comment by bipul-mohanto** [comment]
> You may find _DirectX Tool Kit_ useful. There's both a [DirectX 11](https://github.com/microsoft/DirectXTK/wiki/Getting-Started) and a [DirectX 12](https://github.com/microsoft/DirectXTK12/wiki/Getting-Started) version.

Hi @walbourn , do you have any suggested tutorial about directx raytracing api?
