### ISSUE TITLE
noncopyable classes

### ISSUE THREAD

**Issue by jmkinzer** [Microsoft/DirectX-Graphics-Samples#104]
So I just spent a while debugging a crash due to acidentally copying CommandContext. This class (and probably some others) should really be non-copyable to make it more fool-proof, e.g.

struct NonCopyable {
	NonCopyable() = default;
	NonCopyable(const NonCopyable&) = delete;
	NonCopyable & operator=(const NonCopyable&) = delete;
};
class CommandContext : NonCopyable

Can you ensure all non-copyable classes are explictly made such?

**Comment by stanard** [comment]
That's a great idea!  I'll make that change.

**Comment by jmkinzer** [comment]
Thanks!
