### ISSUE TITLE
Placed resources sample crashes AMD drivers

### ISSUE THREAD

**Issue by alessiot89** [Microsoft/DirectX-Graphics-Samples#107]
Driver version: 15.301.1801.1001
On WARP device works fine, but with hardware device when m_usePlacedResources is true (line 350 of D3D12SmallResources.cpp) the AMD driver crashes inexorably.

**Comment by bobbrow** [comment]
Thanks for the report.  I was testing on 15.300.1025.1001 and it was working fine.  I'll pass the bug on to AMD.

**Comment by alessiot89** [comment]
I forgot to mention, the device is PCI\VEN_1002&DEV_679A&SUBSYS_A003174B&REV_00

**Comment by alessiot89** [comment]
AMD Crimson 16.3 drivers finally support 4K alignment.
