### ISSUE TITLE
ExecuteIndirect: The TriangleCount should be a particular value

### ISSUE THREAD

**Issue by koverlu** [Microsoft/DirectX-Graphics-Samples#108]
The CounterOffsetInBytes must be a multiple of D3D12_UAV_COUNTER_PLACEMENT_ALIGNMENT (4096), when create UVA.
So the TriangleCount should make the constant CounterOffsetInBytes to be a multiple of 4k.
If we create another buffer and use it as the counter resource, the triangle count can be any value.
Why not?

**Comment by bobbrow** [comment]
Are you asking why we didn't split the UAV and the counter into separate buffers?  Memory savings was the primary driver.  It seemed excessive to allocate a 64K heap/resource just for a counter when you can potentially save space by aligning it to a 4K boundary in the existing heap for the UAV.  I think it would be better to just make the sample more robust by adding a bit of logic to align the counter for cases when the triangle count is set to something other than 1024.  Expect an update this week.

(BTW, sorry for the delayed response.  I was at a conference last week and I did see your question while checking my mail.  I even wrote a response, but clearly I forgot to click the "comment" button before shutting down my laptop.)

**Comment by koverlu** [comment]
Thank you for answering.
You mean that if we allocate a new heap/resource, it will be 64K aligned. So it will be waste for the counter may only need 2 DWORDS.
But I don't know this 64K aligning is request by whom. IHV? or WDDM2.0?

**Comment by bobbrow** [comment]
I submitted a change that allows you to change the TriangleCount.
