### ISSUE TITLE
Several samples output EXECUTION ERROR #552: COMMAND_ALLOCATOR_SYNC

### ISSUE THREAD

**Issue by trond** [Microsoft/DirectX-Graphics-Samples#109]
On my Asus G551JM laptop, running the samples **D3DHelloTriangle**, **D3D12HelloFrameBuffering** or **D3D12HelloTexture**, I get spammed with the following D3D12 error when the NVIDIA GPU is used ( GTX 860M driver 361.91 ):

**D3D12 ERROR: ID3D12CommandAllocator::Reset: A command allocator is being reset before previous executions associated with the allocator have completed. [ EXECUTION ERROR #552: COMMAND_ALLOCATOR_SYNC]**

The error does not appear if I use the WARP device or hack the sample to use the Intel HD 4600 adapter.

    dxcap -info 

    System32 Info
    =============
    DxCap.exe                       : 10.0.10586.11 (11/13/15 6:52 AM) 869 KB
    DxCaptureReplay.dll             : 10.0.10586.11 (11/13/15 6:51 AM) 8,374 KB
    DxToolsMonitor.dll              : 10.0.10586.11 (11/13/15 6:55 AM) 176 KB
    DxToolsOfflineAnalysis.dll      : 10.0.10586.11 (11/13/15 6:53 AM) 1,049 KB
    DxToolsReportGenerator.dll      : 10.0.10586.0 (10/29/15 8:12 PM) 95 KB
    DxToolsReporting.dll            : 10.0.10586.11 (11/13/15 6:57 AM) 156 KB
    perf_gputiming.dll              : 10.0.10586.0 (10/29/15 7:34 PM) 338 KB
    VsGraphicsCapture.dll           : 10.0.10586.11 (11/13/15 6:54 AM) 154 KB
    VsGraphicsExperiment.dll        : 10.0.10586.11 (11/13/15 6:53 AM) 711 KB
    VsGraphicsProxyStub.dll         : 10.0.10586.0 (10/29/15 7:37 PM) 88 KB
    VsGraphicsRemoteEngine.exe      : 10.0.10586.11 (11/13/15 6:50 AM) 5,433 KB
    d3d11_3sdklayers.dll            : 10.0.10586.0 (10/29/15 7:12 PM) 1,308 KB
    d3d12SDKLayers.dll              : 10.0.10586.0 (10/29/15 7:13 PM) 979 KB
    d3d12warp.dll                   : 10.0.10586.0 (10/29/15 7:28 PM) 3,216 KB
    d2d1debug3.dll                  : 10.0.10586.0 (10/29/15 7:30 PM) 420 KB
    dxgidebug.dll                   : 10.0.10586.0 (10/29/15 7:37 PM) 337 KB

**Comment by bobbrow** [comment]
It certainly sounds like a driver issue.  Thanks for reporting it!  I'll try to get a repro in-house to send over to NVidia.

**Comment by trond** [comment]
Great, thanks!

**Comment by justxyz** [comment]
If swapchain buffer count == 2 will has [EXECUTION ERROR #552: COMMAND_ALLOCATOR_SYNC], but swapchain buffer count == 3 no problem.
So why? any one can explain it?

**Comment by nikitablack** [comment]
I have the same problem. Suddenly I started to receive this messages, thought everything worked ok before. Even in `HelloWindow` sample I have `GT 740M` adapter with `368.22` driver, `Windows 10 Pro 1511` build `10586.318`.

```
System32 Info
=============
DxCap.exe                       : 10.0.10586.11 (11/13/15 7:52) 869 KB
DxCaptureReplay.dll             : 10.0.10586.11 (11/13/15 7:51) 8,374 KB
DxToolsMonitor.dll              : 10.0.10586.11 (11/13/15 7:55) 176 KB
DxToolsOfflineAnalysis.dll      : 10.0.10586.11 (11/13/15 7:53) 1,049 KB
DxToolsReportGenerator.dll      : 10.0.10586.0 (10/29/15 21:12) 95 KB
DxToolsReporting.dll            : 10.0.10586.11 (11/13/15 7:57) 156 KB
perf_gputiming.dll              : 10.0.10586.0 (10/29/15 20:34) 338 KB
VsGraphicsCapture.dll           : 10.0.10586.11 (11/13/15 7:54) 154 KB
VsGraphicsExperiment.dll        : 10.0.10586.11 (11/13/15 7:53) 711 KB
VsGraphicsProxyStub.dll         : 10.0.10586.0 (10/29/15 20:37) 88 KB
VsGraphicsRemoteEngine.exe      : 10.0.10586.11 (11/13/15 7:50) 5,433 KB
d3d11_3sdklayers.dll            : 10.0.10586.0 (10/29/15 20:12) 1,308 KB
d3d12SDKLayers.dll              : 10.0.10586.122 (02/23/16 9:21) 979 KB
d3d12warp.dll                   : 10.0.10586.0 (10/29/15 20:28) 3,216 KB
d2d1debug3.dll                  : 10.0.10586.0 (10/29/15 20:30) 420 KB
dxgidebug.dll                   : 10.0.10586.0 (10/29/15 20:37) 337 KB
```

**Comment by bobbrow** [comment]
I am able to reproduce this issue.  You should only ever see this on a laptop with both a discrete and an integrated GPU in it.  We have a fix for this timing issue and it should be available in the Windows Update coming out next week.  Look for KB 3163018 on Patch Tuesday (next week).

**Comment by nikitablack** [comment]
Thanks @bobbrow, I'll wait for this patch. And will post the result here and [here (#162)](https://github.com/Microsoft/DirectX-Graphics-Samples/issues/162).

**Comment by nikitablack** [comment]
Hi, I'm confirming that KB 3163018 removed this warning for me. I tested HelloWorld samples - all works fine.

**Comment by trond** [comment]
Yeah, that did the trick, thanks!

**Comment by bobbrow** [comment]
Thanks for verifying!
