### ISSUE TITLE
VS 2015 graphics debugger crashing on call of map function

### ISSUE THREAD

**Issue by Yoshusa** [Microsoft/DirectX-Graphics-Samples#110]
Dear Microsoft Team,

Take the following code and add it to the begin of the LoadAssets method of the HelloTriangle example (or any other of the hello world examples):

    HRESULT NativeResult;

    D3D12_HEAP_PROPERTIES NativeUploadHeapProperties;
        
    NativeUploadHeapProperties.Type                 = D3D12_HEAP_TYPE_UPLOAD;
    NativeUploadHeapProperties.CPUPageProperty      = D3D12_CPU_PAGE_PROPERTY_UNKNOWN;
    NativeUploadHeapProperties.MemoryPoolPreference = D3D12_MEMORY_POOL_UNKNOWN;
    NativeUploadHeapProperties.CreationNodeMask     = 0;
    NativeUploadHeapProperties.VisibleNodeMask      = 0;

    D3D12_RESOURCE_DESC NativeUploadResourceDescriptor;

    NativeUploadResourceDescriptor.Dimension          = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
    NativeUploadResourceDescriptor.Alignment          = 0;
    NativeUploadResourceDescriptor.Width              = 1024;
    NativeUploadResourceDescriptor.Height             = 1024;
    NativeUploadResourceDescriptor.DepthOrArraySize   = 1;
    NativeUploadResourceDescriptor.MipLevels          = 1;
    NativeUploadResourceDescriptor.Format             = DXGI_FORMAT_R8G8B8A8_UNORM;
    NativeUploadResourceDescriptor.SampleDesc.Count   = 1;
    NativeUploadResourceDescriptor.SampleDesc.Quality = 0;
    NativeUploadResourceDescriptor.Layout             = D3D12_TEXTURE_LAYOUT_UNKNOWN;
    NativeUploadResourceDescriptor.Flags              = D3D12_RESOURCE_FLAG_NONE;

    ComPtr<ID3D12Resource> NativeUploadResourcePtr;

    NativeResult = m_device->CreateCommittedResource(&NativeUploadHeapProperties, D3D12_HEAP_FLAG_NONE, &NativeUploadResourceDescriptor, D3D12_RESOURCE_STATE_GENERIC_READ, nullptr, IID_PPV_ARGS(&NativeUploadResourcePtr));

    CD3DX12_RANGE NativeRange(0, 0);

    NativeResult = NativeUploadResourcePtr->Map(0, &NativeRange, nullptr);

Running this piece of code without the graphics debugger returns s_OK for all NativeResult values, but the graphics debugger crashes on the Map function with a null pointer exception.
Reading the documentation I thought it was ok to map textures with unknow texture layout, as long as I do not expect a CPU pointer in return and have a zero read range. After the Map Operation I wanted to use the WriteToSubresource method. But maybe I am wrong with this approach.

What I want to do is the following: I have a texture array, whose textures can be edited by the user (terrain materials in a game engine). When the user selects a new material then I have to update some slots in the texture array. My workaround is now to use intermediate buffers for upload, but looking at the code of the UpdateSubresources method I think that mapping an upload texture plus WriteToSubresource would be faster.

Kind Regards,

Joerg Sahm

**Comment by bobbrow** [comment]
I'm surprised you're seeing S_OK for CreateCommittedResource.  I get E_INVALIDARG when I run this on my machine.  Have you run this snippet with the debug layers on?  If you do, you will see the reason why:

D3D12 ERROR: ID3D12Device::CreateCommittedResource: A texture resource cannot be created on a D3D12_HEAP_TYPE_UPLOAD or D3D12_HEAP_TYPE_READBACK heap. Investigate CopyTextureRegion to copy texture data in CPU accessible buffers, or investigate D3D12_HEAP_TYPE_CUSTOM and WriteToSubresource for UMA adapter optimizations. [ STATE_CREATION ERROR #638: CREATERESOURCEANDHEAP_INVALIDHEAPPROPERTIES]

**Comment by Yoshusa** [comment]
Hi Bob,

that is really strange. Yes, the debug layer is on. I added the code to the begin of the LoadAssets method of the HelloTriangle sample. All native results are s_OK and the debug layer states nothing.

I attached a screenshot of my debug view and also the system info and dxdiag info. I'am using the Windows SDK 10586. NVidia driver and operating system should be on the newest version.

Is maybe something wrong with my software installation? Or are there known interferences with NSight?

Grettings,

Joerg

![issue](https://cloud.githubusercontent.com/assets/9078369/13569028/be2eeda8-e465-11e5-8ab1-298f4355c0ca.jpg)
[system_info.txt](https://github.com/Microsoft/DirectX-Graphics-Samples/files/161240/system_info.txt)
[dx_diag.txt](https://github.com/Microsoft/DirectX-Graphics-Samples/files/161241/dx_diag.txt)

**Comment by bobbrow** [comment]
The two things different I see so far is that you are running Windows 10 without the November update, and you are using Visual Studio 2015 Update 2 RC.  I would be more willing to bet that this is a difference between build 10240 (which you have) and build 10586 (which I have).  We tightened up validation between July and November.  I recommend you install the November update.

Do note that after you upgrade, you will need to reinstall the Graphics Tools optional feature (via the Settings app) to get the SDK layers back.  If you're still having trouble after this, please run ```dxcap -info``` and share what you see in the "System32 Info" section.

**Comment by Yoshusa** [comment]
Hi Bob,

sorry for the late response. I've had some nasty exceptions while trying to upgrade my system to 10586, so I decided to reinstall it. Yes, you are right, I now get the same debug layer output as on your system.

I will close the issue. However, please consider the following notes:
- I think, this restriction is worth to mention it in the remarks section of the CreateCommittedResource method documentation (and also in the docs of the other methods for resource creation).
- I would like to have a best practice sample about streaming textures (not only updating a complete texture, but also updating parts of a mega texture or clip map). Getting footprints and copying texture data row-wise as in the UpdateSubresources method seems inefficient to me (though I am aware, that this is maybe the only chance to do it in a hardware independent way).

Greetings,

Joerg
