### ISSUE TITLE
Problem defining root signature in HLSL file

### ISSUE THREAD

**Issue by Yoshusa** [Microsoft/DirectX-Graphics-Samples#111]
Dear Microsoft Team,

I use the following simplified HLSL Code, which is defined in a file named "tone_mapping.fx":

```
Texture2D ps_LightAccumulationTexture : register(t0);

sampler ps_MinMagMipPointClampSampler : register(s0);

cbuffer PSConstantBuffer : register(b0)
{
    float4 ps_Constant0; // Just a dummy constant due to simplified code
};

#define ToneMappingSignature                                                                                                     \
    "RootFlags(ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT),                                                                            " \
    "DescriptorTable(CBV(b0), SRV(t0), visibility = SHADER_VISIBILITY_PIXEL),                                                  " \
    "StaticSampler(s0, addressU = TEXTURE_ADDRESS_CLAMP, addressV = TEXTURE_ADDRESS_CLAMP, filter = FILTER_MIN_MAG_MIP_POINT), " \

struct PSInput
{
    float4 m_Position : SV_POSITION;
    float2 m_TexCoord : TEXCOORD0;
};

[RootSignature(ToneMappingSignature)]
PSInput VSShader(uint _VertexID : SV_VERTEXID)
{
    PSInput Output;

    Output.m_TexCoord = float2(_VertexID & 1, (_VertexID & 2) >> 1);
    Output.m_Position = float4(Output.m_TexCoord * float2(2.0f, -2.0f) + float2(-1.0f, 1.0f), 0.0f, 1.0f);

    return Output;
}

[RootSignature(ToneMappingSignature)]
float4 PSShader(PSInput _Input) : SV_Target
{
    float3 LinearColor;
    float3 ToneMappedColor;
    float3 Color;

    LinearColor = ps_LightAccumulationTexture.SampleLevel(ps_MinMagMipPointClampSampler, _Input.m_TexCoord, 0).rgb;
    
    // ToneMappedColor = GetFilmicToneMapping(LinearColor);
    // Color           = LinearToSRGB(ToneMappedColor);

    Color = LinearColor;

    return float4(Color, 1.0f);
}
```
Now I want to compile the shader and extract the root signature with the following piece of C++ code:
```
unsigned int                Flags;
HRESULT                     NativeResult;
ComPtr<ID3DBlob>            NativeCodeBlobPtr;
ComPtr<ID3DBlob>            NativeErrorBlobPtr;
ComPtr<ID3DBlob>            NativeRootSignatureBlobPtr;
ComPtr<ID3D12RootSignature> NativeRootSignaturePtr;

Flags = D3DCOMPILE_PACK_MATRIX_ROW_MAJOR | D3DCOMPILE_WARNINGS_ARE_ERRORS | D3DCOMPILE_ENABLE_STRICTNESS | D3DCOMPILE_OPTIMIZATION_LEVEL3;

NativeResult = ::D3DCompileFromFile(L"tone_mapping.fx", nullptr, nullptr, "VSShader", "vs_5_1", Flags, 0, &NativeCodeBlobPtr, &NativeErrorBlobPtr);
NativeResult = ::D3DGetBlobPart(NativeCodeBlobPtr->GetBufferPointer(), NativeCodeBlobPtr->GetBufferSize(), D3D_BLOB_ROOT_SIGNATURE, 0, &NativeRootSignatureBlobPtr);
NativeResult = pNativeDevice->CreateRootSignature(0, NativeRootSignatureBlobPtr->GetBufferPointer(), NativeRootSignatureBlobPtr->GetBufferSize(), IID_PPV_ARGS(&NativeRootSignaturePtr));
```
The CreateRootSignature method fails, though the NativeRootSignatureBlobPtr was filled successfully. I get the same issue when replacing D3DGetBlobPart with D3DStripShader. Again the last call fails:
```
unsigned int                Flags;
HRESULT                     NativeResult;
ComPtr<ID3DBlob>            NativeCodeBlobPtr;
ComPtr<ID3DBlob>            NativeErrorBlobPtr;
ComPtr<ID3DBlob>            NativeRootSignatureBlobPtr;
ComPtr<ID3D12RootSignature> NativeRootSignaturePtr;

Flags = D3DCOMPILE_PACK_MATRIX_ROW_MAJOR | D3DCOMPILE_WARNINGS_ARE_ERRORS | D3DCOMPILE_ENABLE_STRICTNESS | D3DCOMPILE_OPTIMIZATION_LEVEL3;

NativeResult = ::D3DCompileFromFile(L"tone_mapping.fx", nullptr, nullptr, "VSShader", "vs_5_1", Flags, 0, &NativeCodeBlobPtr, &NativeErrorBlobPtr);
NativeResult = ::D3DStripShader(NativeCodeBlobPtr->GetBufferPointer(), NativeCodeBlobPtr->GetBufferSize(), D3DCOMPILER_STRIP_ROOT_SIGNATURE, &NativeRootSignatureBlobPtr);
NativeResult = pNativeDevice->CreateRootSignature(0, NativeRootSignatureBlobPtr->GetBufferPointer(), NativeRootSignatureBlobPtr->GetBufferSize(), IID_PPV_ARGS(&NativeRootSignaturePtr));
```
Surprisingly (at least for me) the CreateRootSignature signature succeeds if I pass the complete compiled shader code:
```
unsigned int                Flags;
HRESULT                     NativeResult;
ComPtr<ID3DBlob>            NativeCodeBlobPtr;
ComPtr<ID3DBlob>            NativeErrorBlobPtr;
ComPtr<ID3D12RootSignature> NativeRootSignaturePtr;

Flags = D3DCOMPILE_PACK_MATRIX_ROW_MAJOR | D3DCOMPILE_WARNINGS_ARE_ERRORS | D3DCOMPILE_ENABLE_STRICTNESS | D3DCOMPILE_OPTIMIZATION_LEVEL3;

NativeResult = ::D3DCompileFromFile(L"tone_mapping.fx", nullptr, nullptr, "VSShader", "vs_5_1", Flags, 0, &NativeCodeBlobPtr, &NativeErrorBlobPtr);
NativeResult = pNativeDevice->CreateRootSignature(0, NativeCodeBlobPtr->GetBufferPointer(), NativeCodeBlobPtr->GetBufferSize(), IID_PPV_ARGS(&NativeRootSignaturePtr));
```
However, this is not an option for me, because I cannot access the serialized byte code of the root signature to create a hash value (I want to avoid redundant root signatures).

Compiling the root signature explicitely also works:
```
unsigned int                Flags;
HRESULT                     NativeResult;
ComPtr<ID3DBlob>            NativeRootSignatureBlobPtr;
ComPtr<ID3DBlob>            NativeErrorBlobPtr;
ComPtr<ID3D12RootSignature> NativeRootSignaturePtr;

Flags = D3DCOMPILE_PACK_MATRIX_ROW_MAJOR | D3DCOMPILE_WARNINGS_ARE_ERRORS | D3DCOMPILE_ENABLE_STRICTNESS | D3DCOMPILE_OPTIMIZATION_LEVEL3;

NativeResult = ::D3DCompileFromFile(L"tone_mapping.fx", nullptr, nullptr, "ToneMappingSignature", "rootsig_1_0", Flags, 0, &NativeRootSignatureBlobPtr, &NativeErrorBlobPtr);
NativeResult = pNativeDevice->CreateRootSignature(0, NativeRootSignatureBlobPtr->GetBufferPointer(), NativeRootSignatureBlobPtr->GetBufferSize(), IID_PPV_ARGS(&NativeRootSignaturePtr));
```
But this would require a second compile step and additionally parsing the name of the root signature from the HLSL code.

I was irritated by the DirectX 12 documentation of the D3DGetBlobPart function, because it states for the first two arguments to pass the uncompiled ASCII HLSL code (the same for the D3DStripShader method). This does not fit my code samples, cause there I always use the compiled shader code.

Please tell me if I am just getting it wrong or if this is a DirectX 12 issue.

Kind regards,

Joerg Sahm

**Comment by Yoshusa** [comment]
Dear Microsoft Team,

I have done some further research and compared the content of the serialized root signature blob returned by D3DGetBlobPart (first C++ code piece) with the one returned by D3DCompileFromFile when explicitely compiling the root signature (fourth C++ code piece). The first approach returns a blob with 136 bytes, the fourth approach a blob with 180 bytes. When starting with an offset of 44 bytes in the 180 bytes blob the contents of the two blobs are completely identical.

Kind regards,

Joerg Sahm

**Comment by Yoshusa** [comment]
Dear Microsoft Team,

and here goes another comment to my post :)

I've created the same root signature via different methods (e.g. via code piece 3 and code piece 4), and as result I got identical NativeRootSignaturePtr values. So it seems to me, that DirectX is already hashing the root signatures internally and I could go with approach number 3, i.e. simply passing the compiled shader byte code to the CreateRootSignature method.

Can I be sure for 100%, that DirectX is hashing root signatures on all systems and platforms? I have checked the documentation but could not find a hint to this. Otherwise my workaround would be to call D3DGetBlobPart on all blobs containing a root signature (calling D3DGetBlobPart on a serialized blob created via D3D12SerializeRootSignature works fine and returns exactly the same byte block as if calling D3DGetBlobPart  on the compiled shader byte code). Then I would hash the resulting byte block myself.

And finally an explanation to all my questions :)

I am currently porting our game engine from DX 11 to DX 12. Reading the documentation about root signatures I favorized their definition in HLSL for two reasons:
- The root signature definition in HLSL is pretty compact.
- Maybe I can avoid recompiling the C++ code at least for minor changes of the signatures. This point is important to me not only because of compiling times, but also because of flexibility. In our editor artists can define new materials and shaders at runtime (similar to blue prints in Unreal) and therefore recompiling the C++ code is a no-go.

At the current state of the port I am not 100% sure, that all root signatures are defined in HLSL. So maybe we end up with a mixture of signatures defined in C++ and signatures defined in HLSL. In both cases I want to be sure to avoid the creation of redundant signatures.

Sorry for all the text,

Joerg Sahm

**Comment by bobbrow** [comment]
Not to worry about all the text.  Sorry I wasn't able to get back to you sooner.  It's been a pretty busy week for us.

I'm going to have to talk to the compiler guys about this.  This area isn't my specialty.  I just thought I would reply before the weekend hits and let you know that I have seen your post and will get back to you.

**Comment by Yoshusa** [comment]
Hi Bob,

thanks for your reply. I am currently using the third approach, i.e. passing the compiled shader byte code to the CreateRootSignature method. This works fine as long as I do not run the graphics debugger. Take the following C++ code and add it to the begin of the LoadAssets method of the HelloTriangle sample:

```
unsigned int                Flags;
HRESULT                     NativeResult;
ComPtr<ID3DBlob>            NativeShaderCodeBlobPtr;
ComPtr<ID3DBlob>            NativeRootSignatureBlobPtr;
ComPtr<ID3DBlob>            NativeErrorBlobPtr;
ComPtr<ID3D12RootSignature> NativeRootSignatureAPtr;
ComPtr<ID3D12RootSignature> NativeRootSignatureBPtr;

Flags = D3DCOMPILE_PACK_MATRIX_ROW_MAJOR | D3DCOMPILE_WARNINGS_ARE_ERRORS | D3DCOMPILE_ENABLE_STRICTNESS | D3DCOMPILE_OPTIMIZATION_LEVEL3;

NativeResult = ::D3DCompileFromFile(L"tone_mapping.fx", nullptr, nullptr, "PostFXRootSignature", "rootsig_1_0", Flags, 0, &NativeRootSignatureBlobPtr, &NativeErrorBlobPtr);
NativeResult = m_device->CreateRootSignature(0, NativeRootSignatureBlobPtr->GetBufferPointer(), NativeRootSignatureBlobPtr->GetBufferSize(), IID_PPV_ARGS(&NativeRootSignatureAPtr));
NativeResult = ::D3DCompileFromFile(L"tone_mapping.fx", nullptr, nullptr, "VSShader", "vs_5_0", Flags, 0, &NativeShaderCodeBlobPtr, &NativeErrorBlobPtr);
NativeResult = m_device->CreateRootSignature(0, NativeShaderCodeBlobPtr->GetBufferPointer(), NativeShaderCodeBlobPtr->GetBufferSize(), IID_PPV_ARGS(&NativeRootSignatureBPtr));
```
Also take the following shader code:
```
#ifndef __INCLUDE_HLSL_POSTFX_TONE_MAPPING_H_
#define __INCLUDE_HLSL_POSTFX_TONE_MAPPING_H_

#define PostFXRootSignature                                                                                                    \
    "RootFlags(ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT),                                                                          " \
    "DescriptorTable(CBV(b0, numDescriptors = 2)),                                                                           " \
    "RootConstants(num32BitConstants=1, b2, visibility = SHADER_VISIBILITY_PIXEL),                                           " \
    "DescriptorTable(SRV(t0, numDescriptors = 20), visibility = SHADER_VISIBILITY_PIXEL),                                    " \
    "StaticSampler(s0, addressU = TEXTURE_ADDRESS_CLAMP, addressV = TEXTURE_ADDRESS_CLAMP, filter = FILTER_MIN_MAG_MIP_POINT)"

cbuffer PostFXConstantBuffer : register(b1)
{
    float4 g_Constant0;
};

cbuffer g_RootSignatureConstantBuffer : register(b2)
{
    uint g_WindowBaseOffset;
}

Texture2D g_WindowDependentTextures[20] : register(t0);

sampler g_MinMagMipPointClampSampler : register(s0);

struct PSInput
{
    float4 m_Position : SV_POSITION;
    float2 m_TexCoord : TEXCOORD0;
};

[RootSignature(PostFXRootSignature)]
PSInput VSShader(uint _VertexID : SV_VERTEXID)
{
    PSInput Output;

    Output.m_TexCoord = float2(_VertexID & 1, (_VertexID & 2) >> 1);
    Output.m_Position = float4(Output.m_TexCoord * float2(2.0f, -2.0f) + float2(-1.0f, 1.0f), 0.0f, 1.0f);

    return Output;
}

[RootSignature(PostFXRootSignature)]
float4 PSShader(PSInput _Input) : SV_Target
{
    float3 Color;

    Color = float3(((float) g_WindowBaseOffset) / 255.0f,0,0);

    return float4(Color, 1.0f);
}

#endif // __INCLUDE_HLSL_POSTFX_TONE_MAPPING_H_
```
There are some important notes: 
- The code runs fine if not using the graphics debugger
- If running the sample with the graphics debugger I get a GRFXTool::ToolException at the last line
- NativeRootSignatureAPtr and NativeRootSignatureBPtr point to the same address, so DirectX identifies that the same root signature is created
- If replacing NativeRootSignatureAPtr and NativeRootSignatureBPtr by a single NativeRootSignaturePtr even the graphics debugger runs fine, cause the previous created root signature is released before creating the second one

Should I open a new issue for this?

Greetings,

Joerg

**Comment by bobbrow** [comment]
I talked to a couple of people on the compiler and D3D teams about your issue.  To answer your earlier question:
> Can I be sure for 100%, that DirectX is hashing root signatures on all systems and platforms?
Yes, you can be sure that DirectX is hashing root signatures so you don't need to do this yourself. In your case, you should be able to pass in either of your compiled shaders and get the same result.  There should be no need to compile just the root signature out of the .fx file.

I can reproduce the exception in the graphics debugger with the information you have provided, so I can take it from here.  Fortunately, you should be able to workaround this issue by not creating the same root signature twice.  Will this work for you?

**Comment by Yoshusa** [comment]
Hi Bob,

thank you, yes, i can work with that. The issue was mainly a result of my experiments to get the easiest way to define root signatures. I will close the issue.

Greetings,

Joerg
