### ISSUE TITLE
Setting texture from a bitmap in GenerateTextureData()

### ISSUE THREAD

**Issue by bofinbabu** [Microsoft/DirectX-Graphics-Samples#115]
I plan to load an image using WIC and get the texture data so that I can display the image in the triage region, instead of the boxes.

I've loaded my image in 32bppPRGBA. But when I run the program I'm only seeing some gray scale pixels.

Here my modified  GenerateTextureData() function.

```
std::vector<UINT8> D3D12HelloTexture::GenerateTextureData()
{ 
	
	const UINT rowPitch = TextureWidth * TexturePixelSize;
	const UINT cellPitch = rowPitch >> 3;		// The width of a cell in the checkboard texture.
	const UINT cellHeight = TextureWidth >> 3;	// The height of a cell in the checkerboard texture.
	const UINT textureSize = rowPitch * TextureHeight;
	
	HRESULT hr;
	HANDLE hd;

	std::vector<UINT8> data(textureSize);
	UINT8* pData = &data[0];

	//Load image
		IWICImagingFactory * pFactory = nullptr;
		IWICBitmapDecoder * pDecoder = nullptr;
		IWICBitmapFrameDecode * pSource = nullptr;
		IWICStream * pStream = nullptr;
		IWICFormatConverter * pConverter = nullptr;
		IWICBitmapScaler * pScaler = nullptr;
		UINT width = 0;
		UINT height = 0;
		WICPixelFormatGUID pixelFormat;
		DXGI_FORMAT format;

		hr = CoCreateInstance(CLSID_WICImagingFactory, nullptr, CLSCTX_INPROC_SERVER, IID_PPV_ARGS(&pFactory));


		//Open the file - Make sure the file is in the same diretory


		hd = CreateFile2(L"1.jpg", GENERIC_READ, FILE_SHARE_READ, OPEN_EXISTING, nullptr);

		pFactory->CreateDecoderFromFilename(L"1.jpg", nullptr, GENERIC_READ, WICDecodeMetadataCacheOnLoad, &pDecoder);

		//Get the first frame (useful for cases when the image is gif)
		pDecoder->GetFrame(0, &pSource);

		//Create a converter
		pFactory->CreateFormatConverter(&pConverter);

		//Use the converter to convert image to 32ppPBGRA
		hr = pConverter->Initialize(pSource, GUID_WICPixelFormat32bppPBGRA, WICBitmapDitherTypeNone, nullptr, 0.f, WICBitmapPaletteTypeMedianCut);

		hr = pSource->GetSize(&width, &height);

		assert((width > 0) && (height > 0));

		WICRect rt = { 0 };
		rt.Height = height;
		rt.Width = width;

		//Use CopyPixels to copy the pixels to the new array
		UINT bSize = 0;
		
		UINT rowPitch1 = 4 * width;
		UINT stride = 0; // stride  = bytes per row
						 // (width * (bpp/8)) + padding and round to the nearest DWORD
		stride = ((((width * 32) + 31) & ~31) >> 3);
		bSize = height*stride;
				
		BYTE *pixels = new BYTE[height*stride]();
		
		pSource->CopyPixels(&rt, stride, bSize, pixels);
		 		
                //My image is small, bSize is less than textureSize
		for (UINT n = 0; n < bSize; n += TexturePixelSize)
	{
		
		pData[n] = pixels[n];
		//memcpy(&pData[n], &pixels[n], sizeof(BYTE)*4);
               /*
		pData[n] = pixels[n]; 	// R
		pData[n + 1] = 0x00;	// G
		pData[n + 2] = 0xf3;	// B
		pData[n + 3] = 0x99;	// A
		/*
		UINT x = n % rowPitch;
		UINT y = n / rowPitch;
		UINT i = x / cellPitch;
		UINT j = y / cellHeight;

		if (i % 2 == j % 2)
		{
			pData[n] = pixels[n];//0x00;		// R
			pData[n + 1] = pixels[n +1]; //0x00;	// G
			pData[n + 2] = pixels[n +2]; //0xf3;	// B
			pData[n + 3] = pixels[n +3]; //0x99;	// A
		}
		else
		{
			pData[n] = pixels[n];//0x00;		// R
			pData[n + 1] = pixels[n + 1]; //0x00;	// G
			pData[n + 2] = pixels[n + 2]; //0xf3;	// B
			pData[n + 3] = pixels[n + 3]; //0x99;	// A
			/*
			pData[n] = 0xff;		// R
			pData[n + 1] = 0xff;	// G
			pData[n + 2] = 0x88;	// B
			pData[n + 3] = 0xff;	// A
			
		}
		*/

		
	}
	delete[] pixels;
	
    
	return data;
}
```

What would be the problem?

**Comment by zao** [comment]
Most of your code is dead, which doesn't make it easier to find the problem.

You're assigning only one out of TexturePixelSize bytes of the pixel. Inspect the contents of the array as your code runs in the debugger with a small handcrafted test file and you should be able to spot how your data ends up wrong.

If you have problems once you've gotten your source data in shape, then this issue is relevant to the project.

**Comment by bofinbabu** [comment]
Thank for your suggestion.
Instead of 

```
 pData[n] = pixels[n]
```
I did,

```
pData[n] = pixels[n];
pData[n+1] = pixels[n+1]
pData[n+2] = pixels[n+2]
pData[n+3] = pixels[n+3]
```
And still my output is the same. See the screenshot (attachment). Any suggestions? Image is loading part is fine. I checked it with break points and HR is returning S_OK. I guess I'm missing something here..
Original Image
![1](https://cloud.githubusercontent.com/assets/5749350/13629356/9d67ab4c-e5fe-11e5-99be-941a18343345.jpg)

Output
![capture123](https://cloud.githubusercontent.com/assets/5749350/13629326/65f2c426-e5fe-11e5-8e84-0aac249f44f4.PNG)

**Comment by ClemensX** [comment]
Looks like the two textures have different size. Your image has a 225*225 pixel size. D3D12HelloTexture expects a texture with 256*256 pixels with 4 bytes per pixel.

**Comment by bofinbabu** [comment]
Does that mean I should load a 256*256 image or a 64*64 image (64*(4 Bytes per pixel)). Isn't it that when i converted it into 32ppPBGRA the 4 Bytes per pixel part is already taken care?

**Comment by ClemensX** [comment]
If you just replace the GenerateTextureData() method by your own code, without changing anything else, you have to make sure that you provide data in exactly the same format. That means size and pixel width.

**Comment by bobbrow** [comment]
Or you can change TextureWidth/TextureHeight (defined in D3D12HelloTexture.h) to the width/height of your image.

**Comment by bobbrow** [comment]
@bofinbabu- is there anything else you need from this issue, or is it ready to be closed?

**Comment by bofinbabu** [comment]
Oh.. Sorry please close this issue. Thanks for the replays :)
