### ISSUE TITLE
CounterBuffer (UAV counters) question

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#116]
Hi Guys,

Another curious question. I've noticed that miniEngine's StructuredBuffer has a CounterBuffer as it's member. And dx12 api CreateUnorderedAccessView now also has a new ID3DResource* param which  is called counterbuffer. So I am very curious about the design purpose of this counterbuffer both in api level and engine level: If the counterbuffer is all about counting stuff, we can just use normal buffer with atomic ops, why dx12 have very specific uva counter stuff around its api level? Is there any counting related task that atomic ops cannot do but uva counter can? 

Thanks

Peng

**Comment by stanard** [comment]
With DirectX 11, atomic counters were placed in GDS (global data store), which is faster for atomic updates than if they are in memory.  (GDS and LDS are very fast-but-small chunks of memory that sit directly on the GPU.)  After a shader exits, the driver was responsible for copying that counter value out of GDS to memory.  This requires a lot of expensive driver bookkeeping, and it can also be inefficient for the GPU to flush shader execution before reading back the counter.  With DirectX 12, atomic counters are now more transparent to the user.  (You don't have to create them if you don't use them, but for simplicity MiniEngine always creates one when you create a StructuredBuffer.)  This puts the power in your hands to avoid inefficiencies.  For instance, with DX11, you used to have to call CopyStructureCount() or dispatch a shader to put the counter value in a buffer of your choosing.  Now, you can simply reference the buffer you know already holds the counter--the one you specified.  It's up to you to do hazard tracking such as flushing a dispatch with a resource barrier before reading the counter value.

One other thing I will say is that you shouldn't expect DX12 to use GDS for atomic counters, which could make it a little slower.  Depending on the target GPU, the shader compiler can do things to reduce atomic stores to memory (such as condensing all InterlockedAdd() calls in a wave to one atomic memory op.)  But I recommend you use LDS (groupshared memory) for counters when possible, and at the end of your shader do a single atomic update of the real counter.

**Comment by pengliu916** [comment]
That is really helpful.
Thanks James
