### ISSUE TITLE
DepthBuffer default clear value is 0.0f?

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#118]
Hey Guys,

Just a silly question. I recently tried to use low level miniEngine (not using engine pre-defined rendertargets) to implement a very simple forward rendering demo, but only got black screen. Then I find out that this is caused by the DepthBuffer default clear value, which is set to 0.0f. That means every time after I clean the depth buffer, I was guaranteed that none of my pixel could pass the depth test (D3D12_COMPARISON_FUNC_LESS) since the z value of every pixel after projection is greater than 0.0....

So I looked through miniEngine modelviewer demo and found out that it also use D3D12_COMPARISON_FUNC_GREATER_EQUAL for depth test which is not what I have learned before....

My knowledge in graphics may be out of date, so it will be appreciated if someone could enlighten me about the concept or technique behind this depth test approach.

Thanks

**Comment by jmkinzer** [comment]
This is a clever trick to get better precision out of the zbuffer (basically by using non-linearity of floating point to cancel the non-linearity of z in view-space). Humus I think first [described](http://www.humus.name/index.php?ID=255) this approach.

**Comment by pengliu916** [comment]
Thanks jmkinzer, I really love this educational github repo :-)
