### ISSUE TITLE
D3D12HelloTexture

### ISSUE THREAD

**Issue by cpyburn** [Microsoft/DirectX-Graphics-Samples#119]
Can't increase size of width or height of texture without GPU getting suspended due to bad command list.  I have looked and can't spot anything wrong.  I would assume that you would be able to go to the max size of the D3D11_REQ_TEXTURE2D_U_OR_V_DIMENSION (16384).  We are about to start porting everything over to directx 12 and found this during testing.

**Comment by bobbrow** [comment]
Hi @cpyburn,
I can't reproduce the problem you are having.  Have you tried running the sample using the WARP adapter?  Go to the debugging settings and add ```/warp``` to the command line parameters.  If that works, then I suspect this could be a driver bug and I would ask that you post your GPU & driver information so we can go from there.

**Comment by bobbrow** [comment]
Closing old issue that we can't reproduce.  Please reopen if you are still seeing this.
