### ISSUE TITLE
New Problems when defining Root Signature in HLSL

### ISSUE THREAD

**Issue by Yoshusa** [Microsoft/DirectX-Graphics-Samples#121]
Dear Microsoft Team,

using the D3DCompile function with rootsig_1_0 does not seem to be compatible with shader model 5.1. Just define the following constant buffer in HLSL:
```
struct SFoo
{
    float4 m_Constant;
};

ConstantBuffer<SFoo> ExampleConstantBuffer: register(b0);
```
Also define a root signature in the HLSL file:
```
#define TestRootSignature                                                                                                      \
    "RootFlags(ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT),                                                                          " \
    "DescriptorTable(CBV(b0, numDescriptors = 2)),                                                                           " \
    "RootConstants(num32BitConstants=1, b2, visibility = SHADER_VISIBILITY_PIXEL),                                           " \
    "DescriptorTable(SRV(t0, numDescriptors = 20), visibility = SHADER_VISIBILITY_PIXEL),                                    " \
    "StaticSampler(s0, addressU = TEXTURE_ADDRESS_CLAMP, addressV = TEXTURE_ADDRESS_CLAMP, filter = FILTER_MIN_MAG_MIP_POINT)"
```
Now compile the root signature with D3DCompile and target rootsig_1_0. The compilation will fail because of the ConstantBuffer declaration.

Furthermore rootsig_1_0 does not work with compute shaders (at least if they contain a groupshared declaration). Just take an HLSL file with a compute shader and declare a root signature in it. Compile it via D3DCompile and target rootsig_1_0. As result you will get the following error message: 

ps_5_0 does not support groupshared, groupshared ignored

Kind regards,

Joerg Sahm

**Comment by stanard** [comment]
One thing I notice is that the D3D compiler is saying you tried to compile your compute shader with ps_5_0, which is for pixel shaders.  Pixel shaders don't support groupshared memory.  I'm not sure about the SM5.1 error with root signatures.

**Comment by bobbrow** [comment]
Can you share the full HLSL (or a minimal subset of the HLSL that still has the error)?  We weren't able to reproduce the error with the information you provided.

The second issue is a warning.  Are you not seeing a root signature produced for the second case?

**Comment by Yoshusa** [comment]
Hi all,

thanks for your replies.

@stanard 
The point is, that I am compiling a root signature and not a shader. So the target string of the D3DCompile method is rootsig_1_0 instead of something like ps_5_1 or cs_5_1 (see the C++ example below). In my case the file does not even contain a pixel shader.

@bobbrow
To the second issue: Yes, you are right, it is just a warning. Our engine throws an exception, because we compile everything with the D3DCOMPILE_WARNINGS_ARE_ERRORS flag enabled. Sometimes the warnings contain some important information (e.g. performance loss) and therefore we drive a strict "No Warning" policy. Of course we could disable this flag when compiling root signatures. However, the warning message "ps_5_0 does not support groupshared, groupshared ignored" is quite missleading, especially if the file does not even contain a pixel shader. Also I think, the D3DCompile method should not throw a warning in this case, because there is nothing wrong or inappropriate with the code.

To the first issue: I've attached a text file with some HLSL code. Please note, that the constant buffer and the root signature declarations at the begin of the file do not match the following compute shaders. They are just an example. Now add the following C++ code to the begin of the LoadAssets method of the HelloTriangle sample.
```
unsigned int                Flags;
HRESULT                     NativeResult;
ComPtr<ID3DBlob>            NativeRootSignatureBlobPtr;
ComPtr<ID3DBlob>            NativeErrorBlobPtr;
ComPtr<ID3D12RootSignature> NativeRootSignaturePtr;

Flags = D3DCOMPILE_PACK_MATRIX_ROW_MAJOR | D3DCOMPILE_WARNINGS_ARE_ERRORS | D3DCOMPILE_ENABLE_STRICTNESS | D3DCOMPILE_OPTIMIZATION_LEVEL3;

NativeResult = ::D3DCompileFromFile(L"histogram.txt", nullptr, nullptr, "PostFXRootSignature", "rootsig_1_0", Flags, 0, &NativeRootSignatureBlobPtr, &NativeErrorBlobPtr);

if (NativeResult != S_OK)
{
    ::OutputDebugStringA(static_cast<char*>(NativeErrorBlobPtr->GetBufferPointer()));
}

NativeResult = m_device->CreateRootSignature(0, NativeRootSignatureBlobPtr->GetBufferPointer(), NativeRootSignatureBlobPtr->GetBufferSize(), IID_PPV_ARGS(&NativeRootSignaturePtr));
```
In this case I get the following error message:

E:\histogram.txt(21,1-14): error X3000: unrecognized identifier 'ConstantBuffer'

If you uncomment the ConstantBuffer declaration you can reproduce the second issue.

Greetings

Joerg

[histogram.txt](https://github.com/Microsoft/DirectX-Graphics-Samples/files/185247/histogram.txt)

**Comment by bobbrow** [comment]
So it looks like both of these are issues with the version of the compiler in the current version of Windows 10.  They will be fixed in a future update of the compiler, so thank you for reporting them.

For the first issue, if you don't need to index SFoo, using the following syntax should help you work around that issue:
```
cbuffer SFoo: register(b0)
{
	float4 m_Constant;
};
```
I don't have a good workaround for the second issue besides maybe splitting your root signature definitions into separate files that are then included by the shader file(s) that need(s) them.  The benefits of this approach would be:
* you can leave ```ConstantBuffer<SFoo>``` in your shader files
* you can configure Visual Studio to pre-compile the root signatures at build time

**Comment by Yoshusa** [comment]
Hi Bob,

thanks for your reply. I located the root signatures in separate files, so everything works fine. I will close the issue.

Greetings,

Joerg
