### ISSUE TITLE
I cannot find DirectX samples for C#

### ISSUE THREAD

**Issue by sarahsga** [Microsoft/DirectX-Graphics-Samples#122]
I am working with Kinect and 3D models. I find C# much easier to understand, but I cannot find any samples for C# DirectX on Microsoft website. Please help

**Comment by zao** [comment]
The scope of this repository is primarily native DirectX 12. As there's no first party bindings for DirectX into .NET since the days of Managed DirectX, you'll have a hard time finding anything from MS proper.

The techniques shown in this repository may still apply if you use a binding like SharpDX, but beware of interop costs, their overhead may dominate your runtime cost.

**Comment by bobbrow** [comment]
As @zao points out, Microsoft does not provide any official C# wrapper for the latest DirectX APIs.  SharpDX is actively maintained as far as I am aware, and has ported our "HelloWorld" samples to C# using their API.  I'm not sure how often they update them to keep them in sync with ours, but you can find them [here](https://github.com/sharpdx/SharpDX-Samples/tree/ed7e80cdcac145cf1864c6b9358a558e5fe8deb6/Desktop/Direct3D12)

Do be aware that the HelloWorld samples do not do any frame buffering and will flush the GPU after each frame is presented (not something you want to do in a real app)

**Comment by sarahsga** [comment]
@bobbrow and @zao Would you recommend using SharpDX or SlimDX if I have to use C#?

**Comment by sarahsga** [comment]
Also, @bobbrow I am not restricted to C#, but am bound to use it due to time constraints as I don't have experience with unmanaged C++ and getting used to it will take time.

Since I have to manipulate 3d models, do you think SharpDX would let me do it (ignoring performance issues).

Also, if I am to use DirectX, does DirectX api allow bone-level access to fbx 3D models, or does it restrict us to working with pre-made fbx animations?

**Comment by stanard** [comment]
SharpDX supports D3D12, whereas SlimDX does not as far as I can tell.

DirectX sits closer to the hardware and knows nothing about the FBX model format.  You should have unrestricted access to your model data and formats regardless of graphics API.  DirectX also does not know anything about animation.  You can animate your vertex buffers on the CPU, or you can use vertex shaders to procedurally animate them such as with skinning or blend shapes (which require you update bone positions and blend weights on the CPU.)

-James

**Comment by jmkinzer** [comment]
@sarahsga: Based on your questions you really need a significantly higher level API than SharpDX. Sounds like you're really looking more for an engine (e.g. Unity)... or at the very least something XNA-level so you get some sort of content pipeline. XNA is only DX9 and Unity limits your low-level access to the graphics pipeline but the guy who created SharpDX has created a new [engine](http://xenko.com/) that's sort of an "XNA++" and as of a few weeks ago it now supports DX12 as well (via SharpDX). You'll want to check it out before you embark on a path that involves tons of wheel-reinvention.

**Comment by sarahsga** [comment]
@jmkinzer Thanks. I will try Xenko then. The reason I cannot use Unity3D for my project is because I will need to use OpenCV (or EmguCV C# wrapper) on my 3D model. Unity3D lets you do that through a plugin that costs a crazy $400 which is wayy too expensive for my project. Will I be able to use OpenCV(or Emgu) with Xenko? (From what little search I did right now, it appears I can't)

**Comment by sarahsga** [comment]
@zao 

> If you did not have it built-in in earlier Direct3D versions, you're definitely not going to have it in D3D12.
I didn't quite get that. What's "it" in "If you did not have it built-in"?

Also, I am not going for a very high-end performance at the moment. It''s basically a "proof-of-design" kind of work, which requires me to use rigged 3D fbx models with bone-level access, and some OpenCV(or Emgu) for some Image Processing (finger recognition) with Kinect. I am not yet sure what's new in DirectX 12, so I will look at it and see if my work can be done with DirectX 11.

**Comment by zao** [comment]
By "it" I meant functionality like loading scenes from FBX and other high level functionality.

Unless you use one of the common high level engines, you'll have the pleasure of using things like the Autodesk FBX SDK yourself to interpret and extract the data from your scenes.

In general, Direct3D 12 is way more annoying to work with than Direct3D 11, trading off convenience for extreme power in the hands of the specialized and competent.

From the sounds of it, your application is probably much better served by sticking to the tried and true Direct3D 11, or some existing C++ game/visualisation engine. Nothing about the problem space you describe requires the fancy things you can do in 12.

**Comment by jmkinzer** [comment]
OpenCV integration is orthogonal to any engine you're going to find. So no, Xenko doesn't have it and Unity only has it due to its asset store. So if you want "out-of-the-box" you're probably going to need to look to a major engine for which people are writing plugins. The only other game in town with lots of integrations like Unity is Unreal4. And just quickly checking, it does appear somebody has already [created one](https://wiki.unrealengine.com/Integrating_OpenCV_Into_Unreal_Engine_4). Note UE4 is going to be C++ (or blueprints), however.
In any case this discussion is now totally unrelated to this repository. Good luck!

**Comment by bobbrow** [comment]
Closing old issue.  Please reopen if you feel your issue has not been addressed.
