### ISSUE TITLE
ComPtr question

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#125]
Hey Guys,

I was looking though the GpuResource class and its subclasses, and found a ComPtr usage inconsistency:

in GpuBuffer::Create we have the following code to create gpu resource:
ASSERT_SUCCEEDED( 
		g_Device->CreateCommittedResource( &HeapProps, D3D12_HEAP_FLAG_NONE,
		&ResourceDesc, m_UsageState, nullptr, MY_IID_PPV_ARGS(&m_pResource)) );
where we use &m_pResource to get the ComPtr address

but in Texture::Create what we have for resource creation is this:
ASSERT_SUCCEEDED(
                g_Device->CreateCommittedResource(&HeapProps, D3D12_HEAP_FLAG_NONE, 
                &texDesc, m_UsageState, nullptr,
                MY_IID_PPV_ARGS(m_pResource.ReleaseAndGetAddressOf())));
where we use ComPtr func ReleaseAndGetAddressOf to get the pointer address.

I am not super familiar with ComPtr, but I guess among those two methods, there should be one which is better than the other one (at least the second one will release the previous resource if the previous one exist...)

Actually, after looking though [MSDN](https://msdn.microsoft.com/en-us/library/br230430.aspx) I found it's not very clear to me the difference between &m_pResource and m_pResource.ReleaseAndGetAddressOf()

Thanks

BTW, I have asked a following question in the closed issue #123 , it will be great if someone could help me on that

**Comment by stanard** [comment]
ComPtr is in short a reference-counted smart pointer that will call Release() on a COM object before letting go of its address.

Taking the address of a ComPtr with operator& is equivalent to calling Release() and returning the address of the pointer.  That's also equivalent to ReleaseAndGetAddressOf(), but this latter version is pretty verbose.  For clarity, I should stick with the verbose option, especially when it's not obvious that operator& is NOT equivalent to GetAddressOf().

I agree:  I was inconsistent, but it's not incorrect.  I'll make it consistent, and thanks for paying attention!

-James

**Comment by pengliu916** [comment]
Thanks James, I will close this issue.
