### ISSUE TITLE
MiniEngine: DescriptorTable size limit

### ISSUE THREAD

**Issue by pengliu916** [microsoft/DirectX-Graphics-Samples#126]
Hey Guys,

It seems miniEngine use uint32_t for `DynamicDescriptorHeap::DescriptorTableCache::AssignedHandlesBitMap` which act as bitfield flag to indicate assigned descriptor with in one descriptor table. So if I understand correctly, this put a limit of max 32 descriptors per table.

If that is the case, it will be better to verify that descriptor table size is less than 32 in RootSignature.cpp around line126 otherwise we may create descriptor table with more than 32 descriptors in it which may cause some tricky bugs.

Or miniEngine already check on that in some place where I missed?

Peng

**Comment by stanard** [comment]
I didn't think it would be appropriate to use dynamic descriptor tables with very large tables.  It makes more sense (to me) to use static descriptor tables that you pre-build and keep cached.  Unfortunately, I haven't spent much time developing and testing a system for switching between dynamic and static descriptor tables, so I'll need to put that on my "to do" list.  If you don't need much more than 32, you could try modifying the code to use uint64_t for a maximum of 64 descriptors per table.  I think adding a sanity check would be very appropriate, so thank you for the suggestion.

-James
