### ISSUE TITLE
White Space Alignment

### ISSUE THREAD

**Issue by skln131313** [Microsoft/DirectX-Graphics-Samples#13]
Not in the master branch yet but there are a lot of alignment issues, tabs used where spaces should be used and vice versa.

When using tabs, tabs should only be used in the margin, spaces should be used everywhere else for alignment to ensure that alignment stays regardless of tab size.

    [-- tabs --] ClassType [-- spaces --] name;

    [tab] [s]  if(condition) something();
    [tab] else if(condition) somethingElse();
    [tab] else [spaces]      somethingElseElse();

etc...

That or simply use spaces across for everything. Not that big of a deal just horrible viewing experience since github uses 8 tab size and everything is formatted to use tab size 4.

https://github.com/Microsoft/DirectX-Graphics-Samples/blob/feature_miniengine/MiniEngine/Core/GraphicsCore.h#L35
https://github.com/Microsoft/DirectX-Graphics-Samples/blob/feature_miniengine/MiniEngine/Core/TextureManager.cpp#L54

Edit: Issue #13... I'm a bit paranoid now...

**Comment by bobbrow** [comment]
Thanks.  We're aware of this issue.  This will be cleaned up before we take the code to master.

**Comment by bobbrow** [comment]
Just committed a change to the feature branch that has whitespace fixed up.  GitHub should be ashamed of themselves for setting tab width to 8 ;-)  I think only Notepad still does that.

The big problem that we have is that Visual Studio doesn't let you alternate having TABs at the beginning of the line and spaces in the middle (for variable/name/code/etc alignment).  As soon as you press TAB, it converts the spaces to TABs.  So we removed the alignments and just have a single space after declarations.

**Comment by skln131313** [comment]
Yah mixing tabs and spaces tends to break a lot of autocomplete features and similar things, that's why i stick with spaces. That and what you see is what you get with spaces.

**Comment by bobbrow** [comment]
In my personal projects I usually do as well.  For these projects however, we tried to stick with the default formatting options that Visual Studio selects (for better or for worse).  We intend to provide feedback to the Visual Studio team.  Given how much they've invested in supporting Git workflows, I think they'll be open to the suggestion.
