### ISSUE TITLE
Will DX12 overlap consecutive draw calls within same cmdlist if we don't use sync objs?

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#132]
As we know that DX12 passes a lot of sync jobs to the hand of developer, and as the result, if we don't manually sync GPU tasks, DX12 will try it best to overlap these GPU tasks. So a very simple question come to my mind: does DX12 overlap draw calls if we don't using sync objs between consecutive draw calls? and if it does, will it respect draw call submission order?  And I have crafted up a very simple case to test it:

I have one cmdlist contains 3 drawing commands each of which will draw a square in the same area (with different color) consecutively, and I have disable the depth and alpha test. (the cmdlist looks like the following:)

     cmdlist->DrawRedSquare;
     cmdlist->DrawYellowSquare;
     cmdlist->DrawGreenSquare;

I've tried different orders, and the results indicate that GPU didn't reorder or overlap these draw calls. So does it mean that GPU has other sync objs which is not exposed in the DX12 api, and sync some very basic jobs?

I know my questions may be silly, but I just want to know what happened under the hood, what keeps these draw call synced?

Thanks

Peng

**Comment by gg8345** [comment]
The answer will depend on what mechanism you're using to write. 

If you're writing using rendertargets (color buffers) and depth stencil buffers, there's such a thing as API submission order that is respected for these writes. This is the same guarantee you had on Dx11. The mechanism used to guarantee API order on these writes is hardware specific.

If you're writing using UAVs on the other hand, dx12 differs from dx11, in that submission order is no longer guaranteed starting with dx12. You then risk having Write after Write hazards that you have to solve manually using barrier fences (no need for barrier fences on things that are written exclusively using the rendertargets mechanism).

Rendertargets are not totally safe, of course, with other areas of the pipeline, so if you transition a resource from being a rendertarget to any other position in the pipeline (like becoming a UAV, a SRV, a CBV and so on) you need barriers as well to indicate the transition. This will impose the correct API ordering but will also be used to flush caches and/or do the necessary format transformation if needed.

**Comment by pengliu916** [comment]
Thanks @gg8345 for enlightening me on that, but will it be inefficient for GPU to serialize all draw calls? For example, we have depth test enable, and disabled alpha test, will it be faster if we just overlap draw calls, and make the write to rendertargets atomic (like how the GPU overlap individual triangle drawing within one Draw)? Or the hardware vendor already did that through optimization?

I know we could just convert such individual draw calls into one draw command (by merging vertex and index buffer), but I just want to know whether there is some way we could ask GPU to overlap them instead of spending extra cpu cycles to manually merge them.

Thanks

**Comment by gg8345** [comment]
I personally wouldn't worry too much about that (drawing triangles efficiently is of course the bread and butter of modern GPUs). But I wouldn't discourage you to play with that idea. Who knows what you can unearth.

**Comment by pengliu916** [comment]
Just curious how GPU works in a lower level :-)  Anyway, thanks for sharing your knowledge~

**Comment by stanard** [comment]
I wanted to add some more info despite the case being closed.  Draws should overlap as much as possible, but the GPU is required to write results in the order the draw calls were submitted.  The parts of the GPU that mediate this are the Color Block (CB) and Depth Block (DB).  The rasterizer will allocate threads to shade pixels, and there are on the order of thousands of threads that can be used.  If a triangle only covers 4 pixels, it will get 4 threads.  Without overlapping draw calls, there would often be many unused threads.  So how is write order guaranteed when threads (and draws) can finish in any order?  When a pixel ends, it exports the results to the CB.  The CB has a "current draw ID", and only pixels from the current draw can be processed until that draw is completely finished.  When pixel shaders from other draws try to export, they will block until it is their turn.  To avoid dead locks, all threads have to be allocated for a draw before the next draw can start allocating threads.  You wouldn't want Draw B to be waiting for Draw A to finish and have some pixels from Draw A waiting for available threads which are completely tied up with Draw B.  Confused yet?  :-)

-James

**Comment by pengliu916** [comment]
Thanks James, that's really instructive. I really appreciate it. Just one small follow up question and one big question: 
Small one: is DrawInstanced effectively one draw call where all it's triangles pixel runs simultaneously (so all instance draw has the same Draw ID), or it's just issues serialized draws internally? (MSDN doesn't explain DrawInstanced in that much detail...)

Big one: I can't find any useful information about the Color Block and Depth Block on the internet (or any graphics books I have). It will be much more appreciated if you could point me to some resource pool which explains GPU workflow in detail as you just did~~

Thanks in advance for your time~

**Comment by stanard** [comment]
Now you've got me thinking.  If you sort sprites back-to-front and then draw them in one Draw call (or DrawInstanced), they get rendered in the right order despite the absence of depth testing.  So I guess the GPU has a way to preserve the order of primitives within a draw as well as the draws themselves.

Color Block and Depth Block are not universal terminology, but there is a structure on virtually every GPU that is responsible for committing writes to render targets.  Some call it the "raster backend".  In marketing terms, sometimes they're called ROP (Raster Operation) Units.  I'm not sure where to refer you to get an introduction on GPU architecture and operation.  That's pretty arcane stuff, and the point of Direct3D is to abstract away the unnecessarily gritty details from programmers as well as to unify different GPU architectures under the same programming model.  Plus having a standard  API (including OpenGL) forces GPU makers to sit at the same table and mutually agree to support the same new features.

**Comment by pengliu916** [comment]
Humm... So if I got it right, it should be a little faster if we kick off computer shader to "draw" those sprites with atomic write to "render target" since those "pixel threads" don't have to be serialized.... I will profile this once I got time :-)

Thanks James

**Comment by stanard** [comment]
You could also check out the compute shader tiled particle renderer in MiniEngine.  It blends all particles in one pass and then blends the result with the render target one time.

If you discover anything interesting with your experiments, please let us know!  Doing things in unconventional ways is the seed of progress.
