### ISSUE TITLE
Can we avoid unnecessary flush?

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#136]
Hey Guys,

I recently crafted a volume update then rendering application, and get an interesting observation. First, the following code describes what I want:

```
    ComputeContext& cptContext = EngineContext.GetComputeContext();
    {
        GPU_PROFILE(cptContext, L"Volume Animation Updating");
        cptContext.SetRootSignature(m_RootSignature);
        cptContext.SetPipelineState(m_ComputePSO);
        cptContext.TransitionResource(m_VolumeBuffer[m_onStageIdx], D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
        cptContext.SetDynamicConstantBufferView(0, sizeof(ConstantBuffer), m_pConstantBufferData);
        cptContext.SetBufferUAV(2, m_VolumeBuffer[m_onStageIdx]);
        cptContext.Dispatch(m_volumeWidth / THREAD_X, m_volumeHeight / THREAD_Y, m_volumeDepth / THREAD_Z);
    }
        //cptContext.Flush(); <------------------Look Here!! ------------------

    GraphicsContext& gfxContext = EngineContext.GetGraphicsContext();
    {
        GPU_PROFILE(gfxContext, L"Rendering");

        gfxContext.ClearColor(Graphics::g_pDisplayPlanes[Graphics::g_CurrentDPIdx]);
        gfxContext.ClearDepth(m_DepthBuffer);
        gfxContext.SetRootSignature(m_RootSignature);
        gfxContext.SetPipelineState(m_GraphicsPSO);
        gfxContext.SetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
        gfxContext.TransitionResource(m_VolumeBuffer[m_onStageIdx], D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE );
        gfxContext.SetDynamicConstantBufferView(0, sizeof(ConstantBuffer), m_pConstantBufferData);
        gfxContext.SetBufferSRV(1, m_VolumeBuffer[m_onStageIdx]);  <-------------Got Warning Here---------
        gfxContext.SetRenderTargets(1, &Graphics::g_pDisplayPlanes[Graphics::g_CurrentDPIdx], &m_DepthBuffer);
        gfxContext.SetViewport(Graphics::g_DisplayPlaneViewPort);
        gfxContext.SetScisor(Graphics::g_DisplayPlaneScissorRect);
        gfxContext.SetVertexBuffer(0, m_VertexBuffer.VertexBufferView());
        gfxContext.SetIndexBuffer(m_IndexBuffer.IndexBufferView());
        gfxContext.DrawIndexed(36);
    }
    EngineContext.Finish();
```

The code should be pretty self-explanatory.   If I understand how dx12 workflow correctly,  the Flush command (line marked as "look here") is unnecessary. But without that line I get validation warning:
`D3D12 WARNING: ID3D12CommandList::SetGraphicsRootShaderResourceView: Resource state (0x8) of resource (0x0000017ABCC99550:'Volume Buffer') (subresource: 0) is invalid for use as a root shader resource.  Expected State Bits: 0xC0, Actual State: 0x8, Missing State: 0xC0. While the resource was in a descriptor slot, bound to the pipeline in a descriptor table, the resource may not actually have been read from. If these messages are too noisy, they can be muted. And, the application can switch to use ID3D12DebugCommandQueue::AssertResourceState* directly. [ RESOURCE_MANIPULATION WARNING #607: POSSIBLY_INVALID_SUBRESOURCE_STATE]`

My guess about that warning is that, without that flush when we execute to the line (marked as "Got Warning Here") validation layer thinks the m_VolumeBuffer[m_onStage] is still in D3D12_RESOURCE_STATE_UNORDERED_ACCESS state since the transaction which translate that resource to proper state is not submitted for execution.

So I guess this maybe a driver bug? (I don't get this warning on a different computer) or I messed up something?

Thanks

**Comment by stanard** [comment]
I remember this, and I am pretty sure we have a bug filed already.  (It's probably fixed and coming in a future release.)  What's happening is that the validation layer is checking the usage flags at the time you call SetBufferSRV() (internally SetGraphicsRootShaderResourceView()) rather than at the time you call DrawIndexed().  MiniEngine's wrapper layer doesn't kick off all the resource transitions until the next time you call Draw or Dispatch so that they can be issued all at once and reduce stalls.  So your transition to PIXEL_SHADER_RESOURCE hasn't happened yet, but it will have by the time the Draw happens.  You can ignore that warning for now, but if you want to circumvent it you can flush your transition barriers by passing 'true' as the second argument to TransitionResource().

**Comment by pengliu916** [comment]
Good to know that I am not responsible for that warning. Thanks James, I will close this issue for now.
