### ISSUE TITLE
DX12 ExecuteIndirect argument alignment rules?

### ISSUE THREAD

**Issue by JJoosten** [microsoft/DirectX-Graphics-Samples#138]
Hi everyone,

I have been working with DX12 ExecuteIndirect and noticed that there are alignment rules that are not mentioned on MSDN or in any sample that I have got my hands on so far; therefore I am wondering where I could find documentation on these rules.

When using D3D12_INDIRECT_ARGUMENT_TYPE_VERTEX_BUFFER_VIEW and D3D12_INDIRECT_ARGUMENT_TYPE_INDEX_BUFFER_VIEW, it seems that the address of these views needs to be 8 byte aligned in the indirect argument buffer. As an example, setting 1 root constant before one of these views will result in a device timeout.

I tested the vertex buffer and index buffer view extensively using WARP, NVidia GTX950 and Intel 5100 iris and all of the devices crash or timeout with unaligned data.

I currently found the following rules to be true in my testcase.
- 64 bit addresses need to be aligned to 8 bytes. Note that you thus need to pad the indirect argument struct to align to 8 bytes when using the vertex or index buffer view to also align consecutive arguments.
- Root signature spilling arguments need to be set in the same order as the root arguments are specified in the root-signature.
- A draw or dispatch call always needs to be the last call in the argument buffer.

I also noticed in the last table on the following MSDN page (https://msdn.microsoft.com/en-us/library/windows/desktop/dn903925(v=vs.85).aspx) mentions that the vertex buffer stride comes before the vertex buffer size in the argument buffer. According to the DX12 vertex buffer view struct (and my own experience using it) this is the other way around {size, stride } instead of {stride, size}.

Since I didn't have a better way to reach out to you all; I hope you all don't mind that I ask my questions here :)

Thanks for the help! The MiniEngine has been a great work of reference so far! :)

I made a quick sample modifying MiniEngine, currently NUM_ROOT_CONSTANTS in compute.hlsl and D3D12ExecuteIndirect.h is defined as 1 (this will make it crash). Set this define to 2  in both files to make it work. https://github.com/JJoosten/DirectX-Graphics-Samples

Cheers,

Juul

**Comment by bobbrow** [comment]
Thank you for bringing this to our attention.  I will work with the documentation team to get MSDN updated.  You are also correct about the size/stride ordering.  We'll get that table updated as well.

**Comment by JJoosten** [comment]
Hi Bob,

Thanks for looking into this! 

Have a great day,

Juul

**Comment by walbourn** [comment]
Doc page is updated.
