### ISSUE TITLE
GPUview problem

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#139]
Hey Guys,

Just want to check with you guys: Do you have any problem using GPUview to load captures recently? I have tried using different parameters, under different computers, but every time I load an etl file GPUview gives me an error saying: "Most likely ran out of memory during load, see the /limit option". BTW, I am on Win10 build 14316

I recently port one of my DXUT DX11 demo BoidsSimulation project to miniEngine(only the framework, not any predefind resources), and noticed a 10% perf loss which I can't tell why, I admit that my project render command is very short which may not be able to take the advantages of DX12, but a 10% perf lose is unexpected. So before I am able to look into GPUview capture any suggestions will be greatly appreciated.

**Comment by stanard** [comment]
Have you turned on the MiniEngine profiling stats?  (Do you have a game controller?)  Hitting backspace on the keyboard brings up the engine variables you can change.  One of the first listed is "Display Profiler".  Hit the down arrow key twice and press enter to toggle it on.  You can explore the stats the same way as the engine variables:  with arrow keys.  Left/right go in and out of submenus.

You might see where the time is spent.  MiniEngine has a bunch of post processing that you might have turned on.  Another thing that's more built-in is the concept of an off-screen UI (or overlays) buffer.  This is where the stats and engine variables will draw.  And if your app has a RenderUI() function implemented, it will get rendered there as well.  MiniEngine automatically composites that UI render target with the main scene render target even if you don't draw anything to it.  (The frame rate text that you probably see also draws to the UI render target.  10% could be lost there depending on what your frame time was to begin with.

-James

**Comment by pengliu916** [comment]
I am pretty sure I disabled all those features (actually I even diabled the profiling system). But later I have run the benchmark on a different computer and this time miniEngine version is slight faster than DXUT on dx11. So I guess to fully utilize DX12 we need new hardware (my previous perf test is on a labtop with i7 3820QM with nvidia 680m, but the newer test is performed on i7 4980HQ with nvidia 980m).

But I still have problem work with GPUview :-(  though

**Comment by bobbrow** [comment]
Back to the GPUView issue... When did it stop working for you?  When you upgraded to build 14316?  Do you happen to know which version of GPUView you have?  (I don't think the UI gives you a build number or anything, so maybe the exe's timestamp is all I can go off of)

**Comment by pengliu916** [comment]
Thanks Bob for getting back to me.
I haven't been using GPUView for awhile, so l think last time I run GPUView, I may still be older than 10586. For 14316, I got it around 2 weeks ago.  The GPUView version I got (through the method you described) is 10.0.10240.16384....

So it seems my GPUView is not uptodate.... what's the best way to get the correct version of GPUView then?

Thanks in advance :-)

Peng

**Comment by bobbrow** [comment]
t looks like the GPUView you have came with the 10240 SDK.  You can try to install a newer version with the 10586 SDK by check the box for the "Windows Performance Toolkit", though I haven't had any trouble with either version.

How big is the etl file you're trying to load?  Did you try using the /limit argument like the help text suggested?  Or, if the etl file really is too big, you can try to take a shorter capture.

**Comment by pengliu916** [comment]
The size I generated previously is normal around 200MB, I got error loading it on multiple machines. But today when I create a new log, everything go back to normal. I do upgraded the windows SDK and windows version during the previous 25 days. So I guess the error I got previously may caused by the version mismatch.

Anyway, thanks for all your help. I will close this issue for now
