### ISSUE TITLE
Shader Reflection of Constant Buffer fails when using ConstantBuffer template

### ISSUE THREAD

**Issue by Yoshusa** [Microsoft/DirectX-Graphics-Samples#141]
Dear Microsoft Team,

I've attached two different HLSL files to this post. One of these HLSL files uses the cbuffer declaration, the other one the ConstBuffer template. In the C++ code I added some shader reflection code to the LoadAssets method of the HelloConstBuffers sample.
```
HRESULT                               NativeResult;
ID3D12ShaderReflection*               pNativeShaderReflection;
ID3D12ShaderReflectionConstantBuffer* pNativeConstantBufferReflection;
D3D12_SHADER_INPUT_BIND_DESC          NativeShaderInputBindDescriptor;
D3D12_SHADER_BUFFER_DESC              NativeShaderBufferDescriptor;

D3DCompileFromFile(GetAssetFullPath(L"shaders.hlsl").c_str(), nullptr, nullptr, "VSMain", "vs_5_1", compileFlags, 0, &vertexShader, nullptr);
D3DCompileFromFile(GetAssetFullPath(L"shaders.hlsl").c_str(), nullptr, nullptr, "PSMain", "ps_5_1", compileFlags, 0, &pixelShader , nullptr);

NativeResult = ::D3DReflect(vertexShader->GetBufferPointer(), vertexShader->GetBufferSize(), IID_PPV_ARGS(&pNativeShaderReflection));
NativeResult = pNativeShaderReflection->GetResourceBindingDesc(0, &NativeShaderInputBindDescriptor);
pNativeConstantBufferReflection = pNativeShaderReflection->GetConstantBufferByName(NativeShaderInputBindDescriptor.Name);
NativeResult = pNativeConstantBufferReflection->GetDesc(&NativeShaderBufferDescriptor);
```
The important statement is the last one, where I try to retrieve a descriptor of the constant buffer. Using the shader with the cbuffer declaration succeeds (shaders.hlsl), while using the shader with the ConstantBuffer template (shaders2.hlsl) fails.

Kind regards

Joerg
[shaders.txt](https://github.com/Microsoft/DirectX-Graphics-Samples/files/223617/shaders.txt)
[shaders2.txt](https://github.com/Microsoft/DirectX-Graphics-Samples/files/223618/shaders2.txt)

**Comment by bobbrow** [comment]
Hi Joerg-
Just to let you know, I sent this to the developers on the compiler team earlier this week but I don't have a response from them yet.

**Comment by bobbrow** [comment]
Hi Yoshusa, we have a fix for this that will be released in a future update.  Sorry for the delay on getting back to you.

**Comment by Yoshusa** [comment]
Hi Bob,

thanks for the reply. I close the issue.

Cheers,

Joerg
