### ISSUE TITLE
Graphics Analyzer crashes on opening vslog File

### ISSUE THREAD

**Issue by Yoshusa** [Microsoft/DirectX-Graphics-Samples#146]
Dear Microsoft Team,

I've attached a modified version of the HelloTriangle sample to this post (for some reason I cannot attach zip archives so I renamed the files into txt files). I've marked all my changes with a @issue comment. Now do the follwing:

- Start the program without graphics debugging
- End the programm

As far as I can see, all is running fine and the application exits gracefully.

- Start the programm with the graphics debugger
- Capture a frame
- End the programm

Again the application runs fine. Now open the captured frame. The graphics analyzer crashes with a Runtime exception while opening the vslog file.

Here some details about my changes. I create an upload heap and place a buffer inside it. Then I map the buffer and keep it mapped until the application is closed.
```
D3D12_RESOURCE_DESC NativeResourceDescriptor;

NativeResourceDescriptor.Dimension          = D3D12_RESOURCE_DIMENSION_BUFFER;
NativeResourceDescriptor.Alignment          = 0;
NativeResourceDescriptor.Width              = 256;
NativeResourceDescriptor.Height             = 1;
NativeResourceDescriptor.DepthOrArraySize   = 1;
NativeResourceDescriptor.MipLevels          = 1;
NativeResourceDescriptor.Format             = DXGI_FORMAT_UNKNOWN;
NativeResourceDescriptor.SampleDesc.Count   = 1;
NativeResourceDescriptor.SampleDesc.Quality = 0;
NativeResourceDescriptor.Layout             = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;
NativeResourceDescriptor.Flags              = D3D12_RESOURCE_FLAG_NONE;

D3D12_RESOURCE_ALLOCATION_INFO NativeAllocationInfo = m_device->GetResourceAllocationInfo(0, 1, &NativeResourceDescriptor);

D3D12_HEAP_DESC NativeHeapDescriptor;
        
NativeHeapDescriptor.SizeInBytes                     = NativeAllocationInfo.SizeInBytes;
NativeHeapDescriptor.Properties.Type                 = D3D12_HEAP_TYPE_UPLOAD;
NativeHeapDescriptor.Properties.CPUPageProperty      = D3D12_CPU_PAGE_PROPERTY_UNKNOWN;
NativeHeapDescriptor.Properties.MemoryPoolPreference = D3D12_MEMORY_POOL_UNKNOWN;
NativeHeapDescriptor.Properties.CreationNodeMask     = 1;
NativeHeapDescriptor.Properties.VisibleNodeMask      = 1;
NativeHeapDescriptor.Alignment                       = 0;
NativeHeapDescriptor.Flags                           = D3D12_HEAP_FLAG_ALLOW_ONLY_BUFFERS;

ThrowIfFailed(m_device->CreateHeap(&NativeHeapDescriptor, IID_PPV_ARGS(&m_NativeHeapPtr)));

ThrowIfFailed(m_device->CreatePlacedResource(m_NativeHeapPtr.Get(), 0, &NativeResourceDescriptor, D3D12_RESOURCE_STATE_GENERIC_READ, nullptr, IID_PPV_ARGS(&m_NativeBufferPtr)));

void* pMappedMemory;

CD3DX12_RANGE NativeRange(0, 0);

ThrowIfFailed(m_NativeBufferPtr->Map(0, &NativeRange, &pMappedMemory));
```
The reason for the crash seems to be the call of the Map method.

Here some bachground Information, why I would like to do this: In our engine we go for a triple back buffer swapchain and I've implemented a system to simplify the usage of dynamic buffers (e.g. for constant and instancing buffers). For each back buffer I use a different upload buffer, so I create a heap and place three buffers inside of it. At the end it is an implementation of the earlier NOOVERWRITE idea and of course I could do this with a single buffer. However, the association with the back buffers makes if very easy to ensure that a resource is not longer used by the GPU.

My current work around is to simply create three committed resources (maybe this is also the better approach, since the driver can handle the resources independently).

Kind regards,

Joerg Sahm

[D3D12HelloTriangle_cpp.txt](https://github.com/Microsoft/DirectX-Graphics-Samples/files/234425/D3D12HelloTriangle_cpp.txt)
[D3D12HelloTriangle_h.txt](https://github.com/Microsoft/DirectX-Graphics-Samples/files/234424/D3D12HelloTriangle_h.txt)

**Comment by bobbrow** [comment]
I can reproduce this crash and will forward it on to the tools team.  One thing I noticed in this code, however, is that I don't ever see an aliasing barrier used to "activate" the placed resource.  Not all drivers are strict about this, but take a look at the Remarks section on the MSDN page that discusses [CreatePlacedResource](https://msdn.microsoft.com/en-us/library/dn899180(v=vs.85).aspx).

**Comment by Yoshusa** [comment]
Hi Bob,

thank you for pointing out the need for an aliased barrier. I've skipped that part in the documentation, cause though my placed resources are within the same heap, they do not overlap. Now I know, I was wrong, so thanks again.

I've changed the sample code accordingly and attached the corrected version to this post:
```
D3D12_RESOURCE_BARRIER NativeResourceBarrier;

NativeResourceBarrier.Type                     = D3D12_RESOURCE_BARRIER_TYPE_ALIASING;
NativeResourceBarrier.Flags                    = D3D12_RESOURCE_BARRIER_FLAG_NONE;
NativeResourceBarrier.Aliasing.pResourceBefore = nullptr;
NativeResourceBarrier.Aliasing.pResourceAfter  = m_NativeBufferPtr.Get();

m_commandList->ResourceBarrier(1, &NativeResourceBarrier);
ThrowIfFailed(m_commandList->Close());

ID3D12CommandList* ppNativeCommandLists[] = { m_commandList.Get() };
m_commandQueue->ExecuteCommandLists(_countof(ppNativeCommandLists), ppNativeCommandLists);
```
Unfortunately, the graphics analyzer keeps crashing.

I will close the issue.

Cheers,

Joerg

[D3D12HelloTriangle_cpp.txt](https://github.com/Microsoft/DirectX-Graphics-Samples/files/235902/D3D12HelloTriangle_cpp.txt)
[D3D12HelloTriangle_h.txt](https://github.com/Microsoft/DirectX-Graphics-Samples/files/235901/D3D12HelloTriangle_h.txt)
