### ISSUE TITLE
PreCompile Shader Questions

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#148]
Hey Guys,

I have a question about the proper way to precompile shaders:
Imagine I have a hlsl file which have bunch of macro defines in it, and I need to compile that single hlsl file with bunch of different macro define combinations to generate bunch of different shader byte code files. It can be easily handled if I compile that hlsl file during run time. But how to do it during compile time? I see MiniEngine use shader header file to define the macro it needed, but that will result in tons of shader header files which I try to avoid (and in some rare cases write individual shader headers is not practical...)

I see some other game engines use separate program to handle this (usually they call it 'Linker', which will do a lot of other stuffs too). But I just wondering is there anyway we can have visual studio to properly handle this for us?

Thanks

Peng

**Comment by stanard** [comment]
MiniEngine used to generate .CSO (compiled shader object) files that it would read from disk, but the disadvantage to that was making sure they were on your path, and with multiple projects generating CSOs, that could cause headaches.  I switched to header files out of preference.

But either way, if you choose to build shaders with Visual Studio, it's annoying that you can only define one entry point per file.  I get around that by having dummy wrappers that include the shader file I want to permute with options.  For instance, ToneMap2CS.hlsl includes ToneMapCS.hlsl but only changes some #defines.

If you want to keep doing offline compilation, but your needs are getting more advanced (like procedurally generating shader permutations), you can either have a separate shader build system (e.g. a script or a Makefile), and you can invoke it from Visual Studio as either a project Build Event or Custom Build Step.

One improvement I'd like to make to MiniEngine is for dynamic shader reloading.  I haven't designed that feature yet, but it probably means removing the compile-to-header step.  (Or just using the compiled header as the default version of a shader before recompile.)

-James

**Comment by pengliu916** [comment]
The good thing I noticed about using VS to do offline compilation is that it can skip files which are not modified, which saves iteration time. I guess we cannot easily get this feature with project prebuild event or custom build step unless we have fancy make file or script which can cache build result?

It seems there is no easy solution to that I guess, but thanks so much for answering my questions

Have a great day~

Peng
