### ISSUE TITLE
Best way to emulate DX11.1 constant buffers in DX12

### ISSUE THREAD

**Issue by DrGr4f1x** [Microsoft/DirectX-Graphics-Samples#150]
I'm building a hobby renderer on top of MiniEngine, along with a DX11 MiniEngine-workalike backend.  In DX11 mode I use the 11.1 constant buffer feature to create a single constant buffer for each material, with all constant data for all shader stages packed into the one cbuffer.  I'm trying to figure out the best way to emulate this in DX12/MiniEngine.

So far I've modified the GpuBuffer class, following the pattern in the HelloConstantBuffers sample to create the single constant buffer.  I then map individual CBVs onto the GPU resource and obtain CPU handles, which I can bind to the pipeline using a descriptor table with all the CBV CPU handles.  This works fine.

But what I want to try is embedding the constant buffers in the root signature directly, however I only have one GPU handle for the whole constant buffer, not the several I'd need for the per-shader sub-buffers.  I know the byte offsets to the start of the per-shader data in the main cbuffer - can I safely compute new GPU handles for the sub-buffers using those offsets?  Is there another approach I should try here?  Is there any performance advantage to using constant buffers embedded in the root signature, versus the descriptor table approach?

Thanks,
Dave Elder

**Comment by stanard** [comment]
Yes, you can safely compute new GPU handles by offsetting the 'ptr' field.  That's how you can get SetConstantBuffers1() behavior:  offset the pointer and bind it directly to the root parameters.

The advantage of using a root CBV is that it's fewer indirections for the shader.  The fastest approach is to have inline constants, but you will quickly run out of space in the root table if you go much over 4 inline constants.  You get about 13 words of data before additional parameters spill to a different buffer.

So inline constants have 0 indirections.  They are loaded directly in the shader registers by the GPU command processor.

Root constant buffers have 1 indirection.  A shader register is populated with the pointer, but the shader has to load (and wait for) the constants.

A descriptor table of constant buffers has 2 indirections.  A shader register is populated with the pointer to the table.  The descriptor must first be loaded followed by the constant value.

Each indirection is a measurable stall, but the GPU is good at hiding this latency by switching to other work.  However, multiple indirections can definitely have a noticeable impact.  And remember that if you overflow your root table, you add an indirection to everything that overflowed.

I believe in DX11, everything had 2 indirections, so DX12 makes it possible to optimize them away.  However, it's also possible in DX12 to end up with 3 indirections if you aren't conscious of how big root entries are, and how much you are using.

-James

**Comment by DrGr4f1x** [comment]
Excellent, thanks for the info.  This should improve my strategy for laying out root signatures efficiently.  I don't yet have support for inline constants in my material system, but I plan to add that soon.  Emulated SetConstantBuffers1() should solve my general use case.

-- Dave Elder
