### ISSUE TITLE
Recommendations on CPU update Texture

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#151]
Hey Guys,

My recent project need a CPU update Texture for DX12 renderer (basically the cpu will read Kinect RGBD buffer and copy it to a DX12 texture2d resource almost every 16ms), I have asked for recommendations between [use Buffer or Texture](http://www.gamedev.net/topic/678310-use-buffer-or-texture-ps-or-cs-for-gpu-image-processing/) in gamedev, and get some roughly ideas.

But when I plan to implement it, all the sudden, I figured out there is no "map discard" anymore (normally I use map discard to copy data in to texture in dx11 and before, which suppose to be the fastest way). Then later I find out there is UpdateSubresources could do that kind of CPU->GPU copy. But it seems I have to implement the 'Discard' resource hazard management stuff myself (please correct me if I get that wrong).

What even more interesting to me is that after looking through the implementation for UpdateSubresources, I found it just do kinda row by row memcpy, which means there is no swizzling for this texture. So it seems I cannot get the fast random access by making that as Texture, which made the choice between Buffer or Texture not important anymore (please correct me if Texture and Buffer still make some difference)

My original plan was to extend MiniEngine's Texture class to support this CPU update Texture, but it seems there are more thing I need to understand before I move on. So please give me some hints or suggestions on CPU frequently updating Texture/Buffer (this Texture/Buffer will be read by GPU a few times every frame):

1. Is there any way to fast copy CPU buffer into a swizzled Texture2D?
2. Is the benefit for fast random access worth the overhead by updating swizzled Texture2D?
3. Is it worth to first copy the CPU buffer to a upload heap and then copy it to a default heap every 16ms?
4. What's the proper way to implement "DX11 map discard" routine for texture update in DX12? or are there better ways existing in DX12?
5. If MiniEngine will support this kind of Texture, how will you guys approach it?

Sorry for dumping those questions to you guys, but I can't think of a better place to ask.

Thanks in advance

Peng

**Comment by stanard** [comment]
1) A Texture2D will be swizzled in video memory as per the most optimal tiling mode of the GPU.  When you call something like CopyTextureRegion() from a CPU-visible "upload heap" to the GPU-visible "default heap", it will get swizzled as part of the copy.

2) I think you're asking of it's important to swizzle the texture, and the answer is yes, but only for reused textures.  Not for one-time accesses.

3) You probably want frequently-accessed textures in video memory.  But if the CPU updates the texture every frame, and you only read each pixel once on the GPU, there would be no benefit to copying it to video memory before sampling it.

4) Map discard was an artifact of having the the driver hide the details of a buffer that must be copied in the background to the GPU.  With DX12, you can map an upload heap and manage data hazards yourself.  (You can even leave it mapped permanently.)  Then you will issue a copy command on the GPU timeline to a default heap.  Be sure to wait for that copy to have completed (with a fence) before overwriting the memory in your upload heap.  This is the basis for ring buffer-type allocators.

5) We did not previously have a need for per-frame CPU texture updates, but this is a good use case.  We'll explore adding this functionality to demonstrate best practices.  Thanks for the idea!

-James

**Comment by pengliu916** [comment]
Thanks James, that helps. I will close this issue for now

**Comment by mprevot** [comment]
@stanard @pengliu916 This situation is very interesting. Was the use case added in any sample, to check out the best practices ?
