### ISSUE TITLE
TextVS DrawInstanced(4, primcount, 0, 0)

### ISSUE THREAD

**Issue by cpyburn** [Microsoft/DirectX-Graphics-Samples#152]
while debugging TextRenderer and TextVS I noticed that the shader used a cool trick to create an instanced quad using just one position and the SV_VertexID so when I started investigating further using diagnostic tools I see that after the 3rd vertice the SV_VertexID = 0, but your code still thinks the SV_VertexID = 3.  So I decided to write a small quad engine using your trick from the mini engine, but my SV_VertexID always = 0 after every third vertice
![untitled](https://cloud.githubusercontent.com/assets/17934438/14967578/b2b5725a-107d-11e6-8063-76bd3d4aad30.png)
.  How is this working?  Is it a bug?

**Comment by stanard** [comment]
This trick relies on drawing multiple instances with 4 vertices each.  The sprite data repeats for all four vertices but changes for each instance.  Internally, SV_VertexID should range from 0 to 3 for the four vertices in the quad, and SV_InstanceID should increment for each quad rendered.  Are you setting the instance count to the number of primitives and the vertex count to 4 when you call DrawInstanced()?  Are you setting your vertex streams to be "per instance" as in TextRenderer?  Is primitive topology set to D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP?

D3D12_INPUT_ELEMENT_DESC vertElem[] =
{
	{ "POSITION", 0, DXGI_FORMAT_R32G32_FLOAT     , 0, 0, **D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA**, 1 },
	{ "TEXCOORD", 0, DXGI_FORMAT_R16G16B16A16_UINT, 0, 8, **D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA**, 1 }
};

m_Context.DrawInstanced( 4, primCount );

I hope that helps you find your bug!

-James

**Comment by cpyburn** [comment]
Everything works great until I get to the 4th vert
![allocation](https://cloud.githubusercontent.com/assets/17934438/14968359/2a1786b0-1071-11e6-99d5-c0b492bde4bf.png)
Vert3 looks great
![vert3](https://cloud.githubusercontent.com/assets/17934438/14968364/2d6a5446-1071-11e6-85cd-6f486b3da32b.png)
Vert4 goes to zero
![vert4](https://cloud.githubusercontent.com/assets/17934438/14968367/30966ea2-1071-11e6-83c2-d8c71b6e42f3.png)

**Comment by cpyburn** [comment]
Found the issue, lol, I was using trianglelist and not trianglestrip, thanks so much for your help!
