### ISSUE TITLE
DXGI_ERROR_DRIVER_INTERNAL_ERROR

### ISSUE THREAD

**Issue by cpyburn** [Microsoft/DirectX-Graphics-Samples#157]
DXGI_ERROR_DRIVER_INTERNAL_ERROR: There is strong evidence that the driver has performed an undefined operation; but it may be because the application performed an illegal or undefined operation to begin with.). [ EXECUTION WARNING #233: DEVICE_REMOVAL_PROCESS_POSSIBLY_AT_FAULT]

When trying 900x900 everything works fine, as soon as I increase vertex description to 1000x1000 it crashes.

`		DX::ThrowIfFailed(d3dDevice->CreateCommittedResource(
			&CD3DX12_HEAP_PROPERTIES(D3D12_HEAP_TYPE_UPLOAD),
			D3D12_HEAP_FLAG_NONE,
			&vertexBufferDesc,
			D3D12_RESOURCE_STATE_GENERIC_READ,
			nullptr,
			IID_PPV_ARGS(&m_vertexBufferUpload)));`

**Comment by bobbrow** [comment]
Just to clarify, do you get the error when creating your vertex buffers, or when attempting to execute the command list?

The code you posted does not send vertices to the GPU.  Upload heaps reside in system memory, so hopefully you aren't sending an upload heap with 1,000,000 vertices in it to the GPU for execution.  You should copy them to a Default heap first so that they are resident in GPU memory.

**Comment by cpyburn** [comment]
I edited my original post.  This happens when creating the committed resource, not executing the command list and, yes, I copy them to the default heap first.
'		CD3DX12_RESOURCE_DESC vertexBufferDesc = CD3DX12_RESOURCE_DESC::Buffer(vertexBufferSize);

		DX::ThrowIfFailed(d3dDevice->CreateCommittedResource(
			&CD3DX12_HEAP_PROPERTIES(D3D12_HEAP_TYPE_DEFAULT),
			D3D12_HEAP_FLAG_NONE,
			&vertexBufferDesc,
			D3D12_RESOURCE_STATE_COPY_DEST,
			nullptr,
			IID_PPV_ARGS(&m_vertexBuffer)));

		DX::ThrowIfFailed(d3dDevice->CreateCommittedResource(
			&CD3DX12_HEAP_PROPERTIES(D3D12_HEAP_TYPE_UPLOAD),
			D3D12_HEAP_FLAG_NONE,
			&vertexBufferDesc,
			D3D12_RESOURCE_STATE_GENERIC_READ,
			nullptr,
			IID_PPV_ARGS(&m_vertexBufferUpload)));'

**Comment by bobbrow** [comment]
How large is vertexBufferSize and how much video memory does your GPU have access to?  You can use ```IDXGIAdapter::QueryVideoMemoryInfo``` to learn how much memory your app is budgeted to use.

Based on your posts so far, it appears that creating the default heap was successful, so the GPU does have sufficient memory to store your vertices in the D3D12 version.  However, you may need to work with several smaller Upload heaps and take a round-robin approach to uploading vertices one section at a time to get parity with D3D11 (where the driver might have been doing this for you).  There is an issue in D3D12 related to creating multi-GB Upload heaps that was fixed for the Windows 10 Anniversary Update coming out in a few month, but I can't determine whether this is the issue you're hitting or not.

**Comment by cpyburn** [comment]
As far as I am concerned, its not a big deal nor really a bug, I don't ever load 1000x1000 vertices at once, I break them up into smaller chunks.   I was just testing benchmarks and thresholds when I found it and thought it was weird that something worked in D3D11 that didn't in D3D12.  You can close this issue if you want, or leave it open and I will try to remember to come reply when the new patch comes out next month.

**Comment by bobbrow** [comment]
I'll close it for now.  If you continue to see problems, please reopen it.  Thanks!
