### ISSUE TITLE
Horizontal stripes artifacts with sync interval 1

### ISSUE THREAD

**Issue by nikitablack** [Microsoft/DirectX-Graphics-Samples#162]
Hello,

In HelloTriangle example if I call `Present(0, 0)` - notice `0` as sync interval - **sometimes** horizontal stripes (same color as a background) appears on a triangle. It looks like tearing, but I thought tearing can be visible only on moving objects. With `Present(1, 0)` I can't see any artifacts.

**Comment by bobbrow** [comment]
It sounds more like corruption than true tearing.  I can reproduce this a little bit more reliably on a laptop by dragging the window around.  I presume you're running this on the same laptop that you mentioned in your post for Issue #109.

We have a few fixes coming out for laptops with both discrete and integrated GPUs in next week's Windows Update.  Let me know if KB 3163018 doesn't resolve this issue and we can look into it further.  It appears to resolve the issue for the laptop that I am testing (an 860M).

**Comment by nikitablack** [comment]
Thank you Bob. Yes, I'm working on a laptop. I'll post the result here as soon as I'll get an update.

**Comment by nikitablack** [comment]
I'm confirming that KB 3163018 fixed issues with tearing.
