### ISSUE TITLE
New MiniEngine features

### ISSUE THREAD

**Issue by DrGr4f1x** [Microsoft/DirectX-Graphics-Samples#163]
I noticed that the MiniEngine sample in the March 2016 Xbox One XDK has some new rendering features that the GitHub version doesn't have.  Are there plans to make those features available in this GitHub repo?  What's the expected timeline, if so?

**Comment by stanard** [comment]
The only code that should be absent from GitHub is code that requires an Xbox developer NDA.  But they don't update at the same time, so one released version might have newly developed features that the other still lacks.  What features in particular were you interested in?  (Or if they are Xbox-specific techniques, please just say that so as to not accidentally violate your NDA.)

**Comment by DrGr4f1x** [comment]
I'm specifically interested in depth of field.  That feature is functional
in the Windows build in the XDK, so it doesn't seem to be an Xbox-specific
technique.  But it's not in the public Github yet.

**Comment by stanard** [comment]
It should be, actually, but I confirmed it's not in the master branch yet.  If you switch to the develop branch, it's there.  I'll ask around here why that feature hasn't been pushed to master yet.

**Comment by DrGr4f1x** [comment]
Actually, I just noticed the develop branch, which does have depth of field.  I'd been working off the master branch only, and missed it.

**Comment by bobbrow** [comment]
That was a lapse on my part.  The MiniEngine update that was parked in develop has been merged to master now.
