### ISSUE TITLE
Strange Texture3D perf behavior

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#164]
Hey Guys,

I am sorry for posting a issue which is not super related to this repo. But given the fact no one on gamedev reply my post and that my profiling program is based on a slightly modified MiniEngine. So I hope you guys could give me some insights about what happened or what I did wrong.

The problem is described here (include video capture, and source):
http://www.gamedev.net/topic/679265-texture3d-strange-behavior-in-volume-raycasting/ 

Thanks.

And if you guys think this totally unrelated, please feel free to close this issue.

Peng

**Comment by bobbrow** [comment]
Maybe try the new www.directxtech.com website and see if anyone there can help.
