### ISSUE TITLE
DoFTilePassCS.hlsl missing

### ISSUE THREAD

**Issue by DrGr4f1x** [Microsoft/DirectX-Graphics-Samples#166]
The DoFTilePassCS.hlsl shader seems to be missing after merging develop into master.

**Comment by DrGr4f1x** [comment]
Also DoFTilePassFixupCS.hlsl

**Comment by DrGr4f1x** [comment]
As a local workaround, I dropped in the missing shaders from the XDK and everything works fine, but not everyone has access to that, of course.

**Comment by stanard** [comment]
Sorry about that.  We'll get it fixed tomorrow.

**Comment by bobbrow** [comment]
The shaders have been added.  Thanks for reporting this issue.
