### ISSUE TITLE
About new Multi GPU abstraction layer talked at Polaris tech day..

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectX-Graphics-Samples#173]
according to PCPER:
"Microsoft’s Chas Boyd was on-hand at AMD’s editor’s day for Polaris and previewed ideas that MS is implementing to help improve multi-GPU scaling. The best news surrounded **a new abstraction layer for game developers to utilize for multiple GPU support that MS would be releasing on GitHub very shortly**. According to Microsoft, with only “very little” code adjustment, DX12 titles should be able to implement basic multi-GPU support."

would this layer be avaiable on this repo?

also would be nice to hear also about:
"previewed ideas that MS is implementing to help improve multi-GPU scaling"

thanks..

**Comment by bobbrow** [comment]
Yes, the layer will be available in this repo.  We will also be publishing two mGPU sample projects along with it - one using the layer and one not using the layer.  We're making some final tweaks and doing additional testing and plan to post it all soon.

**Comment by pritster5** [comment]
Will this layer be used to implement Multi-GPU support in games using UWP and the Windows Store (e.g. Gears of War: Ultimate Edition and Quantum Break)?

**Comment by tjukic** [comment]
What will this layer provide actually? In what way?

**Comment by bobbrow** [comment]
@pritster5, the layer is shippable in UWP applications, so yes, titles in the Windows Store will be able to take advantage of the layer.  I can't say whether they will all use it or not though.  It's up to the studios producing the titles.  We believe that studios that write their own mGPU solutions tailored to their engines can outperform our general purpose library, but for studios lacking the resources to do so, this library should be a very effective resource.

@tjukic, this first iteration of the layer will focus on providing a solution for alternate frame rendering (AFR). We will be publishing some documentation with the layer explaining what it does and does not provide and how to weave it into your project. It's more information than would fit nicely into an issue thread such as this, so I'll hold off on that for now.

**Comment by bobbrow** [comment]
I have committed the MultiGPU abstraction layer and sample to the develop branch and merged to master today.  Take a look at the samples and the abstraction layer and let us know what you think.  There are additional details about the layer in the readme.md files for both the [sample](https://github.com/Microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12LinkedGpus) and the [library](https://github.com/Microsoft/DirectX-Graphics-Samples/tree/master/Libraries/D3DX12AffinityLayer)
