### ISSUE TITLE
Root signature validation for the hull shader

### ISSUE THREAD

**Issue by nikitablack** [microsoft/DirectX-Graphics-Samples#174]
Hello,

It looks like root signature validation for the hull shader doesn't work. In my HS I added constant/structured buffer and by purpose omitted a root parameter for this shader or set a deny flag but the PSO was successfully created. I thought I missed something and tried to do the same with vertex/domain/pixel shader. In this cases all worked as expected - I got an error on PSO creation.

**Comment by bobbrow** [comment]
Thank you for reporting the issue.  We'll look into it.

**Comment by walbourn** [comment]
Is this still an issue with the more recent versions of the layers?

**Comment by nikitablack** [comment]
Oh, six years have passed since I opened the issue. I'm closing it because I don't have the code/time to check it.
