### ISSUE TITLE
1 heap with 1 command list or...

### ISSUE THREAD

**Issue by cpyburn** [Microsoft/DirectX-Graphics-Samples#175]
Found the answer, closing issue.  (EDIT: leaving short version of the original question for anyone that wants to know.)

MSDN documentation is not very clear on performance do's and dont's when it comes to calling set heap and reset heap from multiple command lists during the 1 frame call.  Is it considered bad practice to set a heap per command list each frame draw without causing stalls and flushes?

Example: Draw tree with 2 srv with set heap1 execute commandlist1, and draw another tree with 2srv with set heap2 and execute commandlist2 in the same frame.

And is there a good place to post questions about Directx 12 without making an issue here?

**Comment by cpyburn** [comment]
Leave a comment

**Comment by bobbrow** [comment]
I see you have removed your question already. If you have suggestions on what you would like to see in the MSDN documentation, we are always open to feedback.

Also, we recently launched a public forum for D3D12.  [forums.directxtech.com](http://forums.directxtech.com)  That is now the best place to ask questions about D3D12 that don't necessarily relate to the code in this repository.

**Comment by cpyburn** [comment]
Well now I feel bad about removing the original post, so I will put it back up.  I found the answer in IBM documentation about multiple heap set and reset calls being bad.  And after thinking about it, it is not that hard to replace the heap descriptors and index the srv's through the indexes.  Just takes some logic.

**Comment by bobbrow** [comment]
Sorry, my intention was not to make you feel bad about removing the question. Just hoping to help improve our documentation for other developers who may run into a similar question in the future.

**Comment by nikitablack** [comment]
@bobbrow Sorry for writing it here, but I couldn't find another appropriate place. Since you posted a link to the new DirectX12 forum I immediately wanted to register but it seems that registration is broken - I always get `Sorry Guest, you are banned from using this forum!` message when trying to submit my registration data. And there's no any link to report about the problem.

**Comment by bobbrow** [comment]
Hmm, that's strange.  I just registered a new account right now and didn't have any trouble.  Is it alright if I email you and ask for more information so we can debug this?

**Comment by nikitablack** [comment]
Yes, it's absolutely alright.
