### ISSUE TITLE
Multithreading Sync Fence issue?

### ISSUE THREAD

**Issue by cpyburn** [Microsoft/DirectX-Graphics-Samples#177]
I know I am doing something wrong, its obvious because my fence says its complete before it is.  But I feel like I have done everything correctly according to D3D12nBodyGravity example.  Maybe a second set of eyes could help me out.  All I am doing is creating some geometry called terrain that has some vertex, index, and a SRV and uploading it.  Then I am trying to fence until it is done, and then release the upload buffer.  But my fence is saying it is done when it is not.

```
auto d3dDevice = m_deviceResources->GetD3DDevice();
			
			D3D12_COMMAND_QUEUE_DESC queueDesc = {};
			queueDesc.Flags = D3D12_COMMAND_QUEUE_FLAG_NONE;
			queueDesc.Type = D3D12_COMMAND_LIST_TYPE_DIRECT;

			ThrowIfFailed(d3dDevice->CreateCommandQueue(&queueDesc, IID_PPV_ARGS(&m_worldTiles[id].commandQueue)));
			ThrowIfFailed(d3dDevice->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT, IID_PPV_ARGS(&m_worldTiles[id].commandAllocator)));
			ThrowIfFailed(d3dDevice->CreateCommandList(0, D3D12_COMMAND_LIST_TYPE_DIRECT, m_worldTiles[id].commandAllocator.Get(), nullptr, IID_PPV_ARGS(&m_worldTiles[id].commandList)));

			m_worldTiles[id].terrain = new TessellatedTerrain(m_deviceResources);
			m_worldTiles[id].terrain->CreateDeviceDependentResources(m_worldTiles[id].commandList);
			m_worldTiles[id].terrain->CreateBuffers(m_worldTiles[id].commandList);

			// Close the command list and execute it to begin the vertex/index buffer copy into the GPU's default heap.
			DX::ThrowIfFailed(m_worldTiles[id].commandList->Close());
			ID3D12CommandList* ppCommandLists[] = { m_worldTiles[id].commandList.Get() };
			m_worldTiles[id].commandQueue->ExecuteCommandLists(_countof(ppCommandLists), ppCommandLists);

			ThrowIfFailed(d3dDevice->CreateFence(0, D3D12_FENCE_FLAG_SHARED, IID_PPV_ARGS(&m_worldTiles[id].pFence)));
			m_worldTiles[id].fenceHandle = CreateEvent(nullptr, FALSE, FALSE, nullptr);

			ThrowIfFailed(m_worldTiles[id].commandQueue->Signal(m_worldTiles[id].pFence.Get(), m_worldTiles[id].id));
			ThrowIfFailed(m_worldTiles[id].pFence->SetEventOnCompletion(m_worldTiles[id].id, m_worldTiles[id].fenceHandle));
			
			WaitForSingleObject(m_worldTiles[id].fenceHandle, INFINITE);

			// bug: this is released too early!
			m_worldTiles[id].terrain->ReleaseUpload();

			m_worldTiles[id].isLoaded = true;
			m_worldTiles[id].isLoading = false;
```

**Comment by bobbrow** [comment]
What is the value of ```m_worldTiles[id].id```?  Make sure it's greater than the initial value of the fence.

**Comment by cpyburn** [comment]
m_worldTiles[id] was just a unique Identifier.  I wasn't checking for any kind of increase but now that I read, I see I do.  I was thinking the fenceHandle would fire when the GPU was done and WaitForSingleObject was waiting on the event.  So how it really works is it checks for an increase in the fenceValue?  Do I need to use a ThrowIfFailed(m_worldTiles[id].commandQueue->Wait(fence, id>originalId)); ?  Sorry I am confused about the call back from the GPU.

**Comment by bobbrow** [comment]
ID3D12CommandQueue::Wait will insert a wait on the GPU, not the CPU, so you would still not be safe to release your upload heap on the CPU.

I should have been more clear, but all I was trying to say is that if you create a fence with "0" as the initial value and then call SetEventOnCompletion and pass in "0" as the value to monitor, the event will immediately be marked as completed because the fence value is already 0.  So in this case, WaitForSingleObject will return immediately since the fence value has already been satisfied and the CPU may release the upload heap before the GPU is done with it.

**Comment by cpyburn** [comment]
I am still a tad confused on its functionality.  If I create the fence with say 101.  Do I pass 102 into the SetEventOnCompleteion and it will get a call back when complete or do I need to check each update loop to see if the value has increased?

**Comment by bobbrow** [comment]
In this example you would:
  1. Create the fence with 101
  2. Signal the fence with 102
  3. SetEventOnCompletion with 102
  4. WaitForSingleObject  (blocks the CPU until the GPU has executed the Signal command - there is no "call back")

**Comment by cpyburn** [comment]
got it and it is working.
