### ISSUE TITLE
MiniEngine does not compile with /W4 and /WX

### ISSUE THREAD

**Issue by howprice** [microsoft/DirectX-Graphics-Samples#179]
It would be great if you could modify the code so that it compiles at Warning Level 4 with Treat Warnings as Errors enabled. I've had to disable some warnings to get MiniEngine to build with these settings locally.

**Comment by bobbrow** [comment]
I would disable C4100 and C4238 regardless, but I'll let James decide what he wants to do with level 4 warnings for MiniEngine.  Treating warnings as errors is generally good too.  I think that Visual Studio defaults to /W3, so that's why MiniEngine is where it is.

**Comment by walbourn** [comment]
See https://github.com/microsoft/DirectX-Graphics-Samples/pull/493
