### ISSUE TITLE
MiniEngine: RootSignature Hash does not include D3D12_ROOT_SIGNATURE_DESC.Flags 

### ISSUE THREAD

**Issue by howprice** [Microsoft/DirectX-Graphics-Samples#180]
The root signature hash does not include the flags, therefore two signatures that only differ by flags will incorrectly map to the same map entry.

**Comment by stanard** [comment]
Are you referring to MiniEngine?  I just looked in RootSignature.cpp and was shocked to find that you are correct.  Great find!  I will make a change locally and get it fixed on the next push to GitHub.  In the mean time, you can make this change:  

	size_t HashCode = Utility::HashState(&RootDesc.Flags);
	HashCode = Utility::HashState( RootDesc.pStaticSamplers, m_NumSamplers, HashCode );

**Comment by howprice** [comment]
Yes sorry, MiniEngine. That's the fix!
