### ISSUE TITLE
Modelviewer crashes right away

### ISSUE THREAD

**Issue by Swartz27** [Microsoft/DirectX-Graphics-Samples#182]
Hi, I'm on Windows 10 with a GTX 1080 video card and the latest drivers, compiling with Visual Studio 2015.

After successfully compiling the solution, I try and launch ModelViewer, it names my video card and amount of VRAM at the top of the window, then crashes.

I selected Debug and it gave me this error:

Unhandled exception at 0x00007FF727B3C05E in ModelViewer.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

**Comment by howprice** [comment]
> Access violation reading location 0x0000000000000000

What line is the debugger stopped on?

**Comment by Swartz27** [comment]
Disregard what I said. I had run it in Release config which is a bad habit of mine, instead of Debug. In Debug it told me the problem right away: I forgot to copy over the model folder :P 

Sorry for that.
