### ISSUE TITLE
The Graphics Diagnostic engine has encountered a fatal error.

### ISSUE THREAD

**Issue by albinopapa** [Microsoft/DirectX-Graphics-Samples#183]
Click on Debug / Graphics / Start Graphics Debugging, let it play a couple frames, capture a frame and then Stop.  Click on the captured frame title and when the Graphics Diagnostic window shows up it does some processing, then it gives the error message "The Graphics Diagnostic engine has encountered a fatal error."

I'm using Windows 10 release 14388 and Visual Studio Community with Update 3.  I had this problem with the 10240 build, then is was ok for the November update, now I'm having the same problem.

[Report20160719-1902.zip](https://github.com/Microsoft/DirectX-Graphics-Samples/files/372689/Report20160719-1902.zip)

PS, sorry didn't realize this, but this may not be in the right spot, my project isn't from the Graphics samples...let me know where I should direct my issue.

**Comment by nikitablack** [comment]
I also have this problems **sometimes**. Moreover if I open the **same** diagnostic file second time it **can work**! Definitely a strange behavior.

**Comment by albinopapa** [comment]
Ok, so did a reinstall of Windows back to the 1511 version, still had issues with the graphics analyzer, almost same issue, so it may not have been the 14388 release after all.  I originally had Direct2D 1.0 rendering some fonts to a WIC bitmap surface that I then would copy over to a dynamic ID3D11Texture2D, I wanted to avoid shared resources and keyed mutexes.  After updating the code to use Direct2D 1.1 for Windows 8, I was able to omit a lot of the steps and render directly to the texture and the graphics analyzer works as expected.  So perhaps, it doesn't like dealing with two different versions of D3D devices, since D2D 1.0 uses a D3D 10 device and I was using a D3D 11 device?
