### ISSUE TITLE
Request for samples: HDR10 in DXGI and "new wave-level operations in SM6.0" in Anniversary update..

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectX-Graphics-Samples#184]
Hi,
seems Anniversary update brings at least two talked @GDC improvements more early than thought..
and I would like to ask for some samples showing usage of that improvements.. Specifically:
1)HDR support.. there is HDR10 support in DXGI 1.5..
a sample would be good as right now we only had a Nvidia HDR sample using NVAPI..
Some questions:
a) don't read documentation in MSDN in full but that brings also windowed HDR support or that will come on later Windows update.. API wise windowed HDR support will require changes vs a fullscreen HDR app..
b) Driver status: can you talk if current "true HDR" GPUs like AMD RX480 and Nvidia Pascal series current drivers ship both HDR support in DXGI?
2)SM6.0 with wave level ops:
also some sample showing how to take advantage of this ops in practical graphics app will be good..
Also drivers from IHVs support this ops: I mean AMD, Nvidia and even Intel Skylake GPUs?
also talked @GDC was open sourcing a Clang HLSL shader compiler supporting this SM6.0 ops..
has this been done already? or SM6.0 support is in FXC right now with "old" compiler?

thanks..

**Comment by alessiot89** [comment]
As far I know, Shader Model 6.0 requires a new compiler which is not yet public. SM6 rest on DXIL which is based on LLVM IR v3.7. You can ask Microsoft to enter the private beta if you are really interested in the  new compiler development: http://forums.directxtech.com/index.php?topic=5717.0

**Comment by bobbrow** [comment]
Yes, there is some groundwork for future HDR support starting to show up in DXGI 1.5.  We're not all the way there yet though and we'll have more details as well as a sample coming later.

**Comment by oscarbg** [comment]
almost half a year later, any news here?
there have been shipping PC Windows games using HDR like Obduction,Resident Evil 7, ShadowWarrior 2..
are this games using standard DXGI HDR APIs or propietary vendor ones like NVAPI?
I say this because at least Resident Evil 7 is a Windows Store game and think that NVAPI AMD AGS aren't supported there..
So is full HDR support coming in Redstone2 aka Creators update this April or a full HDR Windows compositor for non full screen apps will be coming later (Redstone 3? EOY 2017)
thanks..
