### ISSUE TITLE
DX12 Indirect Drawing Texture Binding

### ISSUE THREAD

**Issue by Jarek232** [Microsoft/DirectX-Graphics-Samples#185]
Hello,

I would like to know if there exists any possibility to change texture binding in command signature. Documentation states "The commands optionally containing state to set for vertex buffer views, index buffer views, root constants and root descriptors (raw or structured SRV/UAV/CBVs). ". Which means that I can only change root descriptors. In example ExecuteIndirect there is only cbv change, what if I need to set texture as well after performing culling. As far as I know textures cannot be placed directly in root descriptors but in tables.

Thanks

**Comment by bobbrow** [comment]
Textures (SRVs) and UAVs can also be placed in root descriptors.  We just didn't do that in the sample.
