### ISSUE TITLE
map subresource 0 but access other subresources

### ISSUE THREAD

**Issue by zhangkeming** [Microsoft/DirectX-Graphics-Samples#189]
This will only map subresource 0, but use pLayouts[i].Offset to access other subresources.
DirectX-Graphics-Samples/Samples/Desktop/D3D12HelloWorld/src/HelloBundles/d3dx12.h
line 1740:   
    HRESULT hr = pIntermediate->Map(0, NULL, reinterpret_cast<void**>(&pData));
    if (FAILED(hr))
    {
        return 0;
    }
    
    for (UINT i = 0; i < NumSubresources; ++i)
    {
        if (pRowSizesInBytes[i] > (SIZE_T)-1) return 0;
        D3D12_MEMCPY_DEST DestData = { pData + pLayouts[i].Offset, pLayouts[i].Footprint.RowPitch, pLayouts[i].Footprint.RowPitch * pNumRows[i] };
        MemcpySubresource(&DestData, &pSrcData[i], (SIZE_T)pRowSizesInBytes[i], pNumRows[i], pLayouts[i].Footprint.Depth);
    }

**Comment by bobbrow** [comment]
Map will get the address of subresource 0's data.  All subresources are in a contiguous block of memory and the layouts tell you where each subresource begins.
