### ISSUE TITLE
MiniEngine: Hard coded for material size

### ISSUE THREAD

**Issue by MichaelWei1990** [microsoft/DirectX-Graphics-Samples#190]
Hi, I am wondering in the mini engine sample, is there anywhere that hard coded the material size to be 26, which is the number of materials for the Sponza.h3d model. The rendering starts to have problem as mini engine removes the previously mapped textures when the number of materials is beyond 26. Perhaps the size is hard coded in shaders, constant buffer view settings or somewhere else?

**Comment by stanard** [comment]
This might point to a bug in the model converter.  Can you put a break point in Model::LoadH3D() and see what you are getting for the materialCount in the header?  I don't see any hard-coding of this size, but it determines the number of materials from the file header and allocates an array of the appropriate size at runtime.

**Comment by MichaelWei1990** [comment]
The number of materials of Sponza model is 27, including the default material but it is never used. In other words, there are only 26 materials is populated in GPU. Perhaps the hard-coding is in shader(s)?

**Comment by stanard** [comment]
In this situation, a "material" is just a set of 6 textures.  The shader root signature defines how large each descriptor table is, which _is_ hard-coded to 6 SRVs.  The number of 6-texture materials associated with a model should be set in the converted model file.  So I'm not sure what could be the problem yet.  Did you start with your own OBJ and convert it?  There are some things about our model and material handling that are tailored for the Sponza scene specifically, but I'd like to know what is actually getting in your way.

**Comment by MichaelWei1990** [comment]
The material number is not hard-coded but the maximum number of descriptors per heap is. The problem is solved by increasing the maximum value. Thank you very much for the help and you may close this issue.

**Comment by stanard** [comment]
We just pushed several bug fixes.  One of them related to dynamic descriptor heap rollover.  If you fixed your problem by increasing the size of the heaps, then maybe you were hitting the bug.  You could try getting our latest code and revert your fix to see if you still have the same problem with textures dropping out.  Cheers.
