### ISSUE TITLE
Calling resize buffers on AMD graphics throws in the Memory Management project

### ISSUE THREAD

**Issue by flying-phoenix** [microsoft/DirectX-Graphics-Samples#193]
After some testing with fullscreen transitions, I realized that my code worked on Intel Graphics, but the resize buffers would throw on AMD Graphics. Did some more testing, and even the Memory Management sample with no changes, throws when calling resize buffers on AMD Graphics.

**Comment by walbourn** [comment]
You should check that it's not an exception being thrown and handled inside the runtime/driver. The debugger can be breaking internally on an exception throw which is then handled before the application gets back an HRESULT.

**Comment by bobbrow** [comment]
I am not seeing any issues with the Memory Management sample on the Windows 10 Anniversary Update with an RX 480 on the latest driver from AMD.  Can you upload a dxdiag to provide more details about your PC?  Is this a laptop?

**Comment by flying-phoenix** [comment]
I should have been more specific. It's a laptop with hybrid graphics Intel(R) HD Graphics 5500 as the secondary card and AMD Radeon R7 M260 as the primary. The OS is Windows 10. If I choose Intel as the adapter in the sample prompt, it runs with no problems. Choosing AMD makes it throw when calling resize buffers. The exception is not being handled, it breaks even while running without debugging. I will provide a dxdiag as soon as I can.

**Comment by flying-phoenix** [comment]
[DxDiag.txt](https://github.com/Microsoft/DirectX-Graphics-Samples/files/454046/DxDiag.txt)

Adding the DXDiag. Also, just realized I was using my "game account" when I opened the issue. Guess I'm sticking to it now.

**Comment by walbourn** [comment]
Does this issue still happen on modern versions of Windows / drivers?
