### ISSUE TITLE
Running these samples with application verifier

### ISSUE THREAD

**Issue by ghost** [microsoft/DirectX-Graphics-Samples#194]
I had an issue with some code and used application verifier to help me track down the issue.  Then I noticed there was an issue very early on.  The errors are from the full screen example, but they are in all the samples.

I tested even the hello world samples and the same issue was coming up.  I get two stops.

The first is on the line:
if (SUCCEEDED(D3D12CreateDevice(pAdapter, D3D_FEATURE_LEVEL_11_0, _uuidof(ID3D12Device), nullptr)))
# the output window says:

VERIFIER STOP 0000000000000900: pid 0xE98: A heap allocation was leaked. 

```
0000021B71B3AFF0 : Address of the leaked allocation. Run !heap -p -a <address> to get additional information about the allocation.
0000021B6A866FF0 : Address to the allocation stack trace. Run dps <address> to view the allocation stack.
0000021B75492FD8 : Address of the owner dll name. Run du <address> to read the dll name.
00007FFD9D6B0000 : Base of the owner dll. Run .reload <dll_name> = <address> to reload the owner dll. Use 'lm' to get more information about the loaded and unloaded modules.
```

The second is in the file client.h from the comptr.
 ref = temp->Release();
the last line of code before going to DXGI was
D3D12Fullscreen.exe!Microsoft::WRL::ComPtr<IDXGISwapChain3>::InternalRelease() Line 196
# the output window says

VERIFIER STOP 0000000000000303: pid 0xE98: NULL handle passed as parameter. A valid handle must be used. 

```
0000000000000000 : Not used.
0000000000000000 : Not used.
0000000000000000 : Not used.
0000000000000000 : Not used.
```

**Comment by bobbrow** [comment]
Thanks for reporting this issue.  We'll take a look.

**Comment by bobbrow** [comment]
Just an update.  The first one is a leak in the debug layer and I filed a bug on that.  I have not been able to reproduce the second one.
