### ISSUE TITLE
Why working DX12 application crashes when launch remotely over RDP?

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#200]
Hey Guys,

Though this topic may seems a little bit irrelevant to MiniEngine, but I think you guys are the best person to ask. So I have a modified version of MiniEngine based application which works properly, but when I use Microsoft RDP to launch my app remotely, it crashes. What more interesting is that if I use Google Remote Desktop to launch remotely, it still works properly. And all MiniEngine demo doesn't have this issue, my guess is that there are some specific configuration I need to set during swap chain creation. So it will be greatly appreciated if you guys could enlightening me or directing me to the right place to ask.

Thanks

Please feel free to close this issue if you think this is totally not relevant to MiniEngine

**Comment by pengliu916** [comment]
It turned out RDP just randomly crash not only my app but also D3D12HelloWorld. 
To be more specific: I was using iPad Pro connected to my home machine which has nVidia GTX 680m running on windows 10.0.14393, sample was uptodate as today.
For me it seems out of 5 launch 3(both my program and D3D12HelloTriangle) will crash right after window is showing up with everything white inside.

Please let me know if you need more information
Thanks

**Comment by bobbrow** [comment]
Do you have trouble with DX11 or DX9 apps as well?  I feel that this issue is beyond the scope of what we cover in this repo, but if it's just a DX12 issue then maybe that will help us understand where to start.  You might also find more people available to help on the DirectXTech forums.

**Comment by pengliu916** [comment]
The problem bothers me is that DX11 apps works as normal when I see DX12 keeps crash during RDP session.

**Comment by pengliu916** [comment]
It turned out that the crash only happened when I RDP connect to one specific machine (specs mentioned in previous comment), so probably GPU HW related. Close this issue for good, thanks.
