### ISSUE TITLE
MiniEngine: CommandListManager::m_CommandQueue is null

### ISSUE THREAD

**Issue by venkatn93** [Microsoft/DirectX-Graphics-Samples#204]
In line 78, `CommandListManager::m_CommandQueue` is NULL when running the Debug and Profile builds. This bug is found in `CommandQueue::Create` of CommandListManager.cpp, part of the Core library. Does not trigger when running Release configuration.

**Fix:** Commenting out line 100 `pDevice->SetStablePowerState(TRUE);` seems to fix this bug. Forcing low GPU clocks seems to put the hardware in a state that fails creation of the CommandQueue.

My system is NVIDIA Geforce 1070, Intel i6500K

**Comment by stanard** [comment]
That's very interesting.  It seems specific to that card and/or driver though.  What version of the Nvidia driver are you using?  What version of Windows?  Maybe I can use this as an excuse to have my boss get me a 1070 (or 1080 ;-)  I'll do a little research into this on Monday morning, but thanks for letting us know.

-James

**Comment by venkatn93** [comment]
Hi James,
This does seem like a very ASIC specific issue, but I have not tested with others. I am using Windows 10 14393. I didnt bother mentioning it because can you even run DX12 without Windows 10? I have the latest public driver from NV.

Enjoy your weekend!

Niraj

**Comment by Warezovvv** [comment]
Same here with AMD 7870 and NVidia 950m.

**Comment by Warezovvv** [comment]
Only in debug crash. Release works as planned.

**Comment by pjx3** [comment]
Hi, I just hit this issue too, running with Windows 10.0.14393 & Nvidia GTX1080 driver version 376.33.

**Comment by Aotner** [comment]
Same issue here with Windows 10.0.14393 GTX1080M driver version 378.66

**Comment by weltkante** [comment]
issue #234 was showing similar symptoms, there it got fixed by enabling developer mode; it seems DEBUG builds are calling functions only available when developer mode is active and MiniEngine isn't graceful about handling/reporting when you aren't on developer mode.

**Comment by chadlayton** [comment]
It appears to be a registry setting: http://stackoverflow.com/questions/41231586/how-to-detect-if-developer-mode-is-active-on-windows-10

**Comment by stanard** [comment]
Thanks, Chad.  I found that same article and put this code in locally.  I'll push it up to GitHub soon.

```
bool DeveloperModeEnabled = false;

// Look in the Windows Registry to determine if Developer Mode is enabled
HKEY hKey;
LSTATUS result = RegOpenKeyEx(HKEY_LOCAL_MACHINE, L"SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\AppModelUnlock", 0, KEY_READ, &hKey);
if (result == ERROR_SUCCESS)
{
	DWORD keyValue, keySize = sizeof(DWORD);
	result = RegQueryValueEx(hKey, L"AllowDevelopmentWithoutDevLicense", 0, NULL, (byte*)&keyValue, &keySize);
	if (result == ERROR_SUCCESS && keyValue == 1)
		DeveloperModeEnabled = true;
	RegCloseKey(hKey);
}

WARN_ONCE_IF_NOT(DeveloperModeEnabled, "Enable Developer Mode on Windows 10 to get consistent profiling results");

// Prevent the GPU from overclocking or underclocking to get consistent timings
if (DeveloperModeEnabled)
	g_Device->SetStablePowerState(TRUE);
```

**Comment by walbourn** [comment]
Is there a non-registry way to detect this? You can't of course call ``RegQueryValueEx`` from a UWP, just Win32 classic desktop apps.

**Comment by stanard** [comment]
MiniEngine is Win32-only for now.  Perhaps with the addition of UWP in the future, we can keep Win32 around for development purposes.  Chuck, do you know what the mechanism for querying Developer Mode is in a UWP?  And can SetStablePowerState() be called in UWP?

**Comment by chadlayton** [comment]
Just a thought but another option would be to move the call to SetStablePowerState to Graphics::Initialize. From there you could test failure and just recreate the device and continue without calling SetStablePowerState again.

**Comment by stanard** [comment]
I made that change too, locally.  It was silly to call it every time a new command queue was created, however we only create one queue.  It belongs at device creation since that is what it operates on.

Cheers

**Comment by walbourn** [comment]
All MSDN has to offer is:

    Do not call this method in normal execution for a shipped application. This method only
    works while the machine is in developer mode. If developer mode is not enabled, then
    device removal will occur. Instead, call this method in response to an off-by-default,
    developer-facing switch. Calling it in response to command line parameters, config files,
    registry keys, and developer console commands are reasonable usage scenarios.

**Comment by stanard** [comment]
This bug fix is included in the Creators Update push.
