### ISSUE TITLE
Can't debug in graphics diagnostics since Windows 10 patch last night

### ISSUE THREAD

**Issue by cpyburn** [Microsoft/DirectX-Graphics-Samples#206]
Since my windows 10 update last night, I can no longer debug shaders using graphics diagnostics.  Attached is a screen shot of perfectly executing code (screenshot of it playing also attached), just crashes when debugged.

![untitled](https://cloud.githubusercontent.com/assets/17934438/19411128/10bc8ac8-92b0-11e6-975e-7b92b2928221.png)
![untitled1](https://cloud.githubusercontent.com/assets/17934438/19411130/13a765a0-92b0-11e6-8ab4-0b2686afe60b.png)

**Comment by bobbrow** [comment]
Can you share the information under the System32 section when you run ```dxcap -info```.  I want to check your binary versions.  I didn't think that there were any updates to the graphics tools in this week's update.

**Comment by cpyburn** [comment]
I already rolled back, to get it working, and it is working
![untitled1](https://cloud.githubusercontent.com/assets/17934438/19411548/af1c900c-92b8-11e6-9b6d-77627f3b878a.png)

**Comment by cpyburn** [comment]
here is the rolled back dxcap - info

System32 Info
=============
DxCap.exe                       : 10.0.10586.589 (09/06/16 9:32 PM) 869 KB
DxCaptureReplay.dll             : 10.0.10586.589 (09/06/16 9:25 PM) 8,374 KB
DxToolsMonitor.dll              : 10.0.10586.494 (06/30/16 8:46 PM) 177 KB
DxToolsOfflineAnalysis.dll      : 10.0.10586.589 (09/06/16 9:33 PM) 1,049 KB
DxToolsReportGenerator.dll      : 10.0.10586.0 (10/29/15 8:12 PM) 95 KB
DxToolsReporting.dll            : 10.0.10586.11 (11/12/15 10:57 PM) 156 KB
perf_gputiming.dll              : 10.0.10586.0 (10/29/15 7:34 PM) 338 KB
VsGraphicsCapture.dll           : 10.0.10586.589 (09/06/16 9:34 PM) 154 KB
VsGraphicsExperiment.dll        : 10.0.10586.589 (09/06/16 9:33 PM) 711 KB
VsGraphicsProxyStub.dll         : 10.0.10586.0 (10/29/15 7:37 PM) 88 KB
VsGraphicsRemoteEngine.exe      : 10.0.10586.589 (09/06/16 9:31 PM) 5,433 KB
d3d11_3sdklayers.dll            : 10.0.10586.0 (10/29/15 7:12 PM) 1,308 KB
d3d12SDKLayers.dll              : 10.0.10586.494 (06/30/16 8:24 PM) 979 KB
d3d12warp.dll                   : 10.0.10586.589 (09/06/16 9:31 PM) 3,216 KB
d2d1debug3.dll                  : 10.0.10586.589 (09/06/16 9:32 PM) 420 KB
dxgidebug.dll                   : 10.0.10586.0 (10/29/15 7:37 PM) 337 KB

**Comment by bobbrow** [comment]
Ah, I was assuming you were already on the Anniversary Update (10.0.14393) and talking about the security update that was published to Windows Update last Tuesday.

Did you verify that the Graphics Tools optional feature was still installed after the update?  Unfortunately, major updates like the Anniversary Update remove this optional package and you have to reinstall it before you can do graphics debugging again.  I just wanted to rule this out first.

**Comment by bobbrow** [comment]
Feel free to reopen this issue if you still have problems when you reinstall the Anniversary update.
