### ISSUE TITLE
Mini Engine Tutorial

### ISSUE THREAD

**Issue by zjxeditor** [Microsoft/DirectX-Graphics-Samples#209]
Hi, I really want to study the code of the DirectX 12 mini engine. However, there are too many codes and functions to dive into. I wonder if there are some code structure guides or wiki documents for me to take off. Thanks.

**Comment by stanard** [comment]
You could start with the other samples first.  MiniEngine is a few things.  It has a collection of D3D12 concepts wrapped in helper classes.  It has a framework of utility code like text rendering, profiling, and Math routines.  And it is a collection of post processing techniques mostly implemented with compute shaders.  If I were to start out exploring MiniEngine, I would put a break point in GameCore::InitializeApplication().  Then step through the initialization code, especially Graphics::Initialize() where a device is created, a command queue, various pipeline state objects (shaders + render state), the swap chain (display buffers), etc.

I think the most important classes to understand are the CommandContext and CommandQueue, which is how commands are issued to the GPU.  The CommandContext wraps a command list, which you build up offline by making various D3D12 API calls.  When you have made all the calls you are going to make, you close the command list and tell the command queue to execute it.  Only after you've told it to execute can the GPU start processing your commands.  This abstraction makes it possible to build up command lists on multiple CPU threads at the same time.  But the GPU is essentially single threaded, and that thread is the command queue.  (There's actually another couple of threads though:  an asynchronous compute queue and a memory copy queue.)

You'll want to dive into the GpuBuffer, Texture, ColorBuffer, and DepthBuffer classes for various types of data.  The PSO and derived classes are very important too.  They encapsulate all of the shaders and render state for a draw or dispatch in one place.  With D3D12, you no longer set each thing separately.  You combine them all together beforehand so there is less CPU work to do at runtime.

I hope that helps get you started.  Let us know if you need any more help.

-James

**Comment by ThorMalleuson** [comment]
Great response! Thank you.

**Comment by zjxeditor** [comment]
Thanks standard. I have already read the book "Introduction to 3D game programming with DirectX 12" and owned a basic knowledge of DirectX 12. I will follow your guidance and dive into the codes.

**Comment by jeongsoopark** [comment]
@stanard  good points to start, Thx!
