### ISSUE TITLE
Switching samples to fullscreen with Alt+Enter crashes samples..

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectX-Graphics-Samples#21]
Hi,
samples seem not capable of switching between fullscreen and windowed mode with Alt+Enter as they crash the sample..
can you fix it?
thanks..

**Comment by bobbrow** [comment]
This is intentional.  The API samples are meant to demonstrate basic functionality.  We do intend to post a sample that specifically addresses fullscreen mode switches in the near future.

**Comment by bobbrow** [comment]
The fullscreen sample is live and in master.  I went ahead and disabled processing of ALT+Enter in the other samples and pulled that change to master as well.
