### ISSUE TITLE
Screen quad vertex shader with no vertex buffer

### ISSUE THREAD

**Issue by RikoOphorst** [Microsoft/DirectX-Graphics-Samples#211]
I noticed that you guys use a special vertex shader to output your screen quad. I was wondering how this actually works.

I always thought that the vertex shader _processes_ vertices, so if there aren't any vertices bound to the pipeline for drawing, the vertex shader will not be invoked. However, in MiniEngine you guys have an explicit shader for the vertex stage which reads:

```
// A vertex shader for full-screen effects without a vertex buffer.  The
// intent is to output an over-sized triangle that encompasses the entire
// screen.  By doing so, we avoid rasterization inefficiency that could
// result from drawing two triangles with a shared edge.
//
// Use null input layout
// Draw(3)

#include "PresentRS.hlsli"

[RootSignature(Present_RootSig)]
void main(
    in uint VertID : SV_VertexID,
    out float4 Pos : SV_Position,
    out float2 Tex : TexCoord0
)
{
    // Texture coordinates range [0, 2], but only [0, 1] appears on screen.
    Tex = float2(uint2(VertID, VertID << 1) & 2);
    Pos = float4(lerp(float2(-1, 1), float2(1, -1), Tex), 0, 1);
}
```

I understand the reasoning behind why you do this: to avoid the inefficiencies in the rasterizer, by only drawing one big triangle which covers the entire screen.

However, where does this triangle come from?

**Comment by RikoOphorst** [comment]
Ah.. I think I understand it a bit. After refactoring my Google search queries to _"Screen quad with no vertex buffer"_ I grasp the concept now. Basically, if you make a draw call which says "draw 3 vertices" with no input layout specified, the vertex shader will be invoked for basically empty vertices - only real data about the vertex you're shading in the vertex shader is the SV_VertexID, which can of course be used to create a triangle. 

I'll leave this up for now, as I might be wrong.

**Comment by zao** [comment]
@RikoOphorst You got it. Very handy if you're computing the geometry from scratch or want to sample it from buffers/textures in a bit more complex manner, and it even works in older APIs.

**Comment by moradin** [comment]
Since you mentioned older APIs is it possible to achieve the same with DX9? Based on the information I found so far vertex index was introduced in DX10 (although the X360 had a solution with DX9 but as far as I know that was custom)

**Comment by walbourn** [comment]
This technique works for Direct3D 10, Direct3D 10.1, Direct3D 11, and Direct3D 12. Not for Direct3D 9.
