### ISSUE TITLE
D3D11On12 sample errors

### ISSUE THREAD

**Issue by Hlexyn** [Microsoft/DirectX-Graphics-Samples#212]
Compiling the D3D11On12 sample with SDK 10.0.10586.0 on NVidia driver 375.70 creates multiple errors during the 2D rendering part. Each EndDraw produces 60 (5 sets of 16) of the following message:

`D3D12 ERROR: CCommandList::SetGraphicsRootDescriptorTable: Specified GPU Descriptor Handle (ptr = 0x2f68bf8 at 0 offsetInDescriptorsFromDescriptorHeapStart), for Root Signature (0x07105E18:'Unnamed ID3D12RootSignature Object')'s Descriptor Table (at Parameter Index [5])'s Descriptor Range (at Range Index [0] of type D3D12_DESCRIPTOR_RANGE_TYPE_SAMPLER) has not been initialized. All descriptors of descriptor ranges declared STATIC (not-DESCRIPTORS_VOLATILE) in a root signature must be initialized prior to being set on the command list. [ EXECUTION ERROR #646: INVALID_DESCRIPTOR_HANDLE]`

**Comment by bobbrow** [comment]
Yes, with the updates to the debug layer that came out last week, you will start seeing this if you use the 11 on 12 layer.  I need to push my commit that mutes these errors.  I'll do that today.

**Comment by bobbrow** [comment]
Committed.
