### ISSUE TITLE
MiniEngine: Possible race condition in FXAA?

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#214]
Hey Guys,

Recently, I looked through MiniEngine's FXAA implementation again for inspiration on dispatch indirect. But as I walk around the code, there is one thing I need to double check with you guys:

During FXAA pass 1, compute shader is populating work queue for later process (writing to g_FXAAWorkQueueH/V and updating its counter buffer, etc.)

Then FXAA pass 2, compute shader is resolving work queue and update indirectparam for later dispatch indirect (reading g_FXAAWorkQueueH/V and its counter buffer, etc. writing to indirectparam...)

The last pass...

I've noticed there is no UAV barrier for g_FXAAWorkQueueH/V and its counter buffer between Pass1 and Pass2. So could it happen where when resolve shader is writing to indirectparam buffer, pass1 computer shader haven't finished adding all necessary works to the queue? Thus ultimately missing some pixels needed to be processed? 

Please correct me if I get something wrong.

Thanks

**Comment by stanard** [comment]
A UAV barrier is useful when you want to flush reads & writes to a UAV but continue to keep it a UAV in the next pass.  The barrier you are looking for is actually a resource transition barrier because g_FXAAWorkQueueH/V go from UNORDERED_ACCESS to NON_PIXEL_SHADER_RESOURCE.  The first pass produced the work queues, and the final pass consumes the work queues.

**Comment by pengliu916** [comment]
Thanks for the clarification, but my understanding in FXAA pass 2(resolve pass) is that we need to make sure all the write to WorkQueueH/V in pass 1 is finished before we launch pass 2 right? So there should be some barrier in between pass1 and resolve pass for WorkQueueH/V right ? But I didn't see any TransitionResource call for WorkQueueH/V between these 2 Dispatch call:

the following codes are from FXAA.cpp line114 to line 190, see the comments I added before Context.Dispatch(1, 1, 1):

	`
	// From FXAA.cpp line 114
	{
		ScopedTimer _prof(L"Pass 1", Context);
		// Begin by analysing the luminance buffer and setting aside high-contrast pixels in
		// work queues to be processed later.  There are horizontal edge and vertical edge work
		// queues so that the shader logic is simpler for each type of edge.

		Context.ResetCounter(g_FXAAWorkQueueH);
		Context.ResetCounter(g_FXAAWorkQueueV);

		Context.TransitionResource(Target, D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
		Context.TransitionResource(g_FXAAWorkQueueH, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
		Context.TransitionResource(g_FXAAWorkQueueV, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
		Context.TransitionResource(g_FXAAColorQueueH, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
		Context.TransitionResource(g_FXAAColorQueueV, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);

		D3D12_CPU_DESCRIPTOR_HANDLE Pass1UAVs[] =
		{
			g_FXAAWorkQueueH.GetUAV(),
			g_FXAAColorQueueH.GetUAV(),
			g_FXAAWorkQueueV.GetUAV(),
			g_FXAAColorQueueV.GetUAV(),
			g_LumaBuffer.GetUAV()
		};

		D3D12_CPU_DESCRIPTOR_HANDLE Pass1SRVs[] =
		{
			Target.GetSRV(),
			g_LumaBuffer.GetSRV()
		};

		if (bUsePreComputedLuma)
		{
			Context.SetPipelineState(Pass1HdrCS);
			Context.TransitionResource(g_LumaBuffer, D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
			Context.SetDynamicDescriptors(1, 0, _countof(Pass1UAVs) - 1, Pass1UAVs);
			Context.SetDynamicDescriptors(2, 0, _countof(Pass1SRVs), Pass1SRVs);
		}
		else
		{
			Context.SetPipelineState(Pass1LdrCS);
			Context.TransitionResource(g_LumaBuffer, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
			Context.SetDynamicDescriptors(1, 0, _countof(Pass1UAVs), Pass1UAVs);
			Context.SetDynamicDescriptors(2, 0, _countof(Pass1SRVs) - 1, Pass1SRVs);
		}

		Context.Dispatch2D(Target.GetWidth(), Target.GetHeight());
	}

	{
		ScopedTimer _prof(L"Pass 2", Context);

		// The next phase involves converting the work queues to DispatchIndirect parameters.
		// The queues are also padded out to 64 elements to simplify the final consume logic.
		Context.SetPipelineState(ResolveWorkCS);
		Context.TransitionResource(IndirectParameters, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);

		Context.SetConstants(0, 1.0f / Target.GetWidth(), 1.0f / Target.GetHeight());

		Context.SetDynamicDescriptor(1, 0, IndirectParameters.GetUAV());
		Context.SetDynamicDescriptor(1, 1, g_FXAAWorkQueueH.GetUAV());
		Context.SetDynamicDescriptor(1, 2, g_FXAAWorkQueueV.GetUAV());
		Context.SetDynamicDescriptor(2, 0, g_FXAAWorkQueueH.GetCounterSRV(Context));
		Context.SetDynamicDescriptor(2, 1, g_FXAAWorkQueueV.GetCounterSRV(Context));

        // Should we add the following line
        // Context.TransitionResource(g_FXAAWorkQueueH, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
        // Context.TransitionResource(g_FXAAWorkQueueV, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);

		Context.Dispatch(1, 1, 1);

		Context.TransitionResource(IndirectParameters, D3D12_RESOURCE_STATE_INDIRECT_ARGUMENT);
		Context.TransitionResource(g_FXAAWorkQueueH, D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
		Context.TransitionResource(g_FXAAColorQueueH, D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
		Context.TransitionResource(g_FXAAWorkQueueV, D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
		Context.TransitionResource(g_FXAAColorQueueV, D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
		Context.TransitionResource(Target, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);

		Context.SetDynamicDescriptor(1, 0, Target.GetUAV());
		Context.SetDynamicDescriptor(2, 0, g_LumaBuffer.GetSRV());
		Context.SetDynamicDescriptor(2, 1, g_FXAAWorkQueueH.GetSRV());`

**Comment by stanard** [comment]
A UAV barrier is not necessary because none of the memory previously written will be touched.  The resolve shader does write more to the work queues, but only at the end of them to pad them out to multiples of 64.  Since all of the writes are going to places that have not yet been written, there should not be any synchronization problems.  Note that the counter buffers themselves did receive a barrier because the call to GetCounterSRV() actually issues a resource transition on the counter buffer to "GENERIC_READ".  This alone will flush all L2 writes, but we don't need a UAV barrier for correctness.

**Comment by pengliu916** [comment]
humm.... I should have dig deeper to find that GetCounterSRV has TransitionResource inside. That explained everything. 

Thanks, I will close this issue for good.
