### ISSUE TITLE
MiniEngine: Simple shader

### ISSUE THREAD

**Issue by amomer** [Microsoft/DirectX-Graphics-Samples#219]
I am having an issue using miniengine with this kind of simple shader(s)

//RS
#if USE_VERTEX_BUFFER

#define Simple_ShaderRS_RootSig \
	"RootFlags(ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT)" 
#elif USE_ROOT_BUFFER_SRV

#define Simple_ShaderRS_RootSig \
	"RootFlags(0)" 
#else

#define Simple_ShaderRS_RootSig \
	"RootFlags(0)"
#endif

//VS
struct PSInput
{
    float4 position : SV_POSITION;
    float4 color : COLOR;
};

//[RootSignature(Simple_ShaderRS_RootSig)]
PSInput main(PSInput input)
{
    PSInput result;

    result.position = input.position;
    result.color = input.color;

    return result;
}

I will help full if you give a hint how to use simple shader like in miniengine without loading a model via mode object.

Thanks

**Comment by bobbrow** [comment]
Can you elaborate a bit more on what your issue is?  What errors are you seeing?

**Comment by amomer** [comment]
the error is generic like this:
Exception thrown at 0x00007FFA12017788 in SimpleViewer.exe: Microsoft C++ exception: _com_error at memory location 0x000000E40890D430.

If there is a handler for this exception, the program may be safely continued.

this is my code try to fill root and PSO:
m_RootSig.Reset(0, 0);
	m_RootSig.Finalize(L"SimpleViewer", D3D12_ROOT_SIGNATURE_FLAG_NONE);

	/*ComPtr<ID3DBlob>  g_pSimple_ShaderVS;
	D3DCompileFromFile(L"Shader//Simple_ShaderVS.hlsl", nullptr, nullptr, "VSMain", "vs_5_0",0, 0, &g_pSimple_ShaderVS, nullptr);
*/

	DXGI_FORMAT ColorFormat = g_SceneColorBuffer.GetFormat();
	DXGI_FORMAT DepthFormat = g_SceneDepthBuffer.GetFormat();

	D3D12_INPUT_ELEMENT_DESC vertElem[] =
	{
		{ "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0,0, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
		{ "COLOR", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 12, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }
	};

	m_ModelPSO.SetRootSignature(m_RootSig);
	m_ModelPSO.SetRasterizerState(RasterizerDefault);
	m_ModelPSO.SetInputLayout(_countof(vertElem), vertElem);
	m_ModelPSO.SetPrimitiveTopologyType(D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE);
	m_ModelPSO.SetDepthStencilState(DepthStateDisabled);
	m_ModelPSO.SetVertexShader(g_pSimple_ShaderVS, sizeof(g_pSimple_ShaderVS));
	m_ModelPSO.SetPixelShader(g_pSimple_ShaderPS, sizeof(g_pSimple_ShaderPS));
	
	m_ModelPSO.SetBlendState(BlendNoColorWrite);
	m_ModelPSO.SetDepthStencilState(DepthStateDisabled);
	m_ModelPSO.SetRenderTargetFormats(1, &ColorFormat, DepthFormat);

   m_ModelPSO.Finalize();
after I call finalize is failing at assert call withing pipelinestate object:
if (firstCompile)
	{
		ASSERT_SUCCEEDED( g_Device->CreateGraphicsPipelineState(&m_PSODesc, MY_IID_PPV_ARGS(&m_PSO)) );
		s_GraphicsPSOHashMap[HashCode].Attach(m_PSO);
	}
Sorry my ignorance I am by an expert but I am learning ...
Thanks

**Comment by amomer** [comment]
I closed by mistake

**Comment by bobbrow** [comment]
ASSERT_SUCCEEDED will print some info into the debug Output window and break into the debugger.  I would expect the SDK Layers to also print some information there as well.  Can you take a look and let me know what you see there?  (Make sure you are running the "Debug" configuration, not "Release" or "Profile")

**Comment by amomer** [comment]
this is what debug output is showing..   aaha ..!
D3D12 ERROR: ID3D12Device::CreateInputLayout: The provided input signature expects to read an element with SemanticName/Index: 'SV_POSITION'/0, but the declaration doesn't provide a matching name. [ STATE_CREATION ERROR #65: CREATEINPUTLAYOUT_MISSINGELEMENT]
D3D12 ERROR: ID3D12Device::CreateGraphicsPipelineState: Graphics pipeline state object uses input-assembler, but the root signature does not have the D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT flag set [ STATE_CREATION ERROR #683: CREATEGRAPHICSPIPELINESTATE_MISSING_ROOT_SIGNATURE_FLAGS]
Exception thrown at 0x00007FFA12017788 in SimpleViewer.exe: Microsoft C++ exception: _com_error at memory location 0x000000AC4A8FD280.

**Comment by amomer** [comment]
[Shaders.zip](https://github.com/Microsoft/DirectX-Graphics-Samples/files/620197/Shaders.zip)
shaders files for the above error

**Comment by bobbrow** [comment]
I can help you debug this, but was hoping you would take a quick look at the errors and try to resolve it yourself before I told you the answer.  I'll give you a hint for the first one.  It's an issue with your vertex shader.

**Comment by amomer** [comment]
It look like I fix both of them or at least the first, now I have this error (it is going deep):

D3D12 ERROR: ID3D12Device::CreateGraphicsPipelineState: Rasterization Unit is enabled (PixelShader is not NULL or Depth/Stencil test is enabled and RasterizedStream is not D3D12_SO_NO_RASTERIZED_STREAM) but position is not provided by the last shader before the Rasterization Unit. [ STATE_CREATION ERROR #682: CREATEGRAPHICSPIPELINESTATE_POSITION_NOT_PRESENT]
Exception thrown at 0x00007FFA12017788 in SimpleViewer.exe: Microsoft C++ exception: _com_error at memory location 0x0000002C45CFD3E0.

**Comment by amomer** [comment]
I changed to POSITION and root.Finalize looks this:
m_RootSig.Finalize(L"SimpleViewer", D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT);

**Comment by bobbrow** [comment]
Very good.  So the issue I would expect that you're hitting now is because your vertex shader is outputting POSITION instead of SV_TARGET.  I would recommend using different structs for VS input and output.

**Comment by bobbrow** [comment]
correction.  I meant to say SV_POSITION, not SV_TARGET.  Sorry about that.  I'll edit my original reply as well.

**Comment by amomer** [comment]
Thanks Bob
With above fix, now my modelPSO is initializing after I also modified my shaders.  See the attached 
Now I have to continue and display my buffer.  I learned a lot since you gave the first hint.
Now this matter is closed
Thanks again .. 
[Shaders.zip](https://github.com/Microsoft/DirectX-Graphics-Samples/files/620475/Shaders.zip)

**Comment by bzm3r** [comment]
I wish @amomer had provided a hint as to how they solved the first error. I am currently struggling with it myself, and came across this through Google.
