### ISSUE TITLE
Request: add multi-adapter sample

### ISSUE THREAD

**Issue by alessiot89** [Microsoft/DirectX-Graphics-Samples#22]
I think it's time to add a public base multi-adapter sample, maybe the one was posted on the DX12 EAP forum? ( :

**Comment by bkaradzic** [comment]
Intel released multi-adapter sample, see: https://github.com/GameTechDev/DX12-Multi-Adapter

**Comment by alessiot89** [comment]
nice, thank you ( :

**Comment by bobbrow** [comment]
Our heterogeneous multi-adapter sample has been committed to the feature_new_samples branch and will be making its way to master later this week.

**Comment by alessiot89** [comment]
sweet, I will have a look on it!
