### ISSUE TITLE
feature request: CD3DX12_GRAPHICS_PIPELINE_STATE_DESC

### ISSUE THREAD

**Issue by nlguillemot** [Microsoft/DirectX-Graphics-Samples#220]
I'd like a CD3DX12_GRAPHICS_PIPELINE_STATE_DESC which initializes its members to sensible defaults. Maybe something like:

    CD3DX12_GRAPHICS_PIPELINE_STATE_DESC( CD3DX12_DEFAULT )
        : D3D12_GRAPHICS_PIPELINE_STATE_DESC()
    {
            BlendState = CD3DX12_BLEND_DESC(D3D12_DEFAULT);
            SampleMask = UINT_MAX;
            RasterizerState = CD3DX12_RASTERIZER_DESC(D3D12_DEFAULT);
            DepthStencilState = CD3DX12_DEPTH_STENCIL_DESC(D3D12_DEFAULT);
            SampleDesc.Count = 1;
    }

These are easy to forget or tedious to set otherwise.

**Comment by nlguillemot** [comment]
Here's the whole thing typed out if you want to save yourself 2 minutes lol :)

```
//------------------------------------------------------------------------------------------------
struct CD3DX12_GRAPHICS_PIPELINE_DESC : public D3D12_GRAPHICS_PIPELINE_STATE_DESC
{
    CD3DX12_GRAPHICS_PIPELINE_DESC()
    {}
    explicit CD3DX12_GRAPHICS_PIPELINE_DESC( const D3D12_GRAPHICS_PIPELINE_STATE_DESC& o ) :
        D3D12_GRAPHICS_PIPELINE_STATE_DESC( o )
    {}
    explicit CD3DX12_GRAPHICS_PIPELINE_DESC( CD3DX12_DEFAULT ) :
        D3D12_GRAPHICS_PIPELINE_STATE_DESC()
    {
        BlendState = CD3DX12_BLEND_DESC(D3D12_DEFAULT);
        SampleMask = UINT_MAX;
        RasterizerState = CD3DX12_RASTERIZER_DESC(D3D12_DEFAULT);
        DepthStencilState = CD3DX12_DEPTH_STENCIL_DESC(D3D12_DEFAULT);
        SampleDesc.Count = 1;
    }
    ~CD3DX12_GRAPHICS_PIPELINE_DESC() {}
    operator const D3D12_GRAPHICS_PIPELINE_STATE_DESC&() const { return *this; }
};
```

**Comment by walbourn** [comment]
One of the challenges here is that what's sensible is quite different from app to app. For example, what's the default render target format?

FWIW, we solve this in [DirectX Tool Kit for DirectX 12](https://github.com/Microsoft/DirectXTK12) with ``CommonStates`` and ``RenderTargetState`` which contains the 'sensible defaults'.

**Comment by nlguillemot** [comment]
>One of the challenges here is that what's sensible is quite different from app to app. For example, what's the default render target format?

Since the format is not known, I would suggest `DXGI_FORMAT_UNKNOWN`, with `NumRenderTargets = 0`. Indeed, the app would have to supply these details itself.

**Comment by bobbrow** [comment]
I'm asking around on the D3D team to see if anyone has opinions about this.  I suspect that for reasons @walbourn mentions it was decided to omit this particular struct.  The implementation you shared only sets a few fields but the rest of the helper structs in d3dx12 always set all the fields.  We would have to decide what to initialize them to.

Of course, you are welcome to do whatever you like with this header file to meet your own project's needs. Those changes just might not make it back into the default library.

**Comment by nlguillemot** [comment]
>Of course, you are welcome to do whatever you like with this header file to meet your own project's needs. Those changes just might not make it back into the default library.

Yup, that's what I'm currently doing. I've had a lot of bugs in my own code by forgetting to set things like SampleMask, so my goal with this helper is to prevent these common bugs.

**Comment by bobbrow** [comment]
Thank you for your feedback.  The general consensus on the team is that there would not be sufficient universal value in adding helpers for this struct so we do not intend to add one to the official header.

**Comment by nlguillemot** [comment]
Sorry to poke this again. I thought about this some more, and I think that it would be generally useful as a guideline if this helper would set the same default state as D3D11.

If the mapping to D3D11 defaults is unambiguous enough, that might be something everybody can agree on as default values for the D3D12 PSO desc.

For example, in D3D11, the documentation for `OMSetBlendState` states that the default value for `SampleMask` is `0xffffffff`. Therefore, the `SampleMask` member of the D3D12 PSO desc should be identical.

Similarly, as far as I can tell, the default behavior of `OMSetRenderTargets` is to unbind all the RTs, meaning it could also make sense to leave them in a NULL state in D3D12's PSO desc (NumRTS = 0, formats = UNKNOWN).

Without this helper, d3dx12 feels somewhat incomplete. The helpers like `CD3DX12_BLEND_DESC` only help you partially set the PSO description, leaving you to manually type in all the other D3D11 defaults.
