### ISSUE TITLE
MiniEngine needs to address new SDK layers errors/warnings

### ISSUE THREAD

**Issue by ssylvan** [Microsoft/DirectX-Graphics-Samples#221]
Check the output window, e.g.:

D3D12 WARNING: ID3D12CommandList::ResourceBarrier: Called on the same subresource(s) of Resource(0x00000225EA677EC0:'Main Color Buffer') in separate Barrier Descs which is inefficient and likely unintentional. Desc[0] on (subresource : 4294967295) and Desc[3] on (subresource : 4294967295). [ RESOURCE_MANIPULATION WARNING #1015: RESOURCE_BARRIER_DUPLICATE_SUBRESOURCE_TRANSITIONS]
D3D12 ERROR: ID3D12CommandList::DrawInstanced: Root Parameter Index [3] is not set. On a Resource Binding Tier 2 hardware, all descriptor tables of type CBV and UAV declared in the currently set Root Signature (0x00000225EA309E50:'Present') must be populated, even if the shaders do not need the descriptor. [ EXECUTION ERROR #998: COMMAND_LIST_DESCRIPTOR_TABLE_NOT_SET]
D3D12 ERROR: ID3D12CommandList::DrawInstanced: Root Parameter Index [3] is not set. On a Resource Binding Tier 2 hardware, all descriptor tables of type CBV and UAV declared in the currently set Root Signature (0x00000225EA309E50:'Present') must be populated, even if the shaders do not need the descriptor. [ EXECUTION ERROR #998: COMMAND_LIST_DESCRIPTOR_TABLE_NOT_SET]
D3D12 WARNING: ID3D12CommandList::ResourceBarrier: Called on the same subresource(s) of Resource(0x00000225EA677EC0:'Main Color Buffer') in separate Barrier Descs which is inefficient and likely unintentional. Desc[0] on (subresource : 4294967295) and Desc[3] on (subresource : 4294967295). [ RESOURCE_MANIPULATION WARNING #1015: RESOURCE_BARRIER_DUPLICATE_SUBRESOURCE_TRANSITIONS]

**Comment by bobbrow** [comment]
Thanks for reporting this.  We've been making improvements to the SDK Layers over time and MiniEngine hasn't been updated for all of them yet.  I'll check with James to see when his next update will be ready.

**Comment by stanard** [comment]
With each SDK revision, we get new validation warnings & errors.  I believe these messages are coming from an SDK that is newer than the source on GitHub.  Am I right?  If so, I haven't had a chance to address these complaints.  My response can come in three forms:  1) change the offending code, 2) convince a D3D programmer that what I'm doing is normal and to please fix the messages, or 3) suppress the messages if it's not relevant.  I work in that order.  In the mean time, you can suppress these messages.  (Look in GraphicsCore.cpp for other suppressed validation.)  Or you can turn off validation entirely.  Profile and Release builds disable validation too.
