### ISSUE TITLE
MiniEngine breaks into the debugger when F12 key is pressed

### ISSUE THREAD

**Issue by ssylvan** [Microsoft/DirectX-Graphics-Samples#222]
Run ModelViewer with Alt+F5, hit F12, bam crash. Can't get symbols from callstack for some reason (exception in ntdll though). 

>	ntdll.dll!00007ffa671b8860()	Unknown
 	ntdll.dll!00007ffa671e22ba()	Unknown
 	kernel32.dll!00007ffa66dc38e4()	Unknown

Module version: 10.0.14971.1000 (rs_prerelease.161111.1700).

**Comment by bobbrow** [comment]
To capture a frame in VSGD, press the Print Screen key.  I also see that F12 is causing MiniEngine to crash when graphics debugging is not enabled.  I will look into that.  I don't think there is an issue with VSGD in this case.

**Comment by bobbrow** [comment]
Actually it is not a crash.  I resolved symbols and can see that this is just a DbgBreakPoint call.  You can continue past this break.  I wasn't aware of this feature, but it seems that Visual Studio has set up a keyboard hook to break into the debugger.  I will ask around to confirm that this is expected.

**Comment by bobbrow** [comment]
It turns out that this is a feature of Windows, not Visual Studio.  F12 is reserved for the debugger in UI applications.

See the Remarks section here:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms646309(v=vs.85).aspx
