### ISSUE TITLE
StreamOut Buffer

### ISSUE THREAD

**Issue by CogSimGuy** [microsoft/DirectX-Graphics-Samples#223]
MiniEngine has been great for learning/migrating DirectX 11 code to DirectX 12! I'm looking to implement a stream out geometry shader and I'm wondering if the StructuredBuffer implementation with Counter will work here?

**Comment by stanard** [comment]
Yes, that should work.  You can take a StructuredBuffer and make a VertexBuffer view of it.  It's just a GPU-visible chunk of memory.  You should also be able to use a ByteAddressBuffer for your purposes.  The difference largely comes down to intent, but fundamentally they are the same thing.  In MiniEngine, a StructuredBuffer automatically allocates a CounterBuffer even if you don't need one.  ByteAddressBuffers do not.

**Comment by stanard** [comment]
I forgot to ask if you have considered using a compute shader rather than VS+GS+StreamOut.  StreamOut isn't used as often with DX11/12 because you can do all of the same stuff with compute shaders but with more power and control.

**Comment by CogSimGuy** [comment]
Thanks for the reply. The compute shader route was my backup plan...just not sure of the performance hit for going with compute/graphics pipeline changes....

**Comment by stanard** [comment]
I don't think there will be a performance hit.  With DX11, using compute shaders could be slower because it would flush a dispatch before starting a new one.  With DX12, those flushes only happen when you issue a resource transition barrier (like UAV to SRV).

**Comment by CogSimGuy** [comment]
That's the thing, unless I'm missing a shortcut I need to transition the resource to an SRV to use it in my rendering pass...or can it be left as an UAV and read from without the transition?

**Comment by stanard** [comment]
Even with stream out you would need a barrier to guarantee all of your vertices are in memory and ready to be consumed.  But you could have several dispatches generating vertex buffers in parallel and then flush them all at once before consuming them.

**Comment by CogSimGuy** [comment]
True, thanks again for the feedback and advice.
