### ISSUE TITLE
Debug Layer: Bogus warning for unmapping CPU accessible textures

### ISSUE THREAD

**Issue by nlguillemot** [Microsoft/DirectX-Graphics-Samples#224]
I don't know if there's an actual issue tracker for the D3D12 debug layer, so I'm posting this here for now.

Unmapping a CPU accessible texture with a pWrittenRange of NULL warns:
```D3D12 WARNING: ID3D12Resource::ID3D12Resource::Unmap: pWrittenRange is NULL and the heap page property is WRITE_BACK. This can be an indicator of inefficiencies that will result on mobile systems, as the range should be as tight as possible. But, it is also possible the range must encompass the whole subresource.A NULL pWrittenRange parameter indicates all resource memory was written to.  [ EXECUTION WARNING #931: UNMAP_INVALID_NULLRANGE]```

Setting the pWrittenRange to (0, width * height * bpp) gives:
```D3D12 ERROR: ID3D12Resource::ID3D12Resource::Unmap: pWrittenRange must be NULL or specify an empty range when Unmap is invoked for a resource with an opaque layout. The resource layout is D3D12_TEXTURE_LAYOUT_UNKNOWN, which is opaque. pWrittenRange is not NULL. [ EXECUTION ERROR #829: UNMAP_INVALIDRANGE]```

Setting the pWrittenRange to (0,0) doesn't give any errors and appears to work anyways, but I'm not sure if that's undefined behaviour or not. As implied by the first message, this only happens on iGPUs (with WRITE_BACK CPU heaps)

I think this is a bug in the debug layer. The first warning shouldn't happen for CPU accessible textures, since they must always be unmapped with a NULL pWrittenRange.

**Comment by bobbrow** [comment]
The best place to report issues with D3D12 and the debug layer is http://forums.directxtech.com.

**Comment by nlguillemot** [comment]
Done. Here's the thread: http://forums.directxtech.com/index.php?topic=5784.0

Thanks!
