### ISSUE TITLE
VSGA: Simple frame capture will not open (Unspecified error, HRESULT 0x80004005)

### ISSUE THREAD

**Issue by sherief** [microsoft/DirectX-Graphics-Samples#225]
I have a frame capture from a simple app (whose binary I can share privately) that fails to open in VSGA with VS2015 update 3. All it draws is a single textured triangle, and an ImGui UI. Interested in fixing this? Let me know what info you need and I'll share as much as I can.

As an aside, this isn't the first bug I've filed against VSGA, but it will unfortunately be the last. We have not been able to get it up and running with even trivial renders of a clear + single triangle, and I've filed bugs in the past. The team on GitHub has been extremely helpful and I've seen the bugs get fixed relatively quickly, and I sincerely appreciate that, but moving forward I do not find the tool to be reliable - which is weird given that I assume at least some MS-related studios like The Coalition are using it?

So long, and thanks for all the fish. We shall be considering other APIs and toolchains for our near to mid-term projects.

**Comment by stanard** [comment]
Hi sherief,

We're sorry about your experience with VSGA.  I think you'll be more impressed with our new PIX for Windows tool which brings our sophisticated Xbox performance analyzer to a variety of GPUs running on Windows.  I passed on your story to others who work on the new tool, and I think they'll chime in shortly to announce it to you and get you an early preview if you are interested.

Cheers,
James

**Comment by brianras** [comment]
Sorry to hear about that. 

I'm the PM for PIX on Windows. Like James said, we're currently sharing the tool with a limited number of external partners prior to release. Feel free to get in touch with me (brianras@microsoft) so we can talk about options. 

Thanks,
Brian

**Comment by bobbrow** [comment]
PIX for Windows has now launched a beta.  https://blogs.msdn.microsoft.com/pix/2017/01/17/introducing-pix-on-windows-beta/

Give it a try and if you run into any issues, please use the feedback button provided in the tool.
