### ISSUE TITLE
Reserved resources sample visual corruption

### ISSUE THREAD

**Issue by RossNordby** [Microsoft/DirectX-Graphics-Samples#230]
It appears to be possible to cause visual corruption by rapidly changing the mip with arrow keys in the reserved resources sample. It looks a bit like the shader is sampling the texture while the tile mappings are being updated.

It's a little tricky to reproduce, but anything that triggers rapid UpdateTileMapping calls seems to work eventually. (Things like hitting both arrow keys at nearly the same time, or holding one key and then the other in succession.) I've only seen it happen when the previous mip of a swap was an unpacked mip so far.

I've reproduced it on both the warp adapter and on my 770 running the latest 376.33 drivers on Windows 10 14393.576.

I actually tried this because I was hitting something similar in my own application. I'm not absolutely sure it's the same issue yet, but it looks very similar. 

(By the way, is there a better spot than this repo to report potential d3d12 runtime/warp bugs? I've also run into another issue, but it's not strictly related to the samples. I don't have any problem opening it here if that's convenient, though. EDIT: Found the directxtech forums and [posted over there.](http://forums.directxtech.com/index.php?topic=5790.0))

Happy new year!

**Comment by bobbrow** [comment]
Thanks for posting this in the DirectXTech forum.  Do you mind if we close this issue here?

**Comment by RossNordby** [comment]
Sure- I've got both issues posted over there now.
