### ISSUE TITLE
XMVector3Less XMVector4Less etc

### ISSUE THREAD

**Issue by cpyburn** [Microsoft/DirectX-Graphics-Samples#237]
I went to post this in the directx 12 forum and looks like I no longer have access or it's down?  Anyways, what is up with these functions returning ? 0xFFFFFFFF : 0

	XMVECTOR xmOut = XMVectorZero();
	for (int i = 0; i < 8; i++)
	{
		xmOut += XMVectorLess(XMLoadFloat3(&m_points[i]), XMVectorZero());
	}

Id expect to have xmOut something like = { 8, 0, 4, 1 } because 8 x values were less than zero, 0 y values less than zero, etc, instead now I have to deal with nulls because of the way Microsoft implemented it.  Am I missing something?

**Comment by walbourn** [comment]
You should file DirectXMath related issues over at that [GitHub](https://github.com/Microsoft/DirectXMath).

``XMVectorLess`` and kin are typically used for doing masking or selecting which his why it returns 0xFFFFFFFF or 0 instead of 1 or 0.

**Comment by cpyburn** [comment]
thanks walbourn, in the future, where do we ask directx 12 general questions?

**Comment by walbourn** [comment]
The DirectX 12 forums are now [here](http://forums.directxtech.com/)
