### ISSUE TITLE
ModelViewer.exe crashes with assertion "Failed to load Models/sponza.h3d"

### ISSUE THREAD

**Issue by sniverty** [Microsoft/DirectX-Graphics-Samples#243]
When I run the .exe generated with Debug build, I see the below error:

Assertion failed in "ModelViewer.cpp" @ 204
--> 'm_Model.Load("Models/sponza.h3d")' is false
--> Failed to load model

However, when I open Visual Studio, place a breakpoint just before this assert and then step through the code, I am able to go past this assert without any error and launch the application.

I'd like to be able to start the application by running the .exe instead of doing it through Visual Studio debugger so that I can capture a few frames on PIX.

Thanks in advance!

**Comment by stanard** [comment]
You just need to run the .exe from the project folder.  E.g.

c:\DirectX-Graphics-Samples\MiniEngine\ModelViewer> ..\Build_VS14\x64\Profile\Output\ModelViewer.exe

Alternatively, you can copy the .exe into the ModelViewer folder and double click it.

**Comment by sniverty** [comment]
Thanks for the reply. 
After copying over the .exe to the project folder, I was able to launch the application without any issues. However, I did run into the same problem when I tried launching the .exe through PIX for GPU capture. I circumvented this by assigning the full windows path as follows:

**TextureManager::Initialize(L"C:/Users/snive/Desktop/DirectX-Graphics-Samples-master/DirectX-Graphics-Samples-master/MiniEngine/ModelViewer/Textures/");**

**ASSERT(m_Model.Load("C:/Users/snive/Desktop/DirectX-Graphics-Samples-master/DirectX-Graphics-Samples-master/MiniEngine/ModelViewer/Models/sponza.h3d"), "Failed to load model");**
