### ISSUE TITLE
Changing shader model for 6.0

### ISSUE THREAD

**Issue by PeterSikachev** [Microsoft/DirectX-Graphics-Samples#244]
What would be the easiest way to compile shaders to shader model 6.0? In project settings, the latest shader model available is 5.1:
![image](https://cloud.githubusercontent.com/assets/7588669/22624264/56a70e72-eb44-11e6-887f-2e6835ae0585.png)

**Comment by weltkante** [comment]
[Last time the question was asked](https://github.com/Microsoft/DirectX-Graphics-Samples/issues/184) the SM 6 compiler was not yet finished:

> As far I know, Shader Model 6.0 requires a new compiler which is not yet public [...] You can ask Microsoft to enter the private beta

**Comment by PeterSikachev** [comment]
Thanks!

**Comment by alessiot89** [comment]
> Last time the question was asked the SM 6 compiler was not yet finished:
The new compiler is now on public preview: https://github.com/Microsoft/DirectXShaderCompiler
