### ISSUE TITLE
Get black screen when g_bEnableHDROutput = true

### ISSUE THREAD

**Issue by gongminmin** [Microsoft/DirectX-Graphics-Samples#245]
Change g_bEnableHDROutput to true, the rendering results doesn't appear.

**Comment by stanard** [comment]
I just responded to your pull request.  This variable is intended to be initialized to true when an HDR display is detected.  The code which detects an HDR display on Windows has not yet been implemented, but expect it to arrive in the near future.

**Comment by stanard** [comment]
I pushed new functionality which enables HDR output on HDR displays if you are using the Creators Update with a fairly recent GPU and running on an HDR TV.  As said before, the variable g_bEnableHDROutput is set to true automatically upon detecting all conditions are satisfied.  To force SDR output, disable the preprocessor macro CONDITIONALLY_ENABLE_HDR_OUTPUT atop GraphicsCore.cpp.

Thanks
