### ISSUE TITLE
Feature IGameApp::Resize(...)

### ISSUE THREAD

**Issue by ChrisKing340** [Microsoft/DirectX-Graphics-Samples#249]
Handling window and resolution changes for resources that depend and scale to the screen WxH (such as UI elements).  Could IGameApp base class have a method:
`	virtual void IGameApp::Resize(uint32_t width, uint32_t height)
	{
		Graphics::Resize(width, height);
	}`
and 
`LRESULT CALLBACK WndProc( HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam )`
be made part of IGameApp so that it can be virtualized along with Resize?  Would process the WM_NCREATE message then similar to:
`    IGameApp *pThis;
    if (msg == WM_NCCREATE)
    {
        pThis = static_cast<Client*>(reinterpret_cast<CREATESTRUCT*>(lParam)->lpCreateParams);
        SetLastError(0);
        if (!SetWindowLongPtr(hwnd, GWL_USERDATA, reinterpret_cast<LONG_PTR>(pThis)))
        {
            if (GetLastError() != 0) return FALSE;
        }
    }
    else
    {
        pThis = reinterpret_cast<IGameApp*>(GetWindowLongPtr(hwnd, GWL_USERDATA));
    }`
mini engine is wonderfully well written.  I hack this into the core functionality currently so I minimize changing the core.  Thanks for your consideration.

**Comment by stanard** [comment]
Thanks for the compliment and the good suggestion!  I think you're right that it's pretty standard for an app to define its own resolution-dependent resources, and so the app should be notified when the resolution has changed.  I am not expecting to make another push to GitHub until later next month or even April (to coincide with the Creators Update of Win10), but when I do, this should be improved.

**Comment by ChrisKing340** [comment]
Looking forward to it.  Will close this, thank you.
