### ISSUE TITLE
D3D12CreateDevice failed after update to Win10 Anniversary Edition

### ISSUE THREAD

**Issue by rajg77** [microsoft/DirectX-Graphics-Samples#250]
Hi, 

I am having issue to as discussed in #234. All the samples were working before the Win10 upgrade, but now on v1607 with debug layer enabled (the Graphics Tools is installed) the D3D12CreateDevice failed with E_INVALIDARG. However, if debug layer is not enabled or Release mode is used the device is created and the samples run fine.
---------------------------------------------------
Some info about my PC:
WIndows 10 Enterprise
Version: 1607

Windows Build: 14393.693.amd64fre.rs1_release.161220-1747

GPU Info
========
Adapter 0: NVIDIA GeForce GTX 970
           D3D Support = D3D12 (FL_12_1)
           Hardware ID = 10DE:13C2
           UMD Version = 21.21.13.7866
           ETW Markers = 9(Yes) 10+(Yes)

Adapter 1: Microsoft Basic Render Driver
           D3D Support = D3D12 (FL_12_1)
           Hardware ID = 1414:008C
           UMD Version = 10.0.14393.576
           ETW Markers = 9(No) 10+(No)

Executing DXCap version
=======================
Path: C:\Windows\system32\DXCap.exe
DxCap.exe                       : 10.0.14393.0 (07/15/16 19:13) 1,171 KB

System32 Info
=============
DxCap.exe                       : 10.0.14393.0 (07/15/16 19:13) 1,171 KB
DxCaptureReplay.dll             : 10.0.14393.0 (07/15/16 19:23) 14,051 KB
DxToolsMonitor.dll              : 10.0.14393.0 (07/15/16 19:12) 194 KB
DxToolsOfflineAnalysis.dll      : 10.0.14393.0 (07/15/16 19:13) 1,959 KB
DxToolsReportGenerator.dll      : 10.0.14393.0 (07/15/16 19:58) 93 KB
DxToolsReporting.dll            : 10.0.14393.0 (07/15/16 19:11) 179 KB
perf_gputiming.dll              : 10.0.14393.0 (07/15/16 19:22) 348 KB
VsGraphicsCapture.dll           : 10.0.14393.0 (07/15/16 19:13) 172 KB
VsGraphicsDesktopEngine.exe     : 10.0.14393.0 (07/15/16 19:16) 5,714 KB
VsGraphicsExperiment.dll        : 10.0.14393.0 (07/15/16 19:12) 291 KB
VsGraphicsProxyStub.dll         : 10.0.14393.0 (07/15/16 19:28) 89 KB
VsGraphicsRemoteEngine.exe      : 10.0.14393.0 (07/15/16 19:16) 4,853 KB
d3d11_3sdklayers.dll            : 10.0.14393.0 (07/15/16 19:19) 1,293 KB
d3d12SDKLayers.dll              : 10.0.14393.0 (07/15/16 19:14) 2,428 KB
d3d12warp.dll                   : 10.0.14393.0 (07/15/16 19:15) 6,429 KB
d2d1debug3.dll                  : 10.0.14393.0 (07/15/16 19:22) 419 KB
dxgidebug.dll                   : 10.0.14393.0 (07/15/16 19:25) 330 KB

SysWow64 Info
=============
DxCap.exe                       : 10.0.14393.0 (07/15/16 18:29) 931 KB
DxCaptureReplay.dll             : 10.0.14393.0 (07/15/16 18:39) 11,397 KB
DxToolsMonitor.dll              : 10.0.14393.0 (07/15/16 18:28) 152 KB
DxToolsOfflineAnalysis.dll      : 10.0.14393.0 (07/15/16 18:28) 1,475 KB
DxToolsReportGenerator.dll      : 10.0.14393.0 (07/15/16 18:58) 93 KB
DxToolsReporting.dll            : 10.0.14393.0 (07/15/16 18:28) 125 KB
perf_gputiming.dll              : 10.0.14393.0 (07/15/16 18:35) 268 KB
VsGraphicsCapture.dll           : 10.0.14393.0 (07/15/16 18:29) 131 KB
VsGraphicsDesktopEngine.exe     : 10.0.14393.0 (07/15/16 18:32) 4,489 KB
VsGraphicsExperiment.dll        : 10.0.14393.0 (07/15/16 18:29) 226 KB
VsGraphicsProxyStub.dll         : 10.0.14393.0 (07/15/16 18:44) 41 KB
VsGraphicsRemoteEngine.exe      : 10.0.14393.0 (07/15/16 18:32) 3,615 KB
d3d11_3sdklayers.dll            : 10.0.14393.0 (07/15/16 18:37) 1,049 KB
d3d12SDKLayers.dll              : 10.0.14393.0 (07/15/16 18:37) 1,890 KB
d3d12warp.dll                   : 10.0.14393.0 (07/15/16 18:31) 4,861 KB
d2d1debug3.dll                  : 10.0.14393.0 (07/15/16 18:38) 363 KB
dxgidebug.dll                   : 10.0.14393.0 (07/15/16 18:41) 234 KB

VS2015 VsGraphics
=================
DxDebugEngine.dll               : 14.0.25420.1 (06/20/16 13:45) 22 KB
DxDebugEngineWorker.dll         : 14.0.25420.1 (06/20/16 13:45) 22 KB
DxDebuggerApi.dll               : 14.0.25420.1 (06/20/16 13:45) 22 KB
DxTex.dll                       : 14.0.23107.0 (07/06/15 23:51) 403 KB
VsGraphics.exe                  : 14.0.25420.1 (06/20/16 13:45) 2,182 KB
VsGraphicsCore.dll              : 14.0.23107.0 (07/06/15 23:51) 929 KB
VsGraphicsDebuggerPkg.dll       : 14.0.25420.1 (06/20/16 13:45) 22 KB
VsGraphicsDesktopEngine.exe     : 14.0.25420.1 (06/20/16 13:45) 23 KB
VsGraphicsNativeUtils.dll       : 14.0.25420.1 (06/20/16 13:45) 22 KB
VsGraphicsProxyStub.dll         : 14.0.25420.1 (06/20/16 13:45) 22 KB
DiagnosticsHub.js               : (06/20/16 13:45) 12 KB
Plugin.js                       : (06/20/16 13:45) 12 KB

VS2015 VsGraphics\amd64
=======================
GpuProfilingCollectionAgent.dll : 14.0.25420.1 (06/20/16 13:45) 22 KB

VS2015 VsGraphics\x86
=====================
GpuProfilingCollectionAgent.dll : 14.0.25420.1 (06/20/16 13:45) 22 KB

VS2015 x86 Remote Debugger
==========================
VsGraphicsCaptureEngine.dll     : 14.0.25420.1 (06/20/16 13:45) 151 KB
VsGraphicsHelper.dll            : 14.0.25420.1 (06/20/16 13:45) 1,784 KB
VsGraphicsRemoteEngine.exe      : 14.0.25420.1 (06/20/16 13:45) 2,503 KB

VS2015 amd64 Remote Debugger
============================
VsGraphicsCaptureEngine.dll     : 14.0.25420.1 (06/20/16 12:51) 195 KB
VsGraphicsHelper.dll            : 14.0.25420.1 (06/20/16 12:51) 3,114 KB
VsGraphicsRemoteEngine.exe      : 14.0.25420.1 (06/20/16 12:51) 3,490 KB

Windows Phone Binaries
======================
Dxcap.exe                       : File not found
DxCaptureReplay.dll             : File not found
DxToolsMonitor.dll              : File not found
DxToolsOfflineAnalysis.dll      : File not found
DxToolsReporting.dll            : File not found
VsGraphicsCapture.dll           : File not found
VsGraphicsCaptureEngine.dll     : 14.0.25420.1 (06/20/16 12:27) 97 KB
VsGraphicsExperiment.dll        : File not found
VsGraphicsRemoteEngine.exe      : File not found

Windows Phone Emulator Binaries
===============================
Dxcap.exe                       : File not found
DxCaptureReplay.dll             : File not found
DxToolsMonitor.dll              : File not found
DxToolsOfflineAnalysis.dll      : File not found
DxToolsReporting.dll            : File not found
VsGraphicsCapture.dll           : File not found
VsGraphicsCaptureEngine.dll     : 14.0.25420.1 (06/20/16 13:45) 92 KB
VsGraphicsExperiment.dll        : File not found
VsGraphicsRemoteEngine.exe      : File not found

GPU Usage Data
==============
Feature Support       : Yes
D3D9 Driver Support   : Pass
D3D10+ Driver Support : Pass
OS Version Check      : Pass
Driver Version Check  : Pass

--------------------------------------------

Thinking it might be conflicting with previous version, I have tried this on a clean install of windows 10 Anniversary Edition with SDK. But that also results in same issue. It seems I am missing something, but not sure what as same steps had previously worked with the older Win 10/SDK.

Any support on this would be very helpful.
Thanks,
Raj

**Comment by bobbrow** [comment]
The problem _looks_ like mismatched sdk layers binaries:

Windows Build: 14393.**693**.amd64fre.rs1_release.161220-1747
d3d12SDKLayers.dll : 10.0.14393.**0** (07/15/16 19:14) 2,428 KB

You can try reinstalling the Graphics Tools optional feature, or rescanning for Windows Updates.  Either (or both) of those will usually resolve the issue.

**Comment by rajg77** [comment]
Thanks bobbrow for the reply..
I have tried uninstalling/installing the graphics tools multiple times, but unfortunately it has not worked. I am assuming getting latest windows update should also load in the latest graphics tools in the feature list which seems to be not happening in our case. Also we are updated to quite a latest windows update. Would it be possible to point out anything  we might be missing that we can't update to latest tools. Also is there a package of latest graphics tools that we could use for a manual install rather as Add a feature.

Thanks,
Rajeev

**Comment by rajg77** [comment]
Also just to mention..we do have internal IT department WSUS server...so usually we have HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windo‌​wsUpdate\AU\UseWUSer‌​ver set to 1. So have to manually set it 0 and reboot to fill the optional feature list. Is there any other registry value that might be effecting getting latest updates for optional features and should be changed?

**Comment by bobbrow** [comment]
Unfortunately, I don't know very much about that.  If your IT department is blocking the update I think you'll need to talk with them about letting the Feature on Demand updates go through.
