### ISSUE TITLE
D3D12CreateDevice return 0x887a0004, but D3D11CreateDevice will create device OK.

### ISSUE THREAD

**Issue by simsergey** [Microsoft/DirectX-Graphics-Samples#253]
Hi,
I tryed to create UWP DX11 and UWP DX12 projects in VS17 and remote debuged it on Tablet Dell Venue 8 Pro (5830) with Windows 10 Home 32bit (10.0.14393.693). 
In UWP DX12 project in GetHardwareAdapter() loop, when create device on "Intel HD Graphics" adapter D3D12CreateDevice() return 0x887a0004.
In UWP DX11 project the device is created for null adapter, and it created succesfuly. I tryed to get it descriptor for get it`s name and Luid, and it`s are identical with adapter in UWP DX12.
May be is somebody have any ideas? Thank you. :)

**Comment by bobbrow** [comment]
I suspect that your GPU does not support DirectX 12.  Intel HD 4400 is the lowest GPU from Intel that supports it (if I recall correctly).  What does dxdiag.exe tell you about your GPU?

**Comment by walbourn** [comment]
You need a WDDM 2.0 driver for your video card to support DirectX 12, and not all hardware is getting them. WDDM 1.0 or better drivers all work with DirectX 11 via [Direct3D Hardware Feature Levels](https://blogs.msdn.microsoft.com/chuckw/2012/06/20/direct3d-feature-levels/).

Also, while it's not a strict requirement, no hardware vendor we are aware of is planning a DirectX 12 driver for a video card older than Direct3D Hardware Feature Level 11.0. The oldest Intel part I'm aware of with DirectX 12 drivers is Intel "Haswell".

    Intel HD Graphics 4400/4600/5000
    Intel Iris Graphics 5100/5200

Note that this is why the ``GetHardwareAdapter`` loop checks that a device supports DirectX 12 because you can have systems where the default device doesn't support DirectX 11 but another one might.

**Comment by alessiot89** [comment]
The Intel Atom Z3740D, which should your CPU, has an Intel Gen. 7 iGPU. The oldest Intel graphics supported start from Gen 7.5 (Haswell). You cannot run DirectX 12 runtime on that hardware.

**Comment by simsergey** [comment]
Big thanks for answers! :)
Some time ago, in [on previouse issuse](https://github.com/Microsoft/DirectX-Graphics-Samples/issues/14#issuecomment-137489988), Bob Brow wrote this:
> The difference between runtime/API version and feature level is one that has confused a lot of people. DirectX 12 only requires "feature level" 11. Note that we pass in D3D_FEATURE_LEVEL_11_0 to the CreateDevice function in the samples. This is how we made DX12 available to the majority of the GPUs already out there. Otherwise it would have needlessly required everyone to buy new graphics cards. There are additional features available for GPUs that support feature level 12 and 12.1, but the current set of samples do not make use of those features.

So, if we have GPU, which has hardware level DX11, we call D3D12CreateDevice() and pass she D3D_FEATURE_LEVEL_11_0, which is tell she that we need DX11 only features, why we get error?
As I understand, the problem is in GPU driver? So, all vendors must update them? Is it`s real?
May be have a sens to use already existing GPU driver interface (which used in DX11) in situation, where DX12 compatible driver not found in the system and programmer ask D3D_FEATURE_LEVEL_11_0?

> Also, while it's not a strict requirement, no hardware vendor we are aware of is planning a DirectX 12 driver for a video card older than Direct3D Hardware Feature Level 11.0.

Thank you Chuck Walbourn, but, for example, I can`t install latest Intel chipset drivers (which contain a GPU driver) for tablet, I get error, that tell me "You need use a vendor specific drivers". This new driver will work?

>  You can try to use WARP for simple samples, the CPU should perform well enough.

Yes, alessiot89, but I will use WARP as programmer, end user cannot use it, end user will use a "Microsoft Basic Render Driver" and it work, but slow, end user will not use my program with this rendering :)

**Comment by walbourn** [comment]
Actually, what I was saying is that if you happen to be using a video card that is below Direct3D hardware feature level 11.0, there won't be a DX 12 driver for it. That is not to say that every Direct3D hardware feature level 11.0 or better card has DX 12 drivers, although AMD, NVIDIA, and INTEL have all worked hard to support a wide swath of the DirectX 11.0 or better video cards in the market. As noted, if you have a Intel part older than a "Haswell", then it isn't going to be have a DirectX 12 capable driver. You can of course continue to use DirectX 11 with these older cards.

**Comment by simsergey** [comment]
Ok, I think that I got answer. Thank you. :)
