### ISSUE TITLE
UWP samples crashed at Xbox

### ISSUE THREAD

**Issue by iHateInventNames** [Microsoft/DirectX-Graphics-Samples#254]

**Comment by walbourn** [comment]
I'm guessing you are using DirectX 12. DirectX 12 is not currently supported for UWP on Xbox One as is documented [here](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/known-issues).

**Comment by iHateInventNames** [comment]
Do I need some SDK?

**Comment by walbourn** [comment]
DirectX

**Comment by iHateInventNames** [comment]
Thank you Chuck
