### ISSUE TITLE
Frame time not accurate in Update(float)

### ISSUE THREAD

**Issue by ChrisKing340** [microsoft/DirectX-Graphics-Samples#256]
`virtual void IGameApp::Update( float deltaT ) = 0;`
deltaT is fixed when s_EnableVSync is true even though the time between frames maybe large and frame rate is lower than the target 60 or 30 fps.  This seems unattended with deltaT not useable to stay in sync with the frame rate.

Suggestion to set the real time in s_FrameTime after it is used to calculate the minimum PresentInterval in Present(...).  Have never done a pull request, is that better for something this small?  Minor tweak suggested:
```
void Graphics::Present(void)
{
	if (g_bEnableHDROutput)
		PreparePresentHDR();
	else
		PreparePresentLDR();

	g_CurrentBuffer = (g_CurrentBuffer + 1) % SWAP_CHAIN_BUFFER_COUNT;

	int64_t CurrentTick = SystemTime::GetCurrentTick();

	if (s_EnableVSync)
	{
		// With VSync enabled, the time step between frames becomes a multiple of 16.666 ms.  We need
		// to add logic to vary between 1 and 2 (or 3 fields).  This delta time also determines how
		// long the previous frame should be displayed (i.e. the present interval.)
		s_FrameTime = (s_LimitTo30Hz ? 2.0f : 1.0f) / 60.0f;
		if (s_DropRandomFrames)
		{
			if (std::rand() % 50 == 0)
				s_FrameTime += (1.0f / 60.0f);
		}
	}

	UINT PresentInterval = s_EnableVSync ? std::min(4, (int)Round(s_FrameTime * 60.0f)) : 0;

	{
		// When running free, keep the most recent total frame time as the time step for
		// the next frame simulation.  This is not super-accurate, but assuming a frame
		// time varies smoothly, it should be close enough.
		float realTime = (float)SystemTime::TimeBetweenTicks(s_FrameStartTick, CurrentTick);
		if (!s_EnableVSync || realTime > s_FrameTime)
			s_FrameTime = realTime;
	}

	s_SwapChain1->Present(PresentInterval, 0);

	// Test robustness to handle spikes in CPU time
	//if (s_DropRandomFrames)
	//{
	//	if (std::rand() % 25 == 0)
	//		BusyLoopSleep(0.010);
	//}

	s_FrameStartTick = CurrentTick;

	++s_FrameIndex;

	SetNativeResolution();
}
```

**Comment by blippyblips** [comment]
The delta time is fixed and the time each frame is left presented is extended to compensate by the (s_FrameTime * 60.0f) that is passed to the swapchain->Present. 

I guess you could argue that there is an issue in that the update method is called more often then once per s_FrameTime making the deltaTime precision an issue.

There is however an issue in this function in that it doesn't take in to account gaming monitors that often have 120 or 144hz update frequency.

Would add something like this to fix:
int32_t g_iFramerateLimit = 60;

DEVMODE lpDevMode = {};
lpDevMode.dmSize = sizeof(DEVMODE);
lpDevMode.dmDriverExtra = 0;
if (EnumDisplaySettings(NULL, ENUM_CURRENT_SETTINGS, &lpDevMode) > 0) {
	g_iFramerateLimit = lpDevMode.dmDisplayFrequency;
}

And in the present function would replace the hard-coded 60.0f with g_iFramerateLimit.

**Comment by stanard** [comment]
You bring up some good points about variable frame rate.  My original intent was to keep the frame rate locked to 30 or 60 Hz, but obviously if this engine is to be used in a variety of circumstances, we need to be more flexible.  I could say that you are welcome to make the changes you need locally, but I like the idea of making these changes more universal, and I will devote some time to considering them carefully.  I especially like the idea of supporting higher frame rates than 60 as well as variable frame rates like with GSync and FreeSync.

**Comment by blippyblips** [comment]
I like the idea of universal changes as well and I'm heading off on a weeks holiday tomorrow morning so won't be doing any changes for a bit.

I wonder if possibly adding a second function FixedUpdate that gets called every 1/30 or 1/60 regardless of frame rate but also keep the regular one with the real delta time could be a nice change.

Having a go to case of how to handle GSync/Freesync in DX12 would be a really nice addition to the MiniEngine.

**Comment by walbourn** [comment]
Note that [StepTimer](https://blogs.msdn.microsoft.com/chuckw/2014/12/03/understanding-game-time-revisited/) in the official UWP sample templates supports both variable-rate and fixed-rate updates.
