### ISSUE TITLE
File VS15.props Missing from Repo

### ISSUE THREAD

**Issue by marselas** [Microsoft/DirectX-Graphics-Samples#257]
All of the *_VS15.vcxproj projects reference missing VS15.props file.

Copying the VS14.props file and editing to change all 14 references to 15 appears to work.  However, it's not clear if there is additional information in the actual VS15.props that this is hack is missing.

**Comment by stanard** [comment]
Sorry about that.  I just noticed that myself, and I pushed up a fix along with some minor changes like fixing newline inconsistency and adding more to .gitignore.
