### ISSUE TITLE
MiniEngine: SDF Font Converter

### ISSUE THREAD

**Issue by blippyblips** [Microsoft/DirectX-Graphics-Samples#260]
Is there a reason (such as license issue) that the application used to convert fonts to SDFFont is not included?

Would be a nice addition to throw in to the project as you did with the ModelConverter if possible.

**Comment by stanard** [comment]
Our font file generator depends on the open source FreeType library.  I need to run it through our open source license experts to see if we can include a pre-compiled binary and/or source code.  At the least, we should be able to include the source code to our tool and instruct you to download freetype yourself as we did with ModelConverter and assimp.

How urgent is this for you?

**Comment by blippyblips** [comment]
Not urgent at all, just noted that there was a piece missing there and thought it could be nice to have for people in general.

**Comment by stanard** [comment]
I'm pleased to announce the availability of SDFFontCreator.  It's in the Tools folder and depends on the NuGet package 'freetype' (freeing me from licensing concerns.)  The package should auto-install unless you turned off that feature.

SDF stands for "signed distance field", which is the technique for generating smooth silhouettes from low resolution data.  To run the tool, you need to provide a TTF font, of which you can find several in C:\Windows\Fonts.  The default settings should be acceptable unless you need to add more Unicode characters than the basic European set.  A preview of the texture is provided as a Windows BMP, but the actual file that is needed is a '.fnt' file which includes a mapping of Unicode values to glyph locations.  (Everything the TextRenderer needs to know.)  I use another tool for converting a binary file to a C header found in the Tools\Scripts folder to generate my statically compiled default font.  That way I don't have to load a file at startup and can guarantee to have a usable font.

Cheers!
