### ISSUE TITLE
Typo in the D3D1211On12 sample?

### ISSUE THREAD

**Issue by KarimLUCCIN** [Microsoft/DirectX-Graphics-Samples#265]
Hi,

In this file:
https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D1211On12/src/DXSample.cpp#L62

It reads
`// Check to see if the adapter supports Direct3D 12, but don't create the
		// actual device yet.
		if (SUCCEEDED(D3D12CreateDevice(adapter.Get(), **D3D_FEATURE_LEVEL_11_0**, _uuidof(ID3D12Device), nullptr)))`

It seems that it should be **D3D_FEATURE_LEVEL_12_0** and not **D3D_FEATURE_LEVEL_11_0**

**Comment by walbourn** [comment]
You are confusing "Direct3D API level" with "Direct3D hardware feature level". This is checking to see if the driver & hardware combination supports Direct3D hardware feature level 11.0. This is the broadest possible set of hardware, as there are no DirectX 12 capable drivers available for Direct3D hardware below feature level 11.0.

If this were set to ``D3D_FEATURE_LEVEL_12_0``, then this sample would only run on a subset of Direct3D 12 capable cards that reported support for 12.0. This is basically the same as Direct3D hardware feature level 11.0 but also mandates support for Tier 2 resource binding, Tier 2 tiled resources, min/max filters, and expanded format support for UAV load.

See [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/mt186615.aspx) and [this blog post]() for more information.

**Comment by KarimLUCCIN** [comment]
Oh I see, it makes sense now. Thank you for the explanation! :)
