### ISSUE TITLE
D3D12nBodyGravity threading issues and DreamBuildPlay2017

### ISSUE THREAD

**Issue by cpyburn** [microsoft/DirectX-Graphics-Samples#268]
I have been working on threading in my app for a while now.  nBodyGravity was my goto for learning.  After the windows 10 anniversary update, my app started crashing.  I narrowed it down to threading of the code below.  Are these commands not thread safe?  Do they have to be run on the main thread?  If they do have to be run on the main thread, then why did it work on separate threads without crashing before windows 10 update, did you change something?  I have searched Microsoft documentation after documentation and it was vague at best on how to use "your own" command queues but never mentioned anything about how thread safe it was.  I posted on directxtech, gamedev, and here and had zero responses.  Is there anywhere to get solid support for directx 12, or is it like a use at your own risk product?  I was planning on entering my game in the Dream Build Play 2017, but its going to be hard to do so if I cant find support for random issues with the D3D12.dll with no explanations.

`		D3D12_COMMAND_QUEUE_DESC queueDesc = { D3D12_COMMAND_LIST_TYPE_COMPUTE, 0, D3D12_COMMAND_QUEUE_FLAG_NONE };
		ThrowIfFailed(m_device->CreateCommandQueue(&queueDesc, IID_PPV_ARGS(&m_computeCommandQueue[threadIndex])));
		ThrowIfFailed(m_device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_COMPUTE, IID_PPV_ARGS(&m_computeAllocator[threadIndex])));
		ThrowIfFailed(m_device->CreateCommandList(0, D3D12_COMMAND_LIST_TYPE_COMPUTE, m_computeAllocator[threadIndex].Get(), nullptr, IID_PPV_ARGS(&m_computeCommandList[threadIndex])));
		ThrowIfFailed(m_device->CreateFence(0, D3D12_FENCE_FLAG_SHARED, IID_PPV_ARGS(&m_threadFences[threadIndex])));`

**Comment by cpyburn** [comment]
This is the error I am getting on windows 10 update.

Faulting application name: App1.exe, version: 0.0.0.0, time stamp: 0x597662c3
 Faulting module name: d3d12.dll, version: 10.0.15063.0, time stamp: 0xf28276bc
 Exception code: 0xc0000005
 Fault offset: 0x00085afb
 Faulting process id: 0x2c2c
 Faulting application start time: 0x01d304c1f396c77e
 Faulting application path: D:\ZeroTutorials\Tutorial Code\Dynamic Vertex\App1\Debug\App1\AppX\App1.exe
 Faulting module path: C:\WINDOWS\SYSTEM32\d3d12.dll
 Report Id: dd87f202-b3bb-4f4f-995b-d7542514d902
 Faulting package full name: c86a24d9-8f28-42ba-a584-0f7c5150f20b_1.0.0.0_x86__e8mhtqen2ce40
 Faulting package-relative application ID: App

**Comment by shuweihsu** [comment]
APIs on the ID3D12Device interface are thread-safe, including CreateCommandQueue, CreateCommandAllocator, CreateCommandList and CreateFence functions you posted above.
Could you please send us a dxdiag.txt and a crash dump of the problem you hit?  Does the sample also crash on your machine too?

To generate a crash dump in Visual Studio, select "DEBUG" menu and then click "Save Dump As" while the app hits an exception that causes the crash. To get a dxdiag.txt, run dxdiag.exe and then click "save all information". 

Thanks!

**Comment by cpyburn** [comment]
app1.dmp zipped
https://www.dropbox.com/s/byk6dfnzkopf4gk/App1.zip?dl=0
DxDiag
https://www.dropbox.com/s/xwzdomykvdc3eo0/DxDiag.txt?dl=0

**Comment by cpyburn** [comment]
This is the line it is crashing on when threading
![crasheshereeverytime](https://user-images.githubusercontent.com/17934438/29413011-909c2b3e-8320-11e7-8f5a-96c23feb05a0.jpg)

**Comment by stanard** [comment]
Assuming your device pointer isn't null, there might be issues with creation flags.  Try setting queueDesc.NodeMask = 1 instead of 0.

**Comment by cpyburn** [comment]
Didn't work.  And even if it did, it wouldn't explain why it magically started throwing the error after windows 10 update.  Is there a limit the number of commandAllocators that can be used at one time?  Maybe that is the cause?

**Comment by shuweihsu** [comment]
The dump indicates an command queue access violation (due to null pointer) during present.
Try checking if the app deletes the command queue currently associated with the swapchain.

The app will get an E_OUTOFMEMORY error if it hits create limitation for command allocators. This is probably not the case here.

**Comment by cpyburn** [comment]
I never delete the command queue associated with the swapchain, I only reset it, reset the command list with it, and execute the command list with it.  But it is possible the command queue in question goes out of scope before execution is complete.  I am going to investigate.

**Comment by Latawiec** [comment]
@cpyburn got anything? 😄

**Comment by cpyburn** [comment]
The issue was resolved when I created the command queue on the main game thread instead of in the thread.
