### ISSUE TITLE
Memory usage increasing continuously

### ISSUE THREAD

**Issue by DreDiki** [microsoft/DirectX-Graphics-Samples#272]
I'm learning directx 12 these days,and i found that memory usage of the samples is increasing continuously.
![memory](https://user-images.githubusercontent.com/6839704/30149568-adc79926-93da-11e7-9021-e4aa3987aef4.PNG)
After about 12 mins running, the **ModelViewer** in **MiniEngine** costs **35M more memory**.
Samples like D3D12Helloworld also have this issue. 
In my project,I use fence and commandlist like add more commands in the commandlist will become more serious...(And I do reset the CommandAllocater and CommandList as the sample does)Is the use of fence inappropriate?
\_(:з)∠)\_ Need help,thx.

**Comment by shuweihsu** [comment]
I didn't see this issue in the D3D12Helloworld and D3D12HelloTexture samples. Could you please share your OS version, GPU model, and GPU driver version? 

From the screenshot, looks like you enabled the Diagnostic Tools ("診斷工具").  In this tool, you can switch to the memory usage view, take a few snapshots, and then click View Heap to see what is taking out the memory space.

**Comment by DreDiki** [comment]
@shuweihsu 

OS : Windows 10 Home China,Insder Preview,OS Version 16288.1
Discrete GPU:
    GPU:Nvidia GTX 960M
    GPU Driver: Nvidia 382.33
Integrated GPU:
    GPU:Intel HD 530
    GPU Driver: 21.20.16.4664

Running Sample:
    D3D12Multithreading x64
    Visual Studio 2017

After running 0.5h,memory usage increased from 246.7M to 378.6M,
![image](https://user-images.githubusercontent.com/6839704/31058078-1445d69c-a720-11e7-95f5-c38bef9c44bc.png)

I have tried using heap profiling,but got nothing useful,most allocations are made in "External code".

**Comment by DreDiki** [comment]
Just found that my project works fine without continuous increasing memory usage while running directly **without the visual studio**,maybe there is somthing wrong with my visual studio?
My Visual Studio Version:15.3.1

**Comment by hegaoxiang** [comment]
me too.is there any solution

**Comment by hegaoxiang** [comment]
D3D12HelloWindow ,12s ,increase 1MB memory

**Comment by hegaoxiang** [comment]
D3D12HelloWindow ,12s ,increase 1MB memory

**Comment by MeepSplize** [comment]
It's the "debugController" (ID3D12Debug) that eats up some memory. Try running the samples in release mode.
