### ISSUE TITLE
MiniEngine can not use in UWP app

### ISSUE THREAD

**Issue by IngoChou** [microsoft/DirectX-Graphics-Samples#278]
Hi,

MiniEngine can not use in UWP app.
How can I do?
Thanks.

**Comment by stanard** [comment]
You may see references to UWP, but it's not functional yet.  There hasn't been a strong motivation to support both Win32 and UWP, and it's too soon to remove Win32.  MiniEngine also supports Xbox One which uses an older form of UWP to utilize system APIs, and that is the reason for the UWP-style code in places.

**Comment by IngoChou** [comment]
Thank you very much, standard. 
I want to develop HoloLens App (or MR App) base on  MiniEngine. As we know, HoloLens only support UWP App. 
So, I very much hope that MiniEngine will be able to provide this support. 
Meanwhile, this support will promote the development of  MR application.

Thank you for your help.

**Comment by ClemensX** [comment]
Ingo, as MiniEngine is a pure DX 12 engine and MR development is currently only supported on DX 11 you will have a hard time using MiniEngine as a base for any MR development.

**Comment by IngoChou** [comment]
@ClemensX 
Thank you.
Has any information about when will D3D12 support MR App development?
