### ISSUE TITLE
Profiling shaders in DirectX

### ISSUE THREAD

**Issue by blippyblips** [Microsoft/DirectX-Graphics-Samples#279]
Is there any way to profile DirectX(12) shader code or is it something that's in the works?

**Comment by blippyblips** [comment]
Have you discontinued updating this repo? Seems like no updates or issues have been done since August last year

**Comment by stanard** [comment]
You might be able to profile shader instructions with PIX.  I'm not sure.

We are not done with this repo.  I personally maintain MiniEngine, and I have a big update planned, but it's not my primary obligation so I've delayed it.  Also, new samples will be added as new features come to D3D.  Lastly, we must update the existing samples as new versions of Visual Studio are released and as d3dx12.h evolves.

**Comment by pkristof** [comment]
We have made some updates in the develop branch, particularly I've added D3D12 xGPU. Samples that depend on a functionality from an upcoming OS update and the update is available to insiders already are being added to develop branch first. Once the OS update releases to everyone, the updates will be pushed to master branch.

**Comment by blippyblips** [comment]
To answer my own question for any future readers; static shader analysis and profiling can be done using https://gpuopen.com/compute-product/codexl/ (https://github.com/GPUOpen-Tools/CodeXL)

There might be other options out there but it did the trick for me.

Thanks for the update and repo updates. Loving the new DXR and DXC stuff.
