### ISSUE TITLE
MiniEngine: Incorrect setup of readable stencil SRV in DepthBuffer

### ISSUE THREAD

**Issue by DrGr4f1x** [microsoft/DirectX-Graphics-Samples#281]
Currently the SRVDesc for stencil SRVs in DepthBuffer::CreateDerivedView is default-constructed, meaning the field SRVDesc.Texture2D.PlaneSlice = 0.

If the depth format includes stencil, then PlaneSlice should be set to 1 (assuming we don't have mips or array slices, but I'm not certain, since the documentation is a little sparse).

The specific error I get is:
ID3D12Device::CreateShaderResourceView: The Plane Slice 0 cannot be used when the resource format is R24G8_TYPELESS and the view format is X24_TYPELESS_G8_UINT.

This is easily repro'd in MiniEngine by changing DSV_FORMAT in BufferManager.cpp to one of the stencil formats.

My local workaround is to check for D24_S8 or D32_S8 format, and set PlaneSlice to 1.

**Comment by mversace** [comment]
hi, bro.
I met an error like this. but I can't solved it, and I don't know how to seach it.
I just want to use stencil. so I modified the g_SceneDepthBuffer's format D24_s8
the g_SceneDepthBuffer is OK.

but I got an error when run time
in bufferManager.cpp, I just leave some line: 
g_SceneDepthBuffer.Create(L"Scene Depth Buffer", bufferWidth, bufferHeight, DXGI_FORMAT_D24_UNORM_S8_UINT, esram);
g_OverlayBuffer.Create(L"UI Overlay", g_DisplayWidth, g_DisplayHeight, 1, DXGI_FORMAT_R8G8B8A8_UNORM, esram);

g_OverlayBuffer.Create has an error:
The Plane Slice 0 cannot be used when the resource format is R24G8_TYPELESS and the view format is X24_TYPELESS_G8_UINT

but I didn't find the PlaneSlice.

**Comment by mversace** [comment]
hi, bro, it's nice!
I solved the error. 
I search the internet but nothing except your answer. thank you!
and may I know how did you find the solved. any papers or books?

**Comment by caotrem** [comment]
The issue still isn''t fixed:
https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/MiniEngine/Core/DepthBuffer.cpp

The error message is:
`D3D12 ERROR: ID3D12Device::CreateShaderResourceView: The Plane Slice 0 cannot be used when the resource format is R32G8X24_TYPELESS and the view format is X32_TYPELESS_G8X24_UINT.  See documentation for the set of valid view format names for this resource format, determining which how the resource (or part of it) will appear to shader. [ STATE_CREATION ERROR #29: CREATESHADERRESOURCEVIEW_INVALIDVIDEOPLANESLICE]`

Here is my fix:

```
if (stencilReadFormat != DXGI_FORMAT_UNKNOWN)
{
    if (m_hStencilSRV.ptr == D3D12_GPU_VIRTUAL_ADDRESS_UNKNOWN)
        m_hStencilSRV = Graphics::AllocateDescriptor(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);

    // MiniEngine does not set the PlaneSlice correctly for DXGI_FORMAT_X24_TYPELESS_G8_UINT
    // https://github.com/microsoft/DirectX-Graphics-Samples/issues/281
    // https://microsoft.github.io/DirectX-Specs/d3d/PlanarDepthStencilDDISpec.html
    SRVDesc.Texture2D.PlaneSlice = StencilPlaneSlice(Format);
    SRVDesc.Format = stencilReadFormat;
    Device->CreateShaderResourceView(Resource, &SRVDesc, m_hStencilSRV);
}
```

And in the PixelBuffer add this function:
```
// Needed due to error in MiniEngine not setting it correctly when setting the SRV for the stencil in DepthBuffer::CreateDerivedViews
// https://github.com/microsoft/DirectX-Graphics-Samples/issues/281
// https://microsoft.github.io/DirectX-Specs/d3d/PlanarDepthStencilDDISpec.html
UINT PixelBuffer::StencilPlaneSlice(DXGI_FORMAT format)
{
    switch (format)
    {
        // 32-bit Z w/ Stencil
    case DXGI_FORMAT_R32G8X24_TYPELESS:
    case DXGI_FORMAT_D32_FLOAT_S8X24_UINT:
    case DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS:
    case DXGI_FORMAT_X32_TYPELESS_G8X24_UINT:
        return 1;

        // 24-bit Z
    case DXGI_FORMAT_R24G8_TYPELESS:
    case DXGI_FORMAT_D24_UNORM_S8_UINT:
    case DXGI_FORMAT_R24_UNORM_X8_TYPELESS:
    case DXGI_FORMAT_X24_TYPELESS_G8_UINT:
        return 0;

    default:
        return 0;
    }
}
```

**Comment by stanard** [comment]
I pushed the fix, but I'm confused by the wording here:  https://microsoft.github.io/DirectX-Specs/d3d/PlanarDepthStencilDDISpec.html#shader-resource-view

"PlaneSlice parameters are not added to the view creation for depth and stencil formats as existing DXGI formats are sufficient to disambiguate which plane or planes view is created form."

I take this to mean that based on the SRV format, it should deduce the PlaneSlice index.

**Comment by stanard** [comment]
I don't think there are any times when the PlaneSlice is 0. There are only two DSV formats with stencil, and they both require PlaneSlice=1.
