### ISSUE TITLE
Memory Align Issue in MiniEngine Math Linrary

### ISSUE THREAD

**Issue by zjxeditor** [Microsoft/DirectX-Graphics-Samples#290]
In the math library of MiniEngine project, please pay attention to the usage of XMVECTOR.

Lots of classes use XMVECTOR directly rather than through XMFloat4 or XMFloat3 such as: Scalar, Vector3, Vector4, Matrix3 and Matrix4. XMVECTOR is 16 byte aligned in memory and is not recommended to be used as class members. Although the code declare `__declspec(align(#))` to indicate the alignment for each class, but no `align alloc` methods are used to create these class, just common `new` process. There are no override 'new' and 'delete' methods to deal with the `align alloc`. And I cannot find any project settings to indicate the compiler to use `align alloc` for these classes. 

The code is runnable, but the proposed issue is really confusing. As a common practice, we should use `XMFloat*` store values, use `load` and `store` methods to do the conversion. While in this project, XMVECTOR is directly used.

**Comment by zjxeditor** [comment]
Your guys just make the target platform as x64. There is no support for any x86 platforms. As for DirectXMath library, On Windows x64, all heap allocations are 16-byte aligned, but for Windows x86, they are only 8-byte aligned. So we can safely make direct usage of XMVECTOR and XMMATRIX with no need for `load` and `store` functions or any overlaods `new/delete`. 

However, if we plan to support any x86 platform, there will be lots of code modification. As far as I am concerned, the code of the math library in this project is not good. It cannot server as somthing "general" or "templated". Direct utility of the code could make other projects run into problems unless  some settings are carefully configured.

On the other hand, the "SimpleMath" code from DirectXTK is well constructed, but make less usage of  SIMD. Some work should be done to improve the basic but important math code.

**Comment by stanard** [comment]
We have no plan to support x86 32-bit in MiniEngine.
