### ISSUE TITLE
I can't download binaries anymore!

### ISSUE THREAD

**Issue by LaurentGarcia** [Microsoft/DirectX-Graphics-Samples#305]
Hello,

It seems that the binaries files .zip are not available. I've been trying to download for a while but ... nothing...

**Comment by pkristof** [comment]
Hi,

We can download the binaries on our side. Do you continue having trouble downloading them?

**Comment by pkristof** [comment]
Glad that you could download the binaries. The releases/binaries are hosted by GitHub so I suggest raising the issue with them if they have a solution for your home connection.
