### ISSUE TITLE
 Failed to compile the shader

### ISSUE THREAD

**Issue by Sumenia** [microsoft/DirectX-Graphics-Samples#312]
i wanted tro try D3D12Raytracing sample on my AMD Vega 56 but can't run any (`D3D12RaytracingHelloWorld`, `D3D12RaytracingSimpleLighting`, `D3D12RaytracingMiniEngineSample`)

i get this following error
```
Cannot find definition of function ?Fallback_GeometryIndex@@YAIXZ

D3D12 Raytracing Fallback Error: Failed to compile the shader
Exception thrown at 0x00007FFA8F5D4008 in D3D12RaytracingSimpleLighting.exe: Microsoft C++ exception: _com_error at memory location 0x000000B447CFE2F0.
```

any idea what i`m doing wrong ?

**Comment by pkristof** [comment]
Fallback_GeometryIndex was removed a while ago. You hitting it suggests that you are using a stale Fallback Layer code or compiler. Make sure to pull the source from Master branch and get matching SDK binaries from the releases. Specifically, go to https://github.com/Microsoft/DirectX-Graphics-Samples/releases and download "DirectX Raytracing Binary Release v1.0".

**Comment by pkristof** [comment]
Then copy all the binaries to Samples\Desktop\D3D12Raytracing\tools\x64.

Let us know how it goes.

**Comment by yy0yaolinjun1** [comment]
excuse me,I wanted tro try D3D12Raytracing sample on vs2017 but can not run any sample projects
can't not open the source file #include "CompiledShaders\Raytracing.hlsl.h
I can't find this file in any path, any ideas what i`m doing wrong ?

**Comment by pkristof** [comment]
Hi,

Raytracing.hlsl.h is a compiled version of Raytracing.hlsl and is included in C++ source. The shader compilation executes as a first part of the project compilation. If the shader compilation failed, the build should have stopped, but in your case it doesn't and proceeds to compile C++ source which depends on the compiled shader being present. 

Do you get any errors if you force compile Assets/Shaders/Raytracing.hlsl (for example in D3D12RaytracingHelloWorld project) from a solution explorer? If it succeeds the compiled version *.h should be in "obj" folder.

Make sure that you are using latest repo source, SDK binaries and a GPU driver.
