### ISSUE TITLE
MiniEngine: Some questions regarding vector math headers

### ISSUE THREAD

**Issue by blippyblips** [microsoft/DirectX-Graphics-Samples#313]
From looking at the most recent DirectXMath library it seems they have added support for constexpr on almost all functions and structures. However MiniEngine seems to be using XMVECTOR directly which seems to go against how it's supposed to be used?

Is the benefit of working directly against an XMVECTOR really that much more worth performance wise then that of extending XMFLOAT3/XMFLOAT4 and loading/storing when neccesary and the benefits you get from being able to use all the constexpr calls?

Also are there any plans to remove/update the ancient versions of DirectXMath that comes with the visual studio/windows sdk?

**Comment by walbourn** [comment]
The latest version of **DirectXMath** an be obtained from [GitHub](https://github.com/Microsoft/DirectXMath), [NuGet](https://www.nuget.org/packages/directxmath), or [vcpkg](https://github.com/microsoft/vcpkg/tree/master/ports/directxmath).

I updated for ``constexpr`` usage in DirectXMath 3.15 which never appeared in a Windows SDK release. [DirectXMath 3.16](https://walbourn.github.io/directxmath-3.16/) shipped in the **Windows 10 SDK (20348), version 2104** which is 'optional' in the latest versions of Visual Studio.
