### ISSUE TITLE
WriteToSubresource fails with E_INVALIDARG

### ISSUE THREAD

**Issue by ankit040683** [microsoft/DirectX-Graphics-Samples#320]
Hi,

I am trying to write to a texture using ID3D12Resource::WriteToSubresource but it fails with E_INVALIDARG. Then I learned from documentation that resource needs to be mapped. Map command also fails with E_INVALIDARG. I create texture using CreateCommittedResource, I have tried various heap flags and initial resource states, but still no success. Any help would be appreciated.

Thanks
Ankit Jain

**Comment by john-h-k** [comment]
You can't write directly to textures without using a custom heap pool. It's generally not a good idea unless you're on a UMA device anyway

**Comment by walbourn** [comment]
Anytime you get ``E_INVALIDARG`` back from DirectX, your best option is to enable the debug layer and look at the debug output. It will explain why it's not supported in most cases.

https://docs.microsoft.com/en-us/windows/win32/direct3d12/directx-12-programming-environment-set-up
