### ISSUE TITLE
Porting Directx12 Asset into XAML element: advice on WRL::ComPtr replacement?

### ISSUE THREAD

**Issue by mprevot** [Microsoft/DirectX-Graphics-Samples#322]
[Original post on StackOverflow](https://stackoverflow.com/questions/49940563/porting-directx12-asset-into-xaml-element-advice-on-wrlcomptr-replacement)

I'm working on creating a WPF asset (like D3D11Image), from a DirectX12 Win32 desktop sample : D3D12PipelineStateCache, so I can embedd it as XAML element in a WPF application.

Microsoft Directx12 samples are having extensive usage of ComPtr (using Microsoft::WRL::ComPtr; and #include <wrl.h>), smart pointers, but build fails because of:

```
// Don't allow to compile sources with /clr
#ifdef _MANAGED
#error WRL cannot be compiled with /clr option enabled
#endif
```

Repro: I started to change configuration properties in the D3D12PipelineStateCache project:

    configuration type: Dynamic Library
    clr support: /clr
    .net target: v4.5

The goal was to "detach stop by stop the code from win32" and make it interfaced with XAML assets.

Do you have any recommendation of smart pointer to replace ComPtr or do you recommend to proceed differently, eg., by building a pure c++ dll with interop with clr dll, and in that case, how ?

**Comment by mprevot** [comment]
Is there any disrecommendation about using [CComPtr](https://docs.microsoft.com/en-us/cpp/atl/reference/ccomptr-class) ?

**Comment by walbourn** [comment]
The main thing to keep in mind is that ``operator&`` in the older ATL ``CComPtr`` asserts that the pointer is always null before doing the equivalent of ``GetAddressOf``. In ``ComPtr`` the use of ``operator&`` explicitly calls the equivalent of ``ReleaseAndGetAddressOf`` to release any existing pointer to avoid potential memory leaks.

**Comment by mprevot** [comment]
Thank you @walbourn. I understand, and I don't believe anymore that having a monolithic DX12-XAML-C++/CLI asset is the right way to achieve what I want.

Until now, the MS strategy was to have a CLI-XAML-DX11 (D3D11Image) asset talking to a native DX11 binary (D3DVisualization), and the latter sends DX11 surfaces to the first.

I think I'll just have a native DX12 dll sending surfaces to D3D11Image. Eventually would it be worth it to upgrade D3D11Image to a D3D12Image in that case ?

**Comment by mprevot** [comment]
I managed to create the DX12 native as XAML asset for WPF thanks to handles. Thanks.
