### ISSUE TITLE
D3D12RaytracingMiniEngineSample - Fails to run on AMD Polaris and Fiji SKUs

### ISSUE THREAD

**Issue by Woking-34** [Microsoft/DirectX-Graphics-Samples#324]
Hi,

I have tested the sample with two different AMD dGPUs (RX 580 and R9 Nano) and I got the same error: buffer creation fails when calling m_MissShaderTable.Create(L"Miss Shader Table",...) at location g_Device->CreateCommittedResource( &HeapProps, D3D12_HEAP_FLAG_NONE,...)

Winver: Version 1803 (OS Build 17134.1)
Radeon Software Version: 18.3.4

Can someone confirm, thanks!

**Comment by wallisc** [comment]
Ah there was a bug where several referenced resources in a shader needed the "globallycoherent" flag, I've fixed this and confirmed it works on Polaris as of c18fe2c in the develop-dxr branch. This should be in master in the coming week or so. Thanks for the issue report!

**Comment by Woking-34** [comment]
Thanks, the sample now works on my RX 580! It seems there is a ray traversal bug when using AMD cards.
Please see: https://github.com/Microsoft/DirectX-Graphics-Samples/issues/332
