### ISSUE TITLE
Compute queue and resource states

### ISSUE THREAD

**Issue by blippyblips** [microsoft/DirectX-Graphics-Samples#334]
If any read states are valid for transitioning/reading on any/multiple queue[s] (1) then why is D3D12_RESOURCE_STATE_GENERIC_READ considered invalid for use with compute queues?

Was trying to figure it out using other resources but was unable to find an answer. Is generic_read too wide with all it's states? Which particular states of "generic_read" are unfit for compute queues? What makes them unfit and should there be a SLIGHTLY_LESS_GENERIC_READ state for use with compute? 

(1) As suggested by https://msdn.microsoft.com/en-us/library/windows/desktop/dn899124(v=vs.85).aspx

**Comment by walbourn** [comment]
For Copy queues, only ``D3D12_RESOURCE_STATE_COPY_DEST`` and ``D3D12_RESOURCE_STATE_COPY_SOURCE`` are valid states.

For Compute queues, you can only use:

* ``D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER``
* ``D3D12_RESOURCE_STATE_UNORDERED_ACCESS``
* ``D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE``
* ``D3D12_RESOURCE_STATE_INDIRECT_ARGUMENT``
* ``D3D12_RESOURCE_STATE_COPY_DEST``
* ``D3D12_RESOURCE_STATE_COPY_SOURCE``

A you surmise, ``D3D12_RESOURCE_STATE_GENERIC_READ`` is a bit too broad to be meaningful for Compute queues.

> You may find it useful to look at my handling of Copy and Compute queues in [ResourceUploadBatch](https://github.com/microsoft/DirectXTK12/blob/master/Src/ResourceUploadBatch.cpp) in the *DirectX Tool Kit for DX12*.
