### ISSUE TITLE
D3D12RaytracingHelloWorld- Run Error. Tips "Fail to compile shader"

### ISSUE THREAD

**Issue by ArionTT** [Microsoft/DirectX-Graphics-Samples#337]
My OS is Windows 10 RS4 update
VS 2017

Build project well. (excepted warning :**FXC : warning : DXIL.dll not found.**)

The error output is : 

D3D12 State Object 0x0000008ABCD3EC70: Raytracing Pipeline
[0]: DXIL Library 0x00007FF75A74B4A0, 5114 bytes
 Ã[0]: MyRaygenShader
 Ã[1]: MyClosestHitShader
 À[2]: MyMissShader
[1]: Hit Group (MyHitGroup)
 Ã[0]: Any Hit Import: [none]
 Ã[1]: Closest Hit Import: MyClosestHitShader
 À[2]: Intersection Import: [none]
[2]: Raytracing Shader Config
 Ã[0]: Max Payload Size: 16 bytes
 À[1]: Max Attribute Size: 8 bytes
[3]: Local Root Signature 0x00000208A5914920
[4]: Subobject to Exports Association (Subobject [3])
 Ã[0]: MyRaygenShader
 Ã[1]: MyMissShader
 À[2]: MyHitGroup
[5]: Root Signature 0x00000208A5914380
[6]: Raytracing Pipeline Config
 À[0]: Max Recursion Depth: 1
**Cannot find definition of function ?Fallback_SetPayloadOffset@@YAII@Z**

**D3D12 Raytracing Fallback Error: Failed to compile the shader**
0x00007FF8430DF218 处(位于 D3D12RaytracingHelloWorld.exe 中)引发的异常: Microsoft C++ 异常: _com_error，位于内存位置 0x0000008ABCD3E0D0 处。
0x00007FF8430DF218 处(位于 D3D12RaytracingHelloWorld.exe 中)有未经处理的异常: Microsoft C++ 异常: _com_error，位于内存位置 0x0000008ABCD3E0D0 处。

Did i make some mistakes or lose some file?

p.s.
Does Fallback layer need Driver? My graphicard is NVIDIA Geforce GTX 1050Ti, and driver is 391.35.

**Comment by pkristof** [comment]
Hello,
This sounds like you have mismatched SDK binaries. Make sure you are using sample code from the Master branch and DirectXRaytracingBinaries**V1.0**.zip for the code from Master branch. See full setup requirements here
https://github.com/Microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12Raytracing#requirements

**Comment by ArionTT** [comment]
Thanks, problem have been fixed.

And i want to ask another question.
Is the fallback layer not contained in DirectX code?
For example, I want to run NVIDIA DXR example with GTX 1050Ti.

**Comment by pkristof** [comment]
Raytracing Fallback Layer API is a layer/library sitting on top of DirectX shared as an open source library via this GitHub repo. The API facing difference between the two APIs is minimal, but a sample need to explicitly use the library. Nvidia DXR samples do not implement the library that so you would have to extend their sample to run on 1050 Ti.
