### ISSUE TITLE
DXRT samples don't work with error in CopyResource

### ISSUE THREAD

**Issue by Kvalme** [Microsoft/DirectX-Graphics-Samples#344]
After getting DX samples and copying DirectXRaytracingBinariesV1.0 into DirectX-Graphics-Samples\Samples\Desktop\D3D12Raytracing\tools\x64 all samples builds fine, but don't work with following error:

```
D3D12 ERROR: ID3D12CommandList::CopyResource: Source and Destination resource must have the same size. But pSrcResource has resource size (3932160) and pDstResource has resource size (4063232). [ RESOURCE_MANIPULATION ERROR #944: COPYRESOURCE_INVALIDDSTRESOURCE]
D3D12: **BREAK** enabled for the previous message, which was: [ ERROR RESOURCE_MANIPULATION #944: COPYRESOURCE_INVALIDDSTRESOURCE ]
Exception thrown at 0x00007FFBF5114008 (KernelBase.dll) in D3D12RaytracingHelloWorld.exe: 0x0000087A (parameters: 0x0000000000000001, 0x000000948AD9B300, 0x000000948AD9D1F0).
Unhandled exception at 0x00007FFBF5114008 (KernelBase.dll) in D3D12RaytracingHelloWorld.exe: 0xC000041D: An unhandled exception was encountered during a user callback.
```

This happens for all demos (HelloWorld, SimpleLighting, MiniEngineSample)

Using fallback layer and Vega56.

**Comment by pkristof** [comment]
Hello,

Are you using the latest AMD drivers? I verified HelloWorld via Fallback Layer to run with 18.4.1 driver on Vega 56.

**Comment by Kvalme** [comment]
Hi, no it was not the latest driver.
I tried another DX12 samples - they woks fine. Problem persists only with ray tracing samples.
Will try latest driver later.

**Comment by pkristof** [comment]
If the latest driver didn't resolve the issue for you, please reactivate this.

**Comment by Kvalme** [comment]
Tried with latest driver - got same issue.
