### ISSUE TITLE
DXR Fallback:  The implementation of EmitRaytracingAccelerationStructurePrebuildInfo does not match the DXR headers.

### ISSUE THREAD

**Issue by jbarczak** [Microsoft/DirectX-Graphics-Samples#366]
The PREBUILD_INFO_DESC for compacted size is defined as a 64-bit integer in the DXR headers, but the fallback layer as implemented assumes 32 bits.  In the case of multiple RTASes passed to the same Emit() call, the  results will be incorrect.  This behavior also differs from that of the Nvidia DXR driver.

**Comment by wallisc** [comment]
Yup, this is definitely a bug. I'll take a look, seems like a quick fix. Thanks for filing an issue on it!

**Comment by wallisc** [comment]
I've fixed this in the develop-dxr branch, expect this to be moved down to master in a week or so
