### ISSUE TITLE
D3dRayTracing Fails to build

### ISSUE THREAD

**Issue by comprodigy** [Microsoft/DirectX-Graphics-Samples#378]
Description isn't very descriptive, but keep getting these errors across the entire solution. Copied the binaries over into the x64 tools folder, but still getting these issues. 

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "cd C:\Users\compg\Downloads\dx12\Samples\Desktop\D3D12Raytracing\src\..\tools\x64\
PrebuildCheck.bat
:VCEnd" exited with code 1.	D3D12RaytracingMiniEngineSample	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	123

**Comment by wallisc** [comment]
Closing, we've made a separate fix that also was causing issues when there were spaces in the directory. If you're still able to repro this with the latest contents in master, please feel free to re-open this

**Comment by HanmingZhang** [comment]
Hey wallisc, I met the same issue when trying to build D3DRaytracing sample. Here is the error message "MSB3073	The command "cd "D:\DX12_Samples\DirectX-Graphics-Samples-master\DirectX-Graphics-Samples-master\Samples\Desktop\D3D12Raytracing\src\..\tools\x64\"
PrebuildCheck.bat
:VCEnd" exited with code 1.	FallbackLayer	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	128	
"

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "cd "D:\DX12_Samples\DirectX-Graphics-Samples-master\DirectX-Graphics-Samples-master\Samples\Desktop\D3D12Raytracing\src\..\tools\x64\"
PrebuildCheck.bat
:VCEnd" exited with code 1.	D3D12RaytracingHelloWorld	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	128

**Comment by HanmingZhang** [comment]
No worries, fixed by putting DirectX Raytracing Binaries Release files under tools\x64 folder
