### ISSUE TITLE
nVidia driver crashes on window resize on hybrid laptop

### ISSUE THREAD

**Issue by mafiesto4** [Microsoft/DirectX-Graphics-Samples#38]
Just add the following line to the code to enable NVidia high performance GPU on laptops.
Works fine until you want to resize the window. Then black magic happens and dx12 device is being removed with error code: DXGI_ERROR_DRIVER_INTERNAL_ERROR

```cpp
// http://developer.download.nvidia.com/devzone/devcenter/gamegraphics/files/OptimusRenderingPolicies.pdf
// The following line is to favor the high performance NVIDIA GPU if there are multiple GPUs
extern "C" { _declspec(dllexport) unsigned int NvOptimusEnablement = 0x00000001; }
```

Any chance to fix it? NVidia knows about it?
Of course transition fullscreen<->windowed works ok.

**Comment by bobbrow** [comment]
I'm seeing this too when I run the app on the NVidia GPU.  I also see a device removed without setting this variable, but manually select the NVidia adapter in the code.

I'll let NVidia know.
