### ISSUE TITLE
Can I contribute tutorials as code and as wiki pages?

### ISSUE THREAD

**Issue by IgrauBezRuk** [Microsoft/DirectX-Graphics-Samples#393]
Hey! I think miniengine is a great way to start learning DX12 from up to down, but except ModelViewer, MiniEngine hasn't any additional API examples. So I think it will be great if any examples will be appear. Like 
from first steps (triangle, texture mapping, 3d space, model loader ...) to custom modelviewer demo

**Comment by walbourn** [comment]
There is also the [DirectX Tool Kit for DX12](https://github.com/Microsoft/DirectXTK12/wiki/Getting-Started) which includes a tutorial series, the [directx-vs-templates](https://github.com/walbourn/directx-vs-templates) support DirectX 12, and a series of simple samples for both DX11 & DX 12 on [Xbox-ATG-Samples](https://github.com/Microsoft/Xbox-ATG-Samples/).

Really we have a ton of resources, but discovering it is a challenge.

**Comment by stanard** [comment]
I think I understand.  You want simpler examples of using MiniEngine.  We have other projects built with MiniEngine here.  For instance, I have an HDR image viewer which applies tone mapping to display the image (and can work with HDR monitors too).  That could be a useful addition to GitHub.  Thanks for the suggestion.

For a bare bones MiniEngine app, have you tried running the CreateNewSolution batch file?  From there it shouldn't be too hard to add a shader and draw something (or compute something).
