### ISSUE TITLE
Add DirectXMesh and DirectXTex as dependencies?

### ISSUE THREAD

**Issue by IgrauBezRuk** [Microsoft/DirectX-Graphics-Samples#395]
Currently MiniEngine supports only .dds format as texture loader and nothing as for models loading. 
I found that XMesh and XTex are pretty nice and complete libraries to extend MiniEngine functionality. So should it be extended?

**Comment by stanard** [comment]
I have a massive update to push when I have time to merge branches.  In my local branch, I added DirectXMesh and DirectXTex as dependencies to assist with loading glTF 2.0 models and animations.  I'm eager to push it out to GitHub, but I think it will take some time, and MiniEngine isn't my top priority yet.  Perhaps I can push a preview of it to the dev branch this month.

**Comment by jmkinzer** [comment]
+1 For having this in dev
