### ISSUE TITLE
Unable to initialize DirectInput8Create 

### ISSUE THREAD

**Issue by kentbarber** [microsoft/DirectX-Graphics-Samples#399]
This may not be an issue with the Mini Engine, but I have been trying to run the ModelViewer (and it is unable to create the DirectInput via DirectInput8Create (line 329 of GameInput.cpp).

I am compiling the MiniEngine\ModelViewer\ModelViewer_VS15.sln.  

This project also seems to use the Windows SDK 10.0.15063.0 for the ModelViewer, where as Core and Model are set to 10.0.17134.0.  But even changing this to 10.0.17134.0 did not help.

I have Windows 10 Pro version 1803   (OS build 17134.81)
I have the very latest version of Visual Studio 2017 (15.7.3).
And I have the latest Windows SDK (10.0.17134.0)

I am wondering if perhaps the Mini Engine also requires that DirectX 8 or 9 runtime to be installed?

**Comment by kentbarber** [comment]
Sorry, it appears my windows version is 10.0.17134.0 and not 1803. Even after doing an update. Please ignore this thread for now, I will close it if it is successful once I update to 1803.

**Comment by stanard** [comment]
It's not supposed to need anything else.  An error reported at that line is unusual, but I probably can't diagnose it until Monday at work.  Chuck Walbourn, if he's listening, might have a suggestion.

**Comment by walbourn** [comment]
You can't install "DirectX" on modern versions of Windows, see [Not So DirectSetup](https://blogs.msdn.microsoft.com/chuckw/2010/09/08/not-so-direct-setup/).

Can you provide any more specifics about what error code you are getting back?

> In general use of DirectInput is discouraged except for supporting specific legacy joysticks and force-feedback/haptic systems. Using it for keyboard/mouse is problematic for many reasons, and overall using XInput or ``Windows.Gaming.Input`` is a better choice especially for an application that only support DirectX 12 and therefore already requires Windows 10.
