### ISSUE TITLE
Textured triangle sample?

### ISSUE THREAD

**Issue by zezba9000** [Microsoft/DirectX-Graphics-Samples#4]
How about a simple texture on a triangle sample?  Wanted to see how one might load texture data in D3D12.

**Comment by bobbrow** [comment]
Thanks for the feedback. We plan to do this one soon. For now you can look at the block of code in the D3D12Bundles sample in D3D12Bundles.cpp around line 312 or so.

**Comment by bobbrow** [comment]
New sample added in the develop branch.  Will be included in the next release when we merge to master.

**Comment by zezba9000** [comment]
Awesome tnx!
