### ISSUE TITLE
Please, make portable example of hello world

### ISSUE THREAD

**Issue by acterhd** [Microsoft/DirectX-Graphics-Samples#40]
For me need portable example of hello world, because need run in node.js gyp module. For GYP need portable code, with separate WinAPI.

**Comment by bobbrow** [comment]
Can you explain what you mean by "portable"?  This is C++ code, not JavaScript.  If you're asking for a Windows Runtime wrapper for Direct3D 12 so you can code against JavaScript, that is well outside the scope of this repo.

**Comment by acterhd** [comment]
I want wrote Node module with Directx 12.
20 окт. 2015 г. 0:28 пользователь "Bob Brown" <notifications@github.com>
написал:

**Comment by bobbrow** [comment]
I'm sorry, but this is not an area we plan to invest in at this time.
