### ISSUE TITLE
CreateNewSolution.bat is missing a 3rdParty folder

### ISSUE THREAD

**Issue by kentbarber** [Microsoft/DirectX-Graphics-Samples#400]
It's not possible to run CreateNewSolution.bat since it checks to see if the folders 3rdparty, core and tools exist. And there is no 3rdParty folder in this repo.

**Comment by stanard** [comment]
Sorry.  I guess that script got a bit stale.  I'm looking to fix it right now and will push an update shortly.  If you're in a hurry, you need to edit CreateNewProject.py in Tools\Scripts.  Look for '3rdParty' and remove it from the list of expected folders.  In the mean time, I'm checking to see if the template project files are also out of date.

**Comment by stanard** [comment]
Files are updated.  (I also changed the Windows SDK version to 17134.)

**Comment by kentbarber** [comment]
Thanks for fixing that. I did find and fix the 3rdParty issue myself when testing. But unfortunately due to the requirement of DirectInput I am not able to use the project. I hope you guys find a fix for that in future. Thanks.

**Comment by IgrauBezRuk** [comment]
Ehm. Why you just didn't accept pull request #387 which was opened 15 days ago?
