### ISSUE TITLE
VS2013 version

### ISSUE THREAD

**Issue by Rich2020** [Microsoft/DirectX-Graphics-Samples#43]
Could we have a VS2013 version, please?

**Comment by bobbrow** [comment]
I'm sorry, but we're not planning to add support for VS 2013 for these samples.  You can download and install Visual Studio 2015 Community edition for free.

https://www.visualstudio.com/products/visual-studio-community-vs

**Comment by Rich2020** [comment]
Pity. Thanks for the reply.
