### ISSUE TITLE
Support for native DXR on Titan V on RS5/RS6 insider previews?

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectX-Graphics-Samples#436]
Hi,
I got a Titan V for testing native (non fallback layer) DXR apps..
the problem is I was on running on a RS5 insider build..
testing your D3D12Raytracing samples **from master branch** as you say RS5 branch requires non existant drivers yet from Nvidia..
and I made sure I have all requisites Ok (I'm on 398.82 drivers, using DirectXRaytracingBinariesV1.2.zip (also tested using V1.3SDK without success) and enabled develop mode) excepting I'm using current insider previews instead of RS4..
tested all exposed below on both 17723 and then gone to RS6 18204 to see if fixed the problems I have..

In debuging D3D12RaytracingHelloWorld app I see in debug console d3d12.dll is loaded from DirectXRaytracingBinariesV1.2.zip:
D:\dxr\DirectX-Graphics-Samples-master\Samples\Desktop\D3D12Raytracing\src\D3D12RaytracingHelloWorld\bin\x64\Debug\d3d12.dll
and also that:
m_isDxrSupported = EnableRaytracing(adapter);
returns ok

the problem is on:
ThrowIfFailed(m_dxgiFactory->CreateSwapChainForHwnd(m_commandQueue.Get(), m_window, &swapChainDesc, &fsSwapChainDesc, nullptr, &swapChain));
Excepción producida en 0x00007FFAEDC0EC8E (dxgi.dll) en D3D12RaytracingHelloWorld.exe: 0xC0000005: Infracción de acceso al leer la ubicación 0x0000000000000000.

so seems being on April update (aka RS4) is a hard requirement, right?

just lazy to switch to RS4, if it's avoidable but seems the problem is on dxgi.dll and you don't ship a dxgi.dll on the DXR SDK.. maybe copying dxgi.dll from RS4 ISO to program folder will fix this problem?

thanks..

**Comment by pkristof** [comment]
Hello,

Yes, for now, you will need to stay on RS4 + overlay 1.3 SDK binaries for DXR capability. RS5 requires a new driver, which is not available yet.

Apologies for the inconvenience.
