### ISSUE TITLE
Using the bat files to create new solutions

### ISSUE THREAD

**Issue by jonny2027** [Microsoft/DirectX-Graphics-Samples#438]
Hi,

I was just wondering the correct parameters to pass into the python script to create a new project using the  core and model libraries

Thanks

**Comment by IgrauBezRuk** [comment]
@jonny2027 is it still or problem or you can close this issue?!

**Comment by jonny2027** [comment]
Sorry. I havent had a chance to test it but I will close it.

Thanks

**Comment by stanard** [comment]
There are two batch files.  CreateNewSolution.bat passes "app" to the python script and the name of the solution to create.  CreateNewLibrary.bat passes in "lib" and the name of the project to create.  Run them from MiniEngine's root folder, and the new folder will be created parallel to "Core".
