### ISSUE TITLE
Can't build in debug under vs2017

### ISSUE THREAD

**Issue by mrobin604** [microsoft/DirectX-Graphics-Samples#440]
I build the tutorial projects using Visual Studio 2017, but when I run them, it is missing the following DLLs:

VCRUNTIME140D.dll
ucrtbased.dll
MSVCP140D.dll

These are from the 2015 VC++ redist installer, which I can't install because I'm running 2017. Is there a way to build these samples under the 2017 redist?

**Comment by stanard** [comment]
Yeah, we should be able to fix that.  I want to deprecate VS2015 entirely, and I'll clean up any stale dependencies.  Thanks for letting us know.  Sometimes we miss these problems because we keep several versions of VS installed.

**Comment by stanard** [comment]
I'm not sure these things are installed with the 2015 VC++ redist package.  On my system, they are loaded from C:\Windows\System32.  And they get loaded even when targeting the v141 platform toolset.  There are no v141 equivalents of the files you listed.  (v140 and v141 are binary compatible.)  I'll ask around, but you might try checking your path in the mean time.

**Comment by walbourn** [comment]
VS 2015 Update 3 - VS 2022 all share the same REDIST. This is part of the [binary compatibility](https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017) support. This means that the VS 2017 CRT Is actually a *newer version* of the VS 2015 Update 3 CRT.

IOW: The ``VCRUNTIME140D.dll``, ``MSVCP140D.dll``, and ``ucrtbased.lib`` are part of Debug runtime for VS 2015 Update 3 all the way through VS 2022. The fact that they are missing indicates that you don't have the VS 2017 Debug C/C++ Runtime either.
