### ISSUE TITLE
GUI from the box

### ISSUE THREAD

**Issue by IgrauBezRuk** [Microsoft/DirectX-Graphics-Samples#444]
Hey!
MiniEngine is very nice engine to make up small experiments with DX12 and graphics techniques, but both of them are mostly always require some dynamic tweaking. I think 99% of people, who want to do something with MiniEngine will integrate UI library into and after continue experiments. It's takes time and it can be reduced.
What I propose is to integrate UI part into miniengine and allow users add UI stuff instantly in Startup() function.
I think we can consider imgui as is most popular UI in the graphics world.
My current task is integrate imgui in MiniEngine and I can, in the end, open a pull request and it can be part of miniengine.
What do you think?

Thanks!

**Comment by stanard** [comment]
Imgui has been proposed before, and it would be quite useful.  But we do already have dynamic tweaking support.  Hit backspace on your keyboard, or if you have a gamepad plugged in, try the "Back" button.  The code for those text-style tweaks is in EngineTuning.

**Comment by IgrauBezRuk** [comment]
Ah okay, didn't know about that. Yeah, i think that is really enough. Thanks.
