### ISSUE TITLE
Can't run D3D12xGPU sample - missing D3D11 SDK Layers for Windows 10??

### ISSUE THREAD

**Issue by CGAndersonSea** [microsoft/DirectX-Graphics-Samples#447]
I have latest windows 10 update, latest vs2017, and did install windows 10 sdk as per directx 12 instructions (had to uninstall the sdk first from VS2017 installation), then just to be sure updated VS2017 installation with a few things to make sure didn't miss anything.

Apparently, I did miss something? The samples compiles fine (no changes to sln), Debug/64, but when run I get the following:

'D3D12xGPU.exe' (Win32): Loaded 'C:\Windows\System32\dxilconv.dll'. Cannot find or open the PDB file.
'D3D12xGPU.exe' (Win32): Loaded 'C:\Users\cyander\Documents\Github\DXR\DirectX-Graphics-Samples-1.3-dxr\Samples\Desktop\D3D12xGPU\src\bin\x64\Debug\DXGIDebug.dll'. Symbols loaded.
D3D11CreateDevice: Flags (0x2) were specified which require the D3D11 SDK Layers for Windows 10, but they are not present on the system.
These flags must be removed, or the Windows 10 SDK must be installed.
Flags include: D3D11_CREATE_DEVICE_DEBUG
Exception thrown at 0x00007FFB08D6A388 in D3D12xGPU.exe: Microsoft C++ exception: _com_error at memory location 0x000000C134D2E210.
Exception thrown at 0x00007FFB08D6A388 in D3D12xGPU.exe: Microsoft C++ exception: HrException at memory location 0x000000C134D2E628.
Application hit a problem: HRESULT of 0x887A002D
Terminating.

**Comment by walbourn** [comment]
The "debug layers" for Windows 10 are a _Windows optional feature_. Normally this is enabled automatically by installing the Windows SDK, but it can depend on your network and if you are using an insider release of Windows 10.

See [this blog post](http://blogs.msdn.com/b/vcblog/archive/2015/03/31/visual-studio-2015-and-graphics-tools-for-windows-10.aspx).

**Comment by CGAndersonSea** [comment]
by the way, it's is expected behavior for the sample to crash if the sdk layers are not in place? correct? you cannot run the sample without them?
thanks

**Comment by pkristof** [comment]
SDK layers shouldn't be required for a sample to run. I've added it to our backlog to review the sample and the hard dependency. Thanks.

**Comment by CGAnderson** [comment]
Yet presumably I'm using a DirectX 12 capable driver/video card (an AMD Vega 64, which is certainly supporting most of DirectX12 and Vulkan...even if it doesn't handle the v1.3 RTRT stuff yet) and it seems odd that a debug layer/optional Graphics Tools would be a hard dependency for a software device. I was taking 'developer only' to not imply a requirement for an optinoal debug layer - only that developer settings must been set in Windows 10 (which they were.) :(

**Comment by walbourn** [comment]
I was pointing out that WARP12 is part of the Graphics Tools optional feature. While you can rely on WARP11 being available on 'retail' systems, you can't rely on WARP12 which is "developer only" because the performance is not considered sufficient (yet).

Anyhow, that may not the problem in your, I just wanted to note on possible source of dependency.

**Comment by CGAnderson** [comment]
I see. Thanks for the explanation.😊

**Comment by WeakKnight** [comment]
In China's Network Environment, I can not install it via Optional Features Panel. Is there any other way to install it?

**Comment by walbourn** [comment]
Which specific build of Windows 10 are you using? The Feature-On-Demand much match your build. Is that Windows 10 (19041)?
