### ISSUE TITLE
D3D12 MiniEngine Sample Samples - DXR Support

### ISSUE THREAD

**Issue by Woking-34** [Microsoft/DirectX-Graphics-Samples#453]
Hi,

This test Currently only runs and supports the Fallback Layer. Is it possible to make it run on DXR, are there any limitations or API differences between DXR and Fallback Layer? Thanks!

**Comment by pkristof** [comment]
Hi,

yes, FL is the only supported mode in the MiniEngine sample for the time being as per https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12Raytracing/src/D3D12RaytracingMiniEngineSample/readme.md#limitations

We will address this limitation and let the sample default to DXR when available.
