### ISSUE TITLE
D3D1211On12 sample exception

### ISSUE THREAD

**Issue by Hlexyn** [Microsoft/DirectX-Graphics-Samples#46]
The debug version of the 11On12 sample produces the exception:

`Exception thrown at 0x00007FFE21AEA1C8 in D3D1211On12.exe: Microsoft C++ exception: _com_error at memory location 0x000000609DD8E3C0.`

at the line 407 of D3D1211On12.cpp:

`ThrowIfFailed(m_d2dDeviceContext->EndDraw());`

but not on the first call.

This unfortunately spams the debug output so a fix would be appreciated.

**Comment by bobbrow** [comment]
The D3D 12 SDK layers uses exceptions to control execution flow and it just so happens that there is a harmless exception being thrown and caught in the 11-on-12 runtime.  The team is aware of the issue and I know they were looking into a way to make these go away.  I'll check to see if they got it fixed or not.  They've been working hard on the SDK layers in the past few months.

**Comment by Hlexyn** [comment]
Excellent, thank you. Just in case it helps it seems to only appear with a D3D11On12Device created with D3D11_CREATE_DEVICE_DEBUG.
