### ISSUE TITLE
DX12 EXECUTEINDIRECT - INDEX FORMAT ISSUE

### ISSUE THREAD

**Issue by HasibuddinShaikh** [microsoft/DirectX-Graphics-Samples#468]
Hi Everyone,

I was trying to implement ExecuteIndirect API with DX12 and noticed some strange behaviour w.r.t Index format specification.

If I generate command list normally with IASETINDEXBUFFER( with index format r16_uint), everything renders fine, but if I implement same thing through ExecuteIndirect , DX12 does not render it. If I change index format to r32_uint, everything renders correctly through ExecuteIndirect.

Issue can be reproduced in DX12EXECUTEINDIRECT sample by adding indexbuffer and changing index values from "UINT" to "uint16_t" or equivalent and Index format from r32_uint to r16_uint.

Is this limitation of ExecuteIndirect API or bug or am I doing something wrong. If you can point me to documentation which provides understanding for it if I am doing something wrong.

Anyways, I am now able to render entire scene with ExecuteIndirect API with individual meshes pointing to their own Vertex, Index and constant Buffers. All this only after using index format of r32_uint and not without.

I was not having better way to reach you out, so I hope you don't mind me asking this question here.

Following is the modified code for sample.

```
//D3D12ExecuteIndirect.h header file
//*** added code
	ComPtr<ID3D12Resource> m_indexBuffer;
	ComPtr<ID3D12Resource> indexBufferUpload;
	D3D12_INDEX_BUFFER_VIEW m_indexBufferView;

	struct ModifiedIndirectCommand
	{	
		D3D12_GPU_VIRTUAL_ADDRESS cbv;
		D3D12_VERTEX_BUFFER_VIEW vbv;
		D3D12_INDEX_BUFFER_VIEW ibv;						
		D3D12_DRAW_INDEXED_ARGUMENTS indexArguments;
		UINT padding; // padding to make sure that vbv and ibv falls at multiple of 8 bytes.
	};
```
```
//D3D12ExecuteIndirect.cpp source file
//*** added code
#ifdef R32FORMAT
		UINT indices[] =
		{
			0, 1, 2
		};
#else
		uint16_t indices[] =
		{
			0, 1, 2
		};
#endif // R32FORMAT

// *** index buffer creation and upload omitted here

//index buffer view format		
#ifdef R32FORMAT
		m_indexBufferView.Format = DXGI_FORMAT_R32_UINT; // DX12 ExecuteIndirect Renders this.
#else
		m_indexBufferView.Format = DXGI_FORMAT_R16_UINT; // DX12 ExecuteIndirect does not Render this.
#endif // R32FORMAT

//*** WITH commandList->IASETINDEXBUFFER, DX12 will render for both format.


//rest is updating command signature, command buffer generation and compute.hlsl structuredbuffer modification. Omitted here.
```

Also, I need to add padding at the end of the Command Structure just to make sure that vbv and ibv start point falls at multiple of 8 bytes. I couldn't find any documentation suggesting the same. In absence of this alignment GPU stalls or windows gets hanged up.

I am not software engineer but mechanical engineer with an enthusiasm for programming. So excuse me for anything wrong that I would have suggested above w.r.t programming or DirectX API. 

Thanks,
Hasibuddin Shaikh

**Comment by stanard** [comment]
Are you saying that specifying the format of the index buffer _within_ the indirect arguments buffer is insufficient and that you need to also precede the ExecuteIndirect call with a redundant call to set the index buffer format?

**Comment by HasibuddinShaikh** [comment]
No,
If indexbuffer view is using r16_uint format, executeindirect does not render. But if i change indexbuffer view to r32_uint, executeindirect renders it.

In absence of execute indirect, when we record commands directly to command list, It will render with both formats .

**Comment by stanard** [comment]
Would it be possible to see more of your code?  Specifically, I'd like to see how you compile the command signature, how you create the arguments buffer, and how you write the arguments to the buffer.  And are you familiar with MiniEngine?  There is a command signature wrapper class (CommandSignature.h/cpp) for constructing signatures as well as a indirect arguments buffer (GpuBuffer.h/cpp : IndirectArgsBuffer).  Maybe you can compare your code and find the problem.

**Comment by HasibuddinShaikh** [comment]
Ok,

Currently I am out of station, will share entire source including shaders of modified dx12executeindirect sample week later.

And yes, I referred to mini engine as well. I was unable to find a source where execute indirect is used with draw_indexed_args, what I found was draw_args for drawing quads for particle effects i guess and since that uses vertex buffer, it will not be problem. Will check it once again. 

Draw_indexed will also not be problem with either r32_uint or r16_uint indexbufferview if you are setting index buffer from outside of indirect args, but the moment you take index buffer binding inside indirect args, you will need to set index buffer view to r32_uint format.

Thanks,

**Comment by HasibuddinShaikh** [comment]
Hi,

Here is the code.
```

//D3D12ExecuteIndirect.h
//*** added code
	ComPtr<ID3D12Resource> m_indexBuffer;
	ComPtr<ID3D12Resource> indexBufferUpload;
	D3D12_INDEX_BUFFER_VIEW m_indexBufferView;

	struct ModifiedIndirectCommand
	{	
		D3D12_GPU_VIRTUAL_ADDRESS cbv;		
		D3D12_INDEX_BUFFER_VIEW ibv;						
		D3D12_DRAW_INDEXED_ARGUMENTS indexArguments;
		UINT padding[1];
	};
```
Code in source file.

-> Index definition for triangle
```
//*** added code
#ifdef R32FORMAT
		UINT indices[] =
		{
			0, 1, 2
		};
#else
		uint16_t indices[] =
		{
			0, 1, 2
		};
#endif // R32FORMAT

//this follows indexbuffer creation.
```

->index buffer view

```
// Initialize the index buffer view.
		m_indexBufferView.BufferLocation = m_indexBuffer->GetGPUVirtualAddress();
		m_indexBufferView.SizeInBytes = sizeof(indices);
		
#ifdef R32FORMAT
		m_indexBufferView.Format = DXGI_FORMAT_R32_UINT;
#else
		m_indexBufferView.Format = DXGI_FORMAT_R16_UINT;
#endif // R32FORMAT
```
->command signature creation

```
// Create the command signature used for indirect drawing.
	{
		// Each command consists of a CBV update and a DrawIndexedInstanced call.
		D3D12_INDIRECT_ARGUMENT_DESC argumentDescs[3] = {};
		argumentDescs[0].Type = D3D12_INDIRECT_ARGUMENT_TYPE_CONSTANT_BUFFER_VIEW;
		argumentDescs[0].ConstantBufferView.RootParameterIndex = Cbv;		
		argumentDescs[1].Type = D3D12_INDIRECT_ARGUMENT_TYPE_INDEX_BUFFER_VIEW;		
		argumentDescs[2].Type = D3D12_INDIRECT_ARGUMENT_TYPE_DRAW_INDEXED;		

		D3D12_COMMAND_SIGNATURE_DESC commandSignatureDesc = {};
		commandSignatureDesc.pArgumentDescs = argumentDescs;
		commandSignatureDesc.NumArgumentDescs = _countof(argumentDescs);
		commandSignatureDesc.ByteStride = sizeof(ModifiedIndirectCommand);

		ThrowIfFailed(m_device->CreateCommandSignature(&commandSignatureDesc, m_rootSignature.Get(), IID_PPV_ARGS(&m_commandSignature)));
		NAME_D3D12_OBJECT(m_commandSignature);
	}
```
-> command buffer recording.
```
commands[commandIndex].cbv = gpuAddress;				
commands[commandIndex].ibv = m_indexBufferView;
commands[commandIndex].indexArguments.IndexCountPerInstance = 3;
commands[commandIndex].indexArguments.InstanceCount = 1;
commands[commandIndex].indexArguments.BaseVertexLocation = 0;
commands[commandIndex].indexArguments.StartIndexLocation = 0;
commands[commandIndex].indexArguments.StartInstanceLocation = 0;
commandIndex++;
gpuAddress += sizeof(SceneConstantBuffer);
```
-> Code in populate command list

```
m_commandList->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP);		
m_commandList->IASetVertexBuffers(0, 1, &m_vertexBufferView);
```
->Modified struct in compute.hlsl

```
struct ModifiedIndirectCommand
{
	uint2 cbvAddress;	
	uint4 ibv;	
	uint4 drawArguments;
	uint drawArguments2;
	uint pad;
};
```

Above are the changes that I made in DX12ExecuteIndirect sample to recreate the issue. Code sets vertexbuffer view outside of Indirect args and sets indexbuffer view inside indirect args. I have #defined R32FORMAT which sets index buffer view to r32_uint and else sets to r16_uint. Also it sets indices values with UINT and uint16_t respectively. If you do this changes in sample and run it with r32format define, sample will work. But if you change r32format define to anything else, it will default to r16_uint and Dx12 won't render through execute indirect. However Dx12 will render in both formats if indexbuffer binding is not inside indirect args. You can check this by taking vertexbuffer inside indirect args and indexbuffer outside of indirect args.

Check and let me know if any further code is required.

**Comment by stanard** [comment]
I can't see anything wrong with your code nor the assumption that you should be able to specify the size of indices via an indirect command.  I wonder if this is a driver issue.  But--with respect--this is not an appropriate use of the DirectX-Graphics-Samples issue tracker.  If you are suggesting that one of the samples executes incorrectly on your system, we would appreciate if you submitted information about your environment such as graphics card, driver version, and Windows SDK.  It may be a known issue, your GPU architecture may be insufficient, or your Windows version may be too old (and it has since been fixed.)

**Comment by HasibuddinShaikh** [comment]
Hi,

Following are the information related to two systems on which I checked working of the sample. It didn't worked on both system. (with 16bit indices)

System -1

OS - Windows 10 Enterprise
Version - 1607
Build - 14393.2485
Graphics Card - Nvidia Quadro k620
Driver version - 391.33

System -2

OS - Windows 10 Pro
Version - 1709
Build - 16299.551
Graphics Card - Nvidia GTX 1060 - 6Gb
Driver version - 391.35

On both the system, I can see that Graphics Card 3d engine is working, but nothing gets displayed on the screen. So information does pass to graphics device and it does work, but it does not result in appropriate rendered output.

Let me know appropriate forum where I can register this issue or guide me to correct channel where I can register this.

**Comment by stanard** [comment]
There is gamedev.net, forum.beyond3d.com, developer.nvidia.com, etc.  I'm not sure if there is a public Microsoft dev forum.

But I should ask first, why are you using ExecuteIndirect, and do you need to use DirectX 12?  If you are not a AAA game developer, you would probably have an easier time with DirectX 11.  ExecuteIndirect is not available in 11, however.  ExecuteIndirect tends to be used for GPU-created commands such as when a shader is used to generate a mesh or do a series of computations.

**Comment by stanard** [comment]
Just found it:  http://www.directxtech.com/
