### ISSUE TITLE
Raytracing demos can only run on Fallback Layer with Nvidia RTX 2080

### ISSUE THREAD

**Issue by shurunxuan** [Microsoft/DirectX-Graphics-Samples#469]
I can successfully build and run the demos, but it can only run on Fallback Layer. The `D3D12EnableExperimentalFeatures` returns `E_NOINTERFACE`.

![image](https://user-images.githubusercontent.com/12070302/46241754-49745a80-c38c-11e8-88c6-5874c0d9a8a5.png)

I believe that there's something wrong with my environment, because I did see the same binaries running with hardware acceleration on another PC.

![image](https://user-images.githubusercontent.com/12070302/46241772-8dfff600-c38c-11e8-9a95-0c70f4423550.png)

My system info:
OS Build: 18247.1001
GPU: Nvidia RTX 2080
GPU Driver: 411.70
Visual Studio: 15.9.0
Windows SDK: 10.0.17134.0
DXR Binary: v1.3

**Comment by pkristof** [comment]
You're running on a skip-ahead OS build, which doesn't support the RS4 preview of the DXR runtime anymore. We are getting close to updating the Master with source that is compatible with the final DXR runtime, pending the launch of the upcoming retail OS update. Alternatively you can move back to RS4 with overlay and continue using v1.3 package until then.
