### ISSUE TITLE
Multithreading sample 

### ISSUE THREAD

**Issue by greatelk** [Microsoft/DirectX-Graphics-Samples#47]
this is a really minor error, when compiling from 
#define SINGLETHREADED FALSE 
to 
#define SINGLETHREADED TRUE

the reinterpret_cast<LPVOID>(i) fails with:

d3d12multithreading.cpp(698): error C2664: 'void D3D12Multithreading::WorkerThread(int)': cannot convert argument 1 from 'LPVOID' to 'int'

this is only for test purposes because i'm looking the performance hit of single threaded vs multi threaded command list generation

Regards

Marc

**Comment by bobbrow** [comment]
Thanks for letting me know.  I'll get a fix out soon.
