### ISSUE TITLE
Can't build on rev 476 due to 'Stale binaries detected...'

### ISSUE THREAD

**Issue by DrGr4f1x** [Microsoft/DirectX-Graphics-Samples#477]
I'm on the Win10 October update, latest WinSDK version, RTX 2080 hardware and current drivers, and I'm getting this build error: 
"Stale binaries detected, please grab the v1.5-dxr binaries from https://github.com/Microsoft/DirectX-Graphics-Samples/releases/tag/v1.5-dxr"

I do have those binaries in the D3D12Raytracing\tools\x64 directory.

**Comment by pkristof** [comment]
What does the version.txt in the tools\x64 folder say? It should be "1.5-dxr". How did you get the latest Master branch source? Is this a fresh clone or an update/pull over an existing clone you already had?

**Comment by DrGr4f1x** [comment]
This was updated over an existing clone, with 'git reset --hard origin/master'.  Version.txt says 1.3-dxr.  I edited that file to 1.5-dxr and can build now.  Thanks!
