### ISSUE TITLE
Framerate counter only goes down to 10

### ISSUE THREAD

**Issue by space928** [Microsoft/DirectX-Graphics-Samples#478]
When running really demanding scenes, where it takes longer than 100ms to render a frame, the frame rate  counter in the title bar of the window remains clamped at 10.0fps as can be seen in the follwoing example running at almost 2 fps:
![image](https://user-images.githubusercontent.com/15130114/46575347-1fd2b900-c9b4-11e8-904a-7d9f281d58f4.png)

**Comment by IgrauBezRuk** [comment]
It's raytracing example. Do you have a videocard, which support DXR? if not, then all raytracing is computed via fallback layer and low fps is expected.

**Comment by pkristof** [comment]
Hi,

the FPS clamping is due to StepTimer class setting it as such. You can adjust its m_qpcMaxDelta to change the clamp FPS limits.
