### ISSUE TITLE
Resizing swapchain with D3D11On12

### ISSUE THREAD

**Issue by Hlexyn** [Microsoft/DirectX-Graphics-Samples#48]
Sorry if I am missing something obvious, but I modified the 11On12 sample to respond to WM_SIZE messages. The problem I am having is that I always get this error message:

`DXGI ERROR: IDXGISwapChain::ResizeBuffers: Swapchain cannot be resized unless all outstanding buffer references have been released. [ MISCELLANEOUS ERROR #19: ]`

Here is the code:
```
void D3D1211on12::Resize(UINT width, UINT height)
{
	for(UINT n = 0; n < FrameCount; n++)
	{
		m_renderTargets[n].Reset();
		m_wrappedBackBuffers[n].Reset();
		m_d2dRenderTargets[n].Reset();
		m_commandAllocators[n].Reset();
	}

	m_d3d11DeviceContext->Flush();

	m_swapChain->ResizeBuffers(FrameCount, width, height, DXGI_FORMAT_R8G8B8A8_UNORM, 0);

	m_viewport.Width = static_cast<float>(width);
	m_viewport.Height = static_cast<float>(height);

	m_scissorRect.right = static_cast<LONG>(width);
	m_scissorRect.bottom = static_cast<LONG>(height);

	// Query the desktop's dpi settings, which will be used to create
	// D2D's render targets.
	float dpiX;
	float dpiY;
	m_d2dFactory->GetDesktopDpi(&dpiX, &dpiY);
	D2D1_BITMAP_PROPERTIES1 bitmapProperties = D2D1::BitmapProperties1(
		D2D1_BITMAP_OPTIONS_TARGET | D2D1_BITMAP_OPTIONS_CANNOT_DRAW,
		D2D1::PixelFormat(DXGI_FORMAT_UNKNOWN, D2D1_ALPHA_MODE_PREMULTIPLIED),
		dpiX,
		dpiY
		);

	// Create frame resources.
	{
		CD3DX12_CPU_DESCRIPTOR_HANDLE rtvHandle(m_rtvHeap->GetCPUDescriptorHandleForHeapStart());

		// Create a RTV, D2D render target, and a command allocator for each frame.
		for(UINT n = 0; n < FrameCount; n++)
		{
			ThrowIfFailed(m_swapChain->GetBuffer(n, IID_PPV_ARGS(&m_renderTargets[n])));
			m_d3d12Device->CreateRenderTargetView(m_renderTargets[n].Get(), nullptr, rtvHandle);

			// Create a wrapped 11On12 resource of this back buffer. Since we are 
			// rendering all D3D12 content first and then all D2D content, we specify 
			// the In resource state as RENDER_TARGET - because D3D12 will have last 
			// used it in this state - and the Out resource state as PRESENT. When 
			// ReleaseWrappedResources() is called on the 11On12 device, the resource 
			// will be transitioned to the PRESENT state.
			D3D11_RESOURCE_FLAGS d3d11Flags = { D3D11_BIND_RENDER_TARGET };
			ThrowIfFailed(m_d3d11On12Device->CreateWrappedResource(
				m_renderTargets[n].Get(),
				&d3d11Flags,
				D3D12_RESOURCE_STATE_RENDER_TARGET,
				D3D12_RESOURCE_STATE_PRESENT,
				IID_PPV_ARGS(&m_wrappedBackBuffers[n])
				));

			// Create a render target for D2D to draw directly to this back buffer.
			ComPtr<IDXGISurface> surface;
			ThrowIfFailed(m_wrappedBackBuffers[n].As(&surface));
			ThrowIfFailed(m_d2dDeviceContext->CreateBitmapFromDxgiSurface(
				surface.Get(),
				&bitmapProperties,
				&m_d2dRenderTargets[n]
				));

			rtvHandle.Offset(1, m_rtvDescriptorSize);

			ThrowIfFailed(m_d3d12Device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT, IID_PPV_ARGS(&m_commandAllocators[n])));
		}
	}
}
```

I've also tried destroying and recreating the swapchain, but I always get an exception at 

`ThrowIfFailed(System::GetDXGIFactory()->CreateSwapChain(m_commandQueue.Get(), &swapchainDesc, &swapchain));`

which returns

`E_ACCESSDENIED General access denied error.`

`Exception thrown at 0x767D3E28 in TestClient.exe: Microsoft C++ exception: _com_error at memory location 0x00ACEF80.`
`Exception thrown at 0x767D3E28 in TestClient.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.`
`Unhandled exception at 0x767D3E28 (KernelBase.dll) in TestClient.exe: 0xC000041D: An unhandled exception was encountered during a user callback.`

along with often making Visual Studio unresponsive. I also get the same error if I try to create multiple swapchains.

**Comment by bobbrow** [comment]
The error message means that you have not released all resources that hold a reference to the swap chain yet.  I think what you're missing here (I'd have to go back and check) is calling SetTarget(nullptr) on the D2D context to remove D2D's reference to the back buffer.  And you'll want to make sure you flush the GPU before releasing everything!  Use the WaitForGpu method at the beginning of your Resize method.

As for the other error, you can't have two swap chains referencing the same HWND at the same time.  Since your original swap chain is still alive, creating a new one that points to the same HWND results in the access denied error.

**Comment by Hlexyn** [comment]
Thank you, your help is very much appreciated. :)

**Comment by HanmingZhang** [comment]
Hey Hlexyn, not sure if you solve the issue or not.

What I found is that it seems CreateWrappedResource() did something weird and make the buffer references can't be released. I first comment out all d2d stuff, so no d2d reference and release  , and the problem still occurs @bobbrow. So the problem must be wrappedBackBuffers. But it's interesting though, wrappedBackBuffers[i].reset() is still not enough and it keeps telling me "Swapchain cannot be resized unless all outstanding buffer references have been released"

**Comment by renfenghuan** [comment]
I did what bobbrow said and the problem didn't get solved

**Comment by Ehobits** [comment]
I did what I said and found it was useless
Just create an _ID3D11Resource*_
Regardless of whether _.Reset()_
Will cause _ResizeBuffers()_ to return an invalid call, am I still missing important procedures?

**Comment by MattGuerrette** [comment]
@Ehobits For those wondering what the solution is, you need to also make sure you null out the ID3D11DeviceContext's views

The following is a snippet from https://github.com/microsoft/Windows-universal-samples/blob/main/Samples/Simple3DGameDX/cppwinrt/Common/DeviceResources.cpp

```
   // Clear the previous window size specific context.
    ID3D11RenderTargetView* nullViews[] = { nullptr };
    m_d3dContext->OMSetRenderTargets(ARRAYSIZE(nullViews), nullViews, nullptr);
    m_d3dRenderTargetView = nullptr;
    m_d3dRenderTargetViewRight = nullptr;
    m_d2dContext->SetTarget(nullptr);
    m_d2dTargetBitmap = nullptr;
    m_d2dTargetBitmapRight = nullptr;
    m_d3dDepthStencilView = nullptr;
    m_d3dContext->Flush();
```

For d3d11on12, you in particular need the first line, d2dContext->SetTarget(nullptr), and the last line to Flush the d3d11 context which should clear out the necessary references to those null'd out resources.

Hope this helps!
