### ISSUE TITLE
errors in d3dx12.h

### ISSUE THREAD

**Issue by John-Kangwa** [Microsoft/DirectX-Graphics-Samples#489]
Hey I am using your engine as a basis of learning. I am currently writing mine and getting a lot of useful information from the core. but I can't get it to run. I keep getting errors that are pointing to d3dx12. most errors point out that identifiers are undeclared

**Comment by pkristof** [comment]
Hi.

Is this on a fresh pull from Master branch (with miniengine building against 17763 SDK)?

**Comment by John-Kangwa** [comment]
Yes, is it possible to retarget to 17134 because I dont have the newer version at the moment and our internet is locally bad to download anything thanks

**Comment by pkristof** [comment]
Hi

You can find a 17134 compatible version in the 17134 release:
https://github.com/Microsoft/DirectX-Graphics-Samples/releases/tag/v10.0.17134.0.2.

**Comment by John-Kangwa** [comment]
Thank you for the time. Will try it out
