### ISSUE TITLE
RaytracingSimpleLighting: is index buffer incorrectly sized ?

### ISSUE THREAD

**Issue by fortgreeneVR** [Microsoft/DirectX-Graphics-Samples#494]
Hi, total newbie to D3D12, so forgive my inexperience

In this line in D3D12RaytracingSimpleLighting.cpp
`    
488: UINT descriptorIndexIB = CreateBufferSRV(&m_indexBuffer, sizeof(indices)/4, 0);
`
indices is an array of unsigned shorts, so 2 bytes per value. The number of elements in the array is passed in as its size divided by 4. This suggest 64 bit units. 
However CreateBufferSRV seems to indicate 32 bit. numElements is passed in as sizeof(indices)/4
`
    srvDesc.Buffer.NumElements = numElements;
    if (elementSize == 0)
    {
        srvDesc.Format = DXGI_FORMAT_R32_TYPELESS;
        srvDesc.Buffer.Flags = D3D12_BUFFER_SRV_FLAG_RAW;
        srvDesc.Buffer.StructureByteStride = 0;
    }
`
Does this miss-count the number by half or do I miss something?
Thanks.

**Comment by stanard** [comment]
A ByteAddressBuffer SRV is created with a ElementSize=0 and NumElements=number of 32-bit words, while a StructuredBuffer SRV is created with a ElementSize=sizeof(struct) and NumElements=ArrayCount.

**Comment by fortgreeneVR** [comment]
Got it, sizeof() gives the size in bytes, not in elements, that confused me.
Thanks!
