### ISSUE TITLE
I just downloaded the Body Gravity code from this repository and when trying to build I get that error. I am not deploying to a remote machine.

### ISSUE THREAD

**Issue by cgraphics** [microsoft/DirectX-Graphics-Samples#495]
"DEP6701: Bootstrapping failed with unexpected error: ArgumentException - The ID value is not specified.
Parameter name: id [0x80070057]	D3D12nBodyGravity"

Anyone else receive this error?

_Originally posted by @cgraphics in https://github.com/Microsoft/DirectX-Graphics-Samples/issue_comments#issuecomment-433181214_

**Comment by cgraphics** [comment]
I'm running this on an older machine. Will the samples from this project work with an Intel Q45/Q43 Express Chipset?
Please see the attached screenshots of my system settings and display settings from DXDIAG.
Any insight will be greatly appreciated.
![display_settings](https://user-images.githubusercontent.com/44477762/47527995-41abb700-d861-11e8-856a-b561fd4e525d.jpg)
![system_settings](https://user-images.githubusercontent.com/44477762/47527996-41abb700-d861-11e8-84b8-5f54c91a6f3f.jpg)


Thanks.

**Comment by cgraphics** [comment]
Looks like the supported feature level is the problem. DXDIAG shows only feature levels 9.1 and 10.  The Body Gravity code uses feature level 11.

**Comment by cgraphics** [comment]
I don't know much about WARP. If I use WARP and pass D3D_FEATURE_LEVEL_10 to CreateDevice I still have problems.

ThrowIfFailed(D3D12CreateDevice(
            warpAdapter.Get(),
            D3D_FEATURE_LEVEL_10_0,
			IID_PPV_ARGS(&m_device)
            ));

This code generates an error about an unexpected parameter.

**Comment by cgraphics** [comment]
Issue resolved.
The Body Gravity app now works with m_useWarpDevice set to 'true' and D3D_FEATURE_LEVEL_11_0.

**Comment by walbourn** [comment]
So the short answer is that you don't have DirectX 12 capable hardware. See [Intel's website](https://www.intel.com/content/www/us/en/support/articles/000005524/graphics-drivers.html).

Note that the minimum feature level for any existing DirectX 12 driver is Feature Level 11.0. As such, none of the samples request anything below that as the minimum.

**Comment by cgraphics** [comment]
> So the short answer is that you don't have DirectX 12 capable hardware. See [Intel's website](https://www.intel.com/content/www/us/en/support/articles/000005524/graphics-drivers.html).
> 
> Note that the minimum feature level for any existing DirectX 12 driver is Feature Level 11.0. As such, none of the samples request anything below that as the minimum.

Thanks. The samples work well with WARP enabled.
