### ISSUE TITLE
MiniEngine: D3D12 ERROR: ID3D12Device::CopyDescriptors: Source ranges and dest ranges overlap, which results in undefined behavior

### ISSUE THREAD

**Issue by jdswebb** [Microsoft/DirectX-Graphics-Samples#504]
Hi,

I see this error around 3 times per frame:

D3D12 ERROR: ID3D12Device::CopyDescriptors: Source ranges and dest ranges overlap, which results in undefined behavior. [ EXECUTION ERROR #653: COPY_DESCRIPTORS_INVALID_RANGES]
D3D12: **BREAK** enabled for the previous message, which was: [ ERROR EXECUTION #653: COPY_DESCRIPTORS_INVALID_RANGES ]

I am curious if it is safe to ignore?

Stack trace of the first occurrence:

`>	ModelViewer.exe!DynamicDescriptorHeap::DescriptorHandleCache::CopyAndBindStaleTables(D3D12_DESCRIPTOR_HEAP_TYPE Type, unsigned int DescriptorSize, DescriptorHandle DestHandleStart, ID3D12GraphicsCommandList * CmdList, void(ID3D12GraphicsCommandList::*)(unsigned int, D3D12_GPU_DESCRIPTOR_HANDLE) SetFunc) Line 247	C++
 	ModelViewer.exe!DynamicDescriptorHeap::CopyAndBindStagedTables(DynamicDescriptorHeap::DescriptorHandleCache & HandleCache, ID3D12GraphicsCommandList * CmdList, void(ID3D12GraphicsCommandList::*)(unsigned int, D3D12_GPU_DESCRIPTOR_HANDLE) SetFunc) Line 263	C++
 	ModelViewer.exe!DynamicDescriptorHeap::CommitGraphicsRootDescriptorTables(ID3D12GraphicsCommandList * CmdList) Line 73	C++
 	ModelViewer.exe!GraphicsContext::DrawIndexedInstanced(unsigned int IndexCountPerInstance, unsigned int InstanceCount, unsigned int StartIndexLocation, int BaseVertexLocation, unsigned int StartInstanceLocation) Line 703	C++
 	ModelViewer.exe!GraphicsContext::DrawIndexed(unsigned int IndexCount, unsigned int StartIndexLocation, int BaseVertexLocation) Line 687	C++
 	ModelViewer.exe!ModelViewer::RenderObjects(GraphicsContext & gfxContext, const Math::Matrix4 & ViewProjMat, ModelViewer::eObjectFilter Filter) Line 345	C++
 	ModelViewer.exe!ModelViewer::RenderLightShadows(GraphicsContext & gfxContext) Line 365	C++
 	ModelViewer.exe!ModelViewer::RenderScene() Line 440	C++
 	ModelViewer.exe!GameCore::UpdateApplication(GameCore::IGameApp & game) Line 75	C++
 	ModelViewer.exe!GameCore::RunApplication(GameCore::IGameApp & app, const wchar_t * className) Line 356	C++
 	ModelViewer.exe!wmain(int argc, wchar_t * * argv) Line 106	C++`

Thanks

**Comment by pkristof** [comment]
This is known to be an issue in validation layer if you're using Shader Model 6.3 or the driver is opting into it by default (which recent NV drivers are). In that case or if you made no changes to the source code that would trigger this then you can ignore it.
