### ISSUE TITLE
ModelViewer is not building because D3D12_RENDER_PASS_ENDING_ACCESS_RESOLVE_PARAMETERS not found

### ISSUE THREAD

**Issue by IgrauBezRuk** [Microsoft/DirectX-Graphics-Samples#507]
In d3dx12.h from line 2657 compiler can't find next things
D3D12_RENDER_PASS_ENDING_ACCESS_RESOLVE_PARAMETERS
D3D12_RENDER_PASS_BEGINNING_ACCESS_CLEAR_PARAMETERS
D3D12_RENDER_PASS_BEGINNING_ACCESS
D3D12_RENDER_PASS_BEGINNING_ACCESS_TYPE_CLEAR
D3D12_RENDER_PASS_RENDER_TARGET_DESC and some more. 
Everything before this lines is okay. Whats can be a problem here?

**Comment by walbourn** [comment]
Those types require that you build with Windows 10 SDK (17763), which is what the latest version of ``d3dx12.h`` assumes.
