### ISSUE TITLE
 PIX event name not show up in GPU usage

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#51]
For ModelViewer sample, even with PIXBeginEvent(...) get called in the right place, GPUusage panel only shows unknown for evey events. Does the pix stuff not working currently?

**Comment by bobbrow** [comment]
GPU Usage support for DirectX12 won't be available until Visual Studio 2015 Update 1 is released (which is actually coming up real soon).

If you don't want to wait for the official release, you are welcome to install the [Release Candidate](http://www.microsoft.com/en-us/download/details.aspx?id=49537) which should be pretty close to the official release.
