### ISSUE TITLE
Validation layer does not check CBV alignment

### ISSUE THREAD

**Issue by sherief** [Microsoft/DirectX-Graphics-Samples#510]
I'm running on Win10 RS5 (Version 1809, Build 17763.134) and when I call SetGraphicsRootConstantBufferView() with a GPU virtual address that is not 256 byte aligned, with the debug SDK layer on, the device only gets removed on some hardware - for example, on my dual GPU laptop, the device gets removed if I'm running on the NVIDIA Pascal GPU, but not if I'm running on the Intel integrated GPU. 

I think the SDK debug layer should check for alignment regardless of the underlying device. The 256B alignment is not an exposed, query-able value, so all D3D12 code is expected to always pass 256B aligned GPU VAs here. The debug layer only checking for this on some hardware can lead to cases of "It Runs On My Machine", with the alternative being more QA workload everywhere. 

I think the !/$ for this low hanging fruit is quite high.

**Comment by pkristof** [comment]
Hello,

Closing as this is not a sample related issue. For platform or tools specific issues or requests, I'd recommend you to to directxtech.com.

Best
Peter

**Comment by sherief** [comment]
Neither my circus nor my monkeys, I'll just add the check in my own code and everyone else in the D3D12 ecosystem will have to deal with it. 

What's your manager's email @ Microsoft? I'd love to explain to her / him how terrible of an idea it is to make people jump through more hoops instead of just filing a bug internally.

**Comment by sherief** [comment]
I can reproduce this today using this line:
`CommandList->SetGraphicsRootConstantBufferView(2, Vidmem);`

When running on an NVIDIA GTX 1060 with the debug layer on, I get this output:

"D3D12 ERROR: ID3D12CommandList::SetGraphicsRootConstantBufferView: Pointer 10840178692 is incorrectly aligned.  Device requires alignment be a multiple of 256. [ EXECUTION ERROR #710: SET_ROOT_CONSTANT_BUFFER_VIEW_INVALID]
D3D12: Removing Device."

Same code running on an Intel GPU (actually, same exact MSHybrid system) works just fine, no complaints from debug layer or driver.

Windows Version 1809, Build 17763.253

**Comment by billkris-ms** [comment]
Thanks sherief.  Your example command line doesn't specify the value of parameter 'Vidmem', but I assume this is being deliberately set to something other than the buffer base VA + n * 256?  It would be interesting to know how Vidmem is being initialized, and also what the base VA of the associated buffer is for each device.  In any case, I'll experiment with similar Intel and Nvidia devices.
