### ISSUE TITLE
MiniEngine on WinRT?

### ISSUE THREAD

**Issue by Zwaliebaba** [microsoft/DirectX-Graphics-Samples#514]
Hi.

Are there any plans to migrate MiniEngine to WinRT?

Thanks!

**Comment by stanard** [comment]
MiniEngine has a private branch containing Xbox One support.  Xbox One games require some amount of WinRT to interact with OS functionality.  There was consideration for maintaining WinRT and adding support for UWP on Windows, but that's not currently a priority.  Some people have successfully added UWP support to their forks, but I'm not sure what all needs to be changed.
