### ISSUE TITLE
ExecuteIndirect DispatchRays

### ISSUE THREAD

**Issue by Nielsbishere** [Microsoft/DirectX-Graphics-Samples#516]
The ID3D12GraphicsCommandList4 documentation states: 
```cpp
typedef struct D3D12_DISPATCH_RAYS_DESC {
  D3D12_GPU_VIRTUAL_ADDRESS_RANGE            RayGenerationShaderRecord;
  D3D12_GPU_VIRTUAL_ADDRESS_RANGE_AND_STRIDE MissShaderTable;
  D3D12_GPU_VIRTUAL_ADDRESS_RANGE_AND_STRIDE HitGroupTable;
  D3D12_GPU_VIRTUAL_ADDRESS_RANGE_AND_STRIDE CallableShaderTable;
  UINT                                       Width;
  UINT                                       Height;
  UINT                                       Depth;
} D3D12_DISPATCH_RAYS_DESC;

void DispatchRays(
  const D3D12_DISPATCH_RAYS_DESC *pDesc
);
```
This could pose a problem, as it requires you to know how many rays you're going to dispatch on the CPU. This means that you can't use a compute shader that calculates all pixels that require shading and dispatch rays for those (without a CPU stall). I'd request adding functionality for DispatchRays to ExecuteIndirect or adding DispatchRaysIndirect, which takes a GPU buffer and reads 3 uints from it. 
Adding this would allow for a lot of optimization, meaning you would only have to dispatch rays that are required (without wasting other RT cores on a raygen shader that doesn't do anything for those threads). 

I see that this is already brought up at the [DXR roadmap](https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/Libraries/D3D12RaytracingFallback/developerguide.md#roadmap), but I didn't see any issues or forum posts about this. Any idea if this might be implemented and at what time?

**Comment by pkristof** [comment]
Hi,

Thanks for the feedback. This is on our roadmap, but unfortunately not something we could do for the v1 of the DXR API. We don't have a specific date when this will be make into the API to announce at this time. Outside the documentation, [Raytracing page on DirectXTech](forums.directxtech.com/index.php?board=248.0
) is a good place to keep track of for API specification discussions or provide other API feedback.

Best
