### ISSUE TITLE
d3dx12.h: CD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT assigment operator does not initialize all members

### ISSUE THREAD

**Issue by snickerbockers** [microsoft/DirectX-Graphics-Samples#520]
https://github.com/Microsoft/DirectX-Graphics-Samples/blob/878cdf5941fc77cae7d7b1f986bcd13634a4870b/Libraries/D3DX12/d3dx12.h#L2183

This assignment operator does not initialize the _Type member.  This can lead to undefined behavior for users who dynamically allocate memory for pipeline state streams.

For example, in the following code snippet the value of _Type will be undefined:

```
uint8_t *stream = new uint8_t[LENGTH_OF_STREAM];
*reinterpret_cast<CD3DX12_PIPELINE_STATE_STREAM_ROOT_SIGNATURE*>(stream) = CD3DX12_PIPELINE_STATE_STREAM_ROOT_SIGNATURE(stub->pRootSignature);
```

**Comment by sebmerry** [comment]
@snickerbockers  @walbourn  thank you! This fix has been merged.
