### ISSUE TITLE
Does anybody know whether the graphics card version problem get any new progress？

### ISSUE THREAD

**Issue by wojun** [microsoft/DirectX-Graphics-Samples#521]
Hi,Mr. @pkristof :
Thank you for your kind cooperation.
Now we have a project that need to use ray tracing technique，everything is ok on RTX graphics card except when we work on fallback layer，there is a odd problem with graphics card driver version.
The same question is appearing in this issue:https://github.com/Microsoft/DirectX-Graphics-Samples/issues/475
and finally the problem is worked out by degrading the graphs card driver from any version newer than 398.82 to 398.82，and you added this question to the limition of README.
So I wanna that do you or your team get some good news  @in fixing this problem?  how can we do in fixing this problem without degrading driver version?
thank you and hope your reply!

**Comment by wojun** [comment]
@stanard  sorry for disturbing you,but can you help me?thank you!

**Comment by pkristof** [comment]
Hello,

NVIDIA is aware of the issue, but there's no update yet.

**Comment by pkristof** [comment]
Closing the issue as FallbackLayer is deprecated as per https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Libraries/D3D12RaytracingFallback#d3d12-raytracing-fallback-layer
