### ISSUE TITLE
Direct3DRaytracing sample doesnt work in VS2017

### ISSUE THREAD

**Issue by erikmartinessanches** [microsoft/DirectX-Graphics-Samples#525]
I'm using a  Macbook Pro Retina mid 2014 (booted into Windows) and VS version 15.9.5 and Windows 10 Edu 1803.

![image](https://user-images.githubusercontent.com/4912935/51964340-7fbf0500-2466-11e9-94b1-27a4a083ed98.png)

**Comment by pkristof** [comment]
Hi,

It looks like you're missing DirectX Raytracing binaries. See the raytracing sample [requirements](https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12Raytracing/readme.md#requirements) section for link to the latest.

**Comment by ValZapod** [comment]
@erikm You should use 1809 windows not 1803, just update it.

**Comment by pkristof** [comment]
DXR samples now work under 2017
