### ISSUE TITLE
Invalid shadermodel/shadertype values when running D3D12Raytracing samples

### ISSUE THREAD

**Issue by Kuchinawa** [Microsoft/DirectX-Graphics-Samples#526]
When trying to run the D3D12Raytracing samples I get the following errors:
![image](https://user-images.githubusercontent.com/2980339/52343820-74954780-2a19-11e9-8087-b3e55eabf421.png)

I have updated the windowsSDK to 10.0.17763, added the lastest binaries (1.5-dxr), updated windows to version 1809, and updated my nvidia (GTX1080) drivers to the lastest version (418.81). But the problem still persists, even on a fresh download of the master branch. What am I missing?

**Comment by pkristof** [comment]
You also need an updated Visual Studio - version 15.8.4 or higher as per https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12Raytracing/readme.md#requirements.

**Comment by Kuchinawa** [comment]
Thank you! Figured it was something obvious like that..
