### ISSUE TITLE
Question/Request: Trace rays stalls

### ISSUE THREAD

**Issue by Nielsbishere** [Microsoft/DirectX-Graphics-Samples#529]
Hello, I was wondering about how trace rays stalls the raygen (or other ray tracing) shaders. Does the driver batch the trace rays, even if there are sequential ones?

Consider the following pseudo code:
[raygen]
foreach light in lights
 trace shadow
 lightResult += doLighting(light) * shadow

My guess is that the code above will stall the raygen until the first shadow ray is traced, then it will return the result and continue with the code (resulting into another shadow ray). Is this assumption correct? Or does the driver batch the trace shadows and then use those results in the foreach?
If it doesn't, maybe it's an idea to be able to use TraceRay with an array of rays, to allow batching them beforehand, and then returning a Payload[]. This might increase performance quite a lot, if it isn't implemented already.

Thank you :+1:

**Comment by pkristof** [comment]
TraceRay serialization / parallelization rules are not explicitly called out in the current DXR specification. We will tighten the spec on this in a future update. For now, you can assume serial behavior as far as Ray payload data visibility passed in and out of TraceRay go, but there’s no guaranteed ordering of side effects such as UAV writes between the caller and a TraceRay or among subsequent TraceRay calls. 

Best,
Peter
