### ISSUE TITLE
passing macro def to D3DCompileFromFile causes access violation error

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#53]
Hi

I am wondering whether dx12 D3DCompileFromFile function work with passing in macro def?  I have the following code not working (crash at that point)

D3D_SHADER_MACRO macroDef[1] = { "COMPUTESHADER", "1" };

VRET( CompileShaderFromFile( GetAssetFullPath( _T( "VolumetricAnimation_shader.hlsl" ) ).c_str(), macroDef, D3D_COMPILE_STANDARD_FILE_INCLUDE, "vsmain", "vs_5_0", compileFlags, 0, &vertexShader ) );

Similar code work in dx11, and the D3D_SHADER_MACRO usage is exactly like the msdn. So does dx12 uses different way to pass in macro def? or there are other flag I have to set to achieve that?

Thanks

**Comment by bobbrow** [comment]
macroDef needs to be NULL terminated since ```D3DCompileFromFile``` does not accept a "size" parameter to describe this array.

Try:
```
D3D_SHADER_MACRO macroDef[] = { "COMPUTESHADER", "1", nullptr, nullptr };
```

**Comment by bobbrow** [comment]
Looking at the MSDN documentation for ```D3D_SHADER_MACRO```, it seems a bit misleading.  I'll file a bug to get that page updated.

**Comment by pengliu916** [comment]
Thanks for the clarification, hoep the msdn doc will be updated more frequently
