### ISSUE TITLE
NuGet package "zlib-vc140-static-64" missing for project "MiniEngine/ModelViewer"

### ISSUE THREAD

**Issue by abhishekaroragamedev** [microsoft/DirectX-Graphics-Samples#533]
Issue:
On a fresh fork of the MiniEngine/ModelViewer project, the build fails owing to a missing NuGet package: "zlib-vc140-static-64" for the project. Running this project is the suggested starting step in the MiniEngine ReadMe, and can thus be blocked initially.

Repro steps:
1. Fork the repository and clone to desktop.
2. Open MiniEngine/ModelViewer/ModelViewer.sln
3. Rebuild Solution
---> Build fails owing to missing NuGet package

Workaround:
Copying the Packages/ folder generated by NuGet packages from the repository root to the MiniEngine/ folder, as the ModelViewer project looks for it there.

**Comment by stanard** [comment]
Which version of Visual Studio are you using?

**Comment by abhishekaroragamedev** [comment]
Thanks for the prompt reply! This is in VS17.

**Comment by stanard** [comment]
I wiped my Packages folder (in the root of DirectX-Graphics-Samples), and I got the same error.  To fix this, you need to download the needed NuGet packages.  Go to "Tools->NuGet Package Manager->Manage NuGet Packages for Solution..."

It will tell you that you are missing packages and to click the "Restore" button in the upper right to download them.

I thought Visual Studio downloaded packages automatically if they were needed by the Solution, but maybe they changed it.  Sorry!

-James

**Comment by abhishekaroragamedev** [comment]
Strangely enough, I did try hitting the Restore button in this case, and it didn't work, which was why I tried the workaround I mentioned. Maybe that's something up with my own VS instance. But that's okay, since I have it working now!
The only thing I'd recommend in this case is a small side note in the MiniEngine readme, if possible. Thank you for being so prompt!

**Comment by hermestrimegistus** [comment]
@abhishekaroragamedev Workaround:
Copying the Packages/ folder generated by NuGet packages from the repository root to the MiniEngine/ folder, as the ModelViewer project looks for it there.
Didn't work out for me. 
@stanard I tried deleting and restoring. This too didn't work out. Can someone help?

**Comment by hermestrimegistus** [comment]
Hi All, @abhishekaroragamedev's workaround will work but somehow the ../Packages/WinPixEventRuntime.1.0.180612001 or ../Packages/zlib-vc140-static-64.1.2.11 path name is different as referred in VS. For WinPixEventRuntime It complains about WinPixEventRuntime.1.0.180612001 but the real folder is WinPixEventRuntime.1.0.181206001

**Comment by stanard** [comment]
I just pushed what I hope fixes the path and version issues.  The NuGet Packages folder lies in the root of the repo, which is ../../Packages relative to the MiniEngine projects.  We had some path confusion where it was assumed Packages were in the MiniEngine folder.  Also, I updated PIX from 1806 (June '18) to 1812 (Dec. '18).
