### ISSUE TITLE
Failed to pull Fallbacklayer to an existing project.

### ISSUE THREAD

**Issue by AlexHonor** [microsoft/DirectX-Graphics-Samples#539]
Hi! I have an existing project and I am trying to use Fallbacklayer in it. I have taken the D3D12RaytracingHelloWorld sample(Which in the original project works fine on my PC) and copied all of the files to this existing project.  Also I have gone through the project properties and configured everything the same way as this sample did(Imported the PIX NuGet as well). But running the exact same code as in the sample throws an exception dropping the following into the console:
```
D3D12 ERROR: ID3D12Device::CreateUnorderedAccessView: Specified CPU descriptor handle ptr=0x000001B546C7A830 does not refer to a location in a descriptor heap.  [ EXECUTION ERROR #646: INVALID_DESCRIPTOR_HANDLE]
D3D12: **BREAK** enabled for the previous message, which was: [ ERROR EXECUTION #646: INVALID_DESCRIPTOR_HANDLE ]
```
The error is happening in D3D12RaytracingHelloWorld.cpp at line 908. I have no clue of why it might happen on the identical code. I would appreciate any help!

**Comment by pkristof** [comment]
Closing the issue as FallbackLayer is deprecated as per https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Libraries/D3D12RaytracingFallback#d3d12-raytracing-fallback-layer
