### ISSUE TITLE
Unable to enable d3d12 debug validation layer for new win10 update 10586

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#54]
As descried in title after the new windows 10 update, the validation layer cannot be enabled. Is it have something to do with the fact that the sln target platform version is still 10.0.10240.0?

**Comment by bobbrow** [comment]
No, this shouldn't have anything to do with your SDK version.  The debug layer doesn't ship with the SDK anymore (though the headers still do...).

Check your c:\windows\system32 folder for d3d12SDKLayers.dll.  If it's not there, try reinstalling the Graphics Tools optional feature using the "Manage Optional Features" page in the Settings app.

**Comment by zao** [comment]
One of the features that people on the Insider builds have enjoyed for a long while is that an Windows "upgrade" like 10586 gets rid of a lot of things. Among these are NVidia OpenCL driver components, any features like Graphics Tools, and assorted settings all over the place.

**Comment by pengliu916** [comment]
hum.... yep, it seems after windows update the Graphics Tools get uninstalled, reinstall it fix that problem, many thanks

**Comment by MattTree** [comment]
This worked for me in 2021. Thank you bobbrow.
