### ISSUE TITLE
GPU/CPU synchronization

### ISSUE THREAD

**Issue by simco50** [microsoft/DirectX-Graphics-Samples#540]
Hi,
I've been looking at the MiniEngine for a while now and there is one high level concept in the codebase I don't quite understand yet. I've found a similar Issue about this posted here before (https://github.com/Microsoft/DirectX-Graphics-Samples/issues/105) but it's not entirely clear to me yet.
According to the answer in that thread, when calling Present, the driver will internally stall the CPU if it is too many frames ahead (depending on how many swapchain buffers there are)

This raised two questions for me:

1. I saw the CPU gets stalled every frame during the profiling in ```GpuTimeManager::BeginReadBack();``` (Line 99 in GpuTimeManager.cpp)
So this will make the CPU wait for the whole previous frame to be finished by the GPU if I'm not mistaken?
If I remove the ```EngineProfiling::Update``` call, the application crashes because it runs out of memory. It seems like the whole application relies on that CPU stall?

2. In the HelloFrameBuffering sample in this repository, there is a mechanism that stalls the CPU until the upcoming frame is ready to be used to queue work on. I've done something similar to that in my project but it doesn't seem to be present in the MiniEngine. This conflicts with the answer on the issue (https://github.com/Microsoft/DirectX-Graphics-Samples/issues/105) because if there would be a CPU stall internally by Present, this wouldn't be necessary right?

Thanks in advance!
Simon

**Comment by stanard** [comment]
Apologies for the slow response.  Sunday morning must be a bad time to get my attention.  This question slipped my mind until I was digging through a week's worth of email.  :-)

1) The first thing BeginReadBack() does is wait for the previous readback to have completed.  This keeps the CPU & GPU in sync but one frame apart.

2) The mechanism that stalls the CPU w.r.t. Present is that a command list cannot be executed which draws to the currently displayed swap chain buffer.  This keeps the CPU from trying to buffer up multiple frames of rendering while the GPU struggles to keep up.  If you want the CPU to get that much farther ahead, you can triple or quadruple buffer your swap chain.  This is good for when your GPU perf is really close to the target frame rate or when you have occasional spikes in GPU time that you want to soak up.  But the deeper the swap chain, the more latency is introduced from input to display.

**Comment by simco50** [comment]
Hi,

Thanks a lot for the answer!
I understand it now. Does that then confirm my suspicions that the CPU wait in the HelloFrameBuffering sample is redundant? Because the Present call will stall the CPU anyway?

Thanks
Simon

**Comment by stanard** [comment]
Hi Simon,

I didn't write any of other the samples, but I took a look at that one.  It looks like the extra synchronization is not to guard the swap chain but instead to make sure the command allocator can be reused.  This sample uses double buffering of resources, and you can't start reusing a command allocator until the previously allocated commands have completed.  The present synchronization I referred to protects the GPU from drawing to the front buffer.  This synchronization protects yet-to-be-executed commands from being overwritten.  A more efficient (and lock-free) way to implement this protection is to use more command allocators.  You probably only need FrameCount+1 allocators to be safe.

Cheers,
James

**Comment by simco50** [comment]
> It looks like the extra synchronization is not to guard the swap chain but instead to make sure the command allocator can be reused. 

Ohhh of course, I've always been looking at it the wrong way, now it makes total sense!
Thanks a lot for the answers, it's super helpful.
