### ISSUE TITLE
Some HLSL system value intrinsics don't work with D3D12RaytracingFallback

### ISSUE THREAD

**Issue by StarsX** [microsoft/DirectX-Graphics-Samples#542]
Anyone who also noticed the same problems? Some raytracing HLSL system value intrinsics don't work normally:
1. DispatchRaysIndex().z and DispatchRaysDimensions().z return wrong values, when using dispatchRays() with D3D12_DISPATCH_RAYS_DESC::Depth > 1.
2. The transform intrinsics, such as ObjectToWorld4x3(), return wrong values.

The problematic intrinsics above work well on DXR hardware devices (I can get the expected results).

**Comment by pkristof** [comment]
Closing the issue as FallbackLayer is deprecated as per https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Libraries/D3D12RaytracingFallback#d3d12-raytracing-fallback-layer
