### ISSUE TITLE
VS 2019

### ISSUE THREAD

**Issue by bobbrow** [microsoft/DirectX-Graphics-Samples#543]
When upgrading samples to VS 2019 and the v142 toolset, DXSampleHelper.h has a compilation error.  STL headers have been refactored in the v142 toolset, and DXSampleHelper.h takes an impicit dependency on the `stdexcept` header.  This header was previously being included by other STL headers, but has been factored out in v142.

Can you please add `#include <stdexcept>` to all copies of DXSampleHelper.h?  This will ensure your customers can use the samples with Visual Studio 2019.

Thank you!

**Comment by pkristof** [comment]
Thanks Bob, this has been added into Master.
