### ISSUE TITLE
D3D12nBodyGravity doesn't work on Xbox one

### ISSUE THREAD

**Issue by jamesic** [microsoft/DirectX-Graphics-Samples#544]
The sample app is not working on Xbox one. Below is the error message I encountered.

Unhandled exception at 0x00007FFB5B64AFAC (ucrtbased.dll) in D3D12nBodyGravity.exe: An invalid parameter was passed to a function that considers invalid parameters fatal. occurred

However, it works on Windows 10. I thought Xbox one supports DirectX 12 as well.

**Comment by walbourn** [comment]
[UWP on Xbox One](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/) does support DirectX 12, but only if you enable Game mode. See [this blog post](https://walbourn.github.io/directx-and-uwp-on-xbox-one/).
