### ISSUE TITLE
MiniEngine missing WinPixEventRuntime dll

### ISSUE THREAD

**Issue by tan-90** [microsoft/DirectX-Graphics-Samples#547]
When trying to run the Model Viewer after a successful build it terminates with an error message saying the system is missing WinPixEventRuntime.dll.

WinPixEventRuntime v1.0.190510001 is installed (using the NuGet package manager from Visual Studio.

I'm running Visual Studio 2019 Comunity, and the solution was retargeted to MSVC v142 and Windows 10 SDK v10.0.17763.0

**Comment by sauparna** [comment]
This has got to do with the build configurations. If you build your project in release mode, by switching to `Release` from the drop-down menu at the top-bar of Visual Studio's UI

![Screenshot (1)](https://user-images.githubusercontent.com/91951/59119955-6563cf00-8911-11e9-9cb2-0e3e3ca3b1af.png)

then the built exe runs fine; you get to see the 3D scene rendered in a window.

The `ModelViewer.exe` generated when the solution is built resides in two places, depending on the type of build:

```
DirectX-Graphics-Samples\MiniEngine\Build_VS15\x64\Release\Output\ModelViewer\ModelViewer.exe
DirectX-Graphics-Samples\MiniEngine\Build_VS15\x64\Debug\Output\ModelViewer\ModelViewer.exe
```

To make the debug exe work (which is run when you hit F5 or Ctrl+F5), copy the DLL file from inside PIX's package directory from here

```
DirectX-Graphics-Samples\Packages\WinPixEventRuntime.1.0.180612001\bin\WinPixEventRuntime.dll
```
and put it in the directory where the debug version of `ModelViewer.exe` is.

There must be a better answer; the DLL from the `WinPixEventRuntime` NuGet package should be picked up by `Debug` too if `Release` can find it, but I am still finding my way around Visual Studio configuration.

**Comment by tan-90** [comment]
My solution was to manually download the NuGet package to get the DLL, but I'm also unsure as to why the package isn't working on a debug build.
