### ISSUE TITLE
CreateEvent returns NULL, not INVALID_HANDLE_VALUE on failure.

### ISSUE THREAD

**Issue by Taylor-Hasterd** [microsoft/DirectX-Graphics-Samples#549]
In CommandListManager.cpp, line 84-85, the code is:
`    m_FenceEventHandle = CreateEvent(nullptr, false, false, nullptr);
    ASSERT(m_FenceEventHandle != INVALID_HANDLE_VALUE);`

However, according to MSDN, the return value of CreateEvent is

> If the function succeeds, the return value is a handle to the event object. If the named event object existed before the function call, the function returns a handle to the existing object and GetLastError returns ERROR_ALREADY_EXISTS.
If the function fails, the return value is NULL. To get extended error information, call GetLastError.

So it should be
`ASSERT(m_FenceEventHandle != NULL);`

**Comment by stanard** [comment]
Thanks for pointing that out.  I'll make the change in the various places I've propagated the mistake and try to push a fix soon, though I'd also accept a pull request.

**Comment by walbourn** [comment]
There a nice blog post on why some Win32 functions return ``INVALID_HANDLE_VALUE`` and others return ``NULL``. See [Why are HANDLE return values so inconsistent?](https://devblogs.microsoft.com/oldnewthing/?p=40443)

Personally I use these helpers when dealing with Win32 functions:

```
struct handle_closer { void operator()(HANDLE h) { assert(h != INVALID_HANDLE_VALUE); if (h) CloseHandle(h); } };

typedef std::unique_ptr<void, handle_closer> ScopedHandle;

inline HANDLE safe_handle(HANDLE h) { return (h == INVALID_HANDLE_VALUE) ? nullptr : h; }
```

and use ``safe_handle`` as a wrapper around the Win32 function call to ensure errors are always null. I've confirmed that there is no *valid* handle that is 0.

**Comment by weltkante** [comment]
> I've confirmed that there is no valid handle that is 0.

Its explained in the linked article, but I think its worth spelling out that the reverse is not true, i.e. the constant `INVALID_HANDLE_VALUE` is actually a valid handle in some contexts because it has the same numerical value as `GetCurrentProcess()` returns. So normalizing to `INVALID_HANDLE_VALUE` is not an option, you can only normalize to null/zero.
