### ISSUE TITLE
Is it will be more efficient if GpuTimeManager buffer is D3D12_HEAP_TYPE_DEFAULT instead of D3D12_HEAP_TYPE_READBACK?

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#55]
Like recommend by msdn, will it be more efficient if we use D3D12_HEAP_TYPE_DEFAULT for GpuTimeManager buffer to record all timestamp every frame and later use an other readback buffer to read the data in a lower frequency though like DMA engine asycnly?

**Comment by bobbrow** [comment]
Yes, this could possibly be more efficient (we'd have to test it out and measure the results).  But if you plan to read back at a lower frequency anyway, you could omit the DEFAULT heap and just Resolve the queries and Map the buffer less frequently to avoid the hassle of copying from a DEFAULT heap to a READBACK heap.  Resolving and Mapping larger blocks of data is more efficient than reading back every query immediately.

Can you link to the MSDN page you referenced?  I'm having trouble locating the recommendation you're talking about.

**Comment by pengliu916** [comment]
I try to find the page where it mentioned about using DEFAULT instead of others types, but since it's long time ago, I couldn't find neither. But I just wondering: if we just render GPU timing data as bar chart we can kick CPU out of the loop, so can we just use DEFAULT heap for store gputimestamp data, then use PS to render the graph(even the fonts)? No CPU read anymore. which should be the most performant way of doing GPU profiling.

**Comment by bobbrow** [comment]
Certainly, if you're able to consume the timing data in a way that's meaningful to you without reading it back onto the CPU, then a READBACK heap is unnecessary.
