### ISSUE TITLE
Pre-processing to move all global shader parameter to a constant buffer caused assertion error 

### ISSUE THREAD

**Issue by moshuiyi** [microsoft/DirectX-Graphics-Samples#551]
Engine to be integrated does a pre-process to move all global shader parameter to a constant buffer named "_RootShaderParameters". This caused there are more than one constant buffers which have same name but with different members in raytracing pipeline object. Looks like the fallback compiler can't handle this case correctly. 

Urgent for our project. Thanks a lot!

![exception](https://user-images.githubusercontent.com/17527296/60108362-0e784980-979b-11e9-834c-ff8c355f459f.PNG)

**Comment by pkristof** [comment]
Hi Moshuiyi,

I'm afraid we won't be able to address your issue as the Raytracing Fallback Layer is not under active development as per its [documentation](https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Libraries/D3D12RaytracingFallback#d3d12-raytracing-fallback-layer). Both Fallback Layer library and the Fallaback Layer compiler source is available online should you wish to investigate the issue.

Best
