### ISSUE TITLE
RTX 2060 fallbackLayer error BitonicPreSortCS.hlsl : could not unroll loop

### ISSUE THREAD

**Issue by GeorgePsom** [microsoft/DirectX-Graphics-Samples#555]
I have latest drivers, windows version 10 (1803) and i cant seem to run any sample and it gives me the error of the title. I can't also run the Nvidia's samples which don't have fallbackLayer and it brings me this message : D3D12CreateDevice(pAdapter,D3D_FEATURE_LEVEL_12_0, IID_PPV_ARGS(&pDevice))
Error! No such interface supported

**Comment by GeorgePsom** [comment]
One update: it seems that it happens the same for 2080ti but if  i retarget to 10.0.18362.0 and later for 10.0.17763.0 it works without issue

**Comment by pkristof** [comment]
Hi,

software setups that don't support DXR will fail the create device call. You should upgrade to the latest Windows update (v1903/build18362 or at least v1809/build17763) and use the native driver based support for DXR.

**Comment by GeorgePsom** [comment]
ok i updated to windows v1903 i retargeted the solution and i still get the same error and when i build it in v1803 it didnt run in DXR but in FL and when i was pressing the button 3 to change to DXR it wouldnt work. This happens in 2060ti

**Comment by GeorgePsom** [comment]
it seems the compilation error is in fallback layer, btw the dxr samples from nvidia now work and don't pop up error messages like :"D3D12CreateDevice(pAdapter,D3D_FEATURE_LEVEL_12_0, IID_PPV_ARGS(&pDevice))
Error! No such interface supported"
How can i use the native dxr support without compiling the fl

**Comment by pkristof** [comment]
This has been fixed in the Develop branch. Note: integration of the deprecated Fallback Layer has been removed from the samples.

Thanks for bringing the issue up!

**Comment by GeorgePsom** [comment]
I compiled and run the develop branch without compilation errors, however i get a strange z-buffer test fail at the procedural geometry sample at the analytic spheres

**Comment by pkristof** [comment]
Thanks for spotting that. It appears there is a compilation issue when using for loop in RaySpheresIntersectionTest() and compiling under Debug. If you manually expand the loop or build under Release, it doesn’t repro. We'll look into it.
