### ISSUE TITLE
The "directxtech.com" link is not accessable 

### ISSUE THREAD

**Issue by fynv** [microsoft/DirectX-Graphics-Samples#558]
Hi, I've just started to look at DXR today. 
I've seen the following link in multiple places (including here):
http://forums.directxtech.com/index.php?topic=5860.0
Seems I need to get the headers likes "d3d12_1.h" from the link.
But I'm keep getting a 404 error.
Have I missed something? Is that link not useful anymore?

**Comment by pkristof** [comment]
Windows October 2018 update (AKA 1809, build 17763) and newer with accompanying SDKs have all the required headers for DXR.

That site and link is deprecated. Outside public MSDN documentation for DirectX and DXR, you can find the actual DXR spec, which was shared via the link, [on the DirectX GitHub spec site](https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html)

**Comment by fynv** [comment]
Great. Thank you pkristof! Closing.
