### ISSUE TITLE
Question/Request: Deferred rendering on dx12

### ISSUE THREAD

**Issue by greatelk** [Microsoft/DirectX-Graphics-Samples#56]
Hello,

this is first of all a question, i'm trying to understand how i can use multiple render targets on dx12 to get one single vertex shader pass and then n pixel shader executions to different gbuffers

currently i'm studding miniengine, and now i can do one vertex and one pixel shader to a gbuffer that can be redirected as shader resource view to another pixel shader

in the pipeline state descriptor you can add NumRenderTargets but i didn't get where i can set the different pixel shader output and also OMSetRenderTargets in command buffer

maybe another sample include this question or in the programming guide (https://msdn.microsoft.com/en-us/library/windows/desktop/Dn899121(v=VS.85).aspx) but i didn't find apart on the miniengine but the codebase is really large and i'm not sure if it's solved here

in any case, if you are busy and only answer the question i can share the result work in a pull request later

maybe this is an obvious question and it's solved in these samples but my opengl background is getting some conflicts to switch to dx12 :)

edit:
maybe isn't possible to get one vertex to n different pixel shaders?

Thanks,

Marc

**Comment by bobbrow** [comment]
If you are aiming to do deferred rendering with multiple render targets set at the same time, nothing much has changed from DX11 to DX12.  With deferred rendering, you generally just want to run the pixel shader once and have it write to all of the render targets at the same time.  I think the HLSL semantic that you're looking for is [COLOR[n]](https://msdn.microsoft.com/en-us/library/windows/desktop/bb509647(v=vs.85).aspx).  When you write your pixel shader, you can have it return a struct like this:

```
struct PSOutput
{
    float4 color : COLOR0;
    float4 normal : COLOR1;
    float4 depth : COLOR2;
    // ...
};
```

As this is a pretty common rendering technique, I think it would make sense for us to consider adding a sample for it.  I'll add it to the backlog.

**Comment by greatelk** [comment]
Thanks!!

This look easier than i expected first, tomorrow i will start working on it

**Comment by bobbrow** [comment]
Just an update, I gave you stale information above.  I just fixed it, so please re-read before working on it. :)

**Comment by greatelk** [comment]
done! thanks
