### ISSUE TITLE
D3D12RaytracingProceduralGeometry Crashes when trying to use DXR

### ISSUE THREAD

**Issue by wukunlinc** [microsoft/DirectX-Graphics-Samples#564]
When I ran D3D12RaytracingProceduralGeometry and tried to use DirectXRaytracing through pressing "3" the program crashes with the following output 

`The thread 0x37fc has exited with code 0 (0x0).
The thread 0x1b34 has exited with code 0 (0x0).
The thread 0x17b8 has exited with code 0 (0x0).
The thread 0x574 has exited with code 0 (0x0).
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispui.inf_amd64_4414fa45d96bb4f5\nvrtum64.dll'
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\nvfatbinaryLoader.dll'
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispui.inf_amd64_4414fa45d96bb4f5\nvcbl64.dll'
The thread 0x3248 has exited with code 0 (0x0).
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\winmm.dll'
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispui.inf_amd64_4414fa45d96bb4f5\nvwgf2umx.dll'
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispui.inf_amd64_4414fa45d96bb4f5\nvldumdx.dll'
'D3D12RaytracingProceduralGeometry.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispui.inf_amd64_4414fa45d96bb4f5\nvldumdx.dll'. 
'D3D12RaytracingProceduralGeometry.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispui.inf_amd64_4414fa45d96bb4f5\nvwgf2umx.dll'. 
'D3D12RaytracingProceduralGeometry.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. 
'D3D12RaytracingProceduralGeometry.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. 
'D3D12RaytracingProceduralGeometry.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. 
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'D3D12RaytracingProceduralGeometry.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. 
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispui.inf_amd64_4414fa45d96bb4f5\nvldumdx.dll'
Direct3D Adapter (0): VID:10DE, PID:1B80 - NVIDIA GeForce GTX 1080
'D3D12RaytracingProceduralGeometry.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispui.inf_amd64_4414fa45d96bb4f5\nvldumdx.dll'. 
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\winmm.dll'
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispui.inf_amd64_4414fa45d96bb4f5\nvwgf2umx.dll'
The thread 0x222c has exited with code 0 (0x0).
'D3D12RaytracingProceduralGeometry.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispui.inf_amd64_4414fa45d96bb4f5\nvwgf2umx.dll'. 
'D3D12RaytracingProceduralGeometry.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. 
'D3D12RaytracingProceduralGeometry.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. 
'D3D12RaytracingProceduralGeometry.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. 
'D3D12RaytracingProceduralGeometry.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. 
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
The thread 0x2f78 has exited with code 0 (0x0).
'D3D12RaytracingProceduralGeometry.exe' (Win32): Loaded 'C:\Windows\System32\dxilconv.dll'. 
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\dxilconv.dll'
Warning: GPUTimer is disabling an unwanted D3D12 debug layer warning: D3D12_MESSAGE_ID_EXECUTECOMMANDLISTS_GPU_WRITTEN_READBACK_RESOURCE_MAPPED.Couldn't get DirectX Raytracing interface for the command list.
Exception thrown at 0x00007FFAA36EA839 in D3D12RaytracingProceduralGeometry.exe: Microsoft C++ exception: HrException at memory location 0x000000C0F0EFE368.
Application hit a problem: HRESULT of 0x80004002
Terminating.
The thread 0x3c5c has exited with code 0 (0x0).
The thread 0x32f4 has exited with code 0 (0x0).
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\winmm.dll'
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispui.inf_amd64_4414fa45d96bb4f5\nvwgf2umx.dll'
'D3D12RaytracingProceduralGeometry.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispui.inf_amd64_4414fa45d96bb4f5\nvldumdx.dll'
The thread 0x3f64 has exited with code 1 (0x1).
The thread 0x2bc4 has exited with code 1 (0x1).
The thread 0x3f1c has exited with code 1 (0x1).
The thread 0xccc has exited with code 1 (0x1).
The thread 0x1c7c has exited with code 1 (0x1).
The program '[15120] D3D12RaytracingProceduralGeometry.exe' has exited with code 1 (0x1).`

I compiled with VS2019 Windows SDK 17763
Graphics card is GTX1080 on Driver Ver. 425.25

Is DXR not supported on this configuration?

edit: updating to the latest drivers 431.60 didn't help

**Comment by pkristof** [comment]
Hello,

Thanks for the report. This is a known issue. You can use the 19h1 sample code from "Develop" branch with 18362 SDK, even on 1809 as per the [note in the readme](https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12Raytracing/readme.md#d3d12-raytracing-samples)
).

**Comment by wukunlinc** [comment]
Develop branch works without a problem. Thanks.
