### ISSUE TITLE
Make Dx12 Helper Library standalone

### ISSUE THREAD

**Issue by ghost** [microsoft/DirectX-Graphics-Samples#565]
I think it would really help developers if the dx12 helper library had a standalone Github page. So that developers could integrate it into their projects easier.

A lot of developers use this library but have less than desirable workflows, examples:
- Have an awkward workflow downloading the entire DirectX-Graphics-Samples and removing unnecessary files.
- Manually download the file every once in a while, which is very error-prone to developers not having up to date copies

If the dx12 helper library was standalone the project could be a small git submodule.

The dx12 helper library is referenced in official MSDN documentation, the only dx12 book, and multiple tutorials online. It is an important enough asset to dx12 libraries that it should have its own github page.

**Comment by walbourn** [comment]
``D3X12.H`` helper is now officially hosted on [DirectX-Headers](https://github.com/microsoft/DirectX-Headers/tree/main/include/directx).
