### ISSUE TITLE
Latest d3dx12.h causes link error - undefined IID_ID3D12Device symbol.

### ISSUE THREAD

**Issue by michal-z** [microsoft/DirectX-Graphics-Samples#567]
Replacing all occurrence of "IID_ID3D12Device" with "__uuidof(*pDevice)" fixes the problem for me. Thanks.

**Comment by michal-z** [comment]
I see, thanks!

**Comment by sebmerry** [comment]
If there is still an issue here, please feel free to add more details and reopen. Thanks!

**Comment by zezba9000** [comment]
FYI LinkedGPU example is missing: dxguid.lib
Causing this error

**Comment by suzp1984** [comment]
both `Replacing all occurrence of "IID_ID3D12Device" with "__uuidof(*pDevice)"`  and  `#include <initguid.h> before including d3d12.h` wouldn't fix this issue.

**Comment by AHappyFun** [comment]
woow, fixed my problem

**Comment by GameDreamByHuo** [comment]
这是来自QQ邮箱的假期自动回复邮件。 你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
