### ISSUE TITLE
d3dx12residency.h has problems if multiple binaries use it with the same queue.

### ISSUE THREAD

**Issue by jenatali** [microsoft/DirectX-Graphics-Samples#568]
There's a hardcoded GUID in the GetFence() method. If two binaries are compiled with the residency library (e.g. d3d11on12.dll plus the app), and both use the residency library with the same queue, they will re-use the same fence without incrementing the number of queues seen, which causes allocations to fail when creating sync points with std::bad_alloc.

The GUID should be generated, either with CoCreateGUID, or (simpler) using hardcoded high bits and AllocateLocallyUniqueId for the low bits.

**Comment by weltkante** [comment]
[Type 3 and 5 GUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier#Versions_3_and_5_(namespace_name-based)) are hash based if you need stable values. Just hash something and overwrite the GUID type bits.

**Comment by sebmerry** [comment]
@jenatali  this is now fixed in the develop branch. Thanks!
