### ISSUE TITLE
D3D12RaytracingHelloWorld issue : Prebuild check failing

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/DirectX-Graphics-Samples#571]
Hi,

I opened the sample and chose to upgrade the project to use 142 platform toolset as suggested and latest SDK. I set the RaytracingHelloWorld as the startup project and run. I get the following errors ..

Error	MSB3073	The command "cd "E:\Dev\Reference C++\DirectX-Graphics-Samples-master\Samples\Desktop\D3D12Raytracing\src\..\tools\x64\"
PrebuildCheck.bat
:VCEnd" exited with code 1.	FallbackLayer	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	128

**Comment by pkristof** [comment]
Hi,
The path gets mangled when you build as per your log. We've seen a report or two of this before, but never root caused it. Actually, Fallback Layer is no longer supported and thus those .bat files are unnecessary. You can use develop branch where samples dont have these dependencies anymore and should build for you.

**Comment by Gavin-Williams** [comment]
Thanks for the very quick response. And the dev branch works. Thank you!
