### ISSUE TITLE
D3D12RaytracingMiniEngineSample is missing DXSampleHelper.h in 'master'

### ISSUE THREAD

**Issue by AdamJMiles** [microsoft/DirectX-Graphics-Samples#576]
Currently D3D12RaytracingMiniEngineSample doesn't compile in 'master'. It's missing DXSampleHelper.h. This file is present in the develop branch but not in master. @stanard / @pkristof

**Comment by pkristof** [comment]
Thanks Adam. Gitignore listed the project's folder and thus the file didn't get picked up in the previous push. I just pushed an update fixing it.
