### ISSUE TITLE
Provide DX/D3D headers as Github repo with simple license

### ISSUE THREAD

**Issue by bkaradzic** [microsoft/DirectX-Graphics-Samples#585]
Obtaining different versions of DX/D3D headers is complicated (they are in multiple redistributables, and SDKs). GIt repo that nicely solves issue is https://github.com/apitrace/dxsdk, but it comes with complicated / non-clear license about ability to redistribute those header files.

This request is just about D3D **header** files not other files distributed by SDK.

Sorry to post here, but I don't have better way to contact someone from D3D team about this particular issue.

**Comment by jenatali** [comment]
These days the easiest way to contact the D3D team is via [Discord](https://discord.gg/directx). With that said, this seems reasonable. Thanks for the suggestion.

**Comment by walbourn** [comment]
Having been involved with basically all the [DXSDK deprecation](aka.ms/dxsdk) efforts for 15  years, I can say that there are reasons why many of them are no longer available in modern SDKs.  In particular, that repro contains D3DX9, D3DX10, and D3DX11 headers which require using the legacy [DirectSetup](https://walbourn.github.io/not-so-direct-setup/) to deploy. While there are limited choices for avoiding D3DX9 if you use it, really nobody should be using D3DX10 (they should use DirectX 11) or D3DX1. See [this blog post](https://walbourn.github.io/living-without-d3dx/).

Other headers like D3DCSX.H require DLLs that are only available for REDIST in the Windows 10 SDK.

I see the value of having a way to get Windows platform headers including DirectX SDK without having to install the Windows 10 SDKs but that's quite different than throwing every header we ever shipped into a repo forever.

**Comment by bkaradzic** [comment]
@walbourn As far as I'm concern I don't need any of those D3DX*.h headers. I need D3D*.h because I'm manually loading .dlls, and want to be able to build my project without need to install multiple SDKs from [random places](https://github.com/apitrace/apitrace/wiki/DirectX-SDK) before everything can be built. Basically I just need definition of COM interface in repo with some license that clearly states it's OK to redistribute it.

**Comment by jenatali** [comment]
FYI, this is now done for D3D12.h: https://github.com/microsoft/DirectX-Headers

**Comment by bkaradzic** [comment]
Excellent, thank you! :+1:
