### ISSUE TITLE
adapter.ptr_ is null when Graphics Debugging

### ISSUE THREAD

**Issue by wukunlinc** [microsoft/DirectX-Graphics-Samples#586]
![image](https://user-images.githubusercontent.com/48650896/66928109-782aa500-f063-11e9-9f65-336cb0f53e75.png)

I am running Visual Studio 2019 in Windows 10.0.18362 with a GTX 1080. The samples run without a problem in both debug and release mode, but when I try to use the Graphics Debugger (Alt + F5), they all crash with access violation. Anyone seen this before?

**Comment by MaximPrime** [comment]
The problem is you use never version of API (SDK above 14393) and it is not supported by GD, use pix instead

**Comment by wukunlinc** [comment]
Ah, I thought GD has better support for newer SDK's, guess not lol
