### ISSUE TITLE
Are there D3D12 samples in C?

### ISSUE THREAD

**Issue by procedural** [microsoft/DirectX-Graphics-Samples#589]
I see C++ here, but no C. Why? Can you write D3D12 in C? Are there any official examples of using D3D12 with C?

Thanks!

**Comment by MaximPrime** [comment]
AFAIK, no

pon., 21 paź 2019, 22:17 użytkownik procedural <notifications@github.com>
napisał:

**Comment by procedural** [comment]
What no? There are no official D3D12 examples in C? Or you can't write D3D12 in C? I wonder why.

**Comment by stanard** [comment]
It's theoretically possible to use D3D12 from C, but I don't know anyone who has.

**Comment by jenatali** [comment]
Note that the C interface included in the header is actually broken. See https://stackoverflow.com/questions/34118929/getcpudescriptorhandleforheapstart-stack-corruption.

I'm hoping we'll actually be able to fix this in the future, but for right now C developers have to work around this.

**Comment by weltkante** [comment]
Just a warning, C isn't fully compatible to the "lightweight" COM interop used in DirectX APIs.

Note that the C ABI for returning structs is different from C++, meaning if D3D12 has any APIs which return structs those cannot be called from C. When using the same STDCALL calling convention a MIDL-style C vtable will return the struct in a register while a C++ interface will return it through the stack.

We have observed this in Direct2D APIs when trying to write C# interop signatures and were very surprised that C and C++ ABIs for the same calling convention differed.

**Comment by GamebabyRockSun** [comment]
https://github.com/GamebabyRockSun/GRSD3D12Sample

**Comment by procedural** [comment]
@GamebabyRockSun 非常感谢你！

**Comment by GamebabyRockSun** [comment]
> @GamebabyRockSun 非常感谢你！

客气

**Comment by procedural** [comment]
@pkristof why you closed this?

**Comment by pkristof** [comment]
Thanks for checking back. We know about the issue, but I agree, it does make sense to keep it open here and close it after we deploy a fix for the C interface.

Best,
Peter

**Comment by JesseRMeyer** [comment]
I'm also interested in using DX12 from C, and from languages that support calling C libraries..

**Comment by JesseRMeyer** [comment]
Please See: https://github.com/Meith/DX12/issues/1#issuecomment-580793673

**Comment by MattGuerrette** [comment]
@jenatali Any movement on a fix for the C interface? I'd think it wouldn't be too difficult of a fix and more of a release management issue of when to update the SDK. For now workarounds are fine, but it would be preferable to have the headers updated.

**Comment by jenatali** [comment]
The Windows Insider SDK has been fixed since earlier this year. Unfortunately it didn't make the 2004 SDK.

**Comment by procedural** [comment]
@JesseRMeyer does it mean D3D12 supports C now? Will other C related bugs be fixed when found too?

**Comment by jenatali** [comment]
@procedural Wrong tag :)

D3D12's C support has always been best-effort, in that we get it for free from using MIDL for header generation, but don't have internal usage of it. I've mixed MIDL to support our headers so that the C definitions should be correct now. If there are further problems, feel free to let us know.

**Comment by procedural** [comment]
I find it strange that C definitions are occasionally fixed thanks to Microsoft people like you, @jenatali, but C is not officially supported and there are no official D3D12 examples in C.

**Comment by MattGuerrette** [comment]
@jenatali This is a bit tangential but it appears that Direct2D no longer contains the C interface as part of the Windows 10 SDK. Was this intentional and could it be fixed at all alongside the D3D12 headers?

**Comment by jenatali** [comment]
@MattGuerrette if the C interface was removed, I have to assume it was intentional.

**Comment by eLeCtrOssSnake** [comment]
I had no problems using C with D3D12 headers, everything works, just as in d3d9(10,11). And thank god Bill Gates for this, because C++ is ok, C is awesome. Sometimes I just don't need C++.
