### ISSUE TITLE
Wrong cosine term for point lights

### ISSUE THREAD

**Issue by Fact87** [microsoft/DirectX-Graphics-Samples#591]
https://github.com/microsoft/DirectX-Graphics-Samples/blob/5c29743681666a5e37be90f8feda1a0d6efe44fe/MiniEngine/ModelViewer/Shaders/ModelViewerPS.hlsl#L142

 If lightColor is the power of the light (flux in Watts) shouldn't the nDotL product removed for point lights? If lightColor is otherwise considered as the radiance then no falloff should be applied since radiance is constant along rays. Here the formula i get:

![OmniRenderingEquation](https://user-images.githubusercontent.com/40348318/67600312-e7795680-f73f-11e9-9f92-506fb8737d6f.jpg)

This proves that the cosine term should be removed for point lights
(Note that the fourth line is from a paper and i don't know an integral without the infinitesimal is possible. If somebody knows...)

**Comment by stanard** [comment]
The N-dot-L term is irrespective of the source of light. Imagine radiance measuring the flux of light through a cylinder (like a pipe).  When the surface normal is parallel to light direction, the cross section of the pipe is a perfect circle.  All of the light impacts the smallest possible area.  As the normal faces further away from the direction of travel, the cross section skews into an elongated ellipse.  This increases the surface area of impact, reducing the intensity of light at each point on the ellipse.  Once the dot product reaches zero, the ellipse is stretched to have infinite area.  So nDotL is a geometric factor expressing how much surface area to spread the flux across.  It affects all light coming from all directions.

**Comment by Fact87** [comment]
Thanks for your reply. It is true that light varies according to the cosine term due to the "projected" area of the hemispherical disk on the surface plane. But this constraint is gone in the line 3 of the equation with division simplification.
I don't understand why the issue has been closed. Is there a formula that shows I am wrong?

**Comment by stanard** [comment]
This is perhaps not the right venue for debating the Lighting Equation or Mathematical models for lighting, so I closed the issue.  That being said, I don't believe there is an error in the shading calculation.  Point lights attenuate in power proportional to 1/D^2, but all incoming light energy is treated the same at interactive surfaces.

**Comment by Fact87** [comment]
I understand :). I agree points lights attenuate in power proportional to 1/D^2. You can see that in the last line of the equation. However this is only true if _lightColor_  is a flux(in Watts).  In that case the cosine term should be removed. Note that this is only valid for direct lighting. So the current shading equation used by the viewer is not physically accurate for point lights in my opinion.

If the light color is considered as being radiance(in W m-2 Sr-1)  then the cosine term is keeped. But the 1/D^2 factor should no longer be applied. This comment saying that lightColor is the radiance of a directional light shows there is something wrong: https://github.com/microsoft/DirectX-Graphics-Samples/blob/5c29743681666a5e37be90f8feda1a0d6efe44fe/MiniEngine/ModelViewer/Shaders/ModelViewerPS.hlsl#L256.
