### ISSUE TITLE
All samples crash (user error?)

### ISSUE THREAD

**Issue by ThorMalleuson** [Microsoft/DirectX-Graphics-Samples#6]
Getting the following error with every sample.
"hr	0x887a0004 : The specified device interface or feature level is not supported on this system. 	HRESULT"

Using Windows 10 Home on a laptop with an Intel i7-3610QM and an nVidia GTX 670M with latest 64 bit drivers.

No problems with DirectX 11 stuff.

Thanks.

**Comment by zao** [comment]
See issue #5. NV cards based on Fermi do not have WDDM 2.0 support yet, and as such cannot be used from Direct3D 12.

**Comment by bobbrow** [comment]
You can go to the project properties and add **/warp** to the command line to instruct the sample to use the WARP driver instead of the hardware driver.

**Comment by ThorMalleuson** [comment]
Ah, nVidia lied! (their site says that this GPU supports DirectX 12). :)
Thank you for the quick response, will add the /warp command.  Thanks again.

**Comment by ThorMalleuson** [comment]
Worked, thanks once again.

**Comment by weltkante** [comment]
Note that if your intel chipset is your first adapter then the nvidia chipset will never be tried. The samples will only ever pick the first chipset reported by windows, even if it doesn't support DX12. I've opened issue #14 for that.
