### ISSUE TITLE
D3D1211On12 doesn't build

### ISSUE THREAD

**Issue by optimiz3** [Microsoft/DirectX-Graphics-Samples#60]
VS2015 debug x64 on Win 10 gives the following build errors:

    1>------ Build started: Project: D3D1211On12, Configuration: Debug x64 ------
    1>  Performing Custom Build Tools
    1>  stdafx.cpp
    1>  Main.cpp
    1>  DXSample.cpp
    1>  D3D1211On12.cpp
    1>  Win32Application.cpp
    1>  Generating Code...
    1>LINK : fatal error LNK1104: cannot open file 'd3d11.lib'
    ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

The closest location of a d3d11.lib is in C:\Program Files (x86)\Windows Kits\8.1\Lib\winv6.3\um\x64, which is not in the default Windows 10 build paths.

However, if I add $(WindowsSDKDir_81)Lib\winv6.3\um\$(PlatformTarget) to the build paths, we now get:

    1>D3D1211On12.obj : error LNK2019: unresolved external symbol D3D11On12CreateDevice referenced in function "private: void __cdecl D3D1211on12::LoadPipeline(void)" (?LoadPipeline@D3D1211on12@@AEAAXXZ)
    1>D:\Users\<USERNAME>\Git\github\DirectX-Graphics-Samples\Samples\D3D1211On12\src\x64\Debug\D3D1211On12.exe : fatal error LNK1120: 1 unresolved externals

AFAICT this shouldn't happen because according to https://msdn.microsoft.com/en-us/library/windows/desktop/dn933209%28v=vs.85%29.aspx, D3D11On12CreateDevice should be in d3d12.lib.

**Comment by weltkante** [comment]
You need Windows 10 for DX12 so looking in the Windows 8.1 libs isn't gonna find anything. Try checking `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64`. If you don't have that then you didn't install the Win10 SDK (one of the options in the VS 2015 installer).

**Comment by alexnagy** [comment]
As per the issue, this is on Windows 10, if you look in that folder, you will not find a d3d11.lib.

**Comment by weltkante** [comment]
It doesn't matter if you build *on* Windows 10, if you are using the 8.1 SDK the compiler will only see features up to Windows 8.1. Thats how compilers always have worked. My Windows 10 SDK most definitely has a d3d11.lib and compiles the sample just fine without changing anything, so it sounds like your installation is broken, not the sample.

`LoadLibraryEx("d3d11.dll", ...` -- that dynamically loads d3d11.dll at runtime instead of letting the compiler link against it, so if you'd just compile against the d3d11.lib from Win10 (and not from Win 8.1) everything would just work.

**Comment by optimiz3** [comment]
Wrong. This is building against the Windows 10 SDK. It doesn't work out of the box. Proof that if you just use stock Win 10 SDK, it will not work:

```
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0>dir /s d3d*
 Volume in drive C has no label.
 Volume Serial Number is B628-1C76

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\arm

07/22/2015  04:44 PM             8,724 d3d10.lib
07/22/2015  04:44 PM             8,816 d3d10_1.lib
07/09/2015  05:43 PM             3,280 d3d12.lib
07/22/2015  04:45 PM             5,062 d3d9.lib
07/09/2015  05:50 PM             8,470 d3dcompiler.lib
               5 File(s)         34,352 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\arm64

07/22/2015  04:38 PM             8,732 d3d10.lib
07/22/2015  04:38 PM             8,824 d3d10_1.lib
07/09/2015  05:36 PM             3,288 d3d12.lib
07/22/2015  04:38 PM             5,088 d3d9.lib
07/09/2015  06:09 PM             8,512 d3dcompiler.lib
               5 File(s)         34,444 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64

07/09/2015  06:19 PM             8,732 d3d10.lib
07/09/2015  06:19 PM             8,824 d3d10_1.lib
07/09/2015  06:19 PM             3,288 d3d12.lib
07/09/2015  06:19 PM             5,088 d3d9.lib
07/09/2015  06:23 PM             8,512 d3dcompiler.lib
07/09/2015  06:24 PM             3,660 d3dcsx.lib
07/09/2015  06:26 PM             3,682 d3dcsxd.lib
               7 File(s)         41,786 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x86

07/09/2015  06:50 PM             9,268 d3d10.lib
07/09/2015  06:50 PM             9,360 d3d10_1.lib
07/09/2015  06:51 PM             3,406 d3d12.lib
07/09/2015  06:50 PM             5,206 d3d9.lib
07/09/2015  06:54 PM             8,986 d3dcompiler.lib
07/09/2015  06:56 PM             3,832 d3dcsx.lib
07/09/2015  06:58 PM             3,854 d3dcsxd.lib
               7 File(s)         43,912 bytes

     Total Files Listed:
              24 File(s)        154,494 bytes
               0 Dir(s)  207,990,185,984 bytes free
```
See? No d3d11.lib.

**Comment by zao** [comment]
It is possible that your installation of the kits has been corrupted or been broken by updates, servicing, personal competence or cosmic rays. If you can figure out how this has happened, it might be helpful in avoiding it in the future or fixing the underlying problem.

Please try to be civil. Adversarial language does not help.

	C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um>dir /s d3d11.lib
	 Volume in drive C is Win 10 - 2015-09-1x
	 Volume Serial Number is 66E4-98C5
	
	 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\arm
	
	09/07/2015  17:43            14,886 d3d11.lib
	               1 File(s)         14,886 bytes
	
	 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\arm64
	
	09/07/2015  17:36            14,972 d3d11.lib
	               1 File(s)         14,972 bytes
	
	 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64
	
	09/07/2015  18:19            14,972 d3d11.lib
	               1 File(s)         14,972 bytes
	
	 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x86
	
	09/07/2015  18:51            15,380 d3d11.lib
	               1 File(s)         15,380 bytes
	
	     Total Files Listed:
	               4 File(s)         60,210 bytes
	               0 Dir(s)  98,266,189,824 bytes free
	
	C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um>

**Comment by optimiz3** [comment]
Currently running a new install of Win10 + VS2015 and will diff against this - stay tuned...

**Comment by optimiz3** [comment]
Just paved VS2015 and the platform SDKs and am seeing a d3d11.lib in the Win10 SDK folder so closing this issue.  No idea what corrupted the SDK installation however.
