### ISSUE TITLE
Fullscreen sample keyboard controls

### ISSUE THREAD

**Issue by walbourn** [microsoft/DirectX-Graphics-Samples#602]
In addition to use "SPACE" to toggle, the sample should also use ALT+ENTER which is the classically implemented hotkey for window vs. fullscreen since the early days of DX

**Comment by sebmerry** [comment]
@walbourn the Fullscreen sample should respect ALT+ENTER. Are there cases where it doesn't work as expected?

**Comment by walbourn** [comment]
@sebmerry Sorry, I saw the handling for ``VK_SPACE`` in D3D12FullScreen.cpp, but didn't the ALT+ENTER hook in Win32Application.cpp code.
