### ISSUE TITLE
Filename length makes my git pull fail

### ISSUE THREAD

**Issue by erich666** [microsoft/DirectX-Graphics-Samples#603]
Using the "Git Extensions" program on Windows 10 I get this pair of errors:

error: unable to create file Samples/Desktop/D3D12Raytracing/src/D3D12RaytracingRealTimeDenoisedAmbientOcclusion/RTAO/Shaders/Denoising/CalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt.hlsl: Filename too long

error: unable to create file Samples/Desktop/D3D12Raytracing/src/D3D12RaytracingRealTimeDenoisedAmbientOcclusion/RTAO/Shaders/Denoising/DisocclusionBlur_DepthAwareSeparableGaussianFilter3x3CS_AnyToAnyWaveReadLaneAt.hlsl: Filename too long

Manually downloading the zip and pulling these files out works, but it'd be nicer to avoid these long file names.

**Comment by walbourn** [comment]
The file path is 191 chars long, so you should be able to use a 'shallow root' for the git. The same name is certainly a bit long.

See also [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation).
