### ISSUE TITLE
Fallback Layer is removed. Why?

### ISSUE THREAD

**Issue by kingofthebongo2008** [microsoft/DirectX-Graphics-Samples#606]
Hello, 
Fallback layer is removed. Can you comment why?
I have test on amd and winver 1903 and my device reports that it is not working.
On NVidia I had no issues.

**Comment by walbourn** [comment]
This is covered in the [readme](https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Libraries/D3D12RaytracingFallback#d3d12-raytracing-fallback-layer)
