### ISSUE TITLE
Exception thrown at 0x00007FFC4312A839 in D3D12HelloTriangle.exe: Microsoft C++ exception: _com_error at memory location 0x00000010DB3DA1C0.

### ISSUE THREAD

**Issue by JesseRMeyer** [microsoft/DirectX-Graphics-Samples#613]
When D3D12CreateDevice is not passed null for a device handle, I receive the exception mentioned in the title.

I am using a dedicated GTX 1070 running Nvidia's 441.87 driver, and using Window's SDK version 10.0.18362.0, with Visual Studio 2019.  The same error occurs when compiled with clang-cl.

This is not restricted to only the HelloTriangle example.  This issue exists for any D3D12CreateDevice call where null is not passed as a device handle. 

```c++
ThrowIfFailed(D3D12CreateDevice(
            hardwareAdapter.Get(),
            D3D_FEATURE_LEVEL_11_0,
            IID_PPV_ARGS(&m_device)
            ));
```

This does not appear to cause actual problems however.  The samples all run correctly, without memory leaks or crashes, and the debug layers do not complain at all.

**Comment by walbourn** [comment]
The internal runtime uses C++ exception handling in some places, so you'll see or even catch some in the debugger that DO NOT propagate outside of the create function. As long as it returns ``SUCCEEDED``, then it's harmless and "by design"
