### ISSUE TITLE
Current functionality support of 10-bit imaging - UWP/D3D12HDR

### ISSUE THREAD

**Issue by jdsterli** [microsoft/DirectX-Graphics-Samples#615]
Hi,  I am somewhat new to DirectX and UWP based programming, so I found your example very helpful:
https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Samples/UWP/D3D12HDR

There seems to be a lot of unwritten rules to swapchain usage and how the data it outputs will translate to monitor display. One being the need to use fullscreen. Also the OS will impact it's look as well:
https://stackoverflow.com/questions/43971434/detect-10-bit-color-support-on-display

Is there a resource you could recommend which covers the caveats to HDR or general 10-bit backbuffer programming within the Windows 10 environment?

**Comment by walbourn** [comment]
You may find [this post](https://walbourn.github.io/hdr-lighting-and-displays/) useful.

**Comment by jdsterli** [comment]
Hi Chuck,
Thank you for the super fast reply. That is definitely a helpful resource.
My situation is a little crazier (and perhaps I should change it), in that I am referencing your examples for guidance for use with XAML Islands inside a SwapChainPanel, specifically with WPF .Net Core 3.
Additionally, I have a 10-bit color monitor but it isn't HDR.
In WPF there is no specific call to set Full Screen, and instead set XAML variables for windowstate=maximized and windowstyle=none.
I use a WinRT component for a UWP SwapChainPanel, but calls to ApplicationView::GetForCurrentView()->TryEnterFullScreenMode(); do not succeed.
As such I am left worried about my 10-bit swapchain being reduced to 8-bit by the OS.

**Comment by jdsterli** [comment]
Quick update on this. I believe I am in fact getting 10-bit output from my swapchain to monitor via XAML Islands workflow (since when I toggle pixel formats I do see banding when in 8-bit mode), so I am happy with that.

In the UWP/D3D12HDR sample, I do notice however that the gradients change to be dramatically darker when using DXGI_FORMAT_R16G16B16A16_FLOAT and DXGI_COLOR_SPACE_RGB_FULL_G10_NONE_P709 when in FullScreen but not in windowed mode. Since the only code difference in this scenario is the window state, I assume one of them is incorrect. But which is it?

**Comment by walbourn** [comment]
When you are using ``DXGI_FORMAT_R16G16B16A16_FLOAT`` the system is doing the HDR10 signal prep and tone-mapping. The difference in the windowed vs. fullscreen is therefore likely different choices being made by the system.

In general for programmer control, you'd be better off doing the HDR10 signal prep and tone-mapping directly yourself and using the output format of ``DXGI_FORMAT_R10G10B10A2_UNORM``. The details for all that is covered by the resources linked in the blog post above.
