### ISSUE TITLE
AnyToAnyWaveReadLaneAt.hlsl.h cannot find the path specified

### ISSUE THREAD

**Issue by AlbanGauthier** [microsoft/DirectX-Graphics-Samples#621]
I can build and run all the samples except for D3D12RaytracingRealTimeDenoisedAmbientOcclusion.
I get this build error when trying to launch the process :

------ Build started: Project: D3D12RaytracingRealTimeDenoisedAmbientOcclusion, Configuration: Release x64 ------
The system cannot find the path specified. 
obj\x64\Release\\CompiledShaders\CalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt.hlsl.h

Any idea why the shader is not compiled?

**Comment by stanard** [comment]
I don't maintain that project, but can you confirm if the shader is part of the project? The header file should be generated by shader compilation. Another suspect is a shader build error. Unfortunately, DXC doesn't seem to report compiler messages to the Build Output window.

**Comment by AlbanGauthier** [comment]
Yes the shader is there, in : 
D3D12RaytracingRealTimeDenoisedAmbientOcclusion\RTAO\Shaders\Denoising\CalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt.hlsl

I also suspect a shader build error (it is explicitly stated there are some known issues with wave read lane support, but I run a GTX1080 so no worries..).
Any idea how I could see the compiler outputs ?

**Comment by stanard** [comment]
Check that the shader file is actually listed in the vcxproj, not just present in the shaders folder. (Unless the project uses a batch file to build shaders. Then check there.) But you can try to compile the shader on the command line using DXC.exe. That will display any errors.

**Comment by AlbanGauthier** [comment]
It is indeed listed in the vcxproj :
<FxCompile Include="RTAO\Shaders\Denoising\CalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt.hlsl">
      <ShaderType Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">Compute</ShaderType>
      <ShaderModel Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">6.3</ShaderModel>
      ...
    </FxCompile>

I tried to compile the shader using DXC.exe, unfortunately I don't know which profile to target, and how to add proper dependencies (the shader has some includes).

Thanks for the help by the way.

**Comment by weltkante** [comment]
In C# projects the multiple backslashes don't hurt and are reduced automatically. Since its an output path it cannot find, maybe make sure that intermediate directories in that path exist. Just a guess.

**Comment by AlbanGauthier** [comment]
The folder exist but is empty.
I don't know how I can have a look at the build config, and see what is executed when I build the project. Do you know how to do this?

**Comment by weltkante** [comment]
If you are building in VS, menu Tools/Options section "Projects and Solution"/"Build and Run" set build output verbosity to "detailed"

**Comment by AlbanGauthier** [comment]
Thanks, I can now see some errors:

Building with tools version "Current".
1>Project file contains ToolsVersion="15.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="Current". For more information, please see http://go.microsoft.com/fwlink/?LinkId=293424.
1>Target "EnableIntermediateOutputPathMismatchWarning" skipped, due to false condition; ('$(RestoreProjectStyle)' == 'PackageReference') was evaluated as ('' == 'PackageReference').
1>Target _CheckForInvalidConfigurationAndPlatform:
1>  Task "Error" skipped, due to false condition; ( '$(_InvalidConfigurationError)' == 'true' ) was evaluated as ( '' == 'true' ).
1>  Task "Warning" skipped, due to false condition; ( '$(_InvalidConfigurationWarning)' == 'true' ) was evaluated as ( '' == 'true' ).
1>  Using "Message" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

**Comment by AlbanGauthier** [comment]
Thanks, now I see where the building fails:

1>  Task "FXC"
1>    Write Tracking log not available, minimal rebuild will be disabled.
1>    Read Tracking Logs:
1>    	obj\x64\Release\D3D12Ray.19585C81.tlog\dxc.read.1.tlog
1>    No output for C:\USERS\ALBAN\DOCUMENTS\WORKSPACE\DIRECTX-GRAPHICS-SAMPLES\SAMPLES\DESKTOP\D3D12RAYTRACING\SRC\D3D12RAYTRACINGREALTIMEDENOISEDAMBIENTOCCLUSION\RTAO\SHADERS\DENOISING\CALCULATEMEANVARIANCE_SEPARABLEFILTERCS_CHECKERBOARDSAMPLING_ANYTOANYWAVEREADLANEAT.HLSL was found in the tracking log; source compilation required.
1>    RTAO\Shaders\Denoising\CalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt.hlsl will be compiled because not all outputs are available.
1>    C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86\dxc.exe /I"C:\Users\alban\Documents\workspace\DirectX-Graphics-Samples\Samples\Desktop\D3D12Raytracing\src\D3D12RaytracingRealTimeDenoisedAmbientOcclusion\\" /IRTAO/shaders /ISampleCore/shaders /ISampleCore/shaders/util /nologo /T cs_6_3 /Fh "obj\x64\Release\\CompiledShaders\CalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt.hlsl.h" /Vn "g_pCalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt" RTAO\Shaders\Denoising\CalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt.hlsl
1>    Tracking command:
1>    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Tracker.exe /d "C:\Program Files (x86)\MSBuild\15.0\FileTracker\FileTracker32.dll" /i C:\Users\alban\Documents\workspace\DirectX-Graphics-Samples\Samples\Desktop\D3D12Raytracing\src\D3D12RaytracingRealTimeDenoisedAmbientOcclusion\obj\x64\Release\D3D12Ray.19585C81.tlog /r C:\USERS\ALBAN\DOCUMENTS\WORKSPACE\DIRECTX-GRAPHICS-SAMPLES\SAMPLES\DESKTOP\D3D12RAYTRACING\SRC\D3D12RAYTRACINGREALTIMEDENOISEDAMBIENTOCCLUSION\RTAO\SHADERS\DENOISING\CALCULATEMEANVARIANCE_SEPARABLEFILTERCS_CHECKERBOARDSAMPLING_ANYTOANYWAVEREADLANEAT.HLSL /b MSBuildConsole_CancelEvent5ce42812b11941eabf2f3bbe414212cb  /c "C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86\dxc.exe"  /I"C:\Users\alban\Documents\workspace\DirectX-Graphics-Samples\Samples\Desktop\D3D12Raytracing\src\D3D12RaytracingRealTimeDenoisedAmbientOcclusion\\" /IRTAO/shaders /ISampleCore/shaders /ISampleCore/shaders/util /nologo /T cs_6_3 /Fh "obj\x64\Release\\CompiledShaders\CalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt.hlsl.h" /Vn "g_pCalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt" RTAO\Shaders\Denoising\CalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt.hlsl
1>    The system cannot find the path specified. obj\x64\Release\\CompiledShaders\CalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt.hlsl.h
1>
1>    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1495,5): error MSB6006: "dxc.exe" exited with code 1.
1>  Done executing task "FXC" -- FAILED.
1>Done building target "FxCompile" in project "D3D12RaytracingRealTimeDenoisedAmbientOcclusion.vcxproj" -- FAILED.
1>
1>Done building project "D3D12RaytracingRealTimeDenoisedAmbientOcclusion.vcxproj" -- FAILED.

**Comment by AlbanGauthier** [comment]
Thanks, now I see where the building fails : 

1>    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Tracker.exe 
/d "C:\Program Files (x86)\MSBuild\15.0\FileTracker\FileTracker32.dll" 
/i C:\Users\alban\Documents\workspace\DirectX-Graphics-Samples\Samples\Desktop\D3D12Raytracing\src\D3D12RaytracingRealTimeDenoisedAmbientOcclusion\obj\x64\Release\D3D12Ray.19585C81.tlog 
/r C:\USERS\ALBAN\DOCUMENTS\WORKSPACE\DIRECTX-GRAPHICS-SAMPLES\SAMPLES\DESKTOP\D3D12RAYTRACING\SRC\D3D12RAYTRACINGREALTIMEDENOISEDAMBIENTOCCLUSION\RTAO\SHADERS\DENOISING\CALCULATEMEANVARIANCE_SEPARABLEFILTERCS_CHECKERBOARDSAMPLING_ANYTOANYWAVEREADLANEAT.HLSL 
/b MSBuildConsole_CancelEvent5ce42812b11941eabf2f3bbe414212cb  
/c "C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86\dxc.exe"  
/I"C:\Users\alban\Documents\workspace\DirectX-Graphics-Samples\Samples\Desktop\D3D12Raytracing\src\D3D12RaytracingRealTimeDenoisedAmbientOcclusion\\" 
/IRTAO/shaders /ISampleCore/shaders /ISampleCore/shaders/util /nologo /T cs_6_3 
/Fh "obj\x64\Release\\CompiledShaders\CalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt.hlsl.h" 
/Vn "g_pCalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt" 
RTAO\Shaders\Denoising\CalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt.hlsl

1>    The system cannot find the path specified. obj\x64\Release\\CompiledShaders\CalculateMeanVariance_SeparableFilterCS_CheckerboardSampling_AnyToAnyWaveReadLaneAt.hlsl.h
1>    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1495,5): error MSB6006: "dxc.exe" exited with code 1.
1>  Done executing task "FXC" -- FAILED.

How am I supposed to get this hlsl.h in the folder?

**Comment by DrGr4f1x** [comment]
That .hlsl.h file is the output.  Is this not just a path-length issue?  I
see that your output path length would be 266, but the max windows path
length is 260.

**Comment by AlbanGauthier** [comment]
FINALLY, thanks @DrGr4f1x . It was indeed a path length problem.
Also thank you @weltkante and @stanard for the help.

**Comment by Kerrash** [comment]
I did not have an issue with the path length, but found that many of the sample projects did not create the required "CompiledShaders" output folders e.g.
\Samples\Desktop\D3D12Raytracing\Build_VS16\x64\Debug\Output\Core\CompiledShaders
\Samples\Desktop\D3D12Raytracing\Build_VS16\x64\Debug\Output\D3D12RaytracingMiniEngineSample\Shaders
\Samples\Desktop\D3D12Raytracing\src\D3D12RaytracingHelloWorld\obj\x64\Debug\CompiledShaders

This caused many vague errors preventing the build until I created them.
These really should be included in a build event or something. :(

**Comment by sebmerry** [comment]
There is a VS issue causing it to not create the dependent folders. You can find it and a suggested workaround here:
https://developercommunity.visualstudio.com/content/problem/1145832/typo-in-fxc-target-in-vs-1671.html
