### ISSUE TITLE
D3D12/DXGUID broken?

### ISSUE THREAD

**Issue by HiImJulien** [microsoft/DirectX-Graphics-Samples#622]
My current task is to implement a simple abstraction above D3D12 using pure C.

In the initialisation procedure I reference `IID_IDXGIAdapter4` (Querying interface from IDXGIAdapter1 to IDXGIAdapter4). However, this code does not build, as the linker is not able to resolve its symbol.

I have following libraries linked, which to my understanding, should be sufficient

```
d3d12.lib
dxgi.lib
dxguid.lib
```

Am I missing something? (I am building with WinSDK 10.0.18362.0).

P.S.: Also, I am not sure, whether this is the right place to post such things, but reading the other issues it seems like so. Correct me, if I am wrong.

**Comment by walbourn** [comment]
It's just a bug. The ``dxgi1_6.h`` header was never added to the ``dxguid.lib``.

**Comment by jenatali** [comment]
You'll also need an SDK preview newer than 19041 in order to have proper C headers for D3D12. Prior to that, MIDL doesn't produce ABI-correct function declarations for some of our functions, specifically the ones which return structures.

**Comment by walbourn** [comment]
This bug is fixed in the current [Windows 10 SDK Insider Preview builds](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK)

**Comment by HiImJulien** [comment]
@jenatali I am wondering. If I use MIDL (from an SDK newer than 19041) to generate a new header and use this header over the default `D3D12.h`, would I be able to circumvent that problem?
Are only the declarations broken or is there something going on within the implementation that might be broken as well for prior versions?

**Comment by walbourn** [comment]
The issue is not with the header. It's the fact that the ``DXGUID.LIB`` generation wasn't done with dxgI1_6.h included.### 

You can use ``__uuidof`` instead or you can just define your own instance of the missing GUIDs.

**Comment by jenatali** [comment]
@HiImJulien Yes-ish. There's a new command line switch to MIDL which produces correct C headers for C++ implementers of returning structs via COM: `/cstruct_out`. Though at that point you might as well just grab the updated d3d12.h from the newer SDK instead of making your own.

**Comment by ttvd** [comment]
@jenatali Is there a documentation regarding /cstruct_out anywhere? Also in which version did it appear? Thank you!

**Comment by jenatali** [comment]
I didn't write documentation for it, so probably not. I'll see if I can get that added.

The updated MIDL should be present in SDKs versioned 19547 or newer.

**Comment by HiImJulien** [comment]
@jenatali Or I could use your repository, [that you created sneakily](https://github.com/microsoft/DirectX-Headers).

This is perfect, because I am stuck on a machine without any administrative privileges. The machine is stuck on "10.0.18362.0".

**Comment by jenatali** [comment]
Ah, right, I didn't even think about the fact that would fix this issue otherwise I would've mentioned it here.

**Comment by HiImJulien** [comment]
I guess it's time to close this, as this is finally solved.

**Comment by walbourn** [comment]
This bug in ``dxguid.lib`` is fixed in [ Windows 10 SDK (20348), version 2104](https://aka.ms/windowssdk).
