### ISSUE TITLE
Raytraced MiniEngine Strange Texture Filtering

### ISSUE THREAD

**Issue by NicoM1** [microsoft/DirectX-Graphics-Samples#625]
Hello,

I've been browsing through the samples here, and I noticed some weird behavior on the "RaytracingMiniEngineSample," looks like something strange is happening with the texture filtering, but only in specific areas. 

![image](https://user-images.githubusercontent.com/6273562/80929263-4d820e80-8d5f-11ea-90eb-de6bb94738ad.png)

This may already be known, but I didn't see mention of it in the issues.

I'm on an RTX 2060, i7 3770k, 18362.778

All the best, Nico.

**Comment by NicoM1** [comment]
I looked into this as a bit of practice reading D3D code, but I think I may have found a solution.

The problem seems to come from either DiffuseHitShaderLib.hlsl/CalculateTrianglePartialDerivatives or DiffuseHitShaderLib.hlsl/CalculateUVDerivatives, although I'm not sure what is actually wrong with the logic there.

However, since the code is already finding the ray-plane intersections of the two neighboring pixels, it is fairly easy to convert the intersection points to barycentrics, and then simply interpolate the vertex uv's by these barycentrics. Then the UV ddX and ddY are simply subtractions of these neighboring UVs (unless something is wrong with my logic here, please let me know if so).

When I tried this method, I get this result:

![Screenshot 5_6_2020 1_23_49 PM (2)](https://user-images.githubusercontent.com/6273562/81224780-1a2cc300-8f9d-11ea-961a-0f9c23b5b3fe.png)

The textures look sharp, and I'm not noticing any aliasing at a distance, so I believe the derivatives are correct.

Here is a Gist with the modified shader: https://gist.github.com/NicoM1/fa2f27de38fd3a80fee0a828f662b52c

Let me know if this method is appropriate, although I'm sure this is not a high-profile issue currently, so no worries!

All the best, Nico.

**Comment by stanard** [comment]
Your fix looks correct and more efficient, so I'm looking to commit it.  Before I do, I'd like to understand why the previous, more-laborious method was failing on those roof tiles. I'd also like to understand if there are any cases in which your simplified method might fail. Thanks for this, Nico!

-James

**Comment by NicoM1** [comment]
Great! Yes I'm not sure why it was failing, but I'll say the things I did notice:

1) It definitely relates to triangle shape/size, I output length(ddX) and length(ddY) and got this image: (note that this also makes clear other areas that were failing, such as the thin triangles in the wall - this is obvious if you look for it once you see where, there are blurring artifacts there).

![image](https://user-images.githubusercontent.com/6273562/81325450-3a1bbf80-904d-11ea-9dd4-aceb272d8476.png)

2) Some NaN's are sneaking through: when I tried to output the lengths for 1), I got big black patches, so I did a NaN test and there were areas in the roof where the derivatives were NaN. I've marked these in 100% red in the above image, see the top of the white banner, and the horizontal piece of roofing on the right.

**Comment by NicoM1** [comment]
Oh and for reference, here is the same test applied to my fix:

![image](https://user-images.githubusercontent.com/6273562/81326289-756abe00-904e-11ea-8d80-ff3914e63c5f.png)

Note that the derivatives are now consistent across the planes, and match what I'd expect (derivatives get larger as camera is closer to parallel with the surface).

**Comment by stanard** [comment]
I'm guessing the matrix inverses are dividing by zero or almost zero.  One INF or NAN can propagate and ruin all the Math. Even though your new method seems better (faster and less error-prone), I want to pin-point the bug in the old method. We need a post mortem on it, essentially, so we can argue why this new method is decidedly better. Also, maybe the old method is better if you pre-compute triangle-space partial derivatives, as the comments suggest.

**Comment by NicoM1** [comment]
Of course, that makes sense! I haven't found the root issue yet, but I did just find what's causing the NaN's.

If the UVs for a triangle are degenerate, for instance two vertices have the same UV, then CalculateTrianglePartialDerivatives is trying to invert a singular matrix. That's why the top of the white banner, and the roof tile have NaN's (see their UVs here):

![image](https://user-images.githubusercontent.com/6273562/81332443-f4b0bf80-9057-11ea-9bcc-fc9858c08329.png)

**Comment by stanard** [comment]
But if the UVs are degenerate, why aren't the textures stretched on those polygons?

**Comment by NicoM1** [comment]
Those polygons are solid-color, so you can't tell they're degenerate UVs.

**Comment by stanard** [comment]
I don't understand. Why do they appear textured if they are solid color?  I believe you that the geometry is broken. There are other geometry problems with Sponza that sometimes generate NANs in shaders or unshaded pixels.

**Comment by NicoM1** [comment]
Ah sorry, I mean those specific small areas are solid colour (the top of the banner, and that small cross-beam in the roof). Those are causing (at least some of) the NaNs.

**Comment by NicoM1** [comment]
Found it!

The matrix inverse function is wrong, [1][0] and [0][1] are flipped, when they should not be.

**Comment by NicoM1** [comment]
Here is the result with the inverse function fixed:

![image](https://user-images.githubusercontent.com/6273562/81338243-237f6380-9061-11ea-8239-8ddbdb4c93d3.png)

Here is a Gist with the fix:

https://gist.github.com/NicoM1/4c2944b90601858862d42084be1c3cf2

NOTE: I didn't fix the NaN errors here, as I'm not sure what the correct solution is when we can't solve for these values, so the top of the banner and the cross-beam will still likely have errors, they just aren't noticable.

**Comment by stanard** [comment]
That's it.  Good job.  :-)  I still like your idea better, but they both rely on having two helper rays, which may be problematic for non-primary rays.

**Comment by NicoM1** [comment]
Thanks James! And yes, I won't claim to know the performance best-practices here, I'm just getting started with these libraries - but I'm glad I was able to find the source of that error.

**Comment by NicoM1** [comment]
Also, this same mistake is made here: https://github.com/microsoft/DirectX-Graphics-Samples/blob/5a407bb063bfcb18aceec0788a6dd7eb804c4812/Samples/Desktop/D3D12Raytracing/src/D3D12RaytracingRealTimeDenoisedAmbientOcclusion/RTAO/Shaders/RaytracingShaderHelper.hlsli#L508

Which corrupts all the CalculateUVDerivatives functions in that file, although I couldn't find anywhere that actually uses those functions currently.

**Comment by NicoM1** [comment]
Would you like me to submit a PR fixing those inverse functions, and then we can potentially come back to looking at other approaches at a later time?

Nico.

**Comment by stanard** [comment]
Yes, go ahead.  I've been honing the Math of the old method to see if it reduces down to basically the same thing.  I noticed it uses two extra inputs:  worldPosition and triangleNormal, but I think they can be eliminated.  Please submit the PR while I play with it some more.

**Comment by NicoM1** [comment]
One other useful thing about the way I found is it avoids the NaNs without special handling, because there's no reliance on the UV geometry, they're simply interpolated. 

(Thanks for the merge by the way!)

Nico.

**Comment by stanard** [comment]
Yours only has one division, which is great, and I'm trying to figure out when it could ever be zero except when the triangle is degenerate.  It's also conceptually much simpler, so it's more appropriate for a sample.

Question:  The helper ray planar intersections could be outside the bounds of the triangle. Are any assumptions violated in the barycentric coordinate calculation, e.g. u = 1 - v - w?

**Comment by NicoM1** [comment]
I should double check, because I just grabbed that Barycentric calculation from stackexchange (we can replace it with any other one). But so long as that doesn't make assumptions about being in-triangle, I believe the interpolation should still be correct (because negative barycentric coords should still span the plane?).

**Comment by NicoM1** [comment]
I have a copy of the book referenced (Christer Ericson's Real-Time Collision Detection), and just confirmed that the stackexchange code is exactly what is written there (page 47 if you have access to a copy).

It is written as a generic solution for finding barycentrics, as the solution of a linear system. I don't believe it makes any extra assumptions on the bounds (in fact it's used to test whether a point is inside a triangle, so it must allow external points).

**Comment by stanard** [comment]
I'm familiar with that book (and Christer), and I am fairly certain that you won't find more optimized or more precise algorithms than those found in his book.  And I'm happy to say that having manipulated the Math for both approaches, they come down to essentially the same thing:  they are isomorphic. Conceptually, they are very different, but when you reorganize the formulas, you have the same ALU costs.  One difference I still haven't been able to eliminate is the need to pick a dominant 2D direction based on the triangle normal. But I got the old approach down to a single 2x2 inverse, which is a single reciprocal.  The GPU time is very similar, but I give the edge to your new version.  Here's what I've got so far:

`float2x2 Inverse2x2(float2x2 mat)
{
    const float determinant = mat[0][0] * mat[1][1] - mat[1][0] * mat[0][1];
    return float2x2(mat[1][1], -mat[0][1], -mat[1][0], mat[0][0]) / determinant;
}

void ComputeUVPartialDerivatives(
    float2 uv0, float2 uv1, float2 uv2,
    float3 p0, float3 p1, float3 p2,
    float2 /*uv*/, float3 triangleNormal, float3 worldPosition,
    float3 xOffsetPoint, float3 yOffsetPoint,
    out float2 UVdx, out float2 UVdy)   // Partial derivatives of UV w.r.t. screenspace X and Y
{
    uv0 -= uv2;
    uv1 -= uv2;
    p0 -= p2;
    p1 -= p2;
    xOffsetPoint -= worldPosition;
    yOffsetPoint -= worldPosition;

    const float3 absNormal = abs(triangleNormal);

    if (absNormal.x > max(absNormal.y, absNormal.z))
    {
        p0.xy = p0.yz;
        p1.xy = p1.yz;
        xOffsetPoint.xy = xOffsetPoint.yz;
        yOffsetPoint.xy = yOffsetPoint.yz;
    }
    else if (absNormal.y > absNormal.z)
    {
        p0.xy = p0.zx;
        p1.xy = p1.zx;
        xOffsetPoint.xy = xOffsetPoint.zx;
        yOffsetPoint.xy = yOffsetPoint.zx;
    }

    const float2x2 inverse = mul(Inverse2x2(float2x2(p0.xy, p1.xy)), float2x2(uv0, uv1));
    UVdx = mul(xOffsetPoint.xy, inverse);
    UVdy = mul(yOffsetPoint.xy, inverse);
}`

vs.

`float3 Barycentric(float3 p, float3 a, float3 b, float3 c)
{
    float3 v0 = b - a;
    float3 v1 = c - a;
    float3 v2 = p - a;
    float d00 = dot(v0, v0);
    float d01 = dot(v0, v1);
    float d11 = dot(v1, v1);
    float d20 = dot(v2, v0);
    float d21 = dot(v2, v1);
    float denom = d00 * d11 - d01 * d01;
    float v = (d11 * d20 - d01 * d21) / denom;
    float w = (d00 * d21 - d01 * d20) / denom;
    float u = 1.0 - v - w;
    return float3(u, v, w);
}

void ComputeUVPartialDerivatives(
    float2 uv0, float2 uv1, float2 uv2,
    float3 p0, float3 p1, float3 p2,
    float2 uv, float3 /*triangleNormal*/, float3 /*worldPosition*/,
    float3 xOffsetPoint, float3 yOffsetPoint,
    out float2 UVdx, out float2 UVdy)   // Partial derivatives of UV w.r.t. screenspace X and Y
{
    float3 baryX = Barycentric(xOffsetPoint, p0, p1, p2);
    float3 baryY = Barycentric(yOffsetPoint, p0, p1, p2);
    float3x2 uvMat = float3x2(uv0, uv1, uv2);
    UVdx = mul(baryX, uvMat) - uv;
    UVdy = mul(baryY, uvMat) - uv;
}`

Note that in your version, both barycentric calculations divide by the same value, so it's not recomputed.  I believe your new partial derivative formula is concise, efficient, easy to understand, and has fewer inputs.  Let's check it in!

**Comment by NicoM1** [comment]
Awesome! How do you want to check it in (should I PR with your cleaned up code?). And how should we credit Christer?

Nico.

**Comment by stanard** [comment]
I'm cleaning it up, commenting it, and there is attribution to Christer and his book.  I will make a PR for you to look over.  Okay?

**Comment by stanard** [comment]
https://github.com/microsoft/DirectX-Graphics-Samples/pull/627

**Comment by NicoM1** [comment]
That looks great, thank you! And nice catch on the normal texture.

Thanks for all your help, looking forward to working more with you this summer! Nico.
