### ISSUE TITLE
C++14 std-like directx 12 wrapper? 

### ISSUE THREAD

**Issue by acterhd** [Microsoft/DirectX-Graphics-Samples#63]
Hello. I suggest make C++14 std-like Directx 12 wrapper. 

For example. Declaring UAV:
```
D3D12::Buffer<sometype>  uavbuffer(... );
```
Creating program (function) : 
```
D3D12::Program prog(....);
D3D12::RootTable root;
root[0] = D3D12::Register(... /* 0 as UAV,  in pixel shader */);
auto func = make_compute(program, root, etc... );
```
Calling:
```
func(D3D12::EnqueueArg(queue, count), uavbuffer) //accumulate calls
queue.execute() //execute
queue.finish()
```

**Comment by bobbrow** [comment]
Thank you for the suggestion.  This is outside the scope of this repo, so I am marking it Won't Fix.  This should not prohibit anyone else who so desires to write such a wrapper, but unfortunately we can't field this request at this time.

**Comment by acterhd** [comment]
Where I can send suggest?
