### ISSUE TITLE
access violation while building D3D12nBodyGravity

### ISSUE THREAD

**Issue by prakashyadav008** [microsoft/DirectX-Graphics-Samples#630]
i am trying to build and run the D3D12nBodyGravity sample program and getting "access violation error" at the line specified in the image file attached. 
I am having the same error pop up in all directx programs.
i updated my windows 10 home version and before that there was no error like this. I can say that because i ran the sample programs in the book "game programming with directx 12" and they run without problems but now even those programs are having this error.
![Capture](https://user-images.githubusercontent.com/20148760/81763733-881d4100-94ed-11ea-8b33-91fd538343b4.JPG)
![Capture](https://user-images.githubusercontent.com/20148760/81763749-923f3f80-94ed-11ea-9fb3-ef0dc99460dc.JPG)

**Comment by walbourn** [comment]
The crash is happening the driver, so you should look at updating that. If the samples "ran before and stopped working lately", then that definitely points to a driver issue.
