### ISSUE TITLE
Error 0x80010135: Path too long with Windows 10 standard archiver

### ISSUE THREAD

**Issue by Phantom772** [microsoft/DirectX-Graphics-Samples#632]
Hi,

Encountered this issue while using the legacy extractor which is provided with Windows 10.
I haven't installed any 3rd party archivers yet. I know this can be resolved using those. Just giving a heads up if this isn't already reported. 

Thanks,
![DirectX-Graphics-Samples_extractionError](https://user-images.githubusercontent.com/66490372/83911233-c559a500-a720-11ea-95b9-6e03b8b103f8.png)

**Comment by Link1J** [comment]
Same problem here. 7Zip does not have a problem with extracting it.

**Comment by weltkante** [comment]
You may get problems with the build though if you force extraction this way, so try to extract into a shorter target path. That said some of the really long filenames have been shortened a bit already, so trying again with a newer archive may also help.

**Comment by walbourn** [comment]
The general answer is to extract it to a shorter root path instead of to the download folder or desktop.

See also [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation)

**Comment by Johnblack115** [comment]
Try LongPathTool program.

**Comment by CharlotteAster** [comment]
You can try using a tool like LongPathTool. It helps manage and delete files or folders with long path issues easily.

**Comment by JackyFlint** [comment]
Using LongPathTool makes managing these long paths much easier.
