### ISSUE TITLE
D3D12RaytracingHelloWorld build fails

### ISSUE THREAD

**Issue by DmitryNazarov** [microsoft/DirectX-Graphics-Samples#642]
Other samples (for example D3D12HelloTriangle) compiles and run without errors.
Windows 10 version 2004 SDK 10.0.18362.0

Build output:
`------ Build started: Project: D3D12RaytracingHelloWorld, Configuration: Debug x64 ------
stdafx.cpp
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1831,1): error C2504: 'D3D12_RESOURCE_DESC1': base class undefined
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1833,79): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1833,64): error C2143: syntax error: missing ',' before '&'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1834,31): error C2065: 'o': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1834,9): error C2614: 'CD3DX12_RESOURCE_DESC1': illegal member initialization: 'D3D12_RESOURCE_DESC1' is not a base or member
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1852,9): error C2065: 'Dimension': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1853,9): error C2065: 'Alignment': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1854,9): error C2065: 'Width': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1855,9): error C2065: 'Height': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1856,9): error C2065: 'DepthOrArraySize': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1857,9): error C2065: 'MipLevels': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1858,9): error C2065: 'Format': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1859,9): error C2065: 'SampleDesc': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1860,9): error C2065: 'SampleDesc': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1861,9): error C2065: 'Layout': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1862,9): error C2065: 'Flags': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1863,9): error C2065: 'SamplerFeedbackMipRegion': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1864,9): error C2065: 'SamplerFeedbackMipRegion': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1865,9): error C2065: 'SamplerFeedbackMipRegion': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1927,15): error C2065: 'Dimension': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1927,65): error C2065: 'DepthOrArraySize': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1929,15): error C2065: 'Dimension': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1929,65): error C2065: 'DepthOrArraySize': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1931,48): error C2065: 'Format': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1933,14): error C2065: 'MipLevels': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1935,69): error C2065: 'MipLevels': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1937,51): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1937,51): error C2143: syntax error: missing ',' before '&'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1938,1): error C2803: 'operator ==' must have at least one formal parameter of class type
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1938,1): error C2805: binary 'operator ==' has too few parameters
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1939,12): error C2065: 'l': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1939,27): error C2065: 'r': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1940,9): error C2065: 'l': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1940,24): error C2065: 'r': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1941,9): error C2065: 'l': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1941,20): error C2065: 'r': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1942,9): error C2065: 'l': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1942,21): error C2065: 'r': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1943,9): error C2065: 'l': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1943,31): error C2065: 'r': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1944,9): error C2065: 'l': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1944,24): error C2065: 'r': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1945,9): error C2065: 'l': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1945,21): error C2065: 'r': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1946,9): error C2065: 'l': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1946,31): error C2065: 'r': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1947,9): error C2065: 'l': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1947,33): error C2065: 'r': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1948,9): error C2065: 'l': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1948,21): error C2065: 'r': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1949,9): error C2065: 'l': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1949,20): error C2065: 'r': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1950,9): error C2065: 'l': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1950,45): error C2065: 'r': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1951,9): error C2065: 'l': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1951,46): error C2065: 'r': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1952,9): error C2065: 'l': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1952,45): error C2065: 'r': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1954,51): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1954,51): error C2143: syntax error: missing ',' before '&'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1955,1): error C2803: 'operator !=' must have at least one formal parameter of class type
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1955,1): error C2805: binary 'operator !=' has too few parameters
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1955,13): error C2065: 'l': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(1955,18): error C2065: 'r': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2332,86): error C2065: 'D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_AS': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2332,124): error C2975: 'Type': invalid template argument for 'CD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT', expected compile-time constant expression
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2304): message : see declaration of 'Type'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2332): error C2440: 'specialization': cannot convert from 'int' to 'D3D12_PIPELINE_STATE_SUBOBJECT_TYPE'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2332): message : Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast)
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2332,124): error C2973: 'CD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT': invalid template argument 'int'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2305): message : see declaration of 'CD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2333,86): error C2065: 'D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_MS': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2333,124): error C2975: 'Type': invalid template argument for 'CD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT', expected compile-time constant expression
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2304): message : see declaration of 'Type'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2333): error C2440: 'specialization': cannot convert from 'int' to 'D3D12_PIPELINE_STATE_SUBOBJECT_TYPE'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2333): message : Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast)
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2333,124): error C2973: 'CD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT': invalid template argument 'int'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2305): message : see declaration of 'CD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2475): error C2440: 'specialization': cannot convert from 'int' to 'D3D12_PIPELINE_STATE_SUBOBJECT_TYPE'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2475): message : Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast)
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2475): message : see reference to class template instantiation 'CD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT<D3D12_SHADER_BYTECODE,0,InnerStructType>' being compiled
        with
        [
            InnerStructType=D3D12_SHADER_BYTECODE
        ]
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2475,40): error C2973: 'CD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT': invalid template argument 'int'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2305): message : see declaration of 'CD3DX12_PIPELINE_STATE_STREAM_SUBOBJECT'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2979,14): error C2065: 'D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_AS': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2983,14): error C2065: 'D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_MS': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2979,1): error C2051: case expression not constant
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(2983,1): error C2051: case expression not constant
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(3739,78): error C2061: syntax error: identifier 'D3D12_RAYTRACING_PIPELINE_FLAGS'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(3749,53): error C2833: 'operator D3D12_RAYTRACING_PIPELINE_CONFIG1' is not a recognized operator or type
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(3749,53): error C2059: syntax error: 'newline'
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(3749,72): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(3757,45): error C3646: 'm_Desc': unknown override specifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(3757,45): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(3741,9): error C2065: 'm_Desc': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(3742,9): error C2065: 'm_Desc': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(3742,24): error C2065: 'Flags': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(3746,16): error C2065: 'D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_PIPELINE_CONFIG1': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(3754,9): error C2065: 'm_Desc': undeclared identifier
some_path\DirectX-Graphics-Samples-master\Libraries\D3DX12\d3dx12.h(3756,46): error C2065: 'm_Desc': undeclared identifier
Done building project "D3D12RaytracingHelloWorld.vcxproj" -- FAILED.`

**Comment by walbourn** [comment]
The  D3DX12.H header was updated for the latest version, which requires Windows 10 SDK (19041).
