### ISSUE TITLE
D3D12RayTracingHelloWorld failing during build

### ISSUE THREAD

**Issue by KyleGrau** [microsoft/DirectX-Graphics-Samples#648]
Hi,

I am trying to run the sample projects for DXRaytracing and am encountering the following error. Where is this file generated? I've read the documentation, and either missed something, or could not find any other additional steps I should be taking.

1>  The system cannot find the path specified. obj\x64\Debug\\CompiledShaders\Raytracing.hlsl.h
1>
1>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1532,5): error MSB6006: "dxc.exe" exited with code 1.

**Comment by KyleGrau** [comment]
Disregard.

**Comment by garlique** [comment]
Wait, how did you fix this?

**Comment by KyleGrau** [comment]
It's been two weeks, but i think the issue is that the CompiledShaders folder didn't exist, when you add it, it magically works. Not sure why the build process isn't making these directories.

**Comment by garlique** [comment]
Yeah, I ended up doing the same, pretty ridiculous that it can't make the folder on its own. Thanks!
