### ISSUE TITLE
D3D12RayTracingHelloWorld failing during build

### ISSUE THREAD

**Issue by garlique** [microsoft/DirectX-Graphics-Samples#655]
> 
> 
> Hi,
> 
> I am trying to run the sample projects for DXRaytracing and am encountering the following error. Where is this file generated? I've read the documentation, and either missed something, or could not find any other additional steps I should be taking.
> 
> 1> The system cannot find the path specified. obj\x64\Debug\CompiledShaders\Raytracing.hlsl.h
> 1>
> 1> C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1532,5): error MSB6006: "dxc.exe" exited with code 1.

Originally posted by Kyle. Same issue. Visual Studio 2019, latest SDK (from Windows 2004), latest everything. Nothing modified. It should work out of the box, it doesn't. What gives?

Also a bunch of these:
```
1>failed writing C:\Users\garlique\DXGS\MiniEngine\Build_VS16\x64\Debug\Output\Core\CompiledShaders\AoBlurUpsampleBlendOutCS.h
1>failed writing C:\Users\garlique\DXGS\MiniEngine\Build_VS16\x64\Debug\Output\Core\CompiledShaders\AoBlurUpsampleCS.h
1>failed writing C:\Users\garlique\DXGS\MiniEngine\Build_VS16\x64\Debug\Output\Core\CompiledShaders\AoBlurUpsamplePreMinBlendOutCS.h
1>failed writing C:\Users\garlique\DXGS\MiniEngine\Build_VS16\x64\Debug\Output\Core\CompiledShaders\AoBlurUpsamplePreMinCS.h
1>failed writing C:\Users\garlique\DXGS\MiniEngine\Build_VS16\x64\Debug\Output\Core\CompiledShaders\AoPrepareDepthBuffers1CS.h
1>failed writing C:\Users\garlique\DXGS\MiniEngine\Build_VS16\x64\Debug\Output\Core\CompiledShaders\AoPrepareDepthBuffers2CS.h
1>failed writing C:\Users\garlique\DXGS\MiniEngine\Build_VS16\x64\Debug\Output\Core\CompiledShaders\AoRender1CS.h
...
```

**Comment by garlique** [comment]
Fixed it. You failed to add a `CompiledShaders` folder to `..../Output/Core/`. Ridiculous.

**Comment by stanard** [comment]
I suspect this might be a new behavior of DXC since updating from the FXC shader compiler.  This didn't used to be a problem.  The output path for the compiled header is somewhere in the Build path, which isn't stored in the repo.  I'm not sure what the best mechanism is to make sure the output folder exists, but I'll look into it.

Please excuse our missing this as we don't often clone a new repository, so this problem didn't immediately jump out at us.
