### ISSUE TITLE
Documentation Inconsistencies in the repo README.md 

### ISSUE THREAD

**Issue by PriyanshJalan** [microsoft/DirectX-Graphics-Samples#656]
I found some outdated information on the repo README. 

In https://github.com/microsoft/DirectX-Graphics-Samples#develop-branch
- Windows has moved towards a new naming scheme of channels. The naming scheme needs to be updated to reflect on those changes. [Fast ring to Dev channel]
- Broken Insider link as a result of this revamp

In https://github.com/microsoft/DirectX-Graphics-Samples#contributing 
 - The blog link points to the old link and should be updated to https://devblogs.microsoft.com/directx/ or be removed as the blog link is already mentioned.
 - The Wiki has not been updated since quite a while, if it will be maintained then ``Troubleshooting information for this repository can be found in the site Wiki.`` should be mentioned in the top or if it will not be maintained, it can be removed.

**Comment by sebmerry** [comment]
@PriyanshJalan thank you for pointing this out!  I have pushed new changes that should resolve the issue.
