### ISSUE TITLE
raytracing sample hlsl compile fail

### ISSUE THREAD

**Issue by toughbro** [microsoft/DirectX-Graphics-Samples#657]
`1>    Environment Variables passed to tool:
1>      TRACKER_CONSOLEPAGE=65001
1>    C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86\dxc.exe /nologo /T lib_6_3 /Fh "obj\x64\Debug\\CompiledShaders\Raytracing.hlsl.h" /Fo "bin\x64\Debug\Raytracing.cso" /Vn "g_pRaytracing" /Od /Zi Raytracing.hlsl
1>    Tracking command:
1>    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Tracker.exe /d "C:\Program Files (x86)\MSBuild\15.0\FileTracker\FileTracker32.dll" /i D:\dev\github\DirectX-Graphics-Samples\Samples\Desktop\D3D12Raytracing\src\D3D12RaytracingHelloWorld\obj\x64\Debug\D3D12Ray.5018F6A3.tlog /r D:\DEV\GITHUB\DIRECTX-GRAPHICS-SAMPLES\SAMPLES\DESKTOP\D3D12RAYTRACING\SRC\D3D12RAYTRACINGHELLOWORLD\RAYTRACING.HLSL /b MSBuildConsole_CancelEvent4eeb68d187cd46a1b81015d545bb1371  /c "C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86\dxc.exe"  /nologo /T lib_6_3 /Fh "obj\x64\Debug\\CompiledShaders\Raytracing.hlsl.h" /Fo "bin\x64\Debug\Raytracing.cso" /Vn "g_pRaytracing" /Od /Zi Raytracing.hlsl
1>    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1532,5): error MSB6006: "dxc.exe" exited with code -1073741819.`

can't get what does the error code means.
anyone can help?
thx

**Comment by toughbro** [comment]
finally, i got this fixed;
seems visual studio have some problems on creating the ouput folder:
"CompiledShaders" in $(IntDir)\CompiledShaders\%(Filename).hlsl.h
after creating one myself, everything goes well;

**Comment by LigaLiao** [comment]
I have the same problem.
This happens in the latest version of Windows and VS.

**Comment by yzdna** [comment]
Me too.  Visual studio 2019 + Win 10.

Microsoft Visual Studio Professional 2019
Version 16.7.6
VisualStudio.16.Release/16.7.6+30611.23
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA133
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

C# Tools   3.7.0-6.20459.4+7ee7c540e3bf19765695b1331c946ddf986d1516
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.7.20248.6
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.7.20248.6
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.7.20248.6
Conda support for Python projects.

Python - Django support   16.7.20248.6
Provides templates and integration for the Django web framework.

Python - IronPython support   16.7.20248.6
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.7.20248.6
Profiling support for Python projects.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-6.20459.4+7ee7c540e3bf19765695b1331c946ddf986d1516
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

**Comment by daemyung** [comment]
@toughbro You save my life! Thanks bro!

**Comment by longod** [comment]
This VS's bug.
https://developercommunity.visualstudio.com/content/problem/1145832/typo-in-fxc-target-in-vs-1671.html

**Comment by walbourn** [comment]
This was fixed in VS 2019 (16.8)

https://developercommunity.visualstudio.com/t/hlsl-shader-compiler-fails-to-create-output-direct/1143412
