### ISSUE TITLE
Project files on VS 2019, solution files need updating

### ISSUE THREAD

**Issue by jpark37** [microsoft/DirectX-Graphics-Samples#659]
D3D12HelloWorld.sln opens with VS 2017, but I don't think that's the only solution file that needs updating. The projects were updated by this commit: ca3f7f4e0a73b69f96371fef0f4a08958b278936

**Comment by walbourn** [comment]
Basically someone needs to update all the SLNs so that:

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
```

is changed to:

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
```

Note that VS 2019 also accepts the older syntax, but the one above is how it creates new solutions

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 16
```

**Comment by sebmerry** [comment]
Thanks for pointing this out, I'll take a look and get them updated.

**Comment by walbourn** [comment]
The sample is VS 2019 v142 now.
