### ISSUE TITLE
Missing Smooth Animation Functionality

### ISSUE THREAD

**Issue by sherief** [microsoft/DirectX-Graphics-Samples#661]
I would like to have a keyboard-triggered animation similar to the Quake console effect. However, I don't want to burn power rendering frames all the time - this is a well behaved app, so it sleeps with an empty present queue waiting for the WM_KEYDOWN.

I would also like the animation to be smooth and responsive relative to real-time, so when running at 30 or 60 Hz I don't do a loop of checking inputs and bucketing all the inputs that happen between two ticks in a bucket - so unlike how most games attribute input to "game tick 42" where they run at a fixed tick rate, giving each input event a timestamp precision of at most one tick duration, my application timestamps every input event, so hitting tilde or whichever keys that trigger the animation early in the frame should yield a different result on the next rendered frame versus hitting it later.

Consider a very low refresh rate display at 10 Hz and the advantage of timing the animation based on exactly when the input arrived versus which general tick period it arrived would make a visible difference. At 60 Hz it's subtle but still there.

Here's the problem: no functionality in DXGI or D3D12 allows me to query when would the next frame added to the present queue be visible. I understand that the best that can be promised is "if you immediately Present1() now you'll _probably_ be displayed at QPC time X", so reading from such an API before rendering the animated frame means I'll have to query it again before the Present1() call to see if I made it in time or not. I also understand that all this is best-effort promises since a Windows machine isn't a real-time system. 

Ideally, I'd like to do something like this:
```
begin:
PTime = SwapChain->GetNextPresentDisplayQPCTime();
BuildSceneCommandListForTime(PTime);
ExecuteCommandLists();
if(PTime == SwapChain->GetNextPresentDisplayQPCTime()) Present1(); else goto begin;
```

Is there some existing functionality that I missed? On a fixed refresh rate display I can predict / guess based on the DXGI_FRAME_STATISTICS but this is very fragile and not usable in practice, and it won't work at all for VRR displays.

**Comment by walbourn** [comment]
You should take this question to the [DirectX Discord Channel](https://discord.gg/directx).

**Comment by sherief** [comment]
A year later, ten words and none of them are "IPresentationManager" - tsk tsk.
