### ISSUE TITLE
FallbackLayer build error on RX 580

### ISSUE THREAD

**Issue by Microsista** [microsoft/DirectX-Graphics-Samples#677]
Is there any way to get rid of this error?
![image](https://user-images.githubusercontent.com/8358987/101236053-2a8d5380-36ce-11eb-81a3-c276855d72f5.png)
I have tried modifying these values, but it didn't help:
![image](https://user-images.githubusercontent.com/8358987/101236092-9374cb80-36ce-11eb-8f58-4c2f4c436a89.png)

**Comment by walbourn** [comment]
The fallback layer has not been updated in some time as it's deprecated. DXC does not support `/O4` so change it to `/O3`.
