### ISSUE TITLE
ModelConverter doesnt compile with Nuget packages

### ISSUE THREAD

**Issue by jonny2027** [microsoft/DirectX-Graphics-Samples#678]
I'm having problems getting the Model Converter project to compile. I have updated it to VS2019,  fixed the zlib directory issue but even after setting the Include and library directories and setting the linker additional dependencies I still end up with unresolved external symbol errors.

Is it still possible to compile the Model Converter project?

**Comment by walbourn** [comment]
What are the errors?

**Comment by stanard** [comment]
I don't know what broke, but it should be possible to revive. Please be aware that it hasn't been maintained in quite some time and is overdue for replacement by the glTF 2.0 asset system.  Code for that should still be in a branch labeled "glTF".
