### ISSUE TITLE
MiniEngine crashes on compile

### ISSUE THREAD

**Issue by tjukic** [Microsoft/DirectX-Graphics-Samples#68]
Compiler crashes when building MiniEngine (VS2015Update1 default cmplr.).

"1>  GraphicsCore.cpp
1>  Generating Code...
1>c:\program files (x86)\microsoft visual studio 14.0\vc\include\xmemory0(909): fatal error C1001: An internal error has occurred in the compiler.
1>  (compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 246)
1>   To work around this problem, try simplifying or changing the program near the locations listed above.
1>  Please choose the Technical Support command on the Visual C++
1>   Help menu, or open the Technical Support help file for more information
1>    CL!InvokeCompilerPass()+0x2d4bd
1>    CL!DllGetC2Telemetry()+0xae663
1>
"

**Comment by tjukic** [comment]
Seems that improper update caused this issue.

**Comment by jpvanoosten** [comment]
@tjukic can you please be more clear about 
> Seems that improper update caused this issue.

**Comment by tjukic** [comment]
I was not able to find the root cause in a timely manner so I cut it and fallen back to downloading a full zip of the project (blog link) and reverting my w10dx12 test machine to a clean state just post VS2015 update 1 installation.
The build did not fail on "Generating code..." line like it did earlier so I assumed there was an error in the process of either project source git fetch or VS2015 update 1 application done prior to project fetch.

Today (2015/12/07) I will test a working (non-clean) machine with a clean project clone and report my findings (if any) here.

**Comment by bobbrow** [comment]
I just hit this today on one of my machines too.  Did you happen to have one of the RC versions of Update 1 installed before taking the final released version?  I'm going to try to track this down as it appears to be more common a problem than it should be based on the reports I'm seeing here.

**Comment by tjukic** [comment]
OK, so: the git source does not work, but a ZIP available does:
![thisoneworkscapture](https://cloud.githubusercontent.com/assets/246141/11636907/cffa5484-9d1e-11e5-93cd-3b6cb76fce8b.PNG)

I am not at all certain why. Haven't yet checked for diff so don't take my word for it that it is the same source (an updated ZIP).

**Comment by bobbrow** [comment]
In my testing I have noticed that only the Profile and Release configs are the ones that fail to compile.  Debug seems to compile and run ok.  You can try using this config for now until I get some more information from the Visual Studio team.

**Comment by tjukic** [comment]
Yes, Debug seems to be fine, other fail. Sure. Ty, let's hope for a fast solution. :)

**Comment by jpvanoosten** [comment]
Disabling optimizations (/Od) is a workaround for profile and release builds. No other changes to the configurations need to be made to workaround this issue.

**Comment by jpvanoosten** [comment]
Today I completely uninstalled Visual Studio 2015 and reinstalled from scratch (including the Windows 10 SDK) and the issue persists. I hope to have a fix from the VS dev team in the near future.

**Comment by tjukic** [comment]
Even with disabled optimizations, there is an error on code generation step. @bobbrow any idea why?

**Comment by bobbrow** [comment]
Not yet.  I filed a bug report to the compiler team, but I haven't heard back yet.

**Comment by etherton** [comment]
I can confirm with a brand new Windows 10 / DevStudio 2015 Professional install (the latter just a few hours old), I get the ICE as well in Release builds of the model viewer.

**Comment by etherton** [comment]
One easy repro is task<ByteArray> Utility::ReadFileAsync(const wstring& fileName) at the bottom of FileUtility.cpp; comment that out and once ICE disappears.

**Comment by bobbrow** [comment]
The VS team found the bug.  The /FAs switch was the culprit.  I removed it and pulled this workaround to master.  Everyone should be unblocked on Profile and Release configs now.
