### ISSUE TITLE
[Question] The "Load3x16BitIndices" function in RaytracingSimpleLighting

### ISSUE THREAD

**Issue by Talesofwing** [microsoft/DirectX-Graphics-Samples#680]
Hello everyone.

```
uint3 Load3x16BitIndices (uint offsetBytes) {
    uint3 indices;

    const uint dwordAlignedOffset = offsetBytes & ~3;
    const uint2 four16BitIndices = Indices.Load2 (dwordAlignedOffset);

    if (dwordAlignedOffset == offsetBytes) {
        indices.x = four16BitIndices.x & 0xffff;
        indices.y = (four16BitIndices.x >> 16) & 0xffff;
        indices.z = four16BitIndices.y & 0xffff;
    } else {
        indices.x = (four16BitIndices.x >> 16) & 0xffff;
        indices.y = four16BitIndices.y & 0xffff;
        indices.z = (four16BitIndices.y >> 16) & 0xffff;
    }

    return indices;
}

[shader ("closesthit")]
void MyClosestHitShader (inout RayPayload payload, in MyAttributes attr) {
  // ...
 
  const uint3 indices = Load3x16BitIndices (baseIndex);
  
  float3 vertexNormals[3] = {
      Vertices[indices[0]].normal,
      Vertices[indices[1]].normal,
      Vertices[indices[2]].normal
   };

  // ...
}
```

I don't understand why using uint3 does not require masking the high digit value.

For instance:
- Load3x16BitIndices (0);
- We get this
[0][1][2][3] [4][5][0][0]

- first index [0][1][2][3]
- second index [2][3][0][0]
- final index [4][5][0][0]

Isn't the first index wrong?

Thanks.

**Comment by stanard** [comment]
Load3x16BitIndices() reads 64 bits (2 x uint32_t) and returns 3 x 16-bit values.  Initially, you have four 16-bit values to work with, but based on the alignment of the read, you either return .xyz or .yzw.  Each uint32_t is split into two uint16_t using shifts and masks.  So even though the return type is uint3, each value can be no larger than 65535.

If you have these 16-bit indices in an index buffer:  [0, 1, 2, 3, 4, 5, 0, 0], then:

Load3x16BitIndices(0) -> [0, 1, 2]
Load3x16BitIndices(6) -> [3, 4, 5]

An index is not four 16-bit words; it's a single 16-bit word.  And this function returns three indices as uint3.

**Comment by Talesofwing** [comment]
Ok, thank you very much.

I mistaked "0xffff" for 32 bits.
