### ISSUE TITLE
When will the GLTF branch be integrated back to main?

### ISSUE THREAD

**Issue by aofer** [microsoft/DirectX-Graphics-Samples#689]
I've seen it was developed a long time ago, are there still plans to bring it to main?

**Comment by stanard** [comment]
The author of MiniEngine (me) is not a regular contributor or maintainer of this repo.  I developed this glTF revision to support more robust content and physically based rendering. But I didn't integrate it into the main branch soon enough, and other projects such as the Sponza DXR sample now depend on MiniEngine (I think). It would require some time to test and update a merge from that very old branch.  That being said, I don't have a lot of time for that right now, but I hope to one day have some time budgeted for this long overdue upkeep.

**Comment by aofer** [comment]
Was thinking of trying to do it myself, haven't really put any time into looking at how much they diverge, from glancing at it seems most of the GLTF stuff is self contained with the big changes in ModelViewer.cpp.
If I done this merge myself, in a way that hopefully doesn't break newer stuff (where can I see what depends on ModelViewer?), what are my chances to actually get this pull reuqest approved and integrated before it starts diverging again?
Trying to understand if this will be worth the effort

**Comment by aofer** [comment]
The GLTF branch basically extracts the renderer into SponzaRenderer, in order to merge the GLTF branch into main the best way will probably be the other way, to extract the PBR and GLTF stuff into a GLTF Model viewer or something simliar.

**Comment by stanard** [comment]
That would be helpful, actually. If you did the merge and looked for other dependencies within the repo, I'd look over your pull request and likely approve it. Thanks for the offer!

**Comment by aofer** [comment]
I spent around two hours trying to merge gltf2 into master with an integration branch, trying to resolve all conflicts and making it compile and run. git didn't handle that merge so well, it seems now that my initial idea of trying to manually integrate the gltf stuff might work better.

**Comment by aofer** [comment]
Hey, would like to give it another go and would appreciate your opinion on this, I see that there's alot of stuff that were changed in graphicsCore\GameCore\GraphicsCommon for the GLTF branch and some stuff were even deleted like the DynamicUploadBuffer, not sure why but by just merging the branches it really breaks a lot of stuff that I need to bring back, do you remember what was the thought behind some of those larger changes and deleted files? Do you think it would be safer and easier to just bring that functionality manually from the GLTF branch then continue fixing my merged code until it works?

Obviously I can dig in gitforce history and compare but I figured asking would take less time, I don't have a lot of time to work on this but I feel its something a lot of people that use the engine can find useful.

**Comment by stanard** [comment]
Hi. Given the difficulty of porting the gltf2 branch, I think it's probably best I handle the merge. I'll try to make time for it soon.

The absence of DynamicUploadBuffer is indicative that I found better ways to do that, like with the LinearAllocator. But as I alluded to earlier, I think I have a newer version of that class (probably with a new name) which is usable for uploading any data to the GPU.  I don't recall any functionality being removed.  It was a lot of new functionality, actually.

I'll ping back when it's done.  Thanks for your patience.  :-)

**Comment by aofer** [comment]
That would be really great if you can make time for it, I'm sure its going to be useful to many mini engine users. Thanks!

**Comment by stanard** [comment]
This work is done now.  It was a bit messy, but there you go!  :-)

Btw, if you want to test out the glTF2 model loading, you can download samples from:
   https://github.com/KhronosGroup/glTF-Sample-Models
   
On the ModelViewer command line, add "-model <path_to_gltf2_file>".  This works for most of the samples and even supports animation, but I tested a glb model that had textures embedded in the binary, and that's not supported yet. It will load, but textures will be missing.

**Comment by aofer** [comment]
Awesome, thanks for doing this.
I'll make sure to check it out this weekend
