### ISSUE TITLE
[Question] Overview of how to use DynamicUploadBuffer?

### ISSUE THREAD

**Issue by vulkan101** [microsoft/DirectX-Graphics-Samples#692]
Are there any examples showing how to use `DynamicUploadBuffer` in the MiniEngine? I'm trying to update (part of) the contents of a `StructuredBuffer` and not sure if I can use `DynamicUploadBuffer` to do it?

Any help here would be really appreciated! I've got a similar situation in Vulkan where I can create a staging buffer and copy from that into the GPU resource, but with the `DynamicUploadBuffer` I'm not sure how to use it as it only seems to be able to be created and mapped?

**Comment by stanard** [comment]
I think I used it in other projects, but if you can't find any examples, it's basically just a wrapper around an upload heap and an SRV.  You map it, copy into the mapped memory, unmap it, and then set it as an SRV to your shader. An upload heap is CPU-writeable and GPU-readable (write combined memory). You can modify it each frame, but there will be synchronization, so you can't modify it for each Draw or Dispatch because it will cause numerous stalls.

**Comment by vulkan101** [comment]
Thanks, I found another method in the MiniEngine (`CommandContext::WriteBuffer`) that's made life very simple - in the example below `m_TransformBuffer` is a `StructuredBuffer` and `m_TransformUploadBuffer` is the `DynamicUploadBuffer`. I call it once per frame and it lets me update a portion of the current buffer (it's hardcoded to update index 1 for testing):

``` 
float* buffer = (float*)m_TransformUploadBuffer.Map();
memcpy(buffer, &rotated_matrix, 16 * sizeof(float));
auto index = 1;
ComputeContext& Ctx = ComputeContext::Begin(L"Upload Test");

Ctx.WriteBuffer(m_TransformBuffer, index * sizeof(float) * 16, buffer, 16 * sizeof(float));
Ctx.Finish(true);
m_TransformUploadBuffer.Unmap();
```
any comments on how to improve the above would be welcome!

**Comment by vulkan101** [comment]
Just one other thing @stanard, you mention `DynamicUploadBuffer` is a wrapper around an upload heap and an SRV, but  I  couldn't see how to get an SRV from it, at least in the same way as a GpuBuffer? 
As a newbie I'm comparing `GpuBuffer::getSRV` which returns a `D3D12_CPU_DESCRIPTOR_HANDLE`, are `DynamicUploadBuffer::VertexBufferView()` and `IndexBufferView()` equivalent to this? 
I wasn't sure (still aren't tbh) what I would do with these, especially in the context of trying to update part of an existing buffer - if you could outline with some pseudocode including how the binding might look,  that would be really helpful!

I'm guessing now, that if `VertexBufferView()` is a generic SRV to be used for say an array of floats, I would give  `VertexBufferView` the offset into the buffer I'm trying to update? Would I put the data I'm uploading into that offset in the mapped resource as well, or could I do as above and create a small buffer large enough for my update buffer? (If I'm on the right track, obviously)

**Comment by stanard** [comment]
Oh, you're right.  I just looked.  This is an older form of the class I was describing. This version was more graphics-based and supports vertex and index buffer views as well as a raw pointer (which could be used for a root CBV). This could be used as a root SRV (ByteAddressBuffer) too which only takes a pointer.
