### ISSUE TITLE
CreateNewSolution and CreateNewLibrary dont work properly, AppTemplate needs to be updated

### ISSUE THREAD

**Issue by aofer** [microsoft/DirectX-Graphics-Samples#696]
Hey, I'm having issues creating a new solution that uses the engine.
There are a couple of new issues related to project version changes and property sheets.
For example, when a new solution is created from the appTemplate it looks for Core_VS15.vcxproj which is now Core.vcxproj.
Another issue is that the newly created project is looking for VS15.props in the propertySheets folder which no longer exists.

**Comment by stanard** [comment]
Sorry.  I overlooked those templates.  They also need to be modernized.  I'll see if I can fix those quickly for you.

**Comment by stanard** [comment]
Try again.  I did my best to refresh the templates.

**Comment by aofer** [comment]
Works great! thanks!
