### ISSUE TITLE
D3D12on7 is compatible with 8.1

### ISSUE THREAD

**Issue by Jaguarek62** [microsoft/DirectX-Graphics-Samples#699]
Why did you guys left 8.1 stranded when it can be easily fixed? i removed your blocking code for nt 6.2 and nt 6.3 and all d3d12on7 games launch on windows 8.

Just why did you do that???

proof: https://www.youtube.com/watch?v=RtZ3R-738fw
https://www.youtube.com/watch?v=HGuQ4SZVSWc

**Comment by shawnhar** [comment]
The Windows 7 version of D3D12.DLL was designed to only be loaded and executed on Windows 7 SP1.  Win8 was not our target.

**Comment by walbourn** [comment]
As to your question "why?", a quick look at the [Steam Hardware Survey](https://store.steampowered.com/hwsurvey) should answer that...

**Comment by trlkly** [comment]
That's not an answer. Just because Windows 7 was your target doesn't explain blocking Windows 8.1 on systems on which is works. You can not support something without directly blocking it.

**Comment by walbourn** [comment]
I'm sorry you are not satisfied with that answer.

It's more correct to say that Microsoft *strongly* encouraged and incented with free upgrades all users of Windows 8.1 to move to Windows 10. Steam numbers tracked that pretty well (at least for gamers).

Windows 8.0 and Windows 8.1 reached end of 'mainstream' support in January 2018. The "extended" support is primarily for Enterprise scenarios, although it does include security updates for all users.

**Comment by Jaguarek62** [comment]
Are you serious? Windows 7 was almost EOL. You did this blockade on purpose to boost windows 10 marketshare even more.

**Comment by walbourn** [comment]
Windows 7 remains important to major publishers for emerging markets like South Korea, China, etc. Historically these markets were stuck on Windows XP and ignored Windows Vista, and have now moved on to Windows 7.

Based on the Steam data I linked to, there's little to no usage of Windows 8.x among gamers. As such, the business case just isn't there.
