### ISSUE TITLE
Device removal has been triggered

### ISSUE THREAD

**Issue by jpvanoosten** [Microsoft/DirectX-Graphics-Samples#70]
I'm using MiniEngine core library to create a DX12 experiment for my master thesis.

In my experiment, I am creating a StructuredBuffer for the dynamic lights in the scene. I want to be able to resize the StructuredBuffer if I add lights (or reduce the StructuredBuffer if I remove lights). In my implementation of the IGameApp class, I override the Update function and in that function the light buffer will be resized if the user presses a key on the keyboard. To resize the buffer, the `GpuBuffer::Create` method is used on the StructuredBuffer object. The StructuredBuffer object is not destroyed, only the Create method is used to recreate the buffer resource.

The problem is that (seemingly randomly but is more easily reproducible with larger buffers) a device removal is triggered:
```
D3D12: Removing Device.
D3D12 ERROR: ID3D12Device::RemoveDevice: Device removal has been triggered for the following reason (DXGI_ERROR_DEVICE_HUNG: The Device took an unreasonable amount of time to execute its commands, or the hardware crashed/hung. As a result, the TDR (Timeout Detection and Recovery) mechanism has been triggered. The current Device Context was executing commands when the hang occurred. The application may want to respawn and fallback to less aggressive use of the display hardware). [ EXECUTION ERROR #232: DEVICE_REMOVAL_PROCESS_AT_FAULT]
D3D12: **BREAK** enabled for the previous message, which was: [ ERROR EXECUTION #232: DEVICE_REMOVAL_PROCESS_AT_FAULT ]
```
The error occurs 100% in the `CommandListManager::ExecuteCommandList` method when the `m_CommandQueue->ExecuteCommandLists` gets invoked.

The size of the StructuredBuffer doesn't seem to matter. It happens if I only have 10 lights (1 KB) or 32 lights (3.5 KB) but the more lights, the more likely the timeout will occur. I suspect it's a threading issue as device removal should not occur when uploading only a few KB to a structured buffer.

Any ideas?

**Comment by bobbrow** [comment]
I have forwarded your question to James.  He will post a response for you.

**Comment by stanard** [comment]
Are you waiting for the GPU to be done using the resource before recreating it?  The StructuredBuffer and other GpuResource objects hold a reference counted pointer (ComPtr) to the underlying D3D object.  When Create() is called, the existing pointer is released, and D3D is free to reclaim the memory immediately.  Before destroying or recreating resources, it's a good idea to idle the GPU, which will flush all pending command lists and make sure that the resource's memory will no longer be needed by the GPU.  There is a method you can call to do this:  g_CommandManager.IdleGPU().  There is an example of calling this whenever the native resolution is changed before resizing all of the render targets.  I hope that fixes your problem.  Best of luck!

**Comment by jpvanoosten** [comment]
@stanard Thanks for the tip! I figured it was something like this. I was thinking of double-buffering the StructuredBuffer in my application so that I don't destroy the one being used by the GPU before it is finished with it but I like your solution better.

To fix this, I added `g_CommandManager.IdleGPU()` call in the `GpuBuffer::Create` method just before the resource is created [on line 40](https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/MiniEngine/Core/GpuBuffer.cpp#L40-L42). This fixed the issue with minimal overhead.

Is this the best solution? Or is there a better way? For example, something similar to the double-buffer solution but delay the deletion of the resource until after the GPU frame is complete? Maybe enqueue the resource on a "delete queue" which is processed at the end of the frame? Maybe the delete queue is processed in a separate thread so the main thread does not need to stall while it waits for the GPU to finish with the resource?

**Comment by stanard** [comment]
Idling the GPU is a non-optimal solution.  You don't want to do it every frame, and if you are creating multiple resources, you wouldn't need to keep idling the GPU.  It's really only in the Destroy() method that you need the idle, as new resources won't have been referenced by the GPU yet.

I think a better solution for you is to use the LinearAllocator class.  If the size of your buffer varies each frame, you can allocate just what you need each time.  You could have a variable number of buffers of different sizes each frame, and the memory gets recycled automatically.  But they are associated with a command context so that they can query whether its fence has transpired and it's safe to reclaim.  (Note that all you need is a GPU virtual pointer to read and write a StructuredBuffer so long as you use root entries to bind it to your shader.)

If you are only changing the size once per frame, a double or triple buffer scheme would possibly be the simplest approach to guarantee safety.
