### ISSUE TITLE
Linkage issues when creating a new solution and trying to import the Model project

### ISSUE THREAD

**Issue by aofer** [microsoft/DirectX-Graphics-Samples#701]
Hey, I'm trying to create a new solution that uses both Core and Model.
I'm using the bat script to create a new solution and then I'm adding the existing Model project, adding a reference under my own project for Model and adding DirectXTex.lib in the Linker->Input and adding both DirectXTex lib and DirectXMesh lib in Linker->General.
Basically I went through the entire project config and compared with the ModelViewer project and solution.
When trying to build my own new solution I keep getting these linking issues:
```
2>DirectXTex.lib(DirectXTexImage.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Main.obj
2>DirectXTex.lib(DirectXTexImage.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in Main.obj
```
And then there are some linking issues with core.lib which I assume are a result of the previous issue.
Now I did some reading on these but I can't seem to find where this is being defined in my solution and how its different than the modelViewer solution, I tried repeating the process a second time but ended up with the same results.
I also looked at the prop files etc.

I'm guessing it something really small that I'm missing, do you have a clue where I should look for this definition?

Thanks

**Comment by walbourn** [comment]
This indicates the project and the static library don't have matching settings for ``/MD`` / ``/MDd`` vs. ``/MT`` / ``/MTd``.

In Visual Studio this is in the project properties under *C/C++* -> *Code Generation* -> *Runtime Library".

The default is to use ``Multi-threaded Debug DLL (/MDd)`` for Debug and ``Multi-threaded DLL (/MD)`` for Release as static CRT linking is not recommended for most cases.

> For PC, could use the NuGet packages for DirectXTex and DirectXMesh instead of having them built directly in the project.

**Comment by aofer** [comment]
Yeah, that's what I have in the settings, which is exactly what ModelViewer is using and I'm linking the same libs

**Comment by aofer** [comment]
Well using Nuget did help.
Now I'm just getting these weird linkage issues with Core.lib that I didn't have before I added Model:
`>Core.lib(FileUtility.obj) : error LNK2019: unresolved external symbol inflate referenced in function "class std::shared_ptr<class std::vector<unsigned char,class std::allocator<unsigned char> > > __cdecl Inflate(class std::shared_ptr<class std::vector<unsigned char,class std::allocator<unsigned char> > >,int &,unsigned int)" (?Inflate@@YA?AV?$shared_ptr@V?$vector@EV?$allocator@E@std@@@std@@@std@@V12@AEAHI@Z)
2>Core.lib(FileUtility.obj) : error LNK2019: unresolved external symbol inflateEnd referenced in function "class std::shared_ptr<class std::vector<unsigned char,class std::allocator<unsigned char> > > __cdecl Inflate(class std::shared_ptr<class std::vector<unsigned char,class std::allocator<unsigned char> > >,int &,unsigned int)" (?Inflate@@YA?AV?$shared_ptr@V?$vector@EV?$allocator@E@std@@@std@@@std@@V12@AEAHI@Z)
2>Core.lib(FileUtility.obj) : error LNK2019: unresolved external symbol inflateInit2_ referenced in function "class std::shared_ptr<class std::vector<unsigned char,class std::allocator<unsigned char> > > __cdecl Inflate(class std::shared_ptr<class std::vector<unsigned char,class std::allocator<unsigned char> > >,int &,unsigned int)" (?Inflate@@YA?AV?$shared_ptr@V?$vector@EV?$allocator@E@std@@@std@@@std@@V12@AEAHI@Z)`
