### ISSUE TITLE
Guidelines on resource barrier.

### ISSUE THREAD

**Issue by karansapra** [microsoft/DirectX-Graphics-Samples#707]
I am working on a shader that I ported from DX11. My shader has multiple phases inside the shader and based on the resource, I decide the action and UAV's that will get written too. I am just getting my head around DX12 and resource barrier, and I was wondering if there is a better solution than me having a bunch of if statements to decide the barrier resource based on the phase. Can I use barriers on all resources.

**Comment by DrGr4f1x** [comment]
Yes, you can use barriers on all resources.  In fact you should do this,
and are required to in many circumstances.  DX12 allows you to (and
requires you to) manage resource transitions yourself.

**Comment by walbourn** [comment]
See [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/direct3d12/using-resource-barriers-to-synchronize-resource-states-in-direct3d-12).

There is also a helpful [blog post](https://devblogs.microsoft.com/directx/a-look-inside-d3d12-resource-state-barriers/) on the topic.

And a [You-Tube video](https://www.youtube.com/watch?v=nmB2XMasz2o).

> You may also find the [DirectX Tool Kit for DX12](https://github.com/microsoft/DirectXTK12/wiki/Getting-Started) useful.
