### ISSUE TITLE
[MiniEngine] SetStablePowerState is back to causing issues?

### ISSUE THREAD

**Issue by Zinadore** [microsoft/DirectX-Graphics-Samples#708]
I'm am having issues with the call to SetStablePowerState causing the CommandQueue creation, etc to fail. I need this call to succeed for benchmarking purposes, so it's not that I can skip it. Things that I have checked:

* Developer mode has been enabled. The check inside MiniEngine succeeds, I can verify the registry key is there, and the settings app says that developer mode is enabled. Finally `Get-WindowsDeveloperLicense` returns a license entry in PowerShell.
* Windows SDK is installed (version 10.0.19041.0).

Am I missing something here? I can reliably reproduce this by having an executable that just calls SetStablePowerState after creating a device. It always results in:

```
D3D12: Removing Device.
D3D12 ERROR: ID3D12Device::RemoveDevice: Device removal has been triggered for the following reason (DXGI_ERROR_INVALID_CALL: There is strong evidence that the application has performed an illegal or undefined operation, and such a condition could not be returned to the application cleanly through a return code). [ EXECUTION ERROR #232: DEVICE_REMOVAL_PROCESS_AT_FAULT]
D3D12: SetStablePowerState is only available when developer mode is enabled.
```

I'm using an RTX 2080Ti, driver version: 465.89
Windows Version 20H2 (Build 19042.867)

**Comment by jenatali** [comment]
This is a known issue in the OS. The workaround is to call `D3D12EnableExperimentalFeatures()` during application startup.

**Comment by Zinadore** [comment]
MiniEngine does that as well though, doesn't it? So why is that failing ?

**Comment by stanard** [comment]
I'm up to do date, and I see in Core/GraphicsCore.cpp:

227    // Temporary workaround because SetStablePowerState() is crashing
228    D3D12EnableExperimentalFeatures(0, nullptr, nullptr, nullptr);

. . .

289        // Prevent the GPU from overclocking or underclocking to get consistent timings
290        if (DeveloperModeEnabled)
291            g_Device->SetStablePowerState(TRUE);
