### ISSUE TITLE
D3D12MeshletCull sample sphere plane intersection test

### ISSUE THREAD

**Issue by rskryptik61636** [microsoft/DirectX-Graphics-Samples#709]
Hello, I had question about the sphere plane intersection test used in the amplification shader of the D3D12MeshletCull sample. Why is the dot product compared against -radius in the intersection test? If I understand correctly, the dot product gives the signed distance of the sphere center from the plane.

https://github.com/microsoft/DirectX-Graphics-Samples/blob/e5ea2ac7430ce39e6f6d619fd85ae32581931589/Samples/Desktop/D3D12MeshShaders/src/MeshletCull/MeshletAS.hlsl#L27

**Comment by stanard** [comment]
I didn't write this code, and this is the first I'm seeing it, but my assumption is that for this code to work, the plane normals must be pointing into the frustum.  A distance of -radius means that the sphere is behind the plane far enough to not penetrate.

**Comment by mhurliman** [comment]
The signed-ness of the dot product is determinate on the direction of the plane normal. I believe I used [this article](https://www.gamedevs.org/uploads/fast-extraction-viewing-frustum-planes-from-world-view-projection-matrix.pdf) to extract the plane equations from the debug camera ViewProjection matrix, which is on the C++ side. 

Knowing me, I probably just tested both ways and found they faced inward, so negative dot product values are outside the frustum.

**Comment by rskryptik61636** [comment]
Ok, that makes sense. Could the shader be updated with this comment? 

Most of the shaders are pretty well documented but there's some math that could be easier to follow with a bit more explanation.
