### ISSUE TITLE
Multiple DirectX12 contexts in one application

### ISSUE THREAD

**Issue by Seniltai** [Microsoft/DirectX-Graphics-Samples#71]
Hello! I've been trying to set up DirectX12 so that multiple device contexts can be run from different threads. However, this only seems to work when driving all the contexts from the same thread, otherwise ->Present() seems to deadlock. I've tried the same thing on a DirectX11 demo, where it does work. 

Also, this seems to happen with either the WARP device, or my NVIDIA card, making me suspect something's going on in DXGI. I also made a minimal reproducable testcase, if you wish I could share my modifications to the Hello World example to create multiple contexts run at different threads.

Am I doing something wrong here, or is this a limitation/known issue right now?

**Comment by Seniltai** [comment]
I've made a fork with the change to easily reproduce the issue.

This is the commit:
https://github.com/Seniltai/DirectX-Graphics-Samples/commit/5118869e424d413d62b3dcdd622d4c0de732103a

**Comment by Seniltai** [comment]
Looking through the closed issue, this might be related to the following issue: https://github.com/Microsoft/DirectX-Graphics-Samples/issues/52

**Comment by anyeung** [comment]
Duplicate

**Comment by bobbrow** [comment]
Closing this issue as it's a bug we've identified in DX and will be fixing in an upcoming OS release.
