### ISSUE TITLE
how to catch d3d12SDKLayers.dll exception

### ISSUE THREAD

**Issue by ganluo960214** [microsoft/DirectX-Graphics-Samples#711]
I am trying to create dxr pipeline state object but throw an exception. I use 'catch (const std::exception& e)' did not work.
```c++
try
{
	ThrowIfFailed(pID3D12Device8->CreateStateObject(
		&stDXRPSODesc
		, IID_PPV_ARGS(&pIDXRSO)));
}
catch (const std::exception& e)
{
	throw "1";
}
```

Exception thrown at 0x00007FFFBE7188EA (d3d12SDKLayers.dll) in a.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

**Comment by jenatali** [comment]
An access violation isn't a C++ exception. It can't be caught with `catch()`. In general, they can't/shouldn't be caught, they should be prevented.

Reading from -1 is an indication that you have invalid data in your state object structures. Try to inspect them and look at all the pointers to make sure everything is valid.

**Comment by walbourn** [comment]
As noted, you probably have a more basic bug like a nullptr. You should check that.

``try`` / ``catch`` can only catch C++ exceptions, *not* Structured Exception Handling (SEH) when using the ``/EHsc`` which is the default and recommended setting. If the function had resulted in a ``FAILED(HRESULT)`` value from ``CreateStateObject``, then it would have been thrown as some kind of C++ exception, but depending on the implementation of ``ThrowIfFailed`` it may or may not be derived from ``std::exception``.

**Comment by ganluo960214** [comment]
thanks so much. I just learn c++ and dxr

**Comment by quadpixels** [comment]
I encountered the same error today. My finding is `pDesc` should be a *pointer to pointer* of `ID3D12RootSignature` not just a *pointer* to it. So:

This is ok:
```
ID3D12RootSignature* sig;
stDXRPSODesc.pDesc = &sig;   <---- Note the &
```

This gives access violation regarding address 0xFFFFFFFFFFFFFFFF:
```
ID3D12RootSignature* sig;
stDXRPSODesc.pDesc = sig;
```

**Comment by GameDreamByHuo** [comment]
这是来自QQ邮箱的假期自动回复邮件。 你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
