### ISSUE TITLE
ModelViewer Debug builds emit new debug layer errors with D3D12 Agility SDK or on Windows Insider builds

### ISSUE THREAD

**Issue by austinkinross** [microsoft/DirectX-Graphics-Samples#716]
**Repro steps:** Run Debug build of ModelViewer on a recent Windows Insider build. Alternatively, configure ModelViewer to use the D3D12 Agility SDK and run it on 20H2.

**Expected result:** application runs, and it emits no debug layer errors

**Actual result:** It emits lots of errors like this:

D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandLists: Cannot Resolve query that has never been performed for Index [2] in QueryHeap (0x000001E51CC80D40:'GpuTimeStamp QueryHeap') in command list (0x000001E50D9A8AE0:'CommandList'). [ EXECUTION ERROR #1319: RESOLVE_QUERY_INVALID_QUERY_STATE]

This error was added to the debug layer recently.

**Comment by ChrisKing340** [comment]
Thanks @Microsista Having been struggle with solving this too. This needs a pull

**Comment by MohammadMDSA** [comment]
@Microsista I don't find most of the names you mentioned. Is your solution still valid or the project structure has changed?

**Comment by MohammadMDSA** [comment]
The error happens when we have at least one scope timer which doesn't submit any timestamp query. Every scope timer with no command context has this problem. This cannot be a real problem because it is pretty logical to have some scope timers which only track CPU time. I think it is best to just ignore this message.

You can do it by adding `D3D12_MESSAGE_ID_RESOLVE_QUERY_INVALID_QUERY_STATE` to your ID3D12InfoQueue deny list. My code looks like this:
```// Configure debug device (if active).
ComPtr<ID3D12InfoQueue> d3dInfoQueue;
if (SUCCEEDED(m_d3dDevice.As(&d3dInfoQueue)))
{
#ifdef _DEBUG
	d3dInfoQueue->SetBreakOnSeverity(D3D12_MESSAGE_SEVERITY_CORRUPTION, true);
	d3dInfoQueue->SetBreakOnSeverity(D3D12_MESSAGE_SEVERITY_ERROR, true);
#endif
	D3D12_MESSAGE_ID hide[] =
	{
		D3D12_MESSAGE_ID_MAP_INVALID_NULLRANGE,
		D3D12_MESSAGE_ID_UNMAP_INVALID_NULLRANGE,
		// Workarounds for debug layer issues on hybrid-graphics systems
		D3D12_MESSAGE_ID_EXECUTECOMMANDLISTS_WRONGSWAPCHAINBUFFERREFERENCE,
		D3D12_MESSAGE_ID_RESOURCE_BARRIER_MISMATCHING_COMMAND_LIST_TYPE,
		D3D12_MESSAGE_ID_RESOLVE_QUERY_INVALID_QUERY_STATE
	};
	D3D12_INFO_QUEUE_FILTER filter = {};
	filter.DenyList.NumIDs = static_cast<UINT>(std::size(hide));
	filter.DenyList.pIDList = hide;
	d3dInfoQueue->AddStorageFilterEntries(&filter);
}
```

I hope it helps!

**Comment by stanard** [comment]
I pushed a fix that suppresses this error message. I apologize that it took so long for me to resolve.
