### ISSUE TITLE
Small Resource placement alignment validation error

### ISSUE THREAD

**Issue by nyorain** [microsoft/DirectX-Graphics-Samples#718]
The D3D12SmallResources sample does not check manually whether the created textures qualify for `D3D12_SMALL_RESOURCE_PLACEMENT_ALIGNMENT`, it always tries to use it and just checks whether alignment is granted or not via `GetResourceAllocationInfo`. When I increase the texture size (e.g. setting `D3D12SmallResources::Texture{Width,Height} = 1024`), the validation layer reports the following error:

> D3D12 ERROR: ID3D12Device::GetResourceAllocationInfo: D3D12_RESOURCE_DESC::Alignment cannot be 4KB, since D3D12_RESOURCE_DESC::Width, D3D12_RESOURCE_DESC::Height, and/ or D3D12_RESOURCE_DESC::DepthOrArraySize are too large. 4KB alignment requires the most detailed mip level be theoretically 64KB or smaller. A 4KB tile shape for D3D12_RESOURCE_DIMENSION_TEXTURE2D and R8G8B8A8_UNORM is 32 texels wide, 32 texels high, and 1 texels deep. When Width = 1024, Height = 1024, and Depth = 1, the number of tiles needed is 1024, while 16 tiles is the maximum. [ STATE_CREATION ERROR #721: CREATERESOURCE_INVALIDALIGNMENT]

Is this an error in the validation layers or is a manual check needed and you are only not doing it here because the texture size is hardcoded? I couldn't find docs explicitly stating whether just calling `GetResourceAllocationInfo` to check is valid or not. If it isn't valid (as the validation layer suggests) it would be a really good idea to add the needed check (computing the tile size of the texture depending on the format, then computing the number of tiles needed and checking whether they fit the requirements) to the sample to avoid future confusion.

**Comment by bioglaze** [comment]
I'm also affected by this. I was trying to use `GetResourceAllocationInfo` to determine if an alignment of 4096 should be used or not for a certain texture (544x80 BC3), but calling `GetResourceAllocationInfo` causes D3D errors.

**Comment by ShumWengSang** [comment]
Unable to replicate validation error on newer Agility SDK
