### ISSUE TITLE
Parameter error when I createstateobject

### ISSUE THREAD

**Issue by Recope** [microsoft/DirectX-Graphics-Samples#719]
When my program reached this line: “ThrowIfFailed(md3dDevice->CreateStateObject(&desc, IID_PPV_ARGS(&mpPipelineState)));”, there was a parameter error, I don't understand what caused this, can someone help me to solve it, I was stuck here for a long time.

**Comment by stanard** [comment]
I have code to print more information about an HRESULT error.  You could try something like this.

```
#include <system_error>

void PrintFailedHRESULT(HRESULT hr)
{
    printf("hr = 0x%08X", hr);
    if (hr == DXGI_ERROR_DEVICE_REMOVED)
    {
        hr = pDevice->GetDeviceRemovedReason();
        printf("Device was removed for the following reason (0x%08X):", hr);
    }

    printf(std::system_category().message(hr).c_str());
}

```

But if that's a shader compilation error, then it might not be obvious from HRESULTs.  I had a problematic shader once that kept failing in CreateStateObject() with an out of memory error.  It turned out I had an infinite for-loop in my code by mistake.

**Comment by Recope** [comment]
> I have code to print more information about an HRESULT error. You could try something like this.
> 
> ```
> #include <system_error>
> 
> void PrintFailedHRESULT(HRESULT hr)
> {
>     printf("hr = 0x%08X", hr);
>     if (hr == DXGI_ERROR_DEVICE_REMOVED)
>     {
>         hr = pDevice->GetDeviceRemovedReason();
>         printf("Device was removed for the following reason (0x%08X):", hr);
>     }
> 
>     printf(std::system_category().message(hr).c_str());
> }
> ```
> 
> But if that's a shader compilation error, then it might not be obvious from HRESULTs. I had a problematic shader once that kept failing in CreateStateObject() with an out of memory error. It turned out I had an infinite for-loop in my code by mistake.

I gave it a try, and there was this error, which didn't seem obvious:
hr = 0x80070057 the parameter is incorrect.

**Comment by jenatali** [comment]
The debug layer should tell you what you've done wrong. Are there any debug messages printed to the debug output in Visual Studio?

**Comment by Recope** [comment]
> The debug layer should tell you what you've done wrong. Are there any debug messages printed to the debug output in Visual Studio?
Yes, Visual Studio printed these errors:
D3D12 ERROR: ID3D12Device::CreateStateObject: Hash check failed for DXILibrary.pShaderBytecode: 0x0000022E1EEB69A0. A typical cause of this is unsigned bytecode. To enable signing by the compiler, ensure DXIL.dll is next to DxCompiler.dll. [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]
D3D12 ERROR: ID3D12Device::CreateStateObject: HitGroupExport "ShadowHitGroup" imports ClosestHitShaderImport named "shadowChs" but there are no exports matching that name. [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]
D3D12 ERROR: ID3D12Device::CreateStateObject: HitGroupExport "SecondaryHitGroup" imports ClosestHitShaderImport named "secondaryChs" but there are no exports matching that name. [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]
D3D12 ERROR: ID3D12Device::CreateStateObject: Subobject association of type D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_SHADER_CONFIG made to export named "rayGen" which doesn't exist. [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]
D3D12 ERROR: ID3D12Device::CreateStateObject: Subobject association of type D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_SHADER_CONFIG made to export named "shadowMiss" which doesn't exist. [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]
D3D12 ERROR: ID3D12Device::CreateStateObject: Subobject association of type D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_SHADER_CONFIG made to export named "secondaryMiss" which doesn't exist. [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]
D3D12 ERROR: ID3D12Device::CreateStateObject: Subobject association of type D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_SHADER_CONFIG made to export named "shadowChs" which doesn't exist. [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]
D3D12 ERROR: ID3D12Device::CreateStateObject: Subobject association of type D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_SHADER_CONFIG made to export named "secondaryChs" which doesn't exist. [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]
D3D12 ERROR: ID3D12Device::CreateStateObject: Subobject association of type D3D12_STATE_SUBOBJECT_TYPE_LOCAL_ROOT_SIGNATURE made to export named "rayGen" which doesn't exist. [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]
D3D12 ERROR: ID3D12Device::CreateStateObject: Subobject association of type D3D12_STATE_SUBOBJECT_TYPE_LOCAL_ROOT_SIGNATURE made to export named "secondaryChs" which doesn't exist. [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]
D3D12 ERROR: ID3D12Device::CreateStateObject: Subobject association of type D3D12_STATE_SUBOBJECT_TYPE_LOCAL_ROOT_SIGNATURE made to export named "secondaryMiss" which doesn't exist. [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]
D3D12 ERROR: ID3D12Device::CreateStateObject: Subobject association of type D3D12_STATE_SUBOBJECT_TYPE_LOCAL_ROOT_SIGNATURE made to export named "shadowMiss" which doesn't exist. [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]
D3D12 ERROR: ID3D12Device::CreateStateObject: Subobject association of type D3D12_STATE_SUBOBJECT_TYPE_LOCAL_ROOT_SIGNATURE made to export named "shadowChs" which doesn't exist. [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]

**Comment by Recope** [comment]
I solved this problem, we need to ensure DXIL.dll is next to DxCompiler.dll.

**Comment by golikeri** [comment]
> I solved this problem, we need to ensure DXIL.dll is next to DxCompiler.dll.

In which folder were these present? Did you have to copy them to a system folder like C:\Windows\System32? I am getting a similar error
