### ISSUE TITLE
Can you provide an example of using DirectX2D rendering to demonstrate Richedit (ITexthost) and APNG file

### ISSUE THREAD

**Issue by williamlzw** [microsoft/DirectX-Graphics-Samples#720]
Can you provide an example of using DirectX2D rendering to demonstrate Richedit (ITexthost) and APNG file?

**Comment by walbourn** [comment]
Your best option is to look at [this sample](https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/Win7Samples/multimedia/wic/wicanimatedgif). It demonstrates how to use Windows Imaging Component (WIC) to load a animated GIF and display it with Direct2D.

``APNG`` is not supported by WIC, and isn't an official format per [this article](https://en.wikipedia.org/wiki/APNG) and has so far been rejected by the PNG group.

**Comment by laizewei** [comment]
https://github.com/laizewei/ExduiR/blob/master/src/Class_Edit_ex.cpp
function:_edit_paint 
line 715 to line 725 
How do I go from ((ITextServices *) pits)-> TXDRAW to ((ITextServices *) pits)-> TXD2D

line 722 
BitBlt((HDC) hDc, rcTmp.left, rcTmp.top, rcTmp.right - rcTmp.left, rcTmp.bottom - rcTmp.top, (HDC) mDc, 0, 0, SRCPAINT);
How does this sentence work with TXDrawD2D

**Comment by walbourn** [comment]
Ah, the readme must have been incorrectly generated for that sample... The focus of that sample is how to do Animated GIF image reconstruction from metadata. There's another sample which shows WIC with D2D: [here](https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/Win7Samples/multimedia/wic/wicviewerd2d).

**Comment by zjq609177738** [comment]
When I use ITextServices: : TxDraw, insert images can be normal mapping, but using ITextServices2: : TxDrawD2D, insert the pictures did not show. When ITextServices: : TxDraw by implementing IDataObject subclasses and IRichEditOle: : InsertObject To insert the picture, but when ITextServices2: : TxDrawD2D, I don't know how to use, I didn't find relevant example
[https://github.com/laizewei/ExduiR]

**Comment by castorix** [comment]
> `APNG` is not supported by WIC, and isn't an official format per [this article](https://en.wikipedia.org/wiki/APNG) which has so far been rejected by the PNG group.

But now, there is :
_On June 24, 2025 it was finally elevated to the Recommendation final status by the W3C._
