### ISSUE TITLE
DXC Erroring in RealTimeDenoisedAmbientOcclusion Sample

### ISSUE THREAD

**Issue by Nolram12345** [microsoft/DirectX-Graphics-Samples#722]
I have been trying to compile the example stated in the title, however DXC keeps erroring out with pretty much no debug information on compile - all other samples work fine. 

```1>------ Rebuild All started: Project: D3D12RaytracingRealTimeDenoisedAmbientOcclusion, Configuration: Profile x64 ------
1>dxc failed : cannot specify entry point for a library
1>E:\Visual Studio 2019\IDE\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1532,5): error MSB6006: "dxc.exe" exited with code 1.
1>Done building project "D3D12RaytracingRealTimeDenoisedAmbientOcclusion.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
``` 

It seems that there is a library with an invalid entry point somewhere, but I have absolutely no clue where. Is there any further debugging for DXC or is there a shader error somewhere ?

**Comment by stanard** [comment]
Can you tell us more about your environment?  What version of VS2019, Windows 10, and the Windows SDK are you using?  I did not reproduce this situation, and I am on 15.8.6, 21H1, and 10.0.19041.0, respectively.  I'll update to VS version 15.10.0 and try again.  Make sure you try Rebuild All in case some shaders need to be recompiled.  Also, to minimize repro time, does this happen with a particular build configuration (e.g. Debug vs. Release)?

**Comment by Nolram12345** [comment]
VS 2019 Version : 16.7.3
Windows version : 21H1 Build 19043.985
Windows SDK : 10.0.18362

It happens with both configurations. Note that I had to manually create the CompiledShaders folders due to the known bug.

**Comment by stanard** [comment]
I think I misspoke about my VS2019 version.  I must have cited my VS2017 version.  Still, I think you have to have the 19043 SDK installed because the sample requires it.  If you don't, that could be the issue.

**Comment by Nolram12345** [comment]
Well, I can try and install that version - however I don't see how that would be the issue here since DXC is failing and only for this sample scene and all the others work perfectly.

**Comment by stanard** [comment]
The shader compiler gets updated with the SDK, and this code is confirmed to compile with 10.0.19041.0.

One thing that I noticed but forgot to mention is your Visual Studio path looks odd to me.  Mine looks like:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise

Yours is installed to E:\ but it has a very a different path.  What "edition" of VS2019 are you using?

Here's another thing:  do you have any files modified locally?  Run "git status" and please share your output.

**Comment by Nolram12345** [comment]
I am on the Community Edition of VScode as I only use it for myself. I have it installed on my E: drive. I am going to try and update my VS and Windows SDK version. I have not modified any files, however "git status" wouldn't work as I haven't cloned the repo over git.

**Comment by Nolram12345** [comment]
I have updated Visual Studio and the Windows SDK, however I am still getting the error : 
```
1>------ Build started: Project: D3D12RaytracingRealTimeDenoisedAmbientOcclusion, Configuration: Profile x64 ------
1>dxc failed : cannot specify entry point for a library
1>E:\Visual Studio 2019\IDE\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1760,5): error MSB6006: "dxc.exe" exited with code 1.
1>Done building project "D3D12RaytracingRealTimeDenoisedAmbientOcclusion.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by jenatali** [comment]
That means that somehow you're getting a `/E` command line parameter while trying to compile either `RTAO.hlsl` or `Pathtracer.hlsl`, which are supposed to be compiled as DXIL libraries. The vcxproj settings for those files don't specify an entrypoint, so I don't know how it's happening. You probably want to inspect the project settings for those files to see if anything's changed for the "profile" configuration - maybe somehow you ended up with additional command line parameters?

**Comment by Nolram12345** [comment]
I have managed to dispose of the error and compile the binary by setting the Solution Configuration to Debug - seems the VS update fixed that config. However the generated executable does not start up...

**Comment by Nolram12345** [comment]
Update : The same goes for the MiniEngine example. Both do not boot up any window and do not throw any error.

**Comment by stanard** [comment]
You said you didn't clone the repo. How did you acquire it, and how do you know it's up to date? These samples build and run on my machine, and we can't be certain you don't have an old version if you got it from a zip. There was a period of time where the raytracing samples were broken because they weren't being maintained.

Another thing to check is in the properties for the project you're debugging, go to...

Configuration Properties -> Debugging -> Debugger to launch, and make sure it says "Local Windows Debugger".  I've seen Visual Studio set that to "Remote Windows Debugger" without reason, and then I keep scratching my head why it fails to launch.

**Comment by Nolram12345** [comment]
I have cloned the repo 3 days ago, originally just to give it a quick test and see how exactly the API is structured. 
I have taken a closer look at the Configuration properties again and changed the mode to release - it now all works in the local Windows Debugger in VS. However the compiled builds do not work standalone, not sure what is up with that.

**Comment by stanard** [comment]
What do you mean "standalone"?  Like double-clicking the built EXE files?  You need to run them from the project folder so that they can find the data.

**Comment by Nolram12345** [comment]
Yes, I meant that exactly. I did run them in their original build location - do they need to be run from the root ?

**Comment by stanard** [comment]
That's correct. When you launch the executable from VS, there is a Working Directory equal to $(ProjectDir).  You need to mimic that on the command line by adding the executable path to your %PATH% and running from the project directory, or you can copy the EXE (and other DLLs) to the project directory folder.

**Comment by Nolram12345** [comment]
Ah, okay ! Makes sense ! Thank you so much for your help, Ill close this issue now.

**Comment by stanard** [comment]
You're welcome!
