### ISSUE TITLE
Path too long error when extracting samples

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/DirectX-Graphics-Samples#728]
When I extract the samples I get an interrupted action error..

Error 0x80010135: Path too long

DepthAwareSeparableGaussianFilter3x3CS_AnyToAnyWaveReadLaneAt.hlsl

**Comment by walbourn** [comment]
What directory are you trying to extract into?

**Comment by Gavin-Williams** [comment]
Desktop

**Comment by cpyburn** [comment]
having the same issue extracting zip to downloads folder and when opening in visual studio.   Visual studio error below.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3491	Could not write lines to file "obj\x64\Debug\D3D12Ray.19585C81.tlog\D3D12RaytracingRealTimeDenoisedAmbientOcclusion.lastbuildstate". Path: obj\x64\Debug\D3D12Ray.19585C81.tlog\D3D12RaytracingRealTimeDenoisedAmbientOcclusion.lastbuildstate exceeds the OS max path limit. The fully qualified file name must be less than 260 characters.	D3D12RaytracingRealTimeDenoisedAmbientOcclusion	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets	382

**Comment by walbourn** [comment]
Try extracting the samples to a more shallow directory: ``C:\DirectX-Graphics-Samples``.

**Comment by Gavin-Williams** [comment]
@walbourn yep, that's what I did, and it's OK. Thanks.
