### ISSUE TITLE
Link error C2375, redefinition when including WinSock2.h

### ISSUE THREAD

**Issue by ChrisKing340** [Microsoft/DirectX-Graphics-Samples#73]
Redefinition error occurring when doing networking through WinSock2.  Fixed with Mini Engine file "pch.h" modified to have WIN32_LEAN_AND_MEAN moved earlier in file and defined before any other header files:
#pragma once
#define WIN32_LEAN_AND_MEAN
...
BTW, your team has done awesome work!  Thank you so much for this repository and great examples.

**Comment by bobbrow** [comment]
Thanks for letting me know.  Yeah, it looks like wrl.h is including windows.h before WIN32_LEAN_AND_MEAN is defined.  We'll get this cleaned up.

**Comment by bobbrow** [comment]
Submitted a fix to the develop branch.
