### ISSUE TITLE
Vendor ID Issue

### ISSUE THREAD

**Issue by SuperWangKai** [microsoft/DirectX-Graphics-Samples#731]
Vendor ID of Intel should be `0x8086` or `32902` instead of `8086` -

https://github.com/microsoft/DirectX-Graphics-Samples/blob/c79f839da1bb2db77d2306be5e4e664a5d23a36b/MiniEngine/Core/GraphicsCore.cpp#L68

Please see -
https://github.com/GameTechDev/gpudetect/blob/648460345d7a393d4854bbc0bf2bb94a02476929/GPUDetect.h#L67

**Comment by stanard** [comment]
Thank you for noticing the bug. I'll get it fixed.

**Comment by SuperWangKai** [comment]
Fixed! - 145b4dd
