### ISSUE TITLE
Pix cannot attach to D3D12RaytracingRealTimeDenoisedAmbientOcclusion.exe

### ISSUE THREAD

**Issue by cpyburn** [microsoft/DirectX-Graphics-Samples#737]
Any ideas why pix cannot attach to D3D12RaytracingRealTimeDenoisedAmbientOcclusion.  Not a huge deal, just wanted to see what was going on in the GPU.  I would think this should be working.

09/06/21 09:06:50.3651:  LaunchProcessRequest working directory: C:\Applications\DirectX\Samples\Desktop\D3D12Raytracing\src\D3D12RaytracingRealTimeDenoisedAmbientOcclusion\bin\x64\Debug
09/06/21 09:06:50.3711:  PIX_NOTIFY_XBOX_STATIC_TITLE_WARNINGS received
09/06/21 09:06:50.3691:  10192 > Watchdog(24428) add 288
09/06/21 09:06:50.3711:  Adding process 288
09/06/21 09:06:50.3711:  Creating capture session on process 288
09/06/21 09:06:50.3711:  Waiting for communication from the target application
09/06/21 09:06:50.3711:  Capture session options:
09/06/21 09:06:50.3711:    Disable HUD: No
09/06/21 09:06:50.3711:    HUD alignment: TopLeft
09/06/21 09:06:50.3711:    Frames per capture: 1
09/06/21 09:06:50.3711:    ForceD3D11On12: Yes
09/06/21 09:06:50.3711:    Automatically Capture to first delimiter: No
09/06/21 09:06:50.3711:    Delimiter Used: Present to Present
09/06/21 09:06:50.4248:  Received ready notification from process 288
09/06/21 09:06:50.4248:  Successfully communicated with target application
09/06/21 09:06:50.4248:  Getting target process friendly name
09/06/21 09:06:50.4248:  Found target process friendly name
09/06/21 09:06:50.4268:  LaunchProcessRequest returned: S_OK (0x00000000) The operation completed successfully.
09/06/21 09:06:51.3562:  PIX_NOTIFY_WIN_TARGET_PROCESS_TERMINATED received
09/06/21 09:06:51.3572:  Submitting detach from target process request, terminateProcess = False
09/06/21 09:06:51.3562:  10192 > Watchdog(24428) remove 288
09/06/21 09:06:51.3572:  10192 > Watchdog(24428) reset
09/06/21 09:06:51.4322:  DetachFromProcessRequest returned: S_OK (0x00000000) The operation completed successfully.

**Comment by jenatali** [comment]
Just a guess, but your working directory is set to `D3D12RaytracingRealTimeDenoisedAmbientOcclusion\bin\x64\Debug`, while there's assets in `D3D12RaytracingRealTimeDenoisedAmbientOcclusion\Assets`. If you launch from VS, the working directory is set to `D3D12RaytracingRealTimeDenoisedAmbientOcclusion`. Maybe try using an explicit working directory?
