### ISSUE TITLE
Geometry limit

### ISSUE THREAD

**Issue by hjmin26** [microsoft/DirectX-Graphics-Samples#738]
I wonder how many AABBs I can use max in the Acceleration Structure.

I set the AS as one geometry with 512 AABBs in a bottom-level AS and 64,640 instances in a top-level AS. 
So total number of AABBs is 33,095,680(=512*64,640).

I think this number of AABBs seems to occur wrong return value of instanceID() or primitiveID() in *.hlsl.

As the result of some experiments, I think that the number of AABBs under about 2^24(16,777,216) is working fine when I call instanceID() or primitiveID().

I read the spec in here.
https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html#geometry-limits

There is not about AABBs limit in detail, and if it is right that one AABB has 12 triangles primitives, in my case of 33,095,680 AABBs have 397,148,160(33,095,680*12) primitives, which is below 2^29(536,870,912) that is written in the spec and it is the proper number. 
But there seem to show the wrong behavior.

So I'd like to know the maximum number of AABBs in the AS.

**Comment by stanard** [comment]
An AABB is a primitive in itself.  It is not comprised of 12 triangles. There is no need to multiply the number of instances with the number of primitives in the BLAS, as that does not contribute to any limit.  There is a 29-bit limit on the number of total primitives in a single BLAS with a 24-bit limit within a single geometry. And the maximum instance count in a TLAS is 24-bit.

If you are getting incorrect values for instance or primitive ID beyond a certain size of BVH, it could either be a bug in the runtime or the driver, or it could be user error. You are welcome to join our Discord channel to extend your questions to a variety of experts.  https://discord.com/invite/directx
