### ISSUE TITLE
D3D12RaytracingRealTimeDenoisedAmbientOcclusion Does not work on systems like laptops with multiple graphics adapters.

### ISSUE THREAD

**Issue by BrennerLittle** [microsoft/DirectX-Graphics-Samples#739]
This sample does not work on my laptop that has a NVidia graphics card and a AMD graphics card, however when I disable the AMD graphics card the sample works. The other raytracing related samples work without having to disable the AMD card.

**Comment by BrennerLittle** [comment]
I fixed this in my pull request https://github.com/microsoft/DirectX-Graphics-Samples/pull/740 however it might not be the propper way to fix it.

**Comment by walbourn** [comment]
It looks like the bug here is that **D3D12RaytracingRealTimeDenoisedAmbientOcclusion** is using ``EnumAdapter`` in the DeviceResoruces instead of ``EnumAdapterByGpuPreference`` using ``DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE``
