### ISSUE TITLE
Is it a good practice to set GPU read only resource state to just GENERIC_READ?

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#74]
As mentioned in the title, I have noticed that for most GPU read only resources MiniEngine set their states to GENERIC_READ (like the linearAllocator for vertex buffer, index buffer, constant buffer...). So my question is that: is there any downside for giving all read only resource GENERIC_READ state instead of being more specific?

Also I am curious why the GENERIC_READ flag hasn't include DEPTH_READ flag which by its name should be a read state...

Thanks

Merry Xmas

**Comment by bobbrow** [comment]
By setting specific states for your resources you are giving the driver hints about the resources you are working with. The intent is to allow GPU vendors to make optimizations in their drivers as they may be able to be more efficient if they have more information about what the memory is being used for. For example, they don't have to pass certain objects to stages of the pipeline that don't need them.

I'm inquiring about the DEPTH_READ omission from the GENERIC_READ state. Not everyone is back from the holiday break yet. I'll add more info when I get it.

**Comment by stanard** [comment]
DEPTH_READ is intended to be used with read-only depth stencil views.  It means "this buffer will be bound as a DSV that supports only depth testing but not depth writing".  If you want to bind a depth buffer for sampling in a shader, you would probably transition it to PIXEL_SHADER_RESOURCE (which is included in GENERIC_READ).  The main thing this affects is what kind of barrier the driver will insert to flush writes and invalidate caches.  It can also be picked up by the debug validation layer to help make sure you are inserting all of the right barriers (state transitions.)

**Comment by pengliu916** [comment]
Thanks for all your detailed explain, that really helps :-)
