### ISSUE TITLE
[Question] Is there a plan for creating D3D12 Video decoding sample?

### ISSUE THREAD

**Issue by michal-z** [microsoft/DirectX-Graphics-Samples#743]
Would be great to have a sample application that shows how to use d3d12video.h header. I can't find any example code for this.

Thanks,
Michal

**Comment by sivileri** [comment]
Thanks for reaching out to us. At the moment there’s no D3D12 Sample for Video Decoding on this repo. But we have other open source projects that can serve as a guide on how to use d3d12 video decode. Please take a look at our 11on12, 9on12 and d3d12 translation layer implementations for video decode, which implement the D3D9 and D3D11 higher level Video Decode API interfaces using D3D12 Video APIs, showing how to manage the d3d12 lower level concepts such as explicit reference frame management.

https://github.com/microsoft/D3D9On12/blob/main/src/9on12DecodeDevice.cpp
https://github.com/microsoft/D3D11On12/blob/master/src/VideoDecode.cpp
https://github.com/microsoft/D3D12TranslationLayer/blob/master/src/VideoDecode.cpp
https://github.com/microsoft/D3D12TranslationLayer/blob/master/src/VideoReferenceDataManager.cpp
