### ISSUE TITLE
win32 error

### ISSUE THREAD

**Issue by Mengm** [Microsoft/DirectX-Graphics-Samples#75]
win32 configration can not build success

**Comment by Mengm** [comment]
the miniEngine project can not build success in win32 configration

**Comment by bobbrow** [comment]
Are you building the Profile or Release configs?  Issue #68 is tracking this issue already.  The Debug config should compile ok.

**Comment by bobbrow** [comment]
Please sync the project and try again.  I just made a change that fixes #68 and pulled it to master.
