### ISSUE TITLE
Copyright(C) 1997,2001 Takuya OOURA (email: ooura@kurims.kyoto-u.ac.jp). You may use, copy, modify this code for any purpose and without fee. You may distribute this ORIGINAL package.

### ISSUE THREAD

**Issue by markymarkfunky** [microsoft/DirectX-Graphics-Samples#762]
https://raw.githubusercontent.com/GoogleChrome/accessibility-developer-tools/master/dist/js/axs_testing.js

**Comment by markymarkfunky** [comment]
Absolutely no idea what this means or does or whatever. I absolutely lost

**Comment by sebmerry** [comment]
Unclear what the issue is.
