### ISSUE TITLE
FAR Clause | 252.227-7013 Rights in Technical Data--Noncommercial Items.

### ISSUE THREAD

**Issue by markymarkfunky** [microsoft/DirectX-Graphics-Samples#764]
https://farclause.com/FARregulation/Clause/DFARS252.227-7013_Basic-rights-in-technical-data--noncommercial-item

**Comment by markymarkfunky** [comment]
48 CFR52. 227-19

**Comment by sebmerry** [comment]
Unclear what the issue is.
