### ISSUE TITLE
Clarify license of d3dx12.h

### ISSUE THREAD

**Issue by hdcmeta** [Microsoft/DirectX-Graphics-Samples#77]
Hi, could the maintainers of this repo clarify the license of d3dx12.h?

The readme.md in the root of the repo indicates that it is MIT, and so does http://blogs.msdn.com/b/chuckw/archive/2013/08/21/living-without-d3dx.aspx, but the header itself just displays a copyright notice.

Is this header available under a MIT license?

**Comment by bobbrow** [comment]
We'll get this updated in a future commit.  The header is MIT along with the rest of the code.  Since it comes from a different location than the rest of the sample code in the source tree, this was an oversight on our part.

**Comment by bobbrow** [comment]
I have updated the code in the develop branch.  This will make it to master the next time I merge.
