### ISSUE TITLE
Are d3d12SDKLayers.dll symbols available?

### ISSUE THREAD

**Issue by ms-RistoRK** [microsoft/DirectX-Graphics-Samples#781]
Hello,

I'm developing a DirectX 12 app and I would like to load a D3d12SDKLayers.dll symbols for a better debugging experience.  Could someone please point me to where/how to get those symbols?  

![image](https://user-images.githubusercontent.com/84108471/162491243-9d558067-2d62-4c17-8e2d-259bc49d2904.png)

Thanks in advance,

Risto

**Comment by PathogenDavid** [comment]
I was able to load them from Microsoft's symbol servers. Make sure they're enabled under Tools > Options > Debugging > Symbols.

If it doesn't load them automatically, go to Debug > Windows > Modules, right-click the module, and select `Load Symbols`.

As an aside though, type information is not provided by the public symbol files. So you won't get any new information in the watch window:

![Screenshot of watch window showing "No type information available" error](https://user-images.githubusercontent.com/278957/162493178-cb385c4b-1bd3-42d5-97cc-160da9149c8e.png)

**Comment by walbourn** [comment]
The Microsoft Symbol Server provides these, although not necessarily if you are running Windows Insider builds.

https://docs.microsoft.com/en-us/windows/win32/dxtecharts/debugging-with-symbols#using-the-microsoft-symbol-server

**Comment by ms-RistoRK** [comment]
Thank you both.  I got the symbols servers referenced and the symbols files are now used.
