### ISSUE TITLE
Solution files for samples appear corrupted in VS2022

### ISSUE THREAD

**Issue by jenatali** [microsoft/DirectX-Graphics-Samples#787]
Attempting to open the .sln file for any of the desktop samples in VS2022 produces:
![image](https://user-images.githubusercontent.com/17788890/172703103-c61445d0-dd32-416f-9486-637cfbfe7cc7.png)

Applying this diff is enough to get them to work:
```diff
--- a/Samples/Desktop/D3D12HelloWorld/src/D3D12HelloWorld.sln
+++ b/Samples/Desktop/D3D12HelloWorld/src/D3D12HelloWorld.sln
@@ -1,8 +1,6 @@
 ﻿
 Microsoft Visual Studio Solution File, Format Version 12.00
 # Visual Studio Version 16
-VisualStudioVersion = 16.0.30621.155.26403.0
-MinimumVisualStudioVersion = 10.0.40219.1
 Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "D3D12HelloTriangle", "HelloTriangle\D3D12HelloTriangle.vcxproj", "{5018F6A3-6533-4744-B1FD-727D199FD2E9}"
 EndProject
 Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "D3D12HelloBundles", "HelloBundles\D3D12HelloBundles.vcxproj", "{CAE2B6C4-B644-4B92-8804-23E18310765B}"
```

**Comment by sebmerry** [comment]
This should be fixed in Visual Studio 2022 version 17.2.2

**Comment by jenatali** [comment]
Yep, sure enough, I had a pending update and once I installed it, everything's working now. Thanks!

**Comment by sebmerry** [comment]
Probably still a good idea to just trim these version numbers to something like:
# Visual Studio Version 16
VisualStudioVersion = 16.0
MinimumVisualStudioVersion = 10.0

I'll consider this for a future update.

**Comment by walbourn** [comment]
Visual Studio writes those values pretty much any time you edit the project, so they can be a real pain to keep to some particular value.

**Comment by jenatali** [comment]
There is no 17.3, 17.2.3 is the latest.

**Comment by PathogenDavid** [comment]
@george-tsiros Yeah, it's still broken in the 17.3 previews. I've reported it here: https://developercommunity.visualstudio.com/t/Visual-Studio-172-preview-2-can-no-long/1695514

**Comment by walbourn** [comment]
Works fine in 17.4
