### ISSUE TITLE
How to submit refine code?

### ISSUE THREAD

**Issue by AlanoSong** [microsoft/DirectX-Graphics-Samples#792]
Dear team, I found several app crash under certain condition, and I want to submit the refine code.
So what the pull & request process is? I didn't found the contribute guide doc.

**Comment by AlanoSong** [comment]
Submit refine code on #794

**Comment by GameDreamByHuo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
