### ISSUE TITLE
What is the maximum value of SyncInterval value in IDXGISwapChain::Present()?

### ISSUE THREAD

**Issue by nikitablack** [Microsoft/DirectX-Graphics-Samples#80]
Hi.

I'm trying to understand how `Present()` work and for this reason I'm tweaking some parameters. I'm using `DXGI_SWAP_CHAIN_DESC1` with `DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL` when creating a swap chain and documentation says that for flip model `SyncInterval  > 0 - Synchronize presentation for at least n vertical blanks`. But the maximum value is 4 (`DXGI ERROR: IDXGISwapChain::Present: SyncInterval must be less than or equal to 4.`), as for the bitblt.

**Comment by bobbrow** [comment]
The MSDN documentation should mention that the maximum interval is still 4 for the flip model swap chains.  I'll file a bug to get this updated.  Thanks for pointing it out!
