### ISSUE TITLE
Error MSB6006 "dxc.exe" exited with code -1073741819. when building D3D12RaytracingRealTimeDenoisedAmbientOcclusion Sample

### ISSUE THREAD

**Issue by disini** [microsoft/DirectX-Graphics-Samples#801]
Hello,

I've just  cloned the master code of this repo, updated on 2022.10.12.
Then I open the the D3D12Raytracing.sln and tried to build the whole solution with Debug-X64 mode.
All of the projects built  successfully but  except the D3D12RaytracingRealTimeDenoisedAmbientOcclusion project only .

I didn't change anything  of the whole solution, 
![QQ截图20221025010753](https://user-images.githubusercontent.com/5233769/197585153-97782ec5-798b-4fd2-82c3-0d63abf6b308.png)

just open the  D3D12Raytracing.sln with VS 2019 and right clicked and build the solution.

My PC's configuration : 
Win10 enterprise version 22H2， OS build 19045.2130
![QQ截图20221025010053](https://user-images.githubusercontent.com/5233769/197585179-cc5a581a-a092-45d0-8e44-35e1914394ea.png)

![QQ截图20221025010220](https://user-images.githubusercontent.com/5233769/197586025-6366e244-0b95-49b8-b548-273a5aba446e.png)

![QQ截图20221025011417](https://user-images.githubusercontent.com/5233769/197586041-fc941f63-d520-4324-8b28-26f3017579a9.png)

My VS 2019 is version 16.11.20, 

![QQ截图20221025011056](https://user-images.githubusercontent.com/5233769/197585493-0d4119ef-571a-4ff5-b0c9-08446f6c38d8.png)

and opened this solution with windows kits/sdk version 19041, and C++ 17 standard。

![QQ截图20221025010916](https://user-images.githubusercontent.com/5233769/197585594-1e472744-aa5d-409b-bcd5-b33cfcff3899.png)

_The Error List:_
Severity	Code	Description	Project	File	Line	Suppression State
**Error	MSB6006	"dxc.exe" exited with code -1073741819.**	
D3D12RaytracingRealTimeDenoisedAmbientOcclusion	 I:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	1759	

and that's the file : 
[Microsoft.CppCommon.targets.zip](https://github.com/microsoft/DirectX-Graphics-Samples/files/9853568/Microsoft.CppCommon.targets.zip)

_The building output :_

Build started...
1>------ Build started: Project: D3D12RaytracingRealTimeDenoisedAmbientOcclusion, Configuration: Debug x64 ------
1>FXC : warning : no output provided for debug - embedding PDB in shader container.  Use -Qembed_debug to silence this warning.
1>
1>I:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1759,5): error MSB6006: "dxc.exe" exited with code -1073741819.
1>Done building project "D3D12RaytracingRealTimeDenoisedAmbientOcclusion.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I searched this error type and the "exited code -1073741819." but find nothing, could you please help? 
Much appreciate!

**Comment by stanard** [comment]
It's possible that your path is too long for that project. It has notoriously long filenames, and your base path is already very long. You could try copying the solution to C:\Temp (or anywhere with a short path length) and see if it is able to build properly.

**Comment by disini** [comment]
> It's possible that your path is too long for that project. It has notoriously long filenames, and your base path is already very long. You could try copying the solution to C:\Temp (or anywhere with a short path length) and see if it is able to build properly.

wow Amazing!!! It worked!!!

Thank you so much for such a quick response! !

**Comment by disini** [comment]
And thanks again for your great work on this project, really ^_^

**Comment by stanard** [comment]
I'm happy to have helped!  :-)
