### ISSUE TITLE
FrameResource

### ISSUE THREAD

**Issue by KaMiletic** [microsoft/DirectX-Graphics-Samples#826]
Hello

I am learning direct3d 12 and I have seen both here and  Frank Luna book use frame resources to keep CPU and GPU busy while building and submiting commands to the GPU for execution. 
Is this approach good enough for production quality applications or another approach would be better ?
In MiniEngine what class is responsible for rendering 3d models , and where would be a good to place to insert brake point to see rendering calls.
Thank you!

**Comment by KaMiletic** [comment]
@walbourn thank you for your answer.
In win32 samples, multithreading there is FrameResource.h and FrameResource.cpp. In Frank Luna book they explain it as a circular buffer holding rendering constant buffer per frame and model object and command allocator. If i would write render engine could I use same pattern or is it inefficient?
In MiniEngine I have seen an issue here where to put brake point for init of engine, but could I put brake point somewhere where I could see rendering calls.
Thank you

**Comment by walbourn** [comment]
In DirectX 12, the application is responsible for ensuring all resources like constant buffers are kept 'alive' until the GPU is done rendering them, which can take up to 3 frames. The samples all tend to use a fairly simplistic model for this. For a "generalized' solution, see LinearAllocator in the [DirectX Tool Kit for DX12](https://github.com/microsoft/DirectXTK12/blob/main/Src/LinearAllocator.cpp).

MiniEngine uses a similar approach [LinearAllocator.cpp](https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/MiniEngine/Core/LinearAllocator.cpp) / [.h](https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/MiniEngine/Core/LinearAllocator.h).
