### ISSUE TITLE
Program Crash

### ISSUE THREAD

**Issue by sirprogramalot** [Microsoft/DirectX-Graphics-Samples#84]
Both programs D3D12Bundles and D3D12DynamicIndexing crash in line m_commandList->ExecuteBundle in functions D3D12Bundles::PopulateCommandList and D3D12DynamicIndexing::PopulateCommandList respectively.

Before crash,
pCommandList->IASetIndexBuffer in FrameResource::PopulateCommandList throws error STATE_CREATION ERROR #725: SET_INDEX_BUFFER_INVALID three times.

**Comment by bobbrow** [comment]
Are you using the latest NVidia driver?  There is a bug in the 361.43 driver reported in issue #76.  I am also seeing this crash on a GTX 980.

**Comment by sirprogramalot** [comment]
Yes, I am using driver 361.43. I have 970 GTX. Thank you for the update.
