### ISSUE TITLE
How to use DXGI_SWAP_CHAIN_FLAG_GDI_COMPATIBLE in D3D12

### ISSUE THREAD

**Issue by LastSunlight** [microsoft/DirectX-Graphics-Samples#846]
I want to use DXGI_SWAP_CHAIN_FLAG_GDI_COMPATIBLE create SwapChain, but it look like not support with D3D12.

**Comment by walbourn** [comment]
I believe that flag is only intended for use with Direct2D.

**Comment by LastSunlight** [comment]
ok，I use this flag with D3D11 to create swapchain in unrealengine5， it works。

this is create details:
`// Create the swapchain.
			DXGI_SWAP_CHAIN_DESC1 SwapChainDesc = {};
			BackBufferCount = 2;
			SwapChainDesc.BufferCount = BackBufferCount;
			SwapChainDesc.Width = SizeX;
			SwapChainDesc.Height = SizeY;
			SwapChainDesc.SampleDesc.Count = 1;
			SwapChainDesc.SampleDesc.Quality = 0;
			SwapChainDesc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
			SwapChainDesc.Flags = DXGI_SWAP_CHAIN_FLAG_GDI_COMPATIBLE;
			SwapChainDesc.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT | DXGI_USAGE_SHADER_INPUT;
			DXGI_SWAP_CHAIN_FULLSCREEN_DESC FSSwapChainDesc = {};
			FSSwapChainDesc.Windowed = !bIsFullscreen;

			IDXGISwapChain1* SwapChain1 = nullptr;
			HRESULT CreateSwapChainForHwndResult = DXGISwapchainProvider ?
				DXGISwapchainProvider->CreateSwapChainForHwnd(Factory2, D3DRHI->GetDevice(), WindowHandle, &SwapChainDesc, &FSSwapChainDesc, nullptr, &SwapChain1) :
				Factory2->CreateSwapChainForHwnd(D3DRHI->GetDevice(), WindowHandle, &SwapChainDesc, &FSSwapChainDesc, nullptr, &SwapChain1);`

![image](https://github.com/microsoft/DirectX-Graphics-Samples/assets/32114897/74abdf83-cd42-44e7-a697-f76adce12436)

but it look like not support with D3D12. This is details:
[https://learn.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgisurface1-getdc](url)

**Comment by LastSunlight** [comment]
ok，I use this flag with D3D11 to create swapchain in unrealengine5， it works。

this is create details:
`// Create the swapchain.
			DXGI_SWAP_CHAIN_DESC1 SwapChainDesc = {};
			BackBufferCount = 2;
			SwapChainDesc.BufferCount = BackBufferCount;
			SwapChainDesc.Width = SizeX;
			SwapChainDesc.Height = SizeY;
			SwapChainDesc.SampleDesc.Count = 1;
			SwapChainDesc.SampleDesc.Quality = 0;
			SwapChainDesc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
			SwapChainDesc.Flags = DXGI_SWAP_CHAIN_FLAG_GDI_COMPATIBLE;
			SwapChainDesc.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT | DXGI_USAGE_SHADER_INPUT;
			DXGI_SWAP_CHAIN_FULLSCREEN_DESC FSSwapChainDesc = {};
			FSSwapChainDesc.Windowed = !bIsFullscreen;

			IDXGISwapChain1* SwapChain1 = nullptr;
			HRESULT CreateSwapChainForHwndResult = DXGISwapchainProvider ?
				DXGISwapchainProvider->CreateSwapChainForHwnd(Factory2, D3DRHI->GetDevice(), WindowHandle, &SwapChainDesc, &FSSwapChainDesc, nullptr, &SwapChain1) :
				Factory2->CreateSwapChainForHwnd(D3DRHI->GetDevice(), WindowHandle, &SwapChainDesc, &FSSwapChainDesc, nullptr, &SwapChain1);`

![image](https://github.com/microsoft/DirectX-Graphics-Samples/assets/32114897/74abdf83-cd42-44e7-a697-f76adce12436)

but it look like not support with D3D12. This is details:
[https://learn.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgisurface1-getdc](url)

**Comment by jenatali** [comment]
Correct, D3D12 does not provide any native GDI interop support.
