### ISSUE TITLE
Warning on debug frame capture.

### ISSUE THREAD

**Issue by nikitablack** [Microsoft/DirectX-Graphics-Samples#85]
Greetings.

In `HelloWindow` sample on debug frame capture a warning appears: `D3D12 WARNING: ID3D12Resource::ID3D12Resource::Map: pReadRange is NULL and the heap page property is WRITE_BACK. This can be an indicator of inefficiencies that will result on mobile systems, as the range should be as tight as possible. But, it is also possible the range must encompass the whole subresource.A NULL pReadRange parameter indicates all resource memory will be read by the CPU.  [ EXECUTION WARNING #930: MAP_INVALID_NULLRANGE]`. That's strange because there's no call to `Map()` function. And sometimes I can't read the captured log - Visual Studio can't open it.

**Comment by bobbrow** [comment]
The debugging tools use Map to inspect buffers on the GPU.  This would be something we'd want the graphics debugging tools team to investigate if they haven't fixed it already.  Can you share the output of ```dxcap -info``` with me so I can check?  This command will print out a lot of text.  I just need the version numbers of the binaries in the System32 section of the output.

Also, if you could please tell me which version of Windows 10 you have (10240 or 10586), and which version of Visual Studio 2015 you have (RTM or Update 1) that would be helpful too.

Thanks!

**Comment by nikitablack** [comment]
With pleasure.

Windows 10 10586.36
VS 2015 Update 1
System32 Info
=============
DxCap.exe                       : 10.0.10586.0 (10/29/15 19:29) 869 KB
DxCaptureReplay.dll             : 10.0.10586.0 (10/29/15 19:24) 8,374 KB
DxToolsMonitor.dll              : 10.0.10586.0 (10/29/15 19:32) 176 KB
DxToolsOfflineAnalysis.dll      : 10.0.10586.0 (10/29/15 19:30) 1,049 KB
DxToolsReportGenerator.dll      : 10.0.10586.0 (10/29/15 20:12) 95 KB
DxToolsReporting.dll            : 10.0.10586.0 (10/29/15 19:34) 156 KB
perf_gputiming.dll              : 10.0.10586.0 (10/29/15 19:34) 338 KB
VsGraphicsCapture.dll           : 10.0.10586.0 (10/29/15 19:31) 154 KB
VsGraphicsExperiment.dll        : 10.0.10586.0 (10/29/15 19:31) 711 KB
VsGraphicsProxyStub.dll         : 10.0.10586.0 (10/29/15 19:37) 88 KB
VsGraphicsRemoteEngine.exe      : 10.0.10586.0 (10/29/15 19:29) 5,432 KB
d3d11_3sdklayers.dll            : 10.0.10586.0 (10/29/15 19:12) 1,308 KB
d3d12SDKLayers.dll              : 10.0.10586.0 (10/29/15 19:13) 979 KB
d3d12warp.dll                   : 10.0.10586.0 (10/29/15 19:28) 3,216 KB
d2d1debug3.dll                  : 10.0.10586.0 (10/29/15 19:30) 420 KB
dxgidebug.dll                   : 10.0.10586.0 (10/29/15 19:37) 337 KB

But why System32? I'm the happy owner of 64 bit Windows.

**Comment by zao** [comment]
@nikitablack Historical reasons -- system32 holds the 64-bit images, syswow64 holds the 32-bit images. (For bonus confusion, in a 32-bit process system32 refers to the files in syswow64.)

**Comment by bobbrow** [comment]
Thanks.  This is a new SDK layers warning that appeared in 10586, but the changes to the graphics debugging tools to address them did not make it in time for the 10586 release.  In any case, this error is just a warning and shouldn't be the cause of the playback error you're seeing.  Do you just see a generic error when playback fails?  How consistent is it?

**Comment by nikitablack** [comment]
I tried to reproduce an error but I couldn't. Maybe it was a bug in the changes I made. So let's not consider it anymore.
Also I found some minor bugs in debug info appearance. Should I post them here of there's a better place?

**Comment by bobbrow** [comment]
You can post it here and I will relay the feedback to the tools team.  I have regular meetings with them.

**Comment by nikitablack** [comment]
Good. Thank you.
