### ISSUE TITLE
[HELP] Can somebody tell me what's the size of this repo....

### ISSUE THREAD

**Issue by RightFS** [microsoft/DirectX-Graphics-Samples#864]
I live in China, and we have a stupid goverment firewall. It makes us hard to access to the real internet...

I have downloaded over 500MB with failure with interrupted with connection broken, and the size is still growing...

**Comment by Jason2013** [comment]
The size of the .git directory in the source root is 624M.

If you don't want the history of the repository and only need the latest version of the repository, you can add '--depth 1' option when you clone the repository:

```
git clone --depth 1 https://github.com/microsoft/DirectX-Graphics-Samples.git
```
