### ISSUE TITLE
Don't get any output using DirectX 9 after using DirectX 11 in flip sequential mode on same window

### ISSUE THREAD

**Issue by MemeTao** [microsoft/DirectX-Graphics-Samples#868]
This issue still unresolved today: 
https://stackoverflow.com/questions/20647359/resetting-window-after-using-directx-11

**Comment by GameDreamByHuo** [comment]
这是来自QQ邮箱的假期自动回复邮件。 你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by jenatali** [comment]
It's not an issue, it's by design. It's also unrelated to this repository.
