### ISSUE TITLE
D3D12Fullscreen is not fullscreen on a WARP device.

### ISSUE THREAD

**Issue by DiligentKeyPresser** [Microsoft/DirectX-Graphics-Samples#87]
Unable to switch to fullscreen mode in a `D3D12Fullscreen` sample.
I'm using a WARP device (GTX470 is my board if anyone wonders).

`m_swapChain->SetFullscreenState(!fullscreenState, nullptr)` returns `HRESULT 0x887a0004`

Debug output is: 
`DXGI ERROR: IDXGISwapChain::GetContainingOutput: The swapchain's adapter does not control the output on which the swapchain's window resides. [ MISCELLANEOUS ERROR #80: ]`

Is this behavior intended?

**Comment by bobbrow** [comment]
Yes, this is the intended behavior.  The swap chain must be using the adapter that is plugged into your display in order to do the fullscreen switch.  Unfortunately it appears that your GPU is a Fermi which does not have DX12 drivers so there is no way for you to try this out on your system.

**Comment by DiligentKeyPresser** [comment]
Thank you for your attention!
