### ISSUE TITLE
[Question] SetEventOnCompletion(value, valid_handle) + WaitForSingleObject() vs SetEventOnCompletion(value, nullptr)

### ISSUE THREAD

**Issue by seungha-yang** [microsoft/DirectX-Graphics-Samples#877]
While `ID3D12Fence::SetEventOnCompletion()` with null event handle will block the calling cpu thread already, every sample code here seems to be using `ID3D12Fence::SetEventOnCompletion()` + immediate `WaitForSingleObject()` pattern. 

Is there any point of creating event handle and passing it to `SetEventOnCompletion()`, then immediate `WaitForSingleObject()` call, instead of `SetEventOnCompletion()` with null event handle?

**Comment by jenatali** [comment]
Only if you want a timeout or to wait for it at some other point.
