### ISSUE TITLE
TGA Texture Loader Does Not Function

### ISSUE THREAD

**Issue by RogersDoug** [Microsoft/DirectX-Graphics-Samples#88]
The BytesPerPixel in TextureManager.cpp does not recognize the DXGI type DXGI_FORMAT_R8G8B8A8_UNORM_SRGB  or DXGI_FORMAT_R8G8B8A8_UNORM which are passed in from CreateTGAFromMemory.

Fix is to use in DDSTextureLoader.cpp BitsPerPixel and convert to bytes

    size_t BitsPerPixel(DXGI_FORMAT fmt);

    static UINT BytesPerPixel(DXGI_FORMAT Format)
    {
        return BitsPerPixel(Format) >> 3;
    }

**Comment by RogersDoug** [comment]
Fix is actually to use in DDSTextureLoader.cpp BitsPerPixel and convert to bytes

**Comment by RogersDoug** [comment]
size_t BitsPerPixel(DXGI_FORMAT fmt);

static UINT BytesPerPixel(DXGI_FORMAT Format)
{
	return BitsPerPixel(Format) >> 3;
}

**Comment by stanard** [comment]
You're right, and that's a good idea.  I had forgotten about that placeholder function for looking up format size.  The one in DDSTextureLoader is much more complete.  I'll make the fix, and it will be included in the next push to GitHub.

**Comment by bobbrow** [comment]
Fix committed to develop branch.
