### ISSUE TITLE
Consider using pre-build event instead of custom build tool for portability

### ISSUE THREAD

**Issue by BanTheRewind** [Microsoft/DirectX-Graphics-Samples#89]
I had a heck of a time getting around the usage of a custom build tool in VS2015 Community. It appears that all the tool does is copy HLSL files to the output directory. Wouldn't it make more sense to simply copy these files in the pre-build step with xcopy?

Project Property Pages > Configuration Properties > Build Events > Pre-Build Event > Command Line
```
xcopy "$(ProjectDir)*.hlsl" "$(OutDir)" /Y /C
```

This would ensure the sample projects build out-of-the-box, and is a simpler approach to copying files.

**Comment by bobbrow** [comment]
Sure, there is more than one way to do this and we're certainly not prescribing how you should or should not deploy assets as part of your build.  Developers will have their own needs for asset deployment and can choose whatever method works for them.

What concerns me though is that it sounds like you're saying the samples didn't build out-of-the-box for you.  We do test these on VS 2015 Community, so this isn't an issue we've seen before.  Are you saying that you couldn't build the samples until you made this change in the project files?

**Comment by BanTheRewind** [comment]
Correct. These projects do not build out of the box for me. And you're right, that is the actual issue. Let's see if I can help.

If assets are handled by the custom build tool, I get a pretty generic MSB6006 error. I increased the build verbosity and I'm seeing this in the "TechniqueDemos\D3D12MemoryManagement" project (every project has this error, but I just picked out this one for example). Starting from when the tracking logs are read.

```
1>  Read Tracking Logs: (TaskId:16)
1>  	x64\Debug\D3D12Mem.DB40D747.tlog\custombuild.read.1.tlog (TaskId:16)
1>  No output for C:\USERS\STEPHEN\DEVELOPER\PROJECTS\NBODYD3D12\TECHNIQUEDEMOS\D3D12MEMORYMANAGEMENT\SRC\COLOR.HLSL|C:\USERS\STEPHEN\DEVELOPER\PROJECTS\NBODYD3D12\TECHNIQUEDEMOS\D3D12MEMORYMANAGEMENT\SRC\TEXTURE.HLSL|C:\USERS\STEPHEN\DEVELOPER\PROJECTS\NBODYD3D12\TECHNIQUEDEMOS\D3D12MEMORYMANAGEMENT\SRC\TILEGRID.DDS was found in the tracking log; source compilation required. (TaskId:16)
1>  Color.hlsl will be compiled as it was not found in the tracking log. (TaskId:16)
1>  Texture.hlsl will be compiled as it was not found in the tracking log. (TaskId:16)
1>  TileGrid.dds will be compiled as it was not found in the tracking log. (TaskId:16)
1>  copy TileGrid.dds "C:\Users\Stephen\Developer\Projects\nBodyD3D12\TechniqueDemos\D3D12MemoryManagement\src\x64\Debug\Assets\Textures" > NUL (TaskId:16)
1>  copy Color.hlsl "C:\Users\Stephen\Developer\Projects\nBodyD3D12\TechniqueDemos\D3D12MemoryManagement\src\x64\Debug\Assets\Shaders" > NUL (TaskId:16)
1>  copy Texture.hlsl "C:\Users\Stephen\Developer\Projects\nBodyD3D12\TechniqueDemos\D3D12MemoryManagement\src\x64\Debug\Assets\Shaders" > NUL (TaskId:16)
1>  Copying TileGrid.dds to output location (TaskId:16)
1>  Copying Color.hlsl to output location (TaskId:16)
1>  Copying Texture.hlsl to output location (TaskId:16)
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
1>Done executing task "CustomBuild" -- FAILED. (TaskId:16)
1>Done building target "CustomBuild" in project "D3D12MemoryManagement.vcxproj" -- FAILED.: (TargetId:30)
```

The source files do exist, as does the destination, but the files never make it there ("TechniqueDemos\D3D12MemoryManagement\src\x64\Debug\Assets\[Folder]"). I'm not working out a special folder or anything (ie, no admin privileges needed, etc).

**Comment by bobbrow** [comment]
No matter what I try, I can't reproduce the error you're seeing.

Have you tried right clicking on the assets in File Explorer and "unblocking" them?  Stuff you download from the Internet gets tagged with an attribute that marks it as unsafe.  I'm not sure if you have an antivirus program running that's blocking the copy.

**Comment by BanTheRewind** [comment]
I'll give that a shot and report back.

**Comment by bobbrow** [comment]
Any update?

**Comment by bobbrow** [comment]
Please reopen if you have an update. Otherwise, I will assume that this is not causing anyone else any problems.  Thanks!
