### ISSUE TITLE
Hello World Samples Not Working

### ISSUE THREAD

**Issue by elviswolcott** [Microsoft/DirectX-Graphics-Samples#9]
When I ran the hello world samples in VS 2015 Community I was getting cryptic exception messages everywhere and the program was failing to run. I was using the D3D12HelloWorld.sln found at Samples\D3D12HelloWorld\src. If needed I can give the exact error message

**Comment by bobbrow** [comment]
Check out issues #5 and #6 and let me know if that is the same thing you're seeing.

**Comment by elviswolcott** [comment]
It is the same thing.

**Comment by elviswolcott** [comment]
how do you add /warp (I can't get it to work)?

**Comment by ThorMalleuson** [comment]
In Visual Studio right click on the project and open the Property Pages.  Add the command argument to Debugging->Command Arguments.

**Comment by elviswolcott** [comment]
thanks, ill do that

**Comment by elviswolcott** [comment]
It worked, turns out I'd been looking in all the wrong places!

**Comment by weltkante** [comment]
Note that if your first adapter doesn't support DX12 then the samples will fail, even if your second adapter supports DX12. I've opened issue #14 for that.
