### ISSUE TITLE
MiniEngine Release build fails to compile.  Internal compiler error.

### ISSUE THREAD

**Issue by RogersDoug** [Microsoft/DirectX-Graphics-Samples#90]
Several files do not compile in Release mode in Windows.  VS 2015, 14.0.24720.0 Update 1

1>c:\program files (x86)\microsoft visual studio 14.0\vc\include\xmemory0(909): fatal error C1001: An internal error has occurred in the compiler.
1>  (compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 246)

Adding this pragma and disabling precompiled headers allow me to compile.
#pragma optimize( "", off )

**Comment by zao** [comment]
Which files are triggering the ICE for you?

**Comment by RogersDoug** [comment]
FileUtility.cpp and GraphRenderer.cpp

**Comment by bobbrow** [comment]
Do you have the latest code changes?  This sounds a lot like issue #68 and I pushed a change to work around it.

**Comment by RogersDoug** [comment]
I concur.  This is a duplicate. Removing the /FA option fixed the issue. 

Please close.
