### ISSUE TITLE
Hardware  Adapter  is empty  at memory location  0x0000000000000000

### ISSUE THREAD

**Issue by Postal86** [Microsoft/DirectX-Graphics-Samples#94]
Exception:  Unhandled exception at 0x00007FFE44F4A1C8 in D3D1211On12.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.

P.S.  I wonder GPU  device  does not supported  or  GPU  Driver  is messing  with me  ?!  I have got  Geforce  GT  630  GPU. On Nvidia  web  site  shown that  DX 12 API  is supported  on  that GPU.

**Comment by bobbrow** [comment]
If GetHardwareAdapter returned null, it means that we were unable to create a D3D12 device (e.g. DX12 is not supported).  The GT 640 is the lowest NVidia card I've tested, so I can't say much about the 630, but I would have expected it to be a Kepler card with DX12 support.  What's your driver version?

**Comment by Postal86** [comment]
Driver version: 10.18.13.6175

**Comment by Postal86** [comment]
Bob if  GT 640 is  the lowest  card , then reason is clear  GPU is  not  supported :).

**Comment by bobbrow** [comment]
No, the reason I haven't tested a GT 630 is because I don't have access to one. :)

**Comment by Postal86** [comment]
:)  Ok  i  will  figure  out  deeply  what  is going on  and later  i'll  be in   touch with you.  
Thnks  :).

**Comment by Postal86** [comment]
Bob I have  acquired GTX  660  OEM  and everything  works  awesome   :).   Guess  Geforce  GT  chipset  is too  old  for DX12 :).

**Comment by bobbrow** [comment]
Closing this issue.  Let me know if there's anything else you want me to follow up on.
