### ISSUE TITLE
D3D12DynamicIndexing crashes

### ISSUE THREAD

**Issue by kenchen3000** [Microsoft/DirectX-Graphics-Samples#95]
I have a crash every time I run D3D12DynamicIndexing sample. during:
m_commandList->ExecuteBundle(pFrameResource->m_bundle.Get());
Exception thrown at 0x00007FF911DFAC7E (d3d12SDKLayers.dll) in D3D12DynamicIndexing.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

It also had D3D error when IASetVertexBuffers before running to here:
D3D12 ERROR: ID3D12CommandList::IASetIndexBuffer: pDesc->BufferLocation + SizeInBytes - 1 (0x000000020390b347) exceeds end of the virtual address range of Resource (0x0000000000000000:'(nullptr)', GPU VA Range: 0x0000000203830000 - 0x00000002038fffff). This is OK as out of bounds access is guarded by the GPU (writes are discarded and reads return 0). However the developer probably did not intend to make use of this behavior.  [ STATE_CREATION ERROR #725: SET_INDEX_BUFFER_INVALID]

I am using NVIDIA GeForce GTX 950, version 361.75, thanks.

**Comment by kenchen3000** [comment]
System32 Info
=============
DxCap.exe                       : 10.0.10586.0 (10/29/15 7:29 PM) 869 KB
DxCaptureReplay.dll             : 10.0.10586.0 (10/29/15 7:24 PM) 8,374 KB
DxToolsMonitor.dll              : 10.0.10586.0 (10/29/15 7:32 PM) 176 KB
DxToolsOfflineAnalysis.dll      : 10.0.10586.0 (10/29/15 7:30 PM) 1,049 KB
DxToolsReportGenerator.dll      : 10.0.10586.0 (10/29/15 8:12 PM) 95 KB
DxToolsReporting.dll            : 10.0.10586.0 (10/29/15 7:34 PM) 156 KB
perf_gputiming.dll              : 10.0.10586.0 (10/29/15 7:34 PM) 338 KB
VsGraphicsCapture.dll           : 10.0.10586.0 (10/29/15 7:31 PM) 154 KB
VsGraphicsExperiment.dll        : 10.0.10586.0 (10/29/15 7:31 PM) 711 KB
VsGraphicsProxyStub.dll         : 10.0.10586.0 (10/29/15 7:37 PM) 88 KB
VsGraphicsRemoteEngine.exe      : 10.0.10586.0 (10/29/15 7:29 PM) 5,432 KB
d3d11_3sdklayers.dll            : 10.0.10586.0 (10/29/15 7:12 PM) 1,308 KB
d3d12SDKLayers.dll              : 10.0.10586.0 (10/29/15 7:13 PM) 979 KB
d3d12warp.dll                   : 10.0.10586.0 (10/29/15 7:28 PM) 3,216 KB
d2d1debug3.dll                  : 10.0.10586.0 (10/29/15 7:30 PM) 420 KB
dxgidebug.dll                   : 10.0.10586.0 (10/29/15 7:37 PM) 337 KB

**Comment by bobbrow** [comment]
This is the same as issue #76.  It's a bug in d3d12sdklayers.dll exposed by recent NVidia drivers.  We have a fix for it, but getting it into a Windows Update has taken some time.  I'm expecting the package to be built soon so I can verify it before it goes out to Windows Update later this month.  Until then, you can work around the crash by rounding up all Committed resources to multiples of 64K, or run the sample using the "Release" config in the project.
