### ISSUE TITLE
D3D12HelloFrameBuffering m_fenceValues not initialized?

### ISSUE THREAD

**Issue by alek314** [Microsoft/DirectX-Graphics-Samples#96]
m_fenceValues happen to be initialize to 0 in debug build. But  IIRC this behavior is not guarantee in Release build, and it may cause WaitForSingleObjectEx  in MoveToNextFrame to block forever.

**Comment by bobbrow** [comment]
Good eye.  I missed this when I was reviewing the code.  I'll fix this up when I get back in to work on Tuesday.  Thanks for reporting the issue.

**Comment by bobbrow** [comment]
Committed a fix for this in the develop branch
