### ISSUE TITLE
Unable to run MS Graphics Debugging Tools in VS2015 update 2

### ISSUE THREAD

**Issue by pergamonster** [Microsoft/DirectX-Graphics-Samples#98]
![image](https://cloud.githubusercontent.com/assets/1788119/13033760/01f0220c-d366-11e5-9def-34fc0ec2f2a6.png)

Exception thrown at 0x00007FFC875DA1C8 in D3D12ExecuteIndirect.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.

Could this be related to the known issue with the SDKLayers.dll and the latest Nvidia drivers?

**Comment by bobbrow** [comment]
The execute indirect sample doesn't have any known issues with the SDK layers.  It runs ok for me on the same driver as you with a GT 640.

VS 2015 Update 2 is in preview right now and I haven't tried it yet.  I would suspect that your issue is with the CTP.  Do you have a callstack you can share?

**Comment by Leyvin** [comment]
This looks like the issue it throws whenever I forget to reinstall the Graphics Tools (optional features) after a Windows 10 Preview update, GPU Open (AMDs Projects) force them as a requirement even to run the Debug let alone actually run Graphics Debugging Tools. Might be worth just double checking they've not been uninstalled accidentally.

**Comment by bobbrow** [comment]
Closing older issue.  Please reopen if you have any additional information to share.
