### ISSUE TITLE
Why dx12 runtime doesn't output any debug error message when i misuse some API

### ISSUE THREAD

**Issue by lijipeng787** [Microsoft/DirectX-Graphics-Samples#99]
In early version of DirectX ,like dx11,when i misuse some function (with wrong or invalid arguments),there will be some helpful message in debug output window.But in my development environment,for example,i create a pipeline state object with an imcompatible vertex shader bitcode, my application will break down with nothing in debug output window. 
MSDN documents that dx12 has remove some runtime and driver error check for performance reason,but it still do some check when application create some objects like pso.
There must be something wrong in my visual studio,but now i have no idea about it.
This my some info:
sdk:10586 and 10240 
In debug mode, i have enable dx12 debug layer.
visual studio version:2015 with update 1.
Windows Graphics Tools installed and i can use the vs graphics debugger normaly.
thanks :)

**Comment by weltkante** [comment]
Are you sure you enabled the debug layer via the DirectX control panel (from the VS Debug/Graphics menu) or from your code? I'm getting plenty of error feedback in the debug console when something goes wrong.

See [here](https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12HelloWorld/src/HelloWindow/D3D12HelloWindow.cpp#L35) for an example how to write your code to call D3D12GetDebugInterface to enable this functionality in debug builds.

**Comment by lijipeng787** [comment]
hey,weltkante
I'm sure I enabled the debug layer in my application.Actually I found even in the DirectX-Graphics-Samples soluntion(D3D12HelloWorld,D3D12ConstantBuffers ...),there is no any error output message in my debug output window when I made some mistakes on purpose.Both d3d12sdklayer.dll and DXGIDebug.dll was loaded.The Win SDK target is 10586.
I don't know where the problem is.Is a rare bug,or I still keep a wrong option?

**Comment by lijipeng787** [comment]
Well,I found something wrong.
This function: OutputDebugString() not work.I didn't saw anything about this function's output in my debugger.
It seems like my IDE problem.

**Comment by weltkante** [comment]
If you use a managed language like C# (instead of C++) then you need to enable native debugging in the project options to receive debug output in the IDE. You may also want to check if displaying debug output is disabled in the IDE debugging options. Other than that I have no idea what could cause this.

**Comment by bobbrow** [comment]
If OutputDebugString is not working for you as expected (I do recommend you check your settings as @weltkante suggests), you can also try running the DX control panel (dxcpl.exe) and enable breaking on Warnings/Errors in the debug layer to see if that detects the test errors you've introduced.

**Comment by lijipeng787** [comment]
Thanks ! @weltkante @bobbrow
DX control panel has a affect scope setting,this is the problem.Add development floder into this scope can resolve all the wrong things.
OutputDebugString also work as expected.(I didn't konw the reason...)
